rule win_shylock_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.shylock."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.shylock"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { e8???????? eb75 8d75d0 e8???????? 8d75a4 e8???????? 8d75c4 }
                                                                                                
        $sequence_1 = { c20800 55 8bec 83ec1c 56 8d45ec 57 }
                                                                                                
        $sequence_2 = { ff75e0 e8???????? 83c410 33c0 eb0c b857000780 eb05 }
                                                                                                
        $sequence_3 = { ff75b8 53 e8???????? 83c420 85c0 7439 3975fc }
                                                                                                
        $sequence_4 = { e8???????? 59 85c0 751a e8???????? 3db7000000 740e }
                                                                                                
        $sequence_5 = { e8???????? 59 50 ff750c ff7508 e8???????? 8d751c }
                                                                                                
        $sequence_6 = { ff75f8 e8???????? 8d45f0 50 8bc6 8b7508 50 }
                                                                                                
        $sequence_7 = { 8d75fc e8???????? 6a00 68???????? 8d5d0c e8???????? 6a00 }
                                                                                                
        $sequence_8 = { eb06 8b4d20 8d3488 e8???????? 8b75f0 8d7ddc e8???????? }
                                                                                                
        $sequence_9 = { ff75f0 e8???????? 8b5d0c 8d45d0 50 e8???????? 8bd8 }
                                                                                                
    condition:
        7 of them and filesize < 630784
}