rule win_fanny_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.fanny."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.fanny"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { e8???????? 8d4dd8 e8???????? 8b45b4 }
                                                            
        $sequence_1 = { 8b7d0c 8bf7 8b4508 3bc3 0f84b8020000 }
                                                                        
        $sequence_2 = { a2???????? 8d45fc 50 8d45f0 a4 6a08 50 }
                                                                                                
        $sequence_3 = { 57 895df0 740b c1e809 894df4 c1e009 eb03 }
                                                                                                
        $sequence_4 = { 5d c3 66c78594fbffff6800 b903000000 8dbd90fbffff 8db5d0fbffff 33d2 }
                                                                                                
        $sequence_5 = { 8b4c2408 33f6 8901 8bc6 }
                                                            
        $sequence_6 = { 50 6808100000 56 ffd7 8b0d???????? }
                                                                        
        $sequence_7 = { 83780c00 7422 8b4dfc 83790400 7419 8b55fc 837a0800 }
                                                                                                
        $sequence_8 = { e8???????? 8b45d0 50 8b4d08 51 }
                                                                        
        $sequence_9 = { 894508 8b5510 83ea05 895510 eb09 }
                                                                        
        $sequence_10 = { e9???????? 8b5508 0fb602 3d90000000 753b 8b4d08 }
                                                                                    
        $sequence_11 = { f3ab 66ab aa 8a4508 }
                                                            
        $sequence_12 = { 5b 5d c3 55 8bec 83ec2c 8065ff00 }
                                                                                                
        $sequence_13 = { 832700 6800800000 6a00 53 ff15???????? }
                                                                        
        $sequence_14 = { 8b45fc 83c012 50 ffd3 8bf0 59 }
                                                                                    
        $sequence_15 = { 8913 751b c745fc01000000 ff33 ff15???????? }
                                                                        
    condition:
        7 of them and filesize < 368640
}