rule win_darkrat_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.darkrat."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.darkrat"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 83c408 837b100a 8b7dd4 0f8514ffffff 8b55ec }
                                                                        
        $sequence_1 = { e8???????? 83c408 c745e800000000 8d4dd8 }
                                                            
        $sequence_2 = { 51 56 e8???????? 83c40c c6043e00 eb17 57 }
                                                                                                
        $sequence_3 = { 72bd 8b4d08 42 8bc1 81fa00100000 72a5 8b49fc }
                                                                                                
        $sequence_4 = { 7435 6a13 68???????? 8bcb }
                                                            
        $sequence_5 = { 85c0 7527 6a0c 68???????? 8bcb e8???????? }
                                                                                    
        $sequence_6 = { c645fc01 8b45cc 83f810 7227 8d4801 }
                                                                        
        $sequence_7 = { c7856cffffff0f000000 c68558ffffff00 6880000000 8d8570ffffff c745fc01000000 }
                                                                        
        $sequence_8 = { c745d400000000 e8???????? 50 e8???????? 83c408 c745e800000000 8d4dd8 }
                                                                                                
        $sequence_9 = { 8b4314 0f43d6 8b7b10 2bc7 8b4dc8 3bc8 7726 }
                                                                                                
    condition:
        7 of them and filesize < 884736
}