rule MALPEDIA_Win_Eternal_Petya_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "bf49aeac-2e4f-5384-8db1-b43fb4139322"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.eternal_petya"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.eternal_petya_auto.yar#L1-L162"
    license_url        = "N/A"
    logic_hash         = "715ae6ddfaceb7ac967a454caeda07039960e25d99f3dc3f83571a182c2a56de"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0  = { 55 8b ec 51 57 68 00 00 00 f0 }
    $sequence_1  = { 53 8d 46 44 50 53 }
    $sequence_2  = { 57 68 00 00 00 f0 6a 18 33 ff }
    $sequence_3  = { 53 6a 21 8d 46 0c 50 }
    $sequence_4  = { 68 f0 00 00 00 6a 40 ff 15 ?? ?? ?? ?? 8b d8 }
    $sequence_5  = { 49 75 f2 8b 43 64 03 43 60 8b 4b 68 89 4d d4 }
    $sequence_6  = { 89 45 d0 8b c7 8b 7d f8 d3 e8 8b 4d e0 03 c1 8d 3c 87 }
    $sequence_7  = { 55 8b ec 8b 4d 0c ba ff 00 00 00 }
    $sequence_8  = { 8d 45 08 50 53 ff 75 0c 89 75 08 }
    $sequence_9  = { 68 ?? ?? ?? ?? e8 ?? ?? ?? ?? 85 c0 74 03 83 ce 02 }
    $sequence_10 = { 68 e8 03 00 00 ff 15 ?? ?? ?? ?? 3b fe 75 d3 }
    $sequence_11 = { 55 8b ec 8b 55 08 53 56 57 8b 72 1c }
    $sequence_12 = { 8b 07 85 c0 75 c3 8b 75 f4 }
    $sequence_13 = { e8 ?? ?? ?? ?? 89 46 10 89 56 14 8b c6 5f 5e }
    $sequence_14 = { 89 85 02 fc ff ff 8b 85 e8 fb ff ff 99 81 e2 ff 01 00 00 }
    $sequence_15 = { 56 51 ff d3 8b 15 ?? ?? ?? ?? 56 52 89 85 f0 fb ff ff }

  condition:
    7 of them and filesize < 851968
}