rule rule_PowerSharpPack_offensive_tool_keyword
{
    meta:
        description = "Detection patterns for the tool 'PowerSharpPack' taken from the ThreatHunting-Keywords github project"
        author = "@mthcht"
        reference = "https://github.com/mthcht/ThreatHunting-Keywords"
        tool = "PowerSharpPack"
        rule_category = "offensive_tool_keyword"

    strings:
                        $string1_PowerSharpPack_offensive_tool_keyword = " -grouper2 -Command " nocase ascii wide
                        $string2_PowerSharpPack_offensive_tool_keyword = " -Internalmonologue  -Command " nocase ascii wide
                        $string3_PowerSharpPack_offensive_tool_keyword = " -lockless -Command " nocase ascii wide
                        $string4_PowerSharpPack_offensive_tool_keyword = /\s\-Rubeus\s\-Command\s.{0,1000}kerberoast/ nocase ascii wide
                        $string5_PowerSharpPack_offensive_tool_keyword = " -SauronEye -Command " nocase ascii wide
                        $string6_PowerSharpPack_offensive_tool_keyword = " -seatbelt -Command " nocase ascii wide
                        $string7_PowerSharpPack_offensive_tool_keyword = " -SharpChromium " nocase ascii wide
                        $string8_PowerSharpPack_offensive_tool_keyword = " -SharpDPAPI -Command " nocase ascii wide
                        $string9_PowerSharpPack_offensive_tool_keyword = " -SharPersist " nocase ascii wide
                        $string10_PowerSharpPack_offensive_tool_keyword = " -SharpShares " nocase ascii wide
                        $string11_PowerSharpPack_offensive_tool_keyword = " -SharpSniper " nocase ascii wide
                        $string12_PowerSharpPack_offensive_tool_keyword = " -SharpSpray " nocase ascii wide
                        $string13_PowerSharpPack_offensive_tool_keyword = " -SharpUp -Command " nocase ascii wide
                        $string14_PowerSharpPack_offensive_tool_keyword = " -Sharpview " nocase ascii wide
                        $string15_PowerSharpPack_offensive_tool_keyword = " -sharpweb -Command " nocase ascii wide
                        $string16_PowerSharpPack_offensive_tool_keyword = " -Tokenvator -Command " nocase ascii wide
                        $string17_PowerSharpPack_offensive_tool_keyword = " -UrbanBishop -Command " nocase ascii wide
                        $string18_PowerSharpPack_offensive_tool_keyword = " -watson -Command " nocase ascii wide
                        $string19_PowerSharpPack_offensive_tool_keyword = " -winPEAS " nocase ascii wide
                        $string20_PowerSharpPack_offensive_tool_keyword = /\/GzipB64\.exe/ nocase ascii wide
                        $string21_PowerSharpPack_offensive_tool_keyword = /\/PowerSharpPack\.git/ nocase ascii wide
                        $string22_PowerSharpPack_offensive_tool_keyword = /\\GzipB64\.exe/ nocase ascii wide
                        $string23_PowerSharpPack_offensive_tool_keyword = /\\windows\\temp\\pwned\.trx/ nocase ascii wide
                        $string24_PowerSharpPack_offensive_tool_keyword = "03C4F510E0DA9684181E07BD9F4FB1329BFC9F815856BCDA224D37666704EEAF" nocase ascii wide
                        $string25_PowerSharpPack_offensive_tool_keyword = "04DD48A0AFD6D6EA2969225DE9DDEF69EDB3DBC1D8C1AED2C4F12E9621C948F1" nocase ascii wide
                        $string26_PowerSharpPack_offensive_tool_keyword = "04E8D9E98A7BAF3AFBA44E9FCFF34659979ED27AC3AE92EE2184F5963F339E32" nocase ascii wide
                        $string27_PowerSharpPack_offensive_tool_keyword = "0800C357553BD74B42A5DD8A7C80C59422BFBC23F3E3F81CF0B16DEF66D4A70F" nocase ascii wide
                        $string28_PowerSharpPack_offensive_tool_keyword = "0E7A579798A6A57A88C6CBD5C67313E43B8F7D84DF4798C88142B134D48C263B" nocase ascii wide
                        $string29_PowerSharpPack_offensive_tool_keyword = "15835E15B02D775A71F29ECEF61FC3E5ADB50C13F8987072A945AF99A17C0F6E" nocase ascii wide
                        $string30_PowerSharpPack_offensive_tool_keyword = "1877E0EC0E657212BF5C9C9170427F7B4D8FDCBED8CFE8FAC388827CE33FDADD" nocase ascii wide
                        $string31_PowerSharpPack_offensive_tool_keyword = "1B3D331BD6ABC44B54119E00509215AE3EA4B482DDB0C9F0D21D71C24EC3B5B6" nocase ascii wide
                        $string32_PowerSharpPack_offensive_tool_keyword = "2566C66F43F181F2B8AEFE41D902F02B54AE284B516062270E83F301A32A5F35" nocase ascii wide
                        $string33_PowerSharpPack_offensive_tool_keyword = "4351D871B1B4CB1BA8F54C52A6786C809707A05353B46EA1AF9A4950D88C4E61" nocase ascii wide
                        $string34_PowerSharpPack_offensive_tool_keyword = "648BA42AFD2FEC89A055E69B21A04CB11B74F13916249F4BC3512C3145FDC249" nocase ascii wide
                        $string35_PowerSharpPack_offensive_tool_keyword = "6C3D086F568E4DCF1379D750C48464FC1F737326E2547DEE1EAFFD00F19FF16C" nocase ascii wide
                        $string36_PowerSharpPack_offensive_tool_keyword = "6F3899086ACCAB2E2686ADB078E049066754D0EE7798666042416CEF566F65E0" nocase ascii wide
                        $string37_PowerSharpPack_offensive_tool_keyword = "7D430DB8006F611817143F28D8141BBDB3291348455FB0C53E9EEBE59E890695" nocase ascii wide
                        $string38_PowerSharpPack_offensive_tool_keyword = "9D08025F46B50B02A2B45CC2E6E83F85BC80C4AEEDEB8651E36B38DA29856542" nocase ascii wide
                        $string39_PowerSharpPack_offensive_tool_keyword = "9E6E4B36B39C50C733FE8EB2DD43AB1A6B397066866A1D16987D87275B0359D3" nocase ascii wide
                        $string40_PowerSharpPack_offensive_tool_keyword = "A5FDFE2A253B751DA1A84A41A2B501648735D027E03882CF363ACE84FE235034" nocase ascii wide
                        $string41_PowerSharpPack_offensive_tool_keyword = "B1952AB299560820661C7D76EF8BCF224EBA551C2F5111525428E7F2CEA0AF9A" nocase ascii wide
                        $string42_PowerSharpPack_offensive_tool_keyword = "BAE62044075CF4F76F0BAAD0FA33F6322541CC46F80C81170E97A181CAA43104" nocase ascii wide
                        $string43_PowerSharpPack_offensive_tool_keyword = "C6678CDE09F4A18DD9C295262837C94E8D069295D26CE187C94C8AEDDE996CB3" nocase ascii wide
                        $string44_PowerSharpPack_offensive_tool_keyword = "C7A5E6480C6CEC01E3627AE0A8EAC1FFE13226C560D4E4C05FCE1CAB1168CC8D" nocase ascii wide
                        $string45_PowerSharpPack_offensive_tool_keyword = "C82E994585B5C08F7259B00BD5F91AD45FCC8E42B4BF6A3CA989278D0A63BACF" nocase ascii wide
                        $string46_PowerSharpPack_offensive_tool_keyword = "CA9F2786DFE0A75DAF0A5C711B355D6EE0B2605D7F344E85DA9F4D40127EBC69" nocase ascii wide
                        $string47_PowerSharpPack_offensive_tool_keyword = "CDC35DDA09316ABD091D51CF9EE78DECE9216ABB9F09FC2CDF4EB36E4971AB3C" nocase ascii wide
                        $string48_PowerSharpPack_offensive_tool_keyword = "-Command \"--signature --driver\"" nocase ascii wide
                        $string49_PowerSharpPack_offensive_tool_keyword = "D24C50F9C1F0E6AC82157B0319127ECF72E454FE5A9E86C25891B3101F957769" nocase ascii wide
                        $string50_PowerSharpPack_offensive_tool_keyword = "D60C351E1207F7C344C467BB09EC1EEA33D283C34FA56A531222871BB2542CE4" nocase ascii wide
                        $string51_PowerSharpPack_offensive_tool_keyword = "DA0A017BDD91FE21E8580F8AC005B497743635E73649764D132726E341171D50" nocase ascii wide
                        $string52_PowerSharpPack_offensive_tool_keyword = "E5AF133E4976EE14EA6EDB8652F354A18483289E2E1B6043D905B821FA84C53C" nocase ascii wide
                        $string53_PowerSharpPack_offensive_tool_keyword = "EDE1D800842E11B147A6E039507EA5DCD7F825BF9AF3195F8B1FAF10080CDE77" nocase ascii wide
                        $string54_PowerSharpPack_offensive_tool_keyword = "F5F605F596F85A1344F46774D782F4109EA83DD851139338CB07DF90FD1D0D5A" nocase ascii wide
                        $string55_PowerSharpPack_offensive_tool_keyword = "F74BACC239A453DA97AACA6C0E9E70D2282CE801EC9A1262A8F3237CCFC27E9A" nocase ascii wide
                        $string56_PowerSharpPack_offensive_tool_keyword = "F8D2B9771E5AB15013A38543F05ECD747A23A6A33463D9A53106FDD15DADF002" nocase ascii wide
                        $string57_PowerSharpPack_offensive_tool_keyword = "FC7A5B008FCF3AD0C3535D4463C094D6833F11AB21DD39616B93A5518FB1C316" nocase ascii wide
                        $string58_PowerSharpPack_offensive_tool_keyword = "FFC64B8DA962F05C780B803F11727D9960C31E133523FE9DADA309F8836DD098" nocase ascii wide
                        $string59_PowerSharpPack_offensive_tool_keyword = "Invoke-BadPotato" nocase ascii wide
                        $string60_PowerSharpPack_offensive_tool_keyword = "Invoke-BetterSafetyKatz" nocase ascii wide
                        $string61_PowerSharpPack_offensive_tool_keyword = "Invoke-BlockETW" nocase ascii wide
                        $string62_PowerSharpPack_offensive_tool_keyword = "Invoke-Carbuncle" nocase ascii wide
                        $string63_PowerSharpPack_offensive_tool_keyword = "Invoke-Certify" nocase ascii wide
                        $string64_PowerSharpPack_offensive_tool_keyword = /Invoke\-DAFT\./ nocase ascii wide
                        $string65_PowerSharpPack_offensive_tool_keyword = "Invoke-DinvokeKatz" nocase ascii wide
                        $string66_PowerSharpPack_offensive_tool_keyword = "Invoke-Eyewitness" nocase ascii wide
                        $string67_PowerSharpPack_offensive_tool_keyword = "Invoke-FakeLogonScreen" nocase ascii wide
                        $string68_PowerSharpPack_offensive_tool_keyword = "Invoke-Farmer" nocase ascii wide
                        $string69_PowerSharpPack_offensive_tool_keyword = "Invoke-Get-RBCD-Threaded" nocase ascii wide
                        $string70_PowerSharpPack_offensive_tool_keyword = "Invoke-Gopher" nocase ascii wide
                        $string71_PowerSharpPack_offensive_tool_keyword = "Invoke-Grouper2" nocase ascii wide
                        $string72_PowerSharpPack_offensive_tool_keyword = "Invoke-Grouper3" nocase ascii wide
                        $string73_PowerSharpPack_offensive_tool_keyword = "Invoke-HandleKatz" nocase ascii wide
                        $string74_PowerSharpPack_offensive_tool_keyword = "Invoke-Internalmonologue" nocase ascii wide
                        $string75_PowerSharpPack_offensive_tool_keyword = "Invoke-KrbRelay" nocase ascii wide
                        $string76_PowerSharpPack_offensive_tool_keyword = "Invoke-LdapSignCheck" nocase ascii wide
                        $string77_PowerSharpPack_offensive_tool_keyword = "Invoke-Lockless" nocase ascii wide
                        $string78_PowerSharpPack_offensive_tool_keyword = "Invoke-MalSCCM" nocase ascii wide
                        $string79_PowerSharpPack_offensive_tool_keyword = "Invoke-MITM6" nocase ascii wide
                        $string80_PowerSharpPack_offensive_tool_keyword = "Invoke-NanoDump" nocase ascii wide
                        $string81_PowerSharpPack_offensive_tool_keyword = "Invoke-OxidResolver" nocase ascii wide
                        $string82_PowerSharpPack_offensive_tool_keyword = "Invoke-P0wnedshell" nocase ascii wide
                        $string83_PowerSharpPack_offensive_tool_keyword = "Invoke-P0wnedshellx86" nocase ascii wide
                        $string84_PowerSharpPack_offensive_tool_keyword = "Invoke-PPLDump" nocase ascii wide
                        $string85_PowerSharpPack_offensive_tool_keyword = "Invoke-Rubeus" nocase ascii wide
                        $string86_PowerSharpPack_offensive_tool_keyword = "Invoke-SafetyKatz" nocase ascii wide
                        $string87_PowerSharpPack_offensive_tool_keyword = "Invoke-SauronEye" nocase ascii wide
                        $string88_PowerSharpPack_offensive_tool_keyword = "Invoke-SCShell" nocase ascii wide
                        $string89_PowerSharpPack_offensive_tool_keyword = "Invoke-Seatbelt" nocase ascii wide
                        $string90_PowerSharpPack_offensive_tool_keyword = "Invoke-ShadowSpray" nocase ascii wide
                        $string91_PowerSharpPack_offensive_tool_keyword = "Invoke-SharpAllowedToAct" nocase ascii wide
                        $string92_PowerSharpPack_offensive_tool_keyword = "Invoke-SharpBlock" nocase ascii wide
                        $string93_PowerSharpPack_offensive_tool_keyword = "Invoke-SharpBypassUAC" nocase ascii wide
                        $string94_PowerSharpPack_offensive_tool_keyword = "Invoke-SharpChromium" nocase ascii wide
                        $string95_PowerSharpPack_offensive_tool_keyword = "Invoke-SharpClipboard" nocase ascii wide
                        $string96_PowerSharpPack_offensive_tool_keyword = "Invoke-SharpCloud" nocase ascii wide
                        $string97_PowerSharpPack_offensive_tool_keyword = "Invoke-SharpDPAPI" nocase ascii wide
                        $string98_PowerSharpPack_offensive_tool_keyword = "Invoke-SharpDump" nocase ascii wide
                        $string99_PowerSharpPack_offensive_tool_keyword = "Invoke-SharPersist" nocase ascii wide
                        $string100_PowerSharpPack_offensive_tool_keyword = "Invoke-SharpGPOAbuse" nocase ascii wide
                        $string101_PowerSharpPack_offensive_tool_keyword = "Invoke-SharpGPO-RemoteAccessPolicies" nocase ascii wide
                        $string102_PowerSharpPack_offensive_tool_keyword = "Invoke-SharpHandler" nocase ascii wide
                        $string103_PowerSharpPack_offensive_tool_keyword = "Invoke-SharpHide" nocase ascii wide
                        $string104_PowerSharpPack_offensive_tool_keyword = "Invoke-Sharphound2" nocase ascii wide
                        $string105_PowerSharpPack_offensive_tool_keyword = "Invoke-Sharphound3" nocase ascii wide
                        $string106_PowerSharpPack_offensive_tool_keyword = "Invoke-SharpHound4" nocase ascii wide
                        $string107_PowerSharpPack_offensive_tool_keyword = "Invoke-SharpImpersonation" nocase ascii wide
                        $string108_PowerSharpPack_offensive_tool_keyword = "Invoke-SharpImpersonationNoSpace" nocase ascii wide
                        $string109_PowerSharpPack_offensive_tool_keyword = "Invoke-SharpKatz" nocase ascii wide
                        $string110_PowerSharpPack_offensive_tool_keyword = "Invoke-SharpLdapRelayScan" nocase ascii wide
                        $string111_PowerSharpPack_offensive_tool_keyword = "Invoke-Sharplocker" nocase ascii wide
                        $string112_PowerSharpPack_offensive_tool_keyword = "Invoke-SharpLoginPrompt" nocase ascii wide
                        $string113_PowerSharpPack_offensive_tool_keyword = "Invoke-SharpMove" nocase ascii wide
                        $string114_PowerSharpPack_offensive_tool_keyword = "Invoke-SharpPrinter" nocase ascii wide
                        $string115_PowerSharpPack_offensive_tool_keyword = "Invoke-SharpPrintNightmare" nocase ascii wide
                        $string116_PowerSharpPack_offensive_tool_keyword = "Invoke-SharpRDP" nocase ascii wide
                        $string117_PowerSharpPack_offensive_tool_keyword = "Invoke-SharpSCCM" nocase ascii wide
                        $string118_PowerSharpPack_offensive_tool_keyword = "Invoke-SharpSecDump" nocase ascii wide
                        $string119_PowerSharpPack_offensive_tool_keyword = "Invoke-Sharpshares" nocase ascii wide
                        $string120_PowerSharpPack_offensive_tool_keyword = "Invoke-SharpSniper" nocase ascii wide
                        $string121_PowerSharpPack_offensive_tool_keyword = "Invoke-SharpSploit" nocase ascii wide
                        $string122_PowerSharpPack_offensive_tool_keyword = "Invoke-Sharpsploit_nomimi" nocase ascii wide
                        $string123_PowerSharpPack_offensive_tool_keyword = "Invoke-SharpSSDP" nocase ascii wide
                        $string124_PowerSharpPack_offensive_tool_keyword = "Invoke-SharpStay" nocase ascii wide
                        $string125_PowerSharpPack_offensive_tool_keyword = "Invoke-SharpUp" nocase ascii wide
                        $string126_PowerSharpPack_offensive_tool_keyword = "Invoke-Sharpview" nocase ascii wide
                        $string127_PowerSharpPack_offensive_tool_keyword = "Invoke-SharpWatson" nocase ascii wide
                        $string128_PowerSharpPack_offensive_tool_keyword = "Invoke-Sharpweb" nocase ascii wide
                        $string129_PowerSharpPack_offensive_tool_keyword = "Invoke-SharpWSUS" nocase ascii wide
                        $string130_PowerSharpPack_offensive_tool_keyword = "Invoke-Snaffler" nocase ascii wide
                        $string131_PowerSharpPack_offensive_tool_keyword = "Invoke-Spoolsample" nocase ascii wide
                        $string132_PowerSharpPack_offensive_tool_keyword = /Invoke\-StandIn\./ nocase ascii wide
                        $string133_PowerSharpPack_offensive_tool_keyword = "Invoke-StickyNotesExtract" nocase ascii wide
                        $string134_PowerSharpPack_offensive_tool_keyword = "Invoke-Thunderfox" nocase ascii wide
                        $string135_PowerSharpPack_offensive_tool_keyword = "Invoke-Tokenvator" nocase ascii wide
                        $string136_PowerSharpPack_offensive_tool_keyword = "Invoke-UrbanBishop" nocase ascii wide
                        $string137_PowerSharpPack_offensive_tool_keyword = "Invoke-Whisker" nocase ascii wide
                        $string138_PowerSharpPack_offensive_tool_keyword = "Invoke-winPEAS" nocase ascii wide
                        $string139_PowerSharpPack_offensive_tool_keyword = "Invoke-WireTap" nocase ascii wide
                        $string140_PowerSharpPack_offensive_tool_keyword = "no Mimik@tz - loaded successfully" nocase ascii wide
                        $string141_PowerSharpPack_offensive_tool_keyword = "PowerSharpBinaries" nocase ascii wide
                        $string142_PowerSharpPack_offensive_tool_keyword = /PowerSharpPack\.ps1/ nocase ascii wide
                        $string143_PowerSharpPack_offensive_tool_keyword = "PowerSharpPack-master" nocase ascii wide
                        $string144_PowerSharpPack_offensive_tool_keyword = "S3cur3Th1sSh1t/PowerSharpPack" nocase ascii wide

    condition:
        any of them
}