rule win_venus_locker_auto {
  meta:
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    date               = "2020-10-14"
    version            = "1"
    description        = "autogenerated rule brought to you by yara-signator"
    tool               = "yara-signator v0.5.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.venus_locker"
    malpedia_rule_date = "20201014"
    malpedia_hash      = "a7e3bd57eaf12bf3ea29a863c041091ba3af9ac9"
    malpedia_version   = "20201014"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"
  

  strings:
    $sequence_0 = { 3a 40 41 f5 53 2e fc 21 b6 79 09 89 81 24 00 d6 }
                                    $sequence_1 = { dc cf fd da ab 36 40 ad 80 46 }
                        $sequence_2 = { 00 d0 e0 59 0e 00 e0 ed 3f }
                                $sequence_3 = { b9 b5 ef 00 00 47 0f af ca 30 4f ff 47 }
                            $sequence_4 = { a4 5d 19 cb 7d c8 05 60 14 a0 06 c0 db b1 }
                                $sequence_5 = { 58 6a 01 e8 ?? ?? ?? ?? 8f 46 1c c7 46 14 0c 00 00 00 8d 85 ba 01 00 00 }
                                $sequence_6 = { ce 8c 9f 02 1f 40 00 26 40 9d 88 0c 51 91 }
                                $sequence_7 = { 13 e0 fd 55 26 02 3e ce 8c 9f 02 1f 40 00 26 40 }
                                    $sequence_8 = { b4 00 3b 26 96 b3 35 70 41 }
                            $sequence_9 = { 00 74 00 61 00 72 00 74 00 4c 00 69 00 6e }
              
  condition:
    7 of them and filesize < 974848
}