rule RemotePC
{
    meta:
        description = "Detection patterns for the tool 'RemotePC' taken from the ThreatHunting-Keywords github project"
        author = "@mthcht"
        reference = "https://github.com/mthcht/ThreatHunting-Keywords"
        tool = "RemotePC"
        rule_category = "greyware_tool_keyword"

    strings:
                        $string1 = " /f /im RemotePCS" nocase ascii wide
                        $string2 = " create RPCService start=" nocase ascii wide
                        $string3 = " create ViewerService start=auto" nocase ascii wide
                        $string4 = /\s\-i\sremotepc\.deb/ nocase ascii wide
                        $string5 = /\sRemotePC\.exe/ nocase ascii wide
                        $string6 = " RemotePCAttendedService " nocase ascii wide
                        $string7 = /\sremotepclauncher\.exe/ nocase ascii wide
                        $string8 = /\sremotepcuiu\.exe/ nocase ascii wide
                        $string9 = /\sRemotePCViewer\.msi/ nocase ascii wide
                        $string10 = /\srpcdownloader\.exe/ nocase ascii wide
                        $string11 = /\srpcperfviewer\.exe/ nocase ascii wide
                        $string12 = /\sRPCWinXP\.exe/ nocase ascii wide
                        $string13 = "\"RemotePCAttendedService\"" nocase ascii wide
                        $string14 = /\.remotepc\.com/ nocase ascii wide
                        $string15 = /\.remotepc\.com/ nocase ascii wide
                        $string16 = /\/AttendedUDP\.zip/ nocase ascii wide
                        $string17 = /\/remotepc\.deb/ nocase ascii wide
                        $string18 = /\/remotepc\.deb/ nocase ascii wide
                        $string19 = /\/RemotePC\.exe/ nocase ascii wide
                        $string20 = /\/RemotePC\.exe/ nocase ascii wide
                        $string21 = /\/RemotePC\.lnk/ nocase ascii wide
                        $string22 = /\/RemotePC\.tmp/ nocase ascii wide
                        $string23 = /\/remotepc\-attended\.deb/ nocase ascii wide
                        $string24 = /\/RemotePCAttended\.dmg/ nocase ascii wide
                        $string25 = /\/remotepclauncher\.exe/ nocase ascii wide
                        $string26 = /\/RemotePCSuite\.dmg/ nocase ascii wide
                        $string27 = /\/remotepcuiu\.exe/ nocase ascii wide
                        $string28 = /\/RemotePCViewer\.msi/ nocase ascii wide
                        $string29 = /\/RpcDND_Console\.exe/ nocase ascii wide
                        $string30 = /\/rpcdownloader\.exe/ nocase ascii wide
                        $string31 = /\/RPCFireWallRule\.exe/ nocase ascii wide
                        $string32 = /\/rpcperfviewer\.exe/ nocase ascii wide
                        $string33 = /\/RPCProxyLatency\.exe/ nocase ascii wide
                        $string34 = /\/viewerhostkeypopup\.exe/ nocase ascii wide
                        $string35 = /\\AttendedServiceRemove\.exe/ nocase ascii wide
                        $string36 = /\\AttendedUDP\.zip/ nocase ascii wide
                        $string37 = /\\BSUtility\.exe/ nocase ascii wide
                        $string38 = /\\Control\\Print\\Monitors\\REMOTEPCPRINTER/ nocase ascii wide
                        $string39 = /\\CurrentVersion\\App\sPaths\\RemotePCPerformance/ nocase ascii wide
                        $string40 = /\\CurrentVersion\\Devices\\RemotePC\sPrinter/ nocase ascii wide
                        $string41 = /\\InventoryApplicationFile\\rpcattendedadmin/ nocase ascii wide
                        $string42 = /\\Print\\Printers\\RemotePC\sPrinter\\/ nocase ascii wide
                        $string43 = /\\Program\sFiles\s\(x86\)\\RemotePC\\/ nocase ascii wide
                        $string44 = /\\program\sfiles\s\(x86\)\\remotepc\\remotepcperformance\\/ nocase ascii wide
                        $string45 = /\\ProgramData\\RemotePC/ nocase ascii wide
                        $string46 = /\\RemotePC\s\(1\)\.exe/ nocase ascii wide
                        $string47 = /\\RemotePC\sAttended\.lnk/ nocase ascii wide
                        $string48 = /\\RemotePC\sAttended\\/ nocase ascii wide
                        $string49 = /\\RemotePC\sPerformance\sHost\\/ nocase ascii wide
                        $string50 = /\\RemotePC\.Common\.dll/ nocase ascii wide
                        $string51 = /\\RemotePC\.exe/ nocase ascii wide
                        $string52 = /\\RemotePC\.exe/ nocase ascii wide
                        $string53 = /\\RemotePC\.lnk/ nocase ascii wide
                        $string54 = /\\RemotePC\.tmp/ nocase ascii wide
                        $string55 = /\\RemotePC\.tmp/ nocase ascii wide
                        $string56 = /\\RemotePC\\.{0,100}\.dll/ nocase ascii wide
                        $string57 = /\\RemotePCAttended\.dmg/ nocase ascii wide
                        $string58 = /\\RemotePCCopyPaste\.txt/ nocase ascii wide
                        $string59 = /\\RemotePCDDriver\.cat/ nocase ascii wide
                        $string60 = /\\RemotePCDDriver\.inf/ nocase ascii wide
                        $string61 = /\\RemotePCDDriverumode1_0\.dll/ nocase ascii wide
                        $string62 = /\\RemotePCDDriverumode1_2\.dll/ nocase ascii wide
                        $string63 = /\\RemotePCDesktop\.txt/ nocase ascii wide
                        $string64 = /\\RemotePCDnD\.dll/ nocase ascii wide
                        $string65 = /\\RemotePCDnDLauncher\.exe/ nocase ascii wide
                        $string66 = /\\RemotePCHDDesktop\.txt/ nocase ascii wide
                        $string67 = /\\RemotePCHDService\.txt/ nocase ascii wide
                        $string68 = /\\remotepclauncher\.exe/ nocase ascii wide
                        $string69 = /\\RemotePCModules\.log/ nocase ascii wide
                        $string70 = /\\RemotePCPDF\.conf/ nocase ascii wide
                        $string71 = /\\RemotePCPerformancePlugins\.exe/ nocase ascii wide
                        $string72 = /\\RemotePCPrinter\.exe/ nocase ascii wide
                        $string73 = /\\RemotePCPrinter\.exe\.config/ nocase ascii wide
                        $string74 = /\\RemotePCPrinter\.pdb/ nocase ascii wide
                        $string75 = /\\RemotePCPrinterCore\.dll/ nocase ascii wide
                        $string76 = /\\RemotePCPrinterCore\.pdb/ nocase ascii wide
                        $string77 = /\\RemotePCProxys\.dat/ nocase ascii wide
                        $string78 = /\\RemotePCPS5UI\.DLL/ nocase ascii wide
                        $string79 = /\\RemotePCPS5UI\.DLL/ nocase ascii wide
                        $string80 = /\\RemotePCPSCRIPT\./ nocase ascii wide
                        $string81 = /\\RemotePCPSCRIPT\.HLP/ nocase ascii wide
                        $string82 = /\\RemotePCPSCRIPT\.NTF/ nocase ascii wide
                        $string83 = /\\RemotePCPSCRIPT5\.DLL/ nocase ascii wide
                        $string84 = /\\RemotePCService\.exe/ nocase ascii wide
                        $string85 = /\\RemotePCService\.txt/ nocase ascii wide
                        $string86 = /\\RemotePCService_2\.txt/ nocase ascii wide
                        $string87 = /\\RemotePCSuite\.dmg/ nocase ascii wide
                        $string88 = /\\RemotePCUDE\.cat/ nocase ascii wide
                        $string89 = /\\RemotePCUDE\.inf/ nocase ascii wide
                        $string90 = /\\RemotePCUDE\.sys/ nocase ascii wide
                        $string91 = /\\RemotePCUDEHost\.cat/ nocase ascii wide
                        $string92 = /\\RemotePCUDEHost\.inf/ nocase ascii wide
                        $string93 = /\\RemotePCUDEHost\.sys/ nocase ascii wide
                        $string94 = /\\RemotePCUIA\.exe/ nocase ascii wide
                        $string95 = /\\RemotePCUIU\.exe/ nocase ascii wide
                        $string96 = /\\remotepcuiu\.exe/ nocase ascii wide
                        $string97 = /\\RemotePCViewer\.msi/ nocase ascii wide
                        $string98 = /\\RpcAccessPermissionNotifier\.exe/ nocase ascii wide
                        $string99 = /\\RpcApp\\RPCCodecEngine\.exe/ nocase ascii wide
                        $string100 = /\\RpcApp\\Tools\\Chat\.exe/ nocase ascii wide
                        $string101 = /\\RpcApp\\Tools\\TransferServer\.exe/ nocase ascii wide
                        $string102 = /\\RPCAppLauncherLogFile\.txt/ nocase ascii wide
                        $string103 = /\\RPCAttended\.log/ nocase ascii wide
                        $string104 = /\\RPCAttendedAdmin\.exe/ nocase ascii wide
                        $string105 = /\\RPCCertificate\.log/ nocase ascii wide
                        $string106 = /\\RPCClipboard\.exe/ nocase ascii wide
                        $string107 = /\\RPCClipboardAttended\.exe/ nocase ascii wide
                        $string108 = /\\RPCConfig\.ini/ nocase ascii wide
                        $string109 = /\\RPCCoreViewer\.exe/ nocase ascii wide
                        $string110 = /\\RpcDND_Console\.exe/ nocase ascii wide
                        $string111 = /\\RPCDownloader\.exe/ nocase ascii wide
                        $string112 = /\\RPCDownloaderLogFile\.txt/ nocase ascii wide
                        $string113 = /\\RPCDragDrop\.txt/ nocase ascii wide
                        $string114 = /\\RPCFirewallAttended\.exe/ nocase ascii wide
                        $string115 = /\\RPCFireWallRule\.exe/ nocase ascii wide
                        $string116 = /\\RPCFireWallRulelogfile\.txt/ nocase ascii wide
                        $string117 = /\\RPCKeyMouseHandler\.txt/ nocase ascii wide
                        $string118 = /\\RPCOTABootstrapper\.exe/ nocase ascii wide
                        $string119 = /\\RPCOTADesktop\.exe/ nocase ascii wide
                        $string120 = /\\RPCOTADesktopUAC\.exe/ nocase ascii wide
                        $string121 = /\\RpcOTADND_Console\.exe/ nocase ascii wide
                        $string122 = /\\RPCOTAElevator\.exe/ nocase ascii wide
                        $string123 = /\\RPCOTAFTHost\.exe/ nocase ascii wide
                        $string124 = /\\RPCOTAKillService\.exe/ nocase ascii wide
                        $string125 = /\\RPCOTARelauncher\.exe/ nocase ascii wide
                        $string126 = /\\RPCOTAService\.exe/ nocase ascii wide
                        $string127 = /\\RPCOTAServiceUAC\.exe/ nocase ascii wide
                        $string128 = /\\RPCOTAUtilityHost\.exe/ nocase ascii wide
                        $string129 = /\\RPCOTAViewerHostKeyPopup\.exe/ nocase ascii wide
                        $string130 = /\\RPCPerformanceService\.exe/ nocase ascii wide
                        $string131 = /\\RPCPerformanceService\.log/ nocase ascii wide
                        $string132 = /\\RPCPerfViewer\.exe/ nocase ascii wide
                        $string133 = /\\rpcperfviewer\.exe/ nocase ascii wide
                        $string134 = /\\RPCPerfViewer\.log/ nocase ascii wide
                        $string135 = /\\RPCPing\.txt/ nocase ascii wide
                        $string136 = /\\RPCPreUninstall\.log/ nocase ascii wide
                        $string137 = /\\RPCPreUninstall\.log/ nocase ascii wide
                        $string138 = /\\RPCPrinterDownloader\.exe/ nocase ascii wide
                        $string139 = /\\RPCPrinterDownloader\.txt/ nocase ascii wide
                        $string140 = /\\RPCProxyLatency\.exe/ nocase ascii wide
                        $string141 = /\\RPCProxyLatencyAttended\.exe/ nocase ascii wide
                        $string142 = /\\RPCSettings\.ini/ nocase ascii wide
                        $string143 = /\\RpcStickyNotes\.exe/ nocase ascii wide
                        $string144 = /\\RPCSuite_.{0,100}_Inc\.log/ nocase ascii wide
                        $string145 = /\\RPCsuiteLaunch\.txt/ nocase ascii wide
                        $string146 = /\\Schedule\\TaskCache\\Tree\\RemotePC/ nocase ascii wide
                        $string147 = /\\Services\\RemotePCAttendedService/ nocase ascii wide
                        $string148 = /\\Tools\\Ninja\.WebSockets\.dll/ nocase ascii wide
                        $string149 = /\\Tracing\\RemotePCLauncher_/ nocase ascii wide
                        $string150 = /\\Tracing\\RemotePCUIU/ nocase ascii wide
                        $string151 = /\\TransferClient\.exe\.config/ nocase ascii wide
                        $string152 = /\\TransferServer\.exe\.config/ nocase ascii wide
                        $string153 = /\\ViewerHostKeyPopup\.exe/ nocase ascii wide
                        $string154 = /\\ViewerHostKeyPopup\.exe/ nocase ascii wide
                        $string155 = /\\WOW6432Node\\RemotePC/ nocase ascii wide
                        $string156 = /AppData\\Local\\Temp\\RemotePC\sAttended/ nocase ascii wide
                        $string157 = /download\.remotepc\.com/ nocase ascii wide
                        $string158 = /HKCR\\REMOTEPC/ nocase ascii wide
                        $string159 = /https\:\/\/login\.remotepc\.com\/rpcnew/ nocase ascii wide
                        $string160 = /ip\.remotepc\.com/ nocase ascii wide
                        $string161 = /login\.remotepc\.com/ nocase ascii wide
                        $string162 = "net start RPCPerformanceService" nocase ascii wide
                        $string163 = /program\sfiles\s\(x86\)\\remotepc\\/ nocase ascii wide
                        $string164 = /ProgramData\\RemotePC\sPerformance/ nocase ascii wide
                        $string165 = /ProgramData\\RemotePC/ nocase ascii wide
                        $string166 = /RemotePC\s\(1\)\.exe/ nocase ascii wide
                        $string167 = /RemotePC\sPerformance\sPrinter\.url/ nocase ascii wide
                        $string168 = /RemotePC.{0,100}\s\-\sA\snew\scomputer\shas\sbeen\sadded\sto\syour\saccount/ nocase ascii wide
                        $string169 = /RemotePC\.exe\s/ nocase ascii wide
                        $string170 = /RemotePC\.WebSockets\.dll/ nocase ascii wide
                        $string171 = /RemotePC\\REMOTE\~2\.DLL/ nocase ascii wide
                        $string172 = /RemotePCAttended\.exe/ nocase ascii wide
                        $string173 = "RemotePCAttendedService" nocase ascii wide
                        $string174 = /RemotePCBlackScreenApp\.exe/ nocase ascii wide
                        $string175 = /RemotePCCopyPaste\.txt/ nocase ascii wide
                        $string176 = /RemotePCDesktop\.exe/ nocase ascii wide
                        $string177 = /RemotePCDesktop\.txt/ nocase ascii wide
                        $string178 = /RemotePCHDDesktop\.txt/ nocase ascii wide
                        $string179 = /RemotePCHDService\.txt/ nocase ascii wide
                        $string180 = /remotepclauncher\.exe\s/ nocase ascii wide
                        $string181 = /RemotePCModules\.log/ nocase ascii wide
                        $string182 = /RemotePCPerformanceWebLauncher\.exe/ nocase ascii wide
                        $string183 = /RemotePCPerformanceWebLauncher\.log/ nocase ascii wide
                        $string184 = /RemotePCPrinter\.exe\.config/ nocase ascii wide
                        $string185 = /RemotePCPrinting\.exe/ nocase ascii wide
                        $string186 = /RemotePCPrintView\.exe/ nocase ascii wide
                        $string187 = /RemotePCProxys\.dat/ nocase ascii wide
                        $string188 = /RemotePCService\.exe/ nocase ascii wide
                        $string189 = /RemotePCService\.txt/ nocase ascii wide
                        $string190 = /RemotePCService_2\.txt/ nocase ascii wide
                        $string191 = /RemotePCShortcut\.exe/ nocase ascii wide
                        $string192 = /RemotePCSuite\.Model\.dll/ nocase ascii wide
                        $string193 = /RemotePCSuite\.Service\.dll/ nocase ascii wide
                        $string194 = /remotepcuiu\.exe\s/ nocase ascii wide
                        $string195 = /RpcApp.{0,100}TransferClient\.exe/ nocase ascii wide
                        $string196 = /RpcApp.{0,100}TransferServer\.exe/ nocase ascii wide
                        $string197 = /RpcApp\\Tools\\TransferClient\.exe/ nocase ascii wide
                        $string198 = /RPCAttendedInstaller\.log/ nocase ascii wide
                        $string199 = /rpcdownloader\.exe\s/ nocase ascii wide
                        $string200 = /RPCDownloaderLogFile\.txt/ nocase ascii wide
                        $string201 = /RPCFireWallRule\.exe/ nocase ascii wide
                        $string202 = /RPCFireWallRulelogfile\.txt/ nocase ascii wide
                        $string203 = /RPCKeyMouseHandler\.txt/ nocase ascii wide
                        $string204 = "RPCPerformanceHealthCheck" nocase ascii wide
                        $string205 = /rpcperformanceservice\.exe/ nocase ascii wide
                        $string206 = /RPCPerformanceService\.exe/ nocase ascii wide
                        $string207 = /rpcperfviewer\.exe\s/ nocase ascii wide
                        $string208 = /RPCPerfViewer\.log/ nocase ascii wide
                        $string209 = /rpcprinterdownloader\.exe/ nocase ascii wide
                        $string210 = /RPCProxyLatency\.exe\s/ nocase ascii wide
                        $string211 = /RPCsuiteLaunch\.txt/ nocase ascii wide
                        $string212 = "rule name=\"TransferServer\"" nocase ascii wide
                        $string213 = "sc  delete \"RPCService\"" nocase ascii wide
                        $string214 = "sc  start \"RPCService\"" nocase ascii wide
                        $string215 = "sc  stop \"RPCService\"" nocase ascii wide
                        $string216 = "sc create RPCService start=auto" nocase ascii wide
                        $string217 = "sc create RPCService" nocase ascii wide
                        $string218 = "sc delete \"RPCService\"" nocase ascii wide
                        $string219 = "sc delete ViewerService" nocase ascii wide
                        $string220 = "sc start ViewerService" nocase ascii wide
                        $string221 = "sc stop \"RPCService\"" nocase ascii wide
                        $string222 = "sc stop ViewerService" nocase ascii wide
                        $string223 = "StartRPCPerformanceService" nocase ascii wide
                        $string224 = "StartRPCPerformanceServiceOnStart" nocase ascii wide
                        $string225 = /static\.remotepc\.com/ nocase ascii wide
                        $string226 = /Uninstall\sRemotePC\.lnk/ nocase ascii wide
                        $string227 = /viewerhostkeypopup\.exe\s/ nocase ascii wide
                        $string228 = /web1\.remotepc\.com/ nocase ascii wide
                        $string229 = /www1\.remotepc\.com/ nocase ascii wide
        $metadata_regex_import = /\bimport\s+[a-zA-Z0-9_.]+\b/ nocase
        $metadata_regex_function = /function\s+[a-zA-Z_][a-zA-Z0-9_]*\(/ nocase ascii
        $metadata_regex_php = /<\?php/ nocase ascii
        $metadata_regex_createobject = /(CreateObject|WScript\.)/ nocase ascii
        $metadata_regex_script = /<script\b/ nocase ascii
        $metadata_regex_javascript = /(let\s|const\s|function\s|document\.|console\.)/ nocase ascii
        $metadata_regex_powershell = /(Write-Host|Get-[a-zA-Z]+|Invoke-|param\(|\.SYNOPSIS)/ nocase ascii
        $metadata_regex_batch = /@(echo\s|call\s|set\s|goto\s|if\s|for\s|rem\s)/ nocase ascii
        $metadata_regex_shebang = /^#!\// nocase ascii

    condition:
        ((filesize < 20MB and (
            uint16(0) == 0x5a4d or             uint16(0) == 0x457f or             uint32be(0) == 0x7f454c46 or uint16(0) == 0xfeca or uint16(0) == 0xfacf or uint32(0) == 0xbebafeca or             uint32(0) == 0x504B0304 or             uint32(0) == 0xCAFEBABE or             uint32(0) == 0x4D534346 or             uint32(0) == 0xD0CF11E0 or             uint16(0) == 0x2321 or             uint16(0) == 0x3c3f         )) and 2 of ($string*)) or
        (filesize < 2MB and
        (
            2 of ($string*) and
            for any of ($metadata_regex_*) : ( @ <= 20000 )
        ))
}