rule MALPEDIA_Win_Voidoor_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "71f97a7b-09b8-5977-a64d-26462fe6285b"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.voidoor"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.voidoor_auto.yar#L1-L134"
    license_url        = "N/A"
    logic_hash         = "c8a62c7797e4a86d80b8a858487a45d1e5042e60b70ed193ca612e4172a00dd8"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0 = { e8 ?? ?? ?? ?? 83 c4 10 83 bf b4 0b 00 00 00 75 2e ff 33 83 bf 50 0b 00 00 00 ff b6 08 40 00 00 }
    $sequence_1 = { c6 45 fc 10 e8 ?? ?? ?? ?? c7 85 74 fe ff ff 0f 00 00 00 c7 85 70 fe ff ff 00 00 00 00 c6 85 60 fe ff ff 00 8d 95 60 fe ff ff 8d 8d 78 fe ff ff }
    $sequence_2 = { 03 f5 74 58 80 3e 2f 75 09 83 f8 04 7d 04 40 }
    $sequence_3 = { 55 8b d8 ff 15 ?? ?? ?? ?? 83 c4 14 85 db 0f 85 c3 01 00 00 8b 54 24 40 }
    $sequence_4 = { 8b 74 24 14 c7 44 24 08 00 00 00 00 83 be c8 02 00 00 00 8b 1e 57 8b 83 4c 01 00 00 8d be 68 05 00 00 }
    $sequence_5 = { c6 02 01 8b 10 2b ca 83 f9 06 7d 0a b8 01 00 00 00 5e }
    $sequence_6 = { 33 c0 5f 59 c3 56 57 e8 ?? ?? ?? ?? }
    $sequence_7 = { b9 1b 00 00 00 5e 0f 44 d9 5d 8b c3 5b 83 c4 08 }
    $sequence_8 = { e8 ?? ?? ?? ?? 83 c4 0c 89 44 24 18 89 83 ac 03 00 00 68 ?? ?? ?? ?? 53 e8 ?? ?? ?? ?? }
    $sequence_9 = { c6 43 45 01 39 44 24 1c 75 20 85 f6 0f 85 65 ff ff ff 83 7c 24 30 20 73 37 }

  condition:
    7 of them and filesize < 1744896
}