rule MALPEDIA_Win_8Base_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "7c9b0c56-079f-5ac3-b0fc-c036345ce952"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.8base"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.8base_auto.yar#L1-L120"
    license_url        = "N/A"
    logic_hash         = "ea755be9fd3154ace1513f9f57e59c67fbe5ae97b6b4073ab7fa5cccbb0a5bb8"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0 = { 6a 00 ff 15 ?? ?? ?? ?? 8d 8e 04 a2 fe ff 81 f9 8c 23 00 00 77 0b }
    $sequence_1 = { f8 29 0c 67 98 a6 73 c2 }
    $sequence_2 = { 88 15 ?? ?? ?? ?? c6 05 ?? ?? ?? ?? 6f 88 0d ?? ?? ?? ?? c6 05 ?? ?? ?? ?? 65 c6 05 ?? ?? ?? ?? 63 }
    $sequence_3 = { 8d 34 85 c0 28 91 00 8b 06 83 e7 1f c1 e7 06 03 c7 8a 58 24 }
    $sequence_4 = { c6 84 24 9c 00 00 00 02 50 c7 44 24 10 04 3a 40 00 e8 ?? ?? ?? ?? }
    $sequence_5 = { d3 ea 89 54 24 14 8b 44 24 34 01 44 24 14 8b 44 24 24 31 44 24 10 }
    $sequence_6 = { ff 15 ?? ?? ?? ?? 8b 44 24 14 40 3d ?? ?? ?? ?? 89 44 24 14 0f 8c 0e ff ff ff 8b 35 ?? ?? ?? ?? }
    $sequence_7 = { 8b f7 83 e6 1f c1 e6 06 03 34 85 c0 28 91 00 c7 45 e4 01 00 00 00 }
    $sequence_8 = { 66 89 44 24 16 33 c9 66 89 54 24 1a 8d 44 24 34 50 66 89 4c 24 1c 8b 4c 24 1c }
    $sequence_9 = { 89 9c 24 ac 00 00 00 3b fb 74 49 8b 84 24 b8 00 00 00 56 8d 74 24 18 }

  condition:
    7 of them and filesize < 10838016
}