rule win_bleachgap_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.bleachgap."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.bleachgap"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 8b4110 89500c 8b4110 894210 8b442410 895110 894a0c }
                                                                                                
        $sequence_1 = { 8d8d80fdffff e8???????? 8d8d48feffff e8???????? 8ac3 8b4df4 64890d00000000 }
                                                                                                
        $sequence_2 = { c78514fdffff00000000 c78524fdffff00000000 c78528fdffff00000000 0f1000 0f118514fdffff f30f7e4010 660fd68524fdffff }
                                                                                                
        $sequence_3 = { 83f81f 0f8783010000 51 52 e8???????? 83c408 8b8d5cffffff }
                                                                                                
        $sequence_4 = { 52 e8???????? 83c408 8a85bffeffff eb61 8b55bc 83ff10 }
                                                                                                
        $sequence_5 = { 83c404 83ee01 7839 0f1f00 56 57 e8???????? }
                                                                                                
        $sequence_6 = { 6859040000 68???????? 68db000000 e9???????? 55 e8???????? 83c404 }
                                                                                                
        $sequence_7 = { 46 8ac8 84c0 75dc 84c0 0f845b020000 e9???????? }
                                                                                                
        $sequence_8 = { 8b542424 8b4c2440 89450c 03ca 8b44243c 894d10 8b04b8 }
                                                                                                
        $sequence_9 = { 8945d0 8d4344 8945d4 8d434c 8945d8 8d4354 8945dc }
                                                                                                
    condition:
        7 of them and filesize < 4538368
}