rule MALPEDIA_Win_Glassrat_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "daeaa019-8217-55aa-beac-5fb62572b79c"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.glassrat"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.glassrat_auto.yar#L1-L117"
    license_url        = "N/A"
    logic_hash         = "c91259f84ec94eec4bc87c666b3c91ba45af3572c135cc4f200070d560141e5d"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0 = { 8d 54 24 38 83 c9 ff 33 c0 f2 ae f7 d1 2b f9 8b c1 }
    $sequence_1 = { ff 15 ?? ?? ?? ?? 33 c0 8b 55 04 89 44 24 1d 8d 4c 24 1c }
    $sequence_2 = { 74 7a 3b fe 74 76 56 56 56 53 }
    $sequence_3 = { 89 5d b8 89 5d bc ff 15 ?? ?? ?? ?? 85 c0 0f 84 bb 00 00 00 }
    $sequence_4 = { 3b c8 b8 02 00 00 00 0f 85 b4 00 00 00 33 d2 b9 09 02 00 00 52 83 ec 10 }
    $sequence_5 = { 6a 04 51 52 88 44 24 3b }
    $sequence_6 = { 8b 46 0c 53 53 57 50 }
    $sequence_7 = { 8b ce ff 12 57 ff 15 ?? ?? ?? ?? 8d 4c 24 20 }
    $sequence_8 = { 89 44 24 18 ff 15 ?? ?? ?? ?? 8b 4d 04 8b 1d ?? ?? ?? ?? }
    $sequence_9 = { 89 44 24 08 89 54 24 04 8a 15 ?? ?? ?? ?? 33 c0 }

  condition:
    7 of them and filesize < 81920
}