rule MALPEDIA_Win_Plaintee_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "e3bbe66b-b26a-510d-8a1b-05b2e6f7426c"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.plaintee"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.plaintee_auto.yar#L1-L116"
    license_url        = "N/A"
    logic_hash         = "8bcc878fa501588c97ae4d4926e84d32a4619fd799353944068271d6d4e36727"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0 = { 8d 4c 24 04 6a 00 8d 54 24 04 51 52 ff d0 8b 4c 24 00 }
    $sequence_1 = { 8b f1 68 02 02 00 00 ff 15 ?? ?? ?? ?? 85 c0 74 0a b0 01 }
    $sequence_2 = { 50 8d 85 3c 01 00 00 50 8b 85 38 01 00 00 6a 5a 52 }
    $sequence_3 = { 8d 44 24 00 56 50 8b f1 68 02 02 00 00 ff 15 ?? ?? ?? ?? }
    $sequence_4 = { 5e 81 c4 90 01 00 00 c3 8b ce }
    $sequence_5 = { 85 f6 74 c6 8b ce e8 ?? ?? ?? ?? }
    $sequence_6 = { f3 ab 66 ab b9 00 01 00 00 33 c0 }
    $sequence_7 = { eb 02 33 f6 8b ce e8 ?? ?? ?? ?? 8a 86 69 01 00 00 }
    $sequence_8 = { 68 ac 01 00 00 e8 ?? ?? ?? ?? 83 c4 04 85 c0 74 12 }
    $sequence_9 = { 75 0a b0 01 5e 81 c4 90 01 00 00 c3 }

  condition:
    7 of them and filesize < 73728
}