rule win_flusihoc_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.flusihoc."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.flusihoc"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 740b 40 8816 8a1408 46 }
                                                                        
        $sequence_1 = { 8b442410 6aff 50 ff15???????? 8b4c2410 }
                                                                        
        $sequence_2 = { 57 6a40 8d442428 6a00 50 c744242c44000000 e8???????? }
                                                                                                
        $sequence_3 = { f3a5 c684246402000000 e8???????? 68d6000000 }
                                                            
        $sequence_4 = { 7507 80864d01000004 83f822 7506 fe8e42010000 }
                                                                        
        $sequence_5 = { 8bec 83e4f8 81ece40b0000 a1???????? 33c4 898424e00b0000 53 }
                                                                                                
        $sequence_6 = { 8d7c2428 50 f3a5 c684246401000000 }
                                                            
        $sequence_7 = { 33c0 888c045e010000 8a4c042c 40 }
                                                            
        $sequence_8 = { 8b8c24ec0b0000 5f 5e 5b 33cc 33c0 e8???????? }
                                                                                                
        $sequence_9 = { ff15???????? 8b4c2410 51 ffd6 8b542414 52 ffd6 }
                                                                                                
        $sequence_10 = { fe06 fe461e 3d68010000 7505 fe06 fe4e17 }
                                                                                    
        $sequence_11 = { 52 ffd6 6a0a ff15???????? }
                                                            
        $sequence_12 = { 8b8df4feffff 6804010000 8d85f8feffff 50 6a01 }
                                                                        
        $sequence_13 = { 8b95f4feffff 52 ff15???????? 8b4dfc 33cd 33c0 }
                                                                                    
        $sequence_14 = { 51 6a00 ff15???????? 8d95f4feffff 52 6806000200 }
                                                                                    
        $sequence_15 = { 6a00 68???????? 6802000080 ff15???????? 85c0 752f }
                                                                                    
    condition:
        7 of them and filesize < 319488
}