rule win_wastedloader_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.wastedloader."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.wastedloader"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 7444 eb00 686bb90000 ff15???????? }
                                                            
        $sequence_1 = { 7ed7 7488 09b31ced6185 1ce2 }
                                                            
        $sequence_2 = { e8???????? 3d1e050000 c10147 833b38 }
                                                            
        $sequence_3 = { a828 b409 1c04 e8???????? }
                                                            
        $sequence_4 = { 7aec e471 e8???????? 0057bb 038919fc885d e479 }
                                                                                    
        $sequence_5 = { b9b5000000 8b55f8 66894a4c 8b45f8 }
                                                            
        $sequence_6 = { 8b45f8 66895056 b9b8000000 8b55f8 66894a58 8b45f8 0fb74858 }
                                                                                                
        $sequence_7 = { 0200 00e7 aa 53 }
                                                            
        $sequence_8 = { 2cbe 832061 5b 5b }
                                                            
        $sequence_9 = { 8b55f8 0fb7421e 83e854 8b4df8 6689411e ba86000000 }
                                                                                    
    condition:
        7 of them and filesize < 2677760
}