rule MALPEDIA_Win_Crat_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "5ca84b15-9c50-5146-aeb0-8e43c37e0140"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.crat"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.crat_auto.yar#L1-L175"
    license_url        = "N/A"
    logic_hash         = "a19b8917ee2e01478bdd8090b22583a65c2cc48e63af4151406da25e5b4c7a8a"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0  = { e8 ?? ?? ?? ?? 48 8b d0 48 8d 8d 90 01 00 00 e8 ?? ?? ?? ?? 90 }
    $sequence_1  = { e8 ?? ?? ?? ?? 48 8b d0 48 8d 8d 88 00 00 00 e8 ?? ?? ?? ?? 90 }
    $sequence_2  = { 74 06 e8 ?? ?? ?? ?? 90 48 8b 54 24 20 48 83 c2 e8 }
    $sequence_3  = { e8 ?? ?? ?? ?? 48 8b c8 48 85 c0 74 33 }
    $sequence_4  = { e8 ?? ?? ?? ?? 48 8b d0 48 8d 8d a8 01 00 00 e8 ?? ?? ?? ?? 90 }
    $sequence_5  = { 48 f7 c2 00 00 ff ff 75 23 0f b7 fa 8b cf e8 ?? ?? ?? ?? 48 85 c0 74 27 }
    $sequence_6  = { e8 ?? ?? ?? ?? 48 8b d0 48 8d 4d 58 e8 ?? ?? ?? ?? 90 }
    $sequence_7  = { eb d0 49 8b c4 48 83 3d ?? ?? ?? ?? 10 48 0f 43 05 ?? ?? ?? ?? 48 2b c8 }
    $sequence_8  = { 33 d2 c1 e9 02 f7 f1 eb 02 }
    $sequence_9  = { ff d0 85 c0 75 0f ff 15 ?? ?? ?? ?? }
    $sequence_10 = { 8b cb e8 ?? ?? ?? ?? 8b 55 d8 8b 4b 0c }
    $sequence_11 = { 8b cb e8 ?? ?? ?? ?? 8b 4b 0c 8d 41 01 }
    $sequence_12 = { 8b 40 04 8b ca 3b c2 0f 47 c8 51 8b 4d 10 e8 ?? ?? ?? ?? }
    $sequence_13 = { 8b 4b 0c 8d 41 01 89 43 0c c6 01 00 8b 4d d4 41 }
    $sequence_14 = { 8b 43 24 66 89 48 fe c7 40 f8 00 00 00 00 c7 40 f4 00 00 00 00 c7 40 f0 00 00 00 00 5f 5e }
    $sequence_15 = { 8b 55 08 0f 57 c0 56 8b 75 0c b8 96 00 00 00 f3 0f 7f 01 }
    $sequence_16 = { 8b 4b 0c 8d 41 01 89 43 0c 8a 45 d3 88 01 8b 4d d4 41 }

  condition:
    7 of them and filesize < 4161536
}