rule rule_ProtectMyTooling_offensive_tool_keyword
{
    meta:
        description = "Detection patterns for the tool 'ProtectMyTooling' taken from the ThreatHunting-Keywords github project"
        author = "@mthcht"
        reference = "https://github.com/mthcht/ThreatHunting-Keywords"
        tool = "ProtectMyTooling"
        rule_category = "offensive_tool_keyword"

    strings:
                        $string1_ProtectMyTooling_offensive_tool_keyword = " --asstrongasfuck-opts " nocase ascii wide
                        $string2_ProtectMyTooling_offensive_tool_keyword = " --asstrongasfuck-path " nocase ascii wide
                        $string3_ProtectMyTooling_offensive_tool_keyword = " --atompepacker-args " nocase ascii wide
                        $string4_ProtectMyTooling_offensive_tool_keyword = " --backdoor-args " nocase ascii wide
                        $string5_ProtectMyTooling_offensive_tool_keyword = " --backdoor-path " nocase ascii wide
                        $string6_ProtectMyTooling_offensive_tool_keyword = " --backdoor-run " nocase ascii wide
                        $string7_ProtectMyTooling_offensive_tool_keyword = " --backdoor-save " nocase ascii wide
                        $string8_ProtectMyTooling_offensive_tool_keyword = " --callobf-config " nocase ascii wide
                        $string9_ProtectMyTooling_offensive_tool_keyword = " --callobf-path-x64 " nocase ascii wide
                        $string10_ProtectMyTooling_offensive_tool_keyword = " --callobf-path-x86 " nocase ascii wide
                        $string11_ProtectMyTooling_offensive_tool_keyword = " --confuserex-args " nocase ascii wide
                        $string12_ProtectMyTooling_offensive_tool_keyword = " --confuserex-module " nocase ascii wide
                        $string13_ProtectMyTooling_offensive_tool_keyword = " --confuserex-modules-in-dir " nocase ascii wide
                        $string14_ProtectMyTooling_offensive_tool_keyword = " --confuserex-path " nocase ascii wide
                        $string15_ProtectMyTooling_offensive_tool_keyword = " --confuserex-project-file " nocase ascii wide
                        $string16_ProtectMyTooling_offensive_tool_keyword = " --confuserex-save-generated-project-file " nocase ascii wide
                        $string17_ProtectMyTooling_offensive_tool_keyword = " --donut-cmdline " nocase ascii wide
                        $string18_ProtectMyTooling_offensive_tool_keyword = " -e shinject -r -E -t " nocase ascii wide
                        $string19_ProtectMyTooling_offensive_tool_keyword = " --enigma-path-x86 " nocase ascii wide
                        $string20_ProtectMyTooling_offensive_tool_keyword = " --enigma-protected-exe-cmdline " nocase ascii wide
                        $string21_ProtectMyTooling_offensive_tool_keyword = " --hyperion-args " nocase ascii wide
                        $string22_ProtectMyTooling_offensive_tool_keyword = " --hyperion-path " nocase ascii wide
                        $string23_ProtectMyTooling_offensive_tool_keyword = " --invobf-args " nocase ascii wide
                        $string24_ProtectMyTooling_offensive_tool_keyword = " --invobf-powershell " nocase ascii wide
                        $string25_ProtectMyTooling_offensive_tool_keyword = " --mangle-strip-go " nocase ascii wide
                        $string26_ProtectMyTooling_offensive_tool_keyword = " --netreactor-control-flow-obfuscation " nocase ascii wide
                        $string27_ProtectMyTooling_offensive_tool_keyword = " --netreactor-incremental-obfuscation " nocase ascii wide
                        $string28_ProtectMyTooling_offensive_tool_keyword = " --netreactor-obfuscate-public-types " nocase ascii wide
                        $string29_ProtectMyTooling_offensive_tool_keyword = " --netreactor-stealth-mode " nocase ascii wide
                        $string30_ProtectMyTooling_offensive_tool_keyword = " --nimcrypt2-llvm-obfuscator " nocase ascii wide
                        $string31_ProtectMyTooling_offensive_tool_keyword = " --nimsyscall-hellsgate " nocase ascii wide
                        $string32_ProtectMyTooling_offensive_tool_keyword = " --nimsyscall-noamsi " nocase ascii wide
                        $string33_ProtectMyTooling_offensive_tool_keyword = " --nimsyscall-obfuscate " nocase ascii wide
                        $string34_ProtectMyTooling_offensive_tool_keyword = " --nimsyscall-obfuscatefunctions " nocase ascii wide
                        $string35_ProtectMyTooling_offensive_tool_keyword = " --nimsyscall-peinject " nocase ascii wide
                        $string36_ProtectMyTooling_offensive_tool_keyword = " --nimsyscall-reflective " nocase ascii wide
                        $string37_ProtectMyTooling_offensive_tool_keyword = " --nimsyscall-remoteinject " nocase ascii wide
                        $string38_ProtectMyTooling_offensive_tool_keyword = " --nimsyscall-remotepatchamsi " nocase ascii wide
                        $string39_ProtectMyTooling_offensive_tool_keyword = " --nimsyscall-remotepatchetw " nocase ascii wide
                        $string40_ProtectMyTooling_offensive_tool_keyword = " --nimsyscall-remoteprocess " nocase ascii wide
                        $string41_ProtectMyTooling_offensive_tool_keyword = " --nimsyscall-selfdelete " nocase ascii wide
                        $string42_ProtectMyTooling_offensive_tool_keyword = " --nimsyscall-shellcode " nocase ascii wide
                        $string43_ProtectMyTooling_offensive_tool_keyword = " --nimsyscall-sleepycrypt " nocase ascii wide
                        $string44_ProtectMyTooling_offensive_tool_keyword = " --nimsyscall-syswhispers " nocase ascii wide
                        $string45_ProtectMyTooling_offensive_tool_keyword = /\sProtectMyTooling\.py/ nocase ascii wide
                        $string46_ProtectMyTooling_offensive_tool_keyword = /\sProtectMyToolingGUI\.py/ nocase ascii wide
                        $string47_ProtectMyTooling_offensive_tool_keyword = /\sRedBackdoorer\.py/ nocase ascii wide
                        $string48_ProtectMyTooling_offensive_tool_keyword = " --scarecrow-inject " nocase ascii wide
                        $string49_ProtectMyTooling_offensive_tool_keyword = " --smartassembly-methodparentobfuscation " nocase ascii wide
                        $string50_ProtectMyTooling_offensive_tool_keyword = " --smartassembly-nameobfuscate " nocase ascii wide
                        $string51_ProtectMyTooling_offensive_tool_keyword = " --smartassembly-typemethodobfuscation " nocase ascii wide
                        $string52_ProtectMyTooling_offensive_tool_keyword = " --srdi-obfuscate-imports " nocase ascii wide
                        $string53_ProtectMyTooling_offensive_tool_keyword = /\(\'Successfully\sbackdoored\sentry\spoint\swith\sjump\/call\sto\sshellcode/ nocase ascii wide
                        $string54_ProtectMyTooling_offensive_tool_keyword = /\.py\scallobf\,upx\,hyperion\s.{0,1000}\.exe/ nocase ascii wide
                        $string55_ProtectMyTooling_offensive_tool_keyword = /\.py\s\-e\sexecute\-assembly\s\-i\s/ nocase ascii wide
                        $string56_ProtectMyTooling_offensive_tool_keyword = /\/AsStrongAsFuck\.exe/ nocase ascii wide
                        $string57_ProtectMyTooling_offensive_tool_keyword = /\/asstrongasfuck\.py/ nocase ascii wide
                        $string58_ProtectMyTooling_offensive_tool_keyword = /\/confuserex\.py/ nocase ascii wide
                        $string59_ProtectMyTooling_offensive_tool_keyword = /\/donut\-packer\.py/ nocase ascii wide
                        $string60_ProtectMyTooling_offensive_tool_keyword = /\/ProtectMyTooling\.git/ nocase ascii wide
                        $string61_ProtectMyTooling_offensive_tool_keyword = /\/ProtectMyTooling\.py/ nocase ascii wide
                        $string62_ProtectMyTooling_offensive_tool_keyword = /\/ProtectMyTooling\.yaml/ nocase ascii wide
                        $string63_ProtectMyTooling_offensive_tool_keyword = /\/ProtectMyToolingGUI\.py/ nocase ascii wide
                        $string64_ProtectMyTooling_offensive_tool_keyword = /\/RedBackdoorer\.py/ nocase ascii wide
                        $string65_ProtectMyTooling_offensive_tool_keyword = ":: RedBackdoorer" nocase ascii wide
                        $string66_ProtectMyTooling_offensive_tool_keyword = ":: RedWatermarker" nocase ascii wide
                        $string67_ProtectMyTooling_offensive_tool_keyword = /\[\+\]\sInjecting\sShellcode\sinto\sRemote\sProcess/ nocase ascii wide
                        $string68_ProtectMyTooling_offensive_tool_keyword = /\[\+\]\sPPID\sspoofing\senabled/ nocase ascii wide
                        $string69_ProtectMyTooling_offensive_tool_keyword = /\[\+\]\sUsing\sObfuscator\-LLVM\sto\scompile/ nocase ascii wide
                        $string70_ProtectMyTooling_offensive_tool_keyword = /\\AsStrongAsFuck\.exe/ nocase ascii wide
                        $string71_ProtectMyTooling_offensive_tool_keyword = /\\asstrongasfuck\.py/ nocase ascii wide
                        $string72_ProtectMyTooling_offensive_tool_keyword = /\\beacon\-obf\.exe/ nocase ascii wide
                        $string73_ProtectMyTooling_offensive_tool_keyword = /\\cobaltProtectMyTooling\.conf/ nocase ascii wide
                        $string74_ProtectMyTooling_offensive_tool_keyword = /\\Confuser\.CLI\.exe/ nocase ascii wide
                        $string75_ProtectMyTooling_offensive_tool_keyword = /\\confuserex\.py/ nocase ascii wide
                        $string76_ProtectMyTooling_offensive_tool_keyword = /\\dbgview64\-infected\.exe/ nocase ascii wide
                        $string77_ProtectMyTooling_offensive_tool_keyword = /\\donut\-packer\.py/ nocase ascii wide
                        $string78_ProtectMyTooling_offensive_tool_keyword = /\\Invoke\-Obfuscation/ nocase ascii wide
                        $string79_ProtectMyTooling_offensive_tool_keyword = /\\ProtectMyTooling\.cna/ nocase ascii wide
                        $string80_ProtectMyTooling_offensive_tool_keyword = /\\ProtectMyTooling\.py/ nocase ascii wide
                        $string81_ProtectMyTooling_offensive_tool_keyword = /\\ProtectMyTooling\.yaml/ nocase ascii wide
                        $string82_ProtectMyTooling_offensive_tool_keyword = /\\ProtectMyToolingGUI\.py/ nocase ascii wide
                        $string83_ProtectMyTooling_offensive_tool_keyword = /\\RedBackdoorer\.py/ nocase ascii wide
                        $string84_ProtectMyTooling_offensive_tool_keyword = /\\signed\-executables\\svchost\.exe/ nocase ascii wide
                        $string85_ProtectMyTooling_offensive_tool_keyword = "163599fee9456a8e2af271824da6e39cfd6aceabb7a62961b8c1a911b94725d6" nocase ascii wide
                        $string86_ProtectMyTooling_offensive_tool_keyword = "3615ddbae2c65e978aa8006c26b5c4a66c2e9433a1460b17ef700a39a708e5c1" nocase ascii wide
                        $string87_ProtectMyTooling_offensive_tool_keyword = "40ce2ea4f4a90332a6e554ddbd9b801e22df018458127ae6ad1243c7d25a5523" nocase ascii wide
                        $string88_ProtectMyTooling_offensive_tool_keyword = "40d86b833531b7f216caa95443f4eb6f0e5b15764072a5708d62380bac2f8ff4" nocase ascii wide
                        $string89_ProtectMyTooling_offensive_tool_keyword = "46793c55c24e616a0d4eaaa0090b70bdde05e50c1b58da753d09063e6e838cc6" nocase ascii wide
                        $string90_ProtectMyTooling_offensive_tool_keyword = "525bb5e67378b9bdc298aceb9e0108603741ae334e8ce748222999fcb2f1d818" nocase ascii wide
                        $string91_ProtectMyTooling_offensive_tool_keyword = "534b0370d1bff7e4a0f327d7fa01679a10cfffc67dbefa5f45e49dbbadec7fa3" nocase ascii wide
                        $string92_ProtectMyTooling_offensive_tool_keyword = "5ed84b98241dd1db44e9e3beae6ec07ce8c64cd9200b73954617113578f91317" nocase ascii wide
                        $string93_ProtectMyTooling_offensive_tool_keyword = "5fa4acad2bf202e61149a7f47189c4d60ac2823ea26d0f449912ab9d28ad0806" nocase ascii wide
                        $string94_ProtectMyTooling_offensive_tool_keyword = "66d16546824f6e98b531bfdfe411ba4b837e99362f735ed2dd61ead2aae4ab91" nocase ascii wide
                        $string95_ProtectMyTooling_offensive_tool_keyword = "77c88d4c67b3600e78f82c938d2ef72525277647a27692b2114c9688bf1da121" nocase ascii wide
                        $string96_ProtectMyTooling_offensive_tool_keyword = "8a575a3e31ecbc724c5b7755ef14a0f645da3cd33ee57f9c91d74b1d94cdf772" nocase ascii wide
                        $string97_ProtectMyTooling_offensive_tool_keyword = "925365b64eb63bafba4fb5c44494428026d98c1a71fc4b54d638c4c22c6e26a7" nocase ascii wide
                        $string98_ProtectMyTooling_offensive_tool_keyword = "9521883a37c093f31e9d3fde7d3293f637ea51ce573c3fa7967843b7e51d8dd0" nocase ascii wide
                        $string99_ProtectMyTooling_offensive_tool_keyword = "9b33e5ff2cc99df282013554ee5cc3a9a0fe737510af24717b48f93c5d66b94a" nocase ascii wide
                        $string100_ProtectMyTooling_offensive_tool_keyword = "9c409702151446f1eb8d951b45a902f2dbad1ebeacab9dd9beeaa5530e65ad0c" nocase ascii wide
                        $string101_ProtectMyTooling_offensive_tool_keyword = "a10190903dfb52127ae37214a8c0124c68fc2f7fc91d0bae55eb9f556fa3c8dd" nocase ascii wide
                        $string102_ProtectMyTooling_offensive_tool_keyword = "a83c33f484a2cbff3bbefdf51880714968930f69778e8921d8182d2b96e03314" nocase ascii wide
                        $string103_ProtectMyTooling_offensive_tool_keyword = "abd9f4b93fc3f2bb0612bfbdef4e0da8797e985e7377ee0c08c2b5b5198c2743" nocase ascii wide
                        $string104_ProtectMyTooling_offensive_tool_keyword = "Append IOC watermark to injected shellcode" nocase ascii wide
                        $string105_ProtectMyTooling_offensive_tool_keyword = "b3ae1abc15df71a69f3a629fbe5a168acc7514905d8fd82eb8c62e60f61e846e" nocase ascii wide
                        $string106_ProtectMyTooling_offensive_tool_keyword = "Backdoored PE file save" nocase ascii wide
                        $string107_ProtectMyTooling_offensive_tool_keyword = "be642266-f34d-43c3-b6e4-eebf8e489519" nocase ascii wide
                        $string108_ProtectMyTooling_offensive_tool_keyword = "Binary-Offensive/ProtectMyTooling" nocase ascii wide
                        $string109_ProtectMyTooling_offensive_tool_keyword = "c39d2a1c303847785a2a2af357dd948f5e6ec8194eb427c52a391db90de34f72" nocase ascii wide
                        $string110_ProtectMyTooling_offensive_tool_keyword = "cecbe047e33d2dc3bc06cc7a62546a4e1a793d8da1dde4ba3aa021f944930d6d" nocase ascii wide
                        $string111_ProtectMyTooling_offensive_tool_keyword = "d43ceb0d2efb5fdee19d4f7b2448c7f69a6c5d24bfdfd21f5e0fce570fb47d79" nocase ascii wide
                        $string112_ProtectMyTooling_offensive_tool_keyword = "d683205c9fad76e28a8e4cd0d72285e9a8573cc95c8b77f30186089459675817" nocase ascii wide
                        $string113_ProtectMyTooling_offensive_tool_keyword = "ddcc3057b5c499e1e90d914d9da185d5860f0e9f44a3e5b8f5c9396eaa216ce0" nocase ascii wide
                        $string114_ProtectMyTooling_offensive_tool_keyword = "e403c105e8167585b1c431cdc86c943a8f93e876b3940668d088b976d8a1e9a2" nocase ascii wide
                        $string115_ProtectMyTooling_offensive_tool_keyword = "e5509a144cb371b7afe6fb6a526fca317688da6b27bfcb7be1faf8fffd58a472" nocase ascii wide
                        $string116_ProtectMyTooling_offensive_tool_keyword = "edb161280fe76c89768cab2f9493295671042046f106a7686854f8b5ed118249" nocase ascii wide
                        $string117_ProtectMyTooling_offensive_tool_keyword = "ee68d7deb7cefdfca66c078d6036d7aa3aa7afcc62b282999034b4a1faed890d" nocase ascii wide
                        $string118_ProtectMyTooling_offensive_tool_keyword = "f109966b6fc1f0ea412a05078baaa79667529be0a387070da7c458a914a07e8e" nocase ascii wide
                        $string119_ProtectMyTooling_offensive_tool_keyword = "f487a8b9f72e87a862c6380d316e93dc4bd0a7e7087d6f430e369885db1d5d3d" nocase ascii wide
                        $string120_ProtectMyTooling_offensive_tool_keyword = "f80f4c638c843e17f384851f397322eaec414b3718ce79056abc15a6644f466f" nocase ascii wide
                        $string121_ProtectMyTooling_offensive_tool_keyword = /hyperion\.exe\s.{0,1000}\.exe.{0,1000}\s.{0,1000}\.exe/ nocase ascii wide
                        $string122_ProtectMyTooling_offensive_tool_keyword = /mgeeky\.tech\/protectmytooling\// nocase ascii wide
                        $string123_ProtectMyTooling_offensive_tool_keyword = "mgeeky@commandoVM" nocase ascii wide
                        $string124_ProtectMyTooling_offensive_tool_keyword = /mimikatz\-obf\.exe/ nocase ascii wide
                        $string125_ProtectMyTooling_offensive_tool_keyword = /NimPackt\.py\s\-i\s/ nocase ascii wide
                        $string126_ProtectMyTooling_offensive_tool_keyword = /Out\-EncodedAsciiCommand\.ps1/ nocase ascii wide
                        $string127_ProtectMyTooling_offensive_tool_keyword = /Out\-EncodedBinaryCommand\./ nocase ascii wide
                        $string128_ProtectMyTooling_offensive_tool_keyword = "Out-EncodedBXORCommand" nocase ascii wide
                        $string129_ProtectMyTooling_offensive_tool_keyword = /Out\-EncodedHexCommand\./ nocase ascii wide
                        $string130_ProtectMyTooling_offensive_tool_keyword = /Out\-EncodedOctalCommand\./ nocase ascii wide
                        $string131_ProtectMyTooling_offensive_tool_keyword = "Out-EncodedSpecialCharOnlyCommand" nocase ascii wide
                        $string132_ProtectMyTooling_offensive_tool_keyword = "Out-EncodedWhitespaceCommand" nocase ascii wide
                        $string133_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedArrayExpressionAst " nocase ascii wide
                        $string134_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedArrayLiteralAst " nocase ascii wide
                        $string135_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedAssignmentStatementAst " nocase ascii wide
                        $string136_ProtectMyTooling_offensive_tool_keyword = /Out\-ObfuscatedAst\.ps1/ nocase ascii wide
                        $string137_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedAstsReordered " nocase ascii wide
                        $string138_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedAttributeAst " nocase ascii wide
                        $string139_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedAttributeBaseAst " nocase ascii wide
                        $string140_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedAttributedExpressionAst " nocase ascii wide
                        $string141_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedBaseCtorInvokeMemberExpressionAst " nocase ascii wide
                        $string142_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedBinaryExpressionAst " nocase ascii wide
                        $string143_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedBlockStatementAst " nocase ascii wide
                        $string144_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedBreakStatementAst " nocase ascii wide
                        $string145_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedCatchClauseAst " nocase ascii wide
                        $string146_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedChildrenAst " nocase ascii wide
                        $string147_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedCommandAst " nocase ascii wide
                        $string148_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedCommandBaseAst " nocase ascii wide
                        $string149_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedCommandElementAst " nocase ascii wide
                        $string150_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedCommandExpressionAst " nocase ascii wide
                        $string151_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedCommandParameterAst " nocase ascii wide
                        $string152_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedConfigurationDefinitionAst " nocase ascii wide
                        $string153_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedConstantExpressionAst " nocase ascii wide
                        $string154_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedContinueStatementAst " nocase ascii wide
                        $string155_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedConvertExpressionAst " nocase ascii wide
                        $string156_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedDataStatementAst " nocase ascii wide
                        $string157_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedDoUntilStatementAst " nocase ascii wide
                        $string158_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedDoWhileStatementAst " nocase ascii wide
                        $string159_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedDynamicKeywordStatementAst " nocase ascii wide
                        $string160_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedErrorExpressionAst " nocase ascii wide
                        $string161_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedErrorStatementAst " nocase ascii wide
                        $string162_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedExitStatementAst " nocase ascii wide
                        $string163_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedExpandableStringExpressionAst " nocase ascii wide
                        $string164_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedExpressionAst " nocase ascii wide
                        $string165_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedFileRedirectionAst " nocase ascii wide
                        $string166_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedForEachStatementAst " nocase ascii wide
                        $string167_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedForStatementAst " nocase ascii wide
                        $string168_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedFunctionDefinitionAst " nocase ascii wide
                        $string169_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedFunctionMemberAst " nocase ascii wide
                        $string170_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedHashtableAst " nocase ascii wide
                        $string171_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedIfStatementAst " nocase ascii wide
                        $string172_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedIndexExpressionAst " nocase ascii wide
                        $string173_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedInvokeMemberExpressionAst " nocase ascii wide
                        $string174_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedLabeledStatementAst " nocase ascii wide
                        $string175_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedLoopStatementAst " nocase ascii wide
                        $string176_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedMemberAst " nocase ascii wide
                        $string177_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedMemberExpressionAst " nocase ascii wide
                        $string178_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedMergingRedirectionAst " nocase ascii wide
                        $string179_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedNamedAttributeArgumentAst " nocase ascii wide
                        $string180_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedNamedBlockAst " nocase ascii wide
                        $string181_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedParamBlockAst " nocase ascii wide
                        $string182_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedParameterAst " nocase ascii wide
                        $string183_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedParenExpressionAst " nocase ascii wide
                        $string184_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedPipelineAst " nocase ascii wide
                        $string185_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedPipelineBaseAst " nocase ascii wide
                        $string186_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedPropertyMemberAst " nocase ascii wide
                        $string187_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedRedirectionAst " nocase ascii wide
                        $string188_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedReturnStatementAst " nocase ascii wide
                        $string189_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedScriptBlockAst " nocase ascii wide
                        $string190_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedScriptBlockExpressionAst " nocase ascii wide
                        $string191_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedStatementAst " nocase ascii wide
                        $string192_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedStatementBlockAst " nocase ascii wide
                        $string193_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedStringCommand" nocase ascii wide
                        $string194_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedStringConstantExpressionAst " nocase ascii wide
                        $string195_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedSubExpressionAst " nocase ascii wide
                        $string196_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedSwitchStatementAst " nocase ascii wide
                        $string197_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedThrowStatementAst " nocase ascii wide
                        $string198_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedTokenCommand" nocase ascii wide
                        $string199_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedTrapStatementAst " nocase ascii wide
                        $string200_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedTryStatementAst " nocase ascii wide
                        $string201_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedTypeConstraintAst " nocase ascii wide
                        $string202_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedTypeDefinitionAst " nocase ascii wide
                        $string203_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedTypeExpressionAst " nocase ascii wide
                        $string204_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedUnaryExpressionAst " nocase ascii wide
                        $string205_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedUsingExpressionAst " nocase ascii wide
                        $string206_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedUsingStatementAst " nocase ascii wide
                        $string207_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedVariableExpressionAst " nocase ascii wide
                        $string208_ProtectMyTooling_offensive_tool_keyword = "Out-ObfuscatedWhileStatementAst " nocase ascii wide
                        $string209_ProtectMyTooling_offensive_tool_keyword = "Out-ParenthesizedString " nocase ascii wide
                        $string210_ProtectMyTooling_offensive_tool_keyword = /packers\/invobf\.py/ nocase ascii wide
                        $string211_ProtectMyTooling_offensive_tool_keyword = /packers\\invobf\.py/ nocase ascii wide
                        $string212_ProtectMyTooling_offensive_tool_keyword = "pip install donut-shellcode" nocase ascii wide
                        $string213_ProtectMyTooling_offensive_tool_keyword = /ProtectMyToolingGUI\.pyw/ nocase ascii wide
                        $string214_ProtectMyTooling_offensive_tool_keyword = /ProtectMyTooling\-master\.zip/ nocase ascii wide
                        $string215_ProtectMyTooling_offensive_tool_keyword = /putty\-infected\.exe/ nocase ascii wide
                        $string216_ProtectMyTooling_offensive_tool_keyword = /Rubeus\-obf\.exe/ nocase ascii wide
                        $string217_ProtectMyTooling_offensive_tool_keyword = /upx\s\-\-brute\s.{0,1000}\.exe/ nocase ascii wide
                        $string218_ProtectMyTooling_offensive_tool_keyword = /upx\s\-ultra\-brute\s.{0,1000}\.exe/ nocase ascii wide
                        $string219_ProtectMyTooling_offensive_tool_keyword = "Your finest PE backdooring companion" nocase ascii wide

    condition:
        any of them
}