rule rule_JohnTheRipper_offensive_tool_keyword
{
    meta:
        description = "Detection patterns for the tool 'JohnTheRipper' taken from the ThreatHunting-Keywords github project"
        author = "@mthcht"
        reference = "https://github.com/mthcht/ThreatHunting-Keywords"
        tool = "JohnTheRipper"
        rule_category = "offensive_tool_keyword"

    strings:
                        $string1_JohnTheRipper_offensive_tool_keyword = " bleeding-jumbo john" nocase ascii wide
                        $string2_JohnTheRipper_offensive_tool_keyword = " --crack-status" nocase ascii wide
                        $string3_JohnTheRipper_offensive_tool_keyword = /\s\-\-format\=netntlmv2\s.{0,100}\.txt/ nocase ascii wide
                        $string4_JohnTheRipper_offensive_tool_keyword = /\s\-\-format\=NT\s\-w\=.{0,100}_password\.txt/
                        $string5_JohnTheRipper_offensive_tool_keyword = /\shack\.py/ nocase ascii wide
                        $string6_JohnTheRipper_offensive_tool_keyword = /\s\-inc\s\-u\=0\s.{0,100}\.pwd/ nocase ascii wide
                        $string7_JohnTheRipper_offensive_tool_keyword = " -inc=digits " nocase ascii wide
                        $string8_JohnTheRipper_offensive_tool_keyword = " john_done" nocase ascii wide
                        $string9_JohnTheRipper_offensive_tool_keyword = " john_fork" nocase ascii wide
                        $string10_JohnTheRipper_offensive_tool_keyword = " john_load" nocase ascii wide
                        $string11_JohnTheRipper_offensive_tool_keyword = " john_load_conf" nocase ascii wide
                        $string12_JohnTheRipper_offensive_tool_keyword = " john_load_conf_db" nocase ascii wide
                        $string13_JohnTheRipper_offensive_tool_keyword = " john_log_format" nocase ascii wide
                        $string14_JohnTheRipper_offensive_tool_keyword = " john_log_format2" nocase ascii wide
                        $string15_JohnTheRipper_offensive_tool_keyword = " john_mpi_wait" nocase ascii wide
                        $string16_JohnTheRipper_offensive_tool_keyword = " john_omp_fallback" nocase ascii wide
                        $string17_JohnTheRipper_offensive_tool_keyword = " john_omp_init" nocase ascii wide
                        $string18_JohnTheRipper_offensive_tool_keyword = " john_omp_maybe_adjust_or_fallback" nocase ascii wide
                        $string19_JohnTheRipper_offensive_tool_keyword = " john_omp_show_info" nocase ascii wide
                        $string20_JohnTheRipper_offensive_tool_keyword = " john_register_all" nocase ascii wide
                        $string21_JohnTheRipper_offensive_tool_keyword = " john_register_one" nocase ascii wide
                        $string22_JohnTheRipper_offensive_tool_keyword = " john_run" nocase ascii wide
                        $string23_JohnTheRipper_offensive_tool_keyword = " john_set_mpi" nocase ascii wide
                        $string24_JohnTheRipper_offensive_tool_keyword = " john_set_tristates" nocase ascii wide
                        $string25_JohnTheRipper_offensive_tool_keyword = " john_wait" nocase ascii wide
                        $string26_JohnTheRipper_offensive_tool_keyword = " JohnTheRipper/" nocase ascii wide
                        $string27_JohnTheRipper_offensive_tool_keyword = " --list=hidden-options" nocase ascii wide
                        $string28_JohnTheRipper_offensive_tool_keyword = " load_extra_pots" nocase ascii wide
                        $string29_JohnTheRipper_offensive_tool_keyword = /\smask\?a\?a\?a\?a\?/ nocase ascii wide
                        $string30_JohnTheRipper_offensive_tool_keyword = /\s\-\-mask\=\?1\?1\?1.{0,100}\s\-\-min\-len/ nocase ascii wide
                        $string31_JohnTheRipper_offensive_tool_keyword = /\spassword\.lst/ nocase ascii wide
                        $string32_JohnTheRipper_offensive_tool_keyword = /\srockyou\.txt\s/ nocase ascii wide
                        $string33_JohnTheRipper_offensive_tool_keyword = " --rules:Jumbo " nocase ascii wide
                        $string34_JohnTheRipper_offensive_tool_keyword = " --session=allrules --wordlist" nocase ascii wide
                        $string35_JohnTheRipper_offensive_tool_keyword = " --show passwd"
                        $string36_JohnTheRipper_offensive_tool_keyword = /\s\-\-single\sshadow\.hashes/ nocase ascii wide
                        $string37_JohnTheRipper_offensive_tool_keyword = /\s\-\-wordlist\=.{0,100}\.lst/ nocase ascii wide
                        $string38_JohnTheRipper_offensive_tool_keyword = /\/ike\-crack\./ nocase ascii wide
                        $string39_JohnTheRipper_offensive_tool_keyword = "/john -"
                        $string40_JohnTheRipper_offensive_tool_keyword = /\/john\/run\/.{0,100}\.pl/ nocase ascii wide
                        $string41_JohnTheRipper_offensive_tool_keyword = /\/john\/run\/.{0,100}\.py/ nocase ascii wide
                        $string42_JohnTheRipper_offensive_tool_keyword = "/JohnTheRipper" nocase ascii wide
                        $string43_JohnTheRipper_offensive_tool_keyword = /\/netntlm\.pl/ nocase ascii wide
                        $string44_JohnTheRipper_offensive_tool_keyword = /\/pass_gen\.pl/ nocase ascii wide
                        $string45_JohnTheRipper_offensive_tool_keyword = /\/password\.lst/ nocase ascii wide
                        $string46_JohnTheRipper_offensive_tool_keyword = /\/run\/leet\.pl/ nocase ascii wide
                        $string47_JohnTheRipper_offensive_tool_keyword = /\/src\/john\.com/ nocase ascii wide
                        $string48_JohnTheRipper_offensive_tool_keyword = /\/src\/jumbo\.c/ nocase ascii wide
                        $string49_JohnTheRipper_offensive_tool_keyword = /\/src\/jumbo\.h/ nocase ascii wide
                        $string50_JohnTheRipper_offensive_tool_keyword = /\/tests\/NIST_CAVS\/.{0,100}\.rsp/ nocase ascii wide
                        $string51_JohnTheRipper_offensive_tool_keyword = /\/unused\/locktest\.sh/ nocase ascii wide
                        $string52_JohnTheRipper_offensive_tool_keyword = /\/unused\/Yosemite\.patch/ nocase ascii wide
                        $string53_JohnTheRipper_offensive_tool_keyword = /\/word_list\.c/
                        $string54_JohnTheRipper_offensive_tool_keyword = /\/word_list\.h/
                        $string55_JohnTheRipper_offensive_tool_keyword = /\\password\.lst/ nocase ascii wide
                        $string56_JohnTheRipper_offensive_tool_keyword = /\\run\\john\s/ nocase ascii wide
                        $string57_JohnTheRipper_offensive_tool_keyword = /\\run\\john\\.{0,100}\./ nocase ascii wide
                        $string58_JohnTheRipper_offensive_tool_keyword = /\\run\\john\\.{0,100}\.com/ nocase ascii wide
                        $string59_JohnTheRipper_offensive_tool_keyword = /\\run\\john\\.{0,100}\.pl/ nocase ascii wide
                        $string60_JohnTheRipper_offensive_tool_keyword = /\\run\\john\\.{0,100}\.py/ nocase ascii wide
                        $string61_JohnTheRipper_offensive_tool_keyword = /1password2john\.py/ nocase ascii wide
                        $string62_JohnTheRipper_offensive_tool_keyword = /2john\.c/ nocase ascii wide
                        $string63_JohnTheRipper_offensive_tool_keyword = /2john\.lua/ nocase ascii wide
                        $string64_JohnTheRipper_offensive_tool_keyword = /2john\.pl/ nocase ascii wide
                        $string65_JohnTheRipper_offensive_tool_keyword = /2john\.py/ nocase ascii wide
                        $string66_JohnTheRipper_offensive_tool_keyword = /7z2john\.pl/ nocase ascii wide
                        $string67_JohnTheRipper_offensive_tool_keyword = /adxcsouf2john\.py/ nocase ascii wide
                        $string68_JohnTheRipper_offensive_tool_keyword = /aem2john\.py/ nocase ascii wide
                        $string69_JohnTheRipper_offensive_tool_keyword = /aix2john\.pl/ nocase ascii wide
                        $string70_JohnTheRipper_offensive_tool_keyword = /aix2john\.py/ nocase ascii wide
                        $string71_JohnTheRipper_offensive_tool_keyword = /andotp2john\.py/ nocase ascii wide
                        $string72_JohnTheRipper_offensive_tool_keyword = /androidbackup2john\.py/ nocase ascii wide
                        $string73_JohnTheRipper_offensive_tool_keyword = /androidfde2john\.py/ nocase ascii wide
                        $string74_JohnTheRipper_offensive_tool_keyword = /ansible2john\.py/ nocase ascii wide
                        $string75_JohnTheRipper_offensive_tool_keyword = /apex2john\.py/ nocase ascii wide
                        $string76_JohnTheRipper_offensive_tool_keyword = /apop2john\.py/ nocase ascii wide
                        $string77_JohnTheRipper_offensive_tool_keyword = /applenotes2john\.py/ nocase ascii wide
                        $string78_JohnTheRipper_offensive_tool_keyword = /apt.{0,100}\sinstall\sjohn/ nocase ascii wide
                        $string79_JohnTheRipper_offensive_tool_keyword = /aruba2john\.py/ nocase ascii wide
                        $string80_JohnTheRipper_offensive_tool_keyword = /atmail2john\.pl/ nocase ascii wide
                        $string81_JohnTheRipper_offensive_tool_keyword = /axcrypt2john\.py/ nocase ascii wide
                        $string82_JohnTheRipper_offensive_tool_keyword = "-b bleeding-jumbo" nocase ascii wide
                        $string83_JohnTheRipper_offensive_tool_keyword = /BCHASH\-Rijndael\-128\.unverified\.test\-vectors\.txt/ nocase ascii wide
                        $string84_JohnTheRipper_offensive_tool_keyword = /BCHASH\-Rijndael\-256\.unverified\.test\-vectors\.txt/ nocase ascii wide
                        $string85_JohnTheRipper_offensive_tool_keyword = /bestcrypt2john\.py/ nocase ascii wide
                        $string86_JohnTheRipper_offensive_tool_keyword = /bestcryptve2john\.py/ nocase ascii wide
                        $string87_JohnTheRipper_offensive_tool_keyword = /bitcoin2john\.py/ nocase ascii wide
                        $string88_JohnTheRipper_offensive_tool_keyword = /bitshares2john\.py/ nocase ascii wide
                        $string89_JohnTheRipper_offensive_tool_keyword = /bitwarden2john\.py/ nocase ascii wide
                        $string90_JohnTheRipper_offensive_tool_keyword = /bks2john\.py/ nocase ascii wide
                        $string91_JohnTheRipper_offensive_tool_keyword = /blockchain2john\.py/ nocase ascii wide
                        $string92_JohnTheRipper_offensive_tool_keyword = /cardano2john\.py/ nocase ascii wide
                        $string93_JohnTheRipper_offensive_tool_keyword = /ccache2john\.py/ nocase ascii wide
                        $string94_JohnTheRipper_offensive_tool_keyword = /ccache2john\.py/ nocase ascii wide
                        $string95_JohnTheRipper_offensive_tool_keyword = /cisco2john\.pl/ nocase ascii wide
                        $string96_JohnTheRipper_offensive_tool_keyword = /coinomi2john\.py/ nocase ascii wide
                        $string97_JohnTheRipper_offensive_tool_keyword = /cracf2john\.py/ nocase ascii wide
                        $string98_JohnTheRipper_offensive_tool_keyword = "crk_get_key1" nocase ascii wide
                        $string99_JohnTheRipper_offensive_tool_keyword = "crk_get_key2" nocase ascii wide
                        $string100_JohnTheRipper_offensive_tool_keyword = "crk_max_keys_per_crypt" nocase ascii wide
                        $string101_JohnTheRipper_offensive_tool_keyword = /crk_methods\./ nocase ascii wide
                        $string102_JohnTheRipper_offensive_tool_keyword = "crk_password_loop" nocase ascii wide
                        $string103_JohnTheRipper_offensive_tool_keyword = /dashlane2john\.py/ nocase ascii wide
                        $string104_JohnTheRipper_offensive_tool_keyword = /deepsound2john\.py/ nocase ascii wide
                        $string105_JohnTheRipper_offensive_tool_keyword = /diskcryptor2john\.py/ nocase ascii wide
                        $string106_JohnTheRipper_offensive_tool_keyword = /dmg2john\.py/ nocase ascii wide
                        $string107_JohnTheRipper_offensive_tool_keyword = /doc\/extras\/HACKING\./ nocase ascii wide
                        $string108_JohnTheRipper_offensive_tool_keyword = /DPAPImk2john\.py/ nocase ascii wide
                        $string109_JohnTheRipper_offensive_tool_keyword = "eapmd5tojohn" nocase ascii wide
                        $string110_JohnTheRipper_offensive_tool_keyword = /ecryptfs2john\.py/ nocase ascii wide
                        $string111_JohnTheRipper_offensive_tool_keyword = /ejabberd2john\.py/ nocase ascii wide
                        $string112_JohnTheRipper_offensive_tool_keyword = /electrum2john\.py/ nocase ascii wide
                        $string113_JohnTheRipper_offensive_tool_keyword = /encdatavault2john\.py/ nocase ascii wide
                        $string114_JohnTheRipper_offensive_tool_keyword = /encfs2john\.py/ nocase ascii wide
                        $string115_JohnTheRipper_offensive_tool_keyword = /enpass2john\.py/ nocase ascii wide
                        $string116_JohnTheRipper_offensive_tool_keyword = /enpass5tojohn\.py/ nocase ascii wide
                        $string117_JohnTheRipper_offensive_tool_keyword = /ethereum2john\.py/ nocase ascii wide
                        $string118_JohnTheRipper_offensive_tool_keyword = "fcrackzip " nocase ascii wide
                        $string119_JohnTheRipper_offensive_tool_keyword = /filezilla2john\.py/ nocase ascii wide
                        $string120_JohnTheRipper_offensive_tool_keyword = /fuzz_option\.pl/ nocase ascii wide
                        $string121_JohnTheRipper_offensive_tool_keyword = /geli2john\.py/ nocase ascii wide
                        $string122_JohnTheRipper_offensive_tool_keyword = "genmkvpwd " nocase ascii wide
                        $string123_JohnTheRipper_offensive_tool_keyword = /gpg2john\./ nocase ascii wide
                        $string124_JohnTheRipper_offensive_tool_keyword = /hccapx2john\.py/ nocase ascii wide
                        $string125_JohnTheRipper_offensive_tool_keyword = /htdigest2john\.py/ nocase ascii wide
                        $string126_JohnTheRipper_offensive_tool_keyword = /http.{0,100}\/john\/Test\/raw\/master\// nocase ascii wide
                        $string127_JohnTheRipper_offensive_tool_keyword = /ibmiscanner2john\.py/ nocase ascii wide
                        $string128_JohnTheRipper_offensive_tool_keyword = /ikescan2john\.py/ nocase ascii wide
                        $string129_JohnTheRipper_offensive_tool_keyword = "insert_top_100_passwords_1_G" nocase ascii wide
                        $string130_JohnTheRipper_offensive_tool_keyword = /InsidePro\-PasswordsPro\.rule/ nocase ascii wide
                        $string131_JohnTheRipper_offensive_tool_keyword = /ios7tojohn\.pl/ nocase ascii wide
                        $string132_JohnTheRipper_offensive_tool_keyword = /itunes_backup2john\.pl/ nocase ascii wide
                        $string133_JohnTheRipper_offensive_tool_keyword = /iwork2john\.py/ nocase ascii wide
                        $string134_JohnTheRipper_offensive_tool_keyword = /john\s.{0,100}\s\-\-incremental/ nocase ascii wide
                        $string135_JohnTheRipper_offensive_tool_keyword = /john\s.{0,100}\s\-w\=/ nocase ascii wide
                        $string136_JohnTheRipper_offensive_tool_keyword = /john\s.{0,100}\s\-\-wordlist\=/
                        $string137_JohnTheRipper_offensive_tool_keyword = /john\s.{0,100}\-groups/ nocase ascii wide
                        $string138_JohnTheRipper_offensive_tool_keyword = /john\s.{0,100}htdigest/ nocase ascii wide
                        $string139_JohnTheRipper_offensive_tool_keyword = /john\s.{0,100}\-inc\s/ nocase ascii wide
                        $string140_JohnTheRipper_offensive_tool_keyword = /john\s.{0,100}\-incremental\s/ nocase ascii wide
                        $string141_JohnTheRipper_offensive_tool_keyword = /john\s.{0,100}\-shells/ nocase ascii wide
                        $string142_JohnTheRipper_offensive_tool_keyword = /john\s.{0,100}\-show/ nocase ascii wide
                        $string143_JohnTheRipper_offensive_tool_keyword = /john\s.{0,100}\-single/ nocase ascii wide
                        $string144_JohnTheRipper_offensive_tool_keyword = /john\s.{0,100}\-users/ nocase ascii wide
                        $string145_JohnTheRipper_offensive_tool_keyword = /john\s.{0,100}\-wordlist/ nocase ascii wide
                        $string146_JohnTheRipper_offensive_tool_keyword = /john\s.{0,100}\-\-wordlist/ nocase ascii wide
                        $string147_JohnTheRipper_offensive_tool_keyword = "john hashes" nocase ascii wide
                        $string148_JohnTheRipper_offensive_tool_keyword = /john\sNTDS\.dit/
                        $string149_JohnTheRipper_offensive_tool_keyword = "john --show " nocase ascii wide
                        $string150_JohnTheRipper_offensive_tool_keyword = "john --status" nocase ascii wide
                        $string151_JohnTheRipper_offensive_tool_keyword = "John the Ripper" nocase ascii wide
                        $string152_JohnTheRipper_offensive_tool_keyword = "john --wordlist" nocase ascii wide
                        $string153_JohnTheRipper_offensive_tool_keyword = /John.{0,100}the.{0,100}Ripper/
                        $string154_JohnTheRipper_offensive_tool_keyword = /john\.bash_completion/
                        $string155_JohnTheRipper_offensive_tool_keyword = /john\.session\.log/ nocase ascii wide
                        $string156_JohnTheRipper_offensive_tool_keyword = /john\.zsh_completion/ nocase ascii wide
                        $string157_JohnTheRipper_offensive_tool_keyword = /john\/run\/fuzz\.dic/ nocase ascii wide
                        $string158_JohnTheRipper_offensive_tool_keyword = "john/src/ztex/" nocase ascii wide
                        $string159_JohnTheRipper_offensive_tool_keyword = "john_log_format" nocase ascii wide
                        $string160_JohnTheRipper_offensive_tool_keyword = /john_mpi\.c/ nocase ascii wide
                        $string161_JohnTheRipper_offensive_tool_keyword = "john_register_all" nocase ascii wide
                        $string162_JohnTheRipper_offensive_tool_keyword = "JohnTheRipper " nocase ascii wide
                        $string163_JohnTheRipper_offensive_tool_keyword = "JohnTheRipper/" nocase ascii wide
                        $string164_JohnTheRipper_offensive_tool_keyword = /kdcdump2john\.py/ nocase ascii wide
                        $string165_JohnTheRipper_offensive_tool_keyword = /keepass_common_plug\./ nocase ascii wide
                        $string166_JohnTheRipper_offensive_tool_keyword = /keepass2john\s.{0,100}\.kdbx/ nocase ascii wide
                        $string167_JohnTheRipper_offensive_tool_keyword = /keychain2john\.py/ nocase ascii wide
                        $string168_JohnTheRipper_offensive_tool_keyword = /keyring2john\.py/ nocase ascii wide
                        $string169_JohnTheRipper_offensive_tool_keyword = /keystore2john\.py/ nocase ascii wide
                        $string170_JohnTheRipper_offensive_tool_keyword = /kirbi2john\./ nocase ascii wide
                        $string171_JohnTheRipper_offensive_tool_keyword = /kirbi2john\.py/ nocase ascii wide
                        $string172_JohnTheRipper_offensive_tool_keyword = /known_hosts2john\.py/ nocase ascii wide
                        $string173_JohnTheRipper_offensive_tool_keyword = /krb2john\.py/ nocase ascii wide
                        $string174_JohnTheRipper_offensive_tool_keyword = /kwallet2john\.py/ nocase ascii wide
                        $string175_JohnTheRipper_offensive_tool_keyword = "lastpass_sniffed_fmt_plug" nocase ascii wide
                        $string176_JohnTheRipper_offensive_tool_keyword = /lastpass2john\.py/ nocase ascii wide
                        $string177_JohnTheRipper_offensive_tool_keyword = /ldif2john\.pl/ nocase ascii wide
                        $string178_JohnTheRipper_offensive_tool_keyword = /libFuzzer\-HOWTO\./ nocase ascii wide
                        $string179_JohnTheRipper_offensive_tool_keyword = /libreoffice2john\.py/ nocase ascii wide
                        $string180_JohnTheRipper_offensive_tool_keyword = /lion2john\.pl/ nocase ascii wide
                        $string181_JohnTheRipper_offensive_tool_keyword = /lion2john\-alt\.pl/ nocase ascii wide
                        $string182_JohnTheRipper_offensive_tool_keyword = /lotus2john\.py/ nocase ascii wide
                        $string183_JohnTheRipper_offensive_tool_keyword = /luks2john\.py/ nocase ascii wide
                        $string184_JohnTheRipper_offensive_tool_keyword = /mac2john\.py/ nocase ascii wide
                        $string185_JohnTheRipper_offensive_tool_keyword = /mac2john\-alt\.py/ nocase ascii wide
                        $string186_JohnTheRipper_offensive_tool_keyword = /mcafee_epo2john\.py/ nocase ascii wide
                        $string187_JohnTheRipper_offensive_tool_keyword = /Md4\-128\.unverified\.test\-vectors\.txt/ nocase ascii wide
                        $string188_JohnTheRipper_offensive_tool_keyword = /Md5\-128\.unverified\.test\-vectors\.txt/ nocase ascii wide
                        $string189_JohnTheRipper_offensive_tool_keyword = /monero2john\.py/ nocase ascii wide
                        $string190_JohnTheRipper_offensive_tool_keyword = /money2john\.py/ nocase ascii wide
                        $string191_JohnTheRipper_offensive_tool_keyword = /mongodb2john\.js/ nocase ascii wide
                        $string192_JohnTheRipper_offensive_tool_keyword = /mosquitto2john\.py/ nocase ascii wide
                        $string193_JohnTheRipper_offensive_tool_keyword = /mozilla2john\.py/ nocase ascii wide
                        $string194_JohnTheRipper_offensive_tool_keyword = /multibit2john\.py/ nocase ascii wide
                        $string195_JohnTheRipper_offensive_tool_keyword = /neo2john\.py/ nocase ascii wide
                        $string196_JohnTheRipper_offensive_tool_keyword = /NETLMv2_fmt_plug\./ nocase ascii wide
                        $string197_JohnTheRipper_offensive_tool_keyword = /netntlm\.pl\s/ nocase ascii wide
                        $string198_JohnTheRipper_offensive_tool_keyword = /network2john\.lua/ nocase ascii wide
                        $string199_JohnTheRipper_offensive_tool_keyword = /office2john\.py/ nocase ascii wide
                        $string200_JohnTheRipper_offensive_tool_keyword = /openbsd_softraid2john\.py/ nocase ascii wide
                        $string201_JohnTheRipper_offensive_tool_keyword = /openssl2john\.py/ nocase ascii wide
                        $string202_JohnTheRipper_offensive_tool_keyword = /openwall\.John\.appdata\.xml/ nocase ascii wide
                        $string203_JohnTheRipper_offensive_tool_keyword = /openwall\.John\.desktop/ nocase ascii wide
                        $string204_JohnTheRipper_offensive_tool_keyword = "openwall/john" nocase ascii wide
                        $string205_JohnTheRipper_offensive_tool_keyword = /padlock2john\.py/ nocase ascii wide
                        $string206_JohnTheRipper_offensive_tool_keyword = /passphrase\-rule1\.rule/ nocase ascii wide
                        $string207_JohnTheRipper_offensive_tool_keyword = /passphrase\-rule2\.rule/ nocase ascii wide
                        $string208_JohnTheRipper_offensive_tool_keyword = /pcap2john\.py/ nocase ascii wide
                        $string209_JohnTheRipper_offensive_tool_keyword = /pdf2john\.pl/ nocase ascii wide
                        $string210_JohnTheRipper_offensive_tool_keyword = /pem2john\.py/ nocase ascii wide
                        $string211_JohnTheRipper_offensive_tool_keyword = /pfx2john\.py/ nocase ascii wide
                        $string212_JohnTheRipper_offensive_tool_keyword = /pgpdisk2john\.py/ nocase ascii wide
                        $string213_JohnTheRipper_offensive_tool_keyword = /pgpsda2john\.py/ nocase ascii wide
                        $string214_JohnTheRipper_offensive_tool_keyword = /pgpwde2john\.py/ nocase ascii wide
                        $string215_JohnTheRipper_offensive_tool_keyword = /pkt_comm\/word_gen\./ nocase ascii wide
                        $string216_JohnTheRipper_offensive_tool_keyword = "pkt_comm/word_list" nocase ascii wide
                        $string217_JohnTheRipper_offensive_tool_keyword = /prosody2john\.py/ nocase ascii wide
                        $string218_JohnTheRipper_offensive_tool_keyword = /ps_token2john\.py/ nocase ascii wide
                        $string219_JohnTheRipper_offensive_tool_keyword = /pse2john\.py/ nocase ascii wide
                        $string220_JohnTheRipper_offensive_tool_keyword = /pwsafe2john\.py/ nocase ascii wide
                        $string221_JohnTheRipper_offensive_tool_keyword = /radius2john\.pl/ nocase ascii wide
                        $string222_JohnTheRipper_offensive_tool_keyword = /radius2john\.py/ nocase ascii wide
                        $string223_JohnTheRipper_offensive_tool_keyword = "rar2john " nocase ascii wide
                        $string224_JohnTheRipper_offensive_tool_keyword = /rar2john\./ nocase ascii wide
                        $string225_JohnTheRipper_offensive_tool_keyword = "rawSHA1_linkedIn_fmt_plug" nocase ascii wide
                        $string226_JohnTheRipper_offensive_tool_keyword = /restic2john\.py/ nocase ascii wide
                        $string227_JohnTheRipper_offensive_tool_keyword = /Ripemd\-160\.test\-vectors\.txt/ nocase ascii wide
                        $string228_JohnTheRipper_offensive_tool_keyword = /rockyou\-30000\./ nocase ascii wide
                        $string229_JohnTheRipper_offensive_tool_keyword = /rules\/d3ad0ne\.rule/ nocase ascii wide
                        $string230_JohnTheRipper_offensive_tool_keyword = /sap2john\.pl/ nocase ascii wide
                        $string231_JohnTheRipper_offensive_tool_keyword = /sense2john\.py/ nocase ascii wide
                        $string232_JohnTheRipper_offensive_tool_keyword = /Sha\-2\-.{0,100}512\.unverified\.test\-vectors\.txt/ nocase ascii wide
                        $string233_JohnTheRipper_offensive_tool_keyword = /Sha\-2\-256\.unverified\.test\-vectors\.txt/ nocase ascii wide
                        $string234_JohnTheRipper_offensive_tool_keyword = /Sha\-2\-384\.unverified\.test\-vectors\.txt/ nocase ascii wide
                        $string235_JohnTheRipper_offensive_tool_keyword = /signal2john\.py/ nocase ascii wide
                        $string236_JohnTheRipper_offensive_tool_keyword = /sipdump2john\.py/ nocase ascii wide
                        $string237_JohnTheRipper_offensive_tool_keyword = /src\/cracker\./ nocase ascii wide
                        $string238_JohnTheRipper_offensive_tool_keyword = /src\/genmkvpwd\./ nocase ascii wide
                        $string239_JohnTheRipper_offensive_tool_keyword = /src\/john\.asm/ nocase ascii wide
                        $string240_JohnTheRipper_offensive_tool_keyword = "src/tests/NESSIE/" nocase ascii wide
                        $string241_JohnTheRipper_offensive_tool_keyword = "ssh2john " nocase ascii wide
                        $string242_JohnTheRipper_offensive_tool_keyword = /ssh2john\.py/ nocase ascii wide
                        $string243_JohnTheRipper_offensive_tool_keyword = /sspr2john\.py/ nocase ascii wide
                        $string244_JohnTheRipper_offensive_tool_keyword = /staroffice2john\.py/ nocase ascii wide
                        $string245_JohnTheRipper_offensive_tool_keyword = /strip2john\.py/ nocase ascii wide
                        $string246_JohnTheRipper_offensive_tool_keyword = /T0XlCv1\.rule/ nocase ascii wide
                        $string247_JohnTheRipper_offensive_tool_keyword = /telegram2john\.py/ nocase ascii wide
                        $string248_JohnTheRipper_offensive_tool_keyword = /test_tezos2john\.py/ nocase ascii wide
                        $string249_JohnTheRipper_offensive_tool_keyword = /tezos2john\.py/ nocase ascii wide
                        $string250_JohnTheRipper_offensive_tool_keyword = /Tiger\-192\.test\-vectors\.txt/ nocase ascii wide
                        $string251_JohnTheRipper_offensive_tool_keyword = /truecrypt2john\.py/ nocase ascii wide
                        $string252_JohnTheRipper_offensive_tool_keyword = /uaf2john\./ nocase ascii wide
                        $string253_JohnTheRipper_offensive_tool_keyword = "unshadow /etc/passwd"
                        $string254_JohnTheRipper_offensive_tool_keyword = "unshadow passwd shadow"
                        $string255_JohnTheRipper_offensive_tool_keyword = /vdi2john\.pl/ nocase ascii wide
                        $string256_JohnTheRipper_offensive_tool_keyword = /vmx2john\.py/ nocase ascii wide
                        $string257_JohnTheRipper_offensive_tool_keyword = /vncpcap2john\./ nocase ascii wide
                        $string258_JohnTheRipper_offensive_tool_keyword = /Whirlpool\-Orig\-512\.verified\.test\-vectors\.txt/ nocase ascii wide
                        $string259_JohnTheRipper_offensive_tool_keyword = /Whirlpool\-Tweak\-512\.verified\.test\-vectors\.txt/ nocase ascii wide
                        $string260_JohnTheRipper_offensive_tool_keyword = /word_gen_b_varlen\./ nocase ascii wide
                        $string261_JohnTheRipper_offensive_tool_keyword = /wpapcap2john\./ nocase ascii wide
                        $string262_JohnTheRipper_offensive_tool_keyword = /zed2john\.py/ nocase ascii wide
                        $string263_JohnTheRipper_offensive_tool_keyword = "zip2john " nocase ascii wide
        $metadata_regex_import = /\bimport\s+[a-zA-Z0-9_.]+\b/ nocase
        $metadata_regex_function = /function\s+[a-zA-Z_][a-zA-Z0-9_]*\(/ nocase ascii
        $metadata_regex_php = /<\?php/ nocase ascii
        $metadata_regex_createobject = /(CreateObject|WScript\.)/ nocase ascii
        $metadata_regex_script = /<script\b/ nocase ascii
        $metadata_regex_javascript = /(let\s|const\s|function\s|document\.|console\.)/ nocase ascii
        $metadata_regex_powershell = /(Write-Host|Get-[a-zA-Z]+|Invoke-|param\(|\.SYNOPSIS)/ nocase ascii
        $metadata_regex_batch = /@(echo\s|call\s|set\s|goto\s|if\s|for\s|rem\s)/ nocase ascii
        $metadata_regex_shebang = /^#!\// nocase ascii

    condition:
        ((filesize < 20MB and (
            uint16(0) == 0x5a4d or             uint16(0) == 0x457f or             uint32be(0) == 0x7f454c46 or uint16(0) == 0xfeca or uint16(0) == 0xfacf or uint32(0) == 0xbebafeca or             uint32(0) == 0x504B0304 or             uint32(0) == 0xCAFEBABE or             uint32(0) == 0x4D534346 or             uint32(0) == 0xD0CF11E0 or             uint16(0) == 0x2321 or             uint16(0) == 0x3c3f         )) and 2 of ($string*)) or
        (filesize < 2MB and
        (
            2 of ($string*) and
            for any of ($metadata_regex_*) : ( @ <= 20000 )
        ))
}