rule MALPEDIA_Win_Buer_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "29f2986a-0230-51bb-b9a2-7f550ca2fb77"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.buer"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.buer_auto.yar#L1-L170"
    license_url        = "N/A"
    logic_hash         = "2390d8b9be10e4a78955cb4e4f9dfe589bef2af5ea30193017caa2f367cbde8d"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0  = { 8b 40 14 8b 00 8b 40 10 89 45 fc 61 8b 45 fc }
    $sequence_1  = { 75 07 e8 ?? ?? ?? ?? eb 05 e8 ?? ?? ?? ?? 46 83 fe 20 7c d1 }
    $sequence_2  = { 60 64 a1 30 00 00 00 8b 40 0c 8b 40 14 8b 00 8b 40 10 }
    $sequence_3  = { 8b c2 eb 19 33 c0 85 d2 7e 13 3b c7 }
    $sequence_4  = { 8b 55 e8 01 51 58 8b 55 d8 89 41 48 8b 45 dc 03 c6 89 41 4c }
    $sequence_5  = { c1 e1 04 0b c8 6a 02 5b }
    $sequence_6  = { 89 45 f8 ff 15 ?? ?? ?? ?? 59 59 85 c0 }
    $sequence_7  = { 83 65 fc 00 53 56 57 60 64 a1 30 00 00 00 8b 40 0c }
    $sequence_8  = { c7 44 24 04 02 00 00 00 8d 44 24 28 c7 44 24 08 ?? ?? ?? ?? c7 44 24 0c 01 00 00 00 }
    $sequence_9  = { e8 ?? ?? ?? ?? 80 fb 03 77 05 80 fb 02 }
    $sequence_10 = { e8 ?? ?? ?? ?? 0f 0b b9 2c 00 00 00 ba 01 00 00 00 e8 ?? ?? ?? ?? 0f 0b 89 f9 }
    $sequence_11 = { c7 44 24 04 01 00 00 00 c7 44 24 08 ?? ?? ?? ?? c7 44 24 0c 01 00 00 00 89 44 24 10 }
    $sequence_12 = { e8 ?? ?? ?? ?? 56 6a 00 50 e8 ?? ?? ?? ?? c7 47 1c 01 00 00 00 }
    $sequence_13 = { c7 44 24 08 00 00 00 00 57 e8 ?? ?? ?? ?? 85 c0 }
    $sequence_14 = { cd 29 0f 0b cc 8b 44 24 04 83 38 00 74 06 ba ?? ?? ?? ?? }
    $sequence_15 = { e8 ?? ?? ?? ?? 80 fb 05 ba 01 00 00 00 0f b6 c3 }

  condition:
    7 of them and filesize < 3031040
}