rule win_spyeye_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.spyeye."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.spyeye"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 740e 837dfcff 7408 ff75fc }
                                                            
        $sequence_1 = { 8b65fc c9 c20800 55 8bec }
                                                                        
        $sequence_2 = { 56 6880000000 6a04 56 6a07 6800000040 57 }
                                                                                                
        $sequence_3 = { ff7508 ffd0 8b65fc c9 c21400 55 8bec }
                                                                                                
        $sequence_4 = { ff750c e8???????? 8bd8 83fbff 751b 57 }
                                                                                    
        $sequence_5 = { 837dfcff 7408 ff75fc e8???????? 3bdf }
                                                                        
        $sequence_6 = { 740a 83e0fe 50 57 }
                                                            
        $sequence_7 = { 6a02 eb08 56 6880000000 6a04 }
                                                                        
        $sequence_8 = { 6a03 57 6a01 56 ff750c e8???????? }
                                                                                    
        $sequence_9 = { 50 e8???????? 85c0 7454 57 56 }
                                                                                    
    condition:
        7 of them and filesize < 741376
}