rule win_jripbot_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.jripbot."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.jripbot"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 52 51 50 0fbf45ee 50 be???????? e8???????? }
                                                                                                
        $sequence_1 = { 50 ff15???????? eb61 ff742434 8d842464010000 ff742414 e8???????? }
                                                                                                
        $sequence_2 = { 7436 830804 f6c302 742e 56 ff15???????? 50 }
                                                                                                
        $sequence_3 = { 8d85a8fcffff 8d5001 8a08 40 3acb 75f9 2bc2 }
                                                                                                
        $sequence_4 = { 50 8d442418 50 894c2420 ff15???????? 83c40c 85c0 }
                                                                                                
        $sequence_5 = { 6a30 ff750c 8d75fc 8bcf e8???????? 83c408 }
                                                                                    
        $sequence_6 = { 8b8de0fdffff 8bc3 668b10 663b11 751e 663bd7 7415 }
                                                                                                
        $sequence_7 = { 33fb 037dfc 8b5ddc 235df4 0bf3 03f7 8b7d88 }
                                                                                                
        $sequence_8 = { 8bf8 83c40c 85ff 0f85da000000 ff742410 8d442448 e8???????? }
                                                                                                
        $sequence_9 = { 8d443718 50 e8???????? 83c40c 8d4618 8bce e8???????? }
                                                                                                
    condition:
        7 of them and filesize < 507904
}