rule win_hacksfase_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.hacksfase."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.hacksfase"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 8965e8 33db 895de0 895de4 895dd8 895ddc 895dfc }
                                                                                                
        $sequence_1 = { 56 6a02 68???????? 56 ff500c }
                                                                        
        $sequence_2 = { 56 ffd3 50 ffd5 56 ff15???????? }
                                                                                    
        $sequence_3 = { 89442418 894c241c 6a00 6a00 6a00 6a06 6a01 }
                                                                                                
        $sequence_4 = { 3975b4 7416 3975bc 7411 ff75b4 8bcb }
                                                                                    
        $sequence_5 = { 7479 bf02000000 8b442414 40 3bc7 89442414 }
                                                                                    
        $sequence_6 = { e8???????? 8b1d???????? 83c40c 68e8030000 ffd3 6a00 6a00 }
                                                                                                
        $sequence_7 = { 895dc8 895dd0 ff5064 3bc3 894508 7d5d }
                                                                                    
        $sequence_8 = { b8???????? e8???????? 83ec0c 8b412c 56 57 }
                                                                                    
        $sequence_9 = { 33d2 8d0cb6 f7f6 8d0c89 }
                                                            
    condition:
        7 of them and filesize < 106496
}