rule win_brambul_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.brambul."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.brambul"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 8d4e03 2bee 8a01 8ad8 80e30f c0e804 }
                                                                                    
        $sequence_1 = { a3???????? 68???????? 68???????? e8???????? 83c408 50 }
                                                                                    
        $sequence_2 = { 8d8c2438020000 51 ff15???????? 8bac2428090000 83c9ff 8bfd }
                                                                                    
        $sequence_3 = { 33c0 8d94240c010000 f2ae f7d1 2bf9 6a00 8bc1 }
                                                                                                
        $sequence_4 = { 8b4c241c 40 3bc1 89442418 0f8cfefeffff 8b442414 }
                                                                                    
        $sequence_5 = { 83c40c 8b5514 833a00 0f84db000000 837decfe 0f8ed1000000 c745e401000000 }
                                                                                                
        $sequence_6 = { 8985a849ffff 8985c05dffff 8985c45dffff 8945f8 895df0 }
                                                                        
        $sequence_7 = { 8b4002 8985b049ffff c785ac49ffff02000000 e9???????? f6c140 0f8428010000 f6c120 }
                                                                                                
        $sequence_8 = { 42 bf08000000 89542410 c6041600 85ed }
                                                                        
        $sequence_9 = { 48 234508 8d0440 8d0441 0fb64801 }
                                                                        
        $sequence_10 = { 8913 5f d3e7 3bc8 7316 }
                                                                        
        $sequence_11 = { 46 6a00 8d849db84dffff 56 }
                                                            
        $sequence_12 = { 0f8e5b020000 68???????? 68???????? 8d54242c 68???????? 52 }
                                                                                    
        $sequence_13 = { 03f3 8bd9 8dbc379979825a 8bf7 }
                                                            
        $sequence_14 = { 81c404010000 c3 56 8d542414 68???????? }
                                                                        
        $sequence_15 = { c1ee17 c1e709 0bf7 33ce 8bf9 33fa }
                                                                                    
    condition:
        7 of them and filesize < 188416
}