rule win_derusbi_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.derusbi."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.derusbi"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 85c0 75be 8b45c8 895db0 895dac 3bc3 0f84affeffff }
                                                                                                
        $sequence_1 = { 72e4 5e c3 55 8bec 51 53 }
                                                                                                
        $sequence_2 = { 6810040000 ff15???????? 8985f8fdffff 85c0 7464 }
                                                                        
        $sequence_3 = { ff7508 ff15???????? 8bf0 59 85f6 740f ff7508 }
                                                                                                
        $sequence_4 = { 56 89442418 57 8d442424 50 8d44242c 50 }
                                                                                                
        $sequence_5 = { 83c108 3d00040000 72f1 e9???????? 215cc70c 8d5cc710 }
                                                                                    
        $sequence_6 = { 50 ff15???????? 83c40c 56 8d4c2470 51 889c2407010000 }
                                                                                                
        $sequence_7 = { 83c40c 8d45dc 50 ff15???????? 83f8ff 740d a810 }
                                                                                                
        $sequence_8 = { 53 50 ffd6 83c40c 8d442424 50 8d84242cbc0200 }
                                                                                                
        $sequence_9 = { 8d85b8f7ffff e8???????? 59 33c9 85c0 7e25 80b40db8fbffff99 }
                                                                                                
    condition:
        7 of them and filesize < 360448
}