rule win_keylogger_apt3_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.keylogger_apt3."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.keylogger_apt3"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 50 ffd7 8b4e08 6a08 51 ffd7 }
                                                                                    
        $sequence_1 = { 8b9c2430040000 55 8bac2430040000 56 57 8bbc2434040000 6800010000 }
                                                                                                
        $sequence_2 = { 52 ffd7 8b0d???????? 8d442424 50 51 }
                                                                                    
        $sequence_3 = { 8d45f0 50 e8???????? cc e8???????? 8b4004 c3 }
                                                                                                
        $sequence_4 = { e8???????? 55 e8???????? 68???????? e8???????? 8b8c2440020000 83c40c }
                                                                                                
        $sequence_5 = { 52 ffd7 a1???????? 896844 8b9eac010000 85db 742e }
                                                                                                
        $sequence_6 = { 52 e8???????? 8d862c020000 50 8d4c242c 68???????? 51 }
                                                                                                
        $sequence_7 = { 8d7c00ff 3bc7 89442418 0f8dc6000000 8b542414 8bd8 69db14010000 }
                                                                                                
        $sequence_8 = { 68???????? 52 ffd7 8b0d???????? 8d442438 50 }
                                                                                    
        $sequence_9 = { e8???????? 83c404 8b442414 6a00 6a00 6a10 8d54244c }
                                                                                                
    condition:
        7 of them and filesize < 761856
}