rule MALPEDIA_Win_Ufrstealer_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "87df7a80-59b4-5e49-9e5c-787423bd5a1a"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.ufrstealer"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.ufrstealer_auto.yar#L1-L129"
    license_url        = "N/A"
    logic_hash         = "bbd8353728980ed7d41eeaaf6b45527dc201d1c8bc1c51c590cb1fee36b76ae8"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0 = { 6a 01 6a 00 6a 00 68 ?? ?? ?? ?? 6a 00 68 ?? ?? ?? ?? ff 15 ?? ?? ?? ?? }
    $sequence_1 = { 0b c0 75 29 8b 43 fc 03 d8 8b 03 83 c3 04 83 f8 ff }
    $sequence_2 = { ff b5 ec f3 ff ff ff 15 ?? ?? ?? ?? 5b 5f 5e c9 }
    $sequence_3 = { 89 4d f4 8b 75 f4 83 ee 01 c7 45 f0 08 00 00 00 0f b6 4e ff 0f b6 16 83 f9 7f }
    $sequence_4 = { 03 c1 80 38 3a 75 05 c6 00 00 eb 03 49 }
    $sequence_5 = { ff 35 ?? ?? ?? ?? ff 15 ?? ?? ?? ?? 85 c0 0f 84 2d eb ff ff a3 ?? ?? ?? ?? 68 ?? ?? ?? ?? ff 15 ?? ?? ?? ?? }
    $sequence_6 = { 0f 85 c0 00 00 00 0f b6 0d ?? ?? ?? ?? a1 ?? ?? ?? ?? 88 08 83 05 ?? ?? ?? ?? 01 89 4d fc bb ?? ?? ?? ?? }
    $sequence_7 = { 8d 45 dc 6a 04 50 e8 ?? ?? ?? ?? 83 05 ?? ?? ?? ?? 04 e8 ?? ?? ?? ?? }
    $sequence_8 = { 50 68 ?? ?? ?? ?? 68 ?? ?? ?? ?? 6a 00 ff 15 ?? ?? ?? ?? 68 ?? ?? ?? ?? ff 15 ?? ?? ?? ?? }
    $sequence_9 = { c7 45 d8 0e 00 00 00 33 c0 8b 75 d8 8b c8 8d b6 5c 88 42 00 }

  condition:
    7 of them and filesize < 770048
}