rule win_crypt0l0cker_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.crypt0l0cker."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.crypt0l0cker"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 8bcb e8???????? eb05 bf03000000 56 6a01 682f5b5412 }
                                                                                                
        $sequence_1 = { 53 e8???????? 59 59 85c0 0f84bbfeffff 8b45f8 }
                                                                                                
        $sequence_2 = { 8bcf e8???????? 8b4c2418 e8???????? 85f6 740f 56 }
                                                                                                
        $sequence_3 = { 0f8e85000000 53 ff75fc 8d45a8 50 8bd0 8d4dbc }
                                                                                                
        $sequence_4 = { 33c1 894ee8 8946ec 8d042e c1f802 8b4c8314 8bc1 }
                                                                                                
        $sequence_5 = { 68???????? bac8cfa6d0 8bce e8???????? 83c404 85c0 0f85b2000000 }
                                                                                                
        $sequence_6 = { e8???????? 83c40c 68fd010000 53 85f6 7506 }
                                                                                    
        $sequence_7 = { 3bf2 7301 47 03d8 895de8 3bd8 }
                                                                                    
        $sequence_8 = { 8be5 5d c3 55 8bec 83ec18 8bc2 }
                                                                                                
        $sequence_9 = { 0f8520080000 c74424143c000000 55 8d4900 837e3400 0f8505080000 833e01 }
                                                                                                
    condition:
        7 of them and filesize < 917504
}