rule Mythic_Apollo_Tasks
{
meta:
	id = "3Knpy0fO9mMnMIWqjX7Zzn"
	fingerprint = "v1_sha256_a8b6a3da21ae7fb70f5feee93fc9838171fcb3e370458dd1331672d0815f0710"
	version = "1.0"
	date = "2026-01-27"
	modified = "2026-01-27"
	status = "RELEASED"
	sharing = "TLP:CLEAR"
	source = "BARTBLAZE"
	author = "@bartblaze"
	description = "Identifies Mythic's Apollo agent, a collaborative, multi-platform, red teaming framework."
	category = "MALWARE"
	malware_type = "HACKTOOL"
	reference = "https://github.com/its-a-feature/Mythic"
	tool = "MYTHIC"

strings:
	$ = "assembly_inject" 
	$ = "blockdlls" 
	$ = "execute_assembly" 
	$ = "execute_coff" 
	$ = "execute_pe" 
	$ = "getprivs" 
	$ = "getsystem" 
	$ = "get_injection_techniques" 
	$ = "inline_assembly" 
	$ = "jobkill" 
	$ = "keylog_inject" 
	$ = "listpipes" 
	$ = "make_token" 
	$ = "net_dclist" 
	$ = "net_localgroup" 
	$ = "net_localgroup_member" 
	$ = "net_shares" 
	$ = "powerpick" 
	$ = "psinject" 
	$ = "register_file" 
	$ = "reg_query" 
	$ = "reg_write_value" 
	$ = "rev2self" 
	$ = "screenshot_inject" 
	$ = "self_delete" 
	$ = "set_injection_technique" 
	$ = "shinject" 
	$ = "spawnto_x64" 
	$ = "spawnto_x86" 
	$ = "steal_token" 
	$ = "wmiexecute"
	
condition:
	20 of them
}