rule win_astralocker_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.astralocker."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.astralocker"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 33d2 33f6 891401 89740104 b808000000 6bc800 8b5508 }
                                                                                                
        $sequence_1 = { 51 8b14d0 52 e8???????? 83c408 8945f4 8955f8 }
                                                                                                
        $sequence_2 = { 891401 89740104 b808000000 6bc800 }
                                                            
        $sequence_3 = { 891401 89740104 b808000000 6bc800 8b5508 8b440a04 }
                                                                                    
        $sequence_4 = { 8955f0 ba08000000 6bf200 8b45ec }
                                                            
        $sequence_5 = { ba08000000 6bf200 8b45ec 8b55f0 b11a }
                                                                        
        $sequence_6 = { 6bc80a 8b5508 33c0 33f6 89040a }
                                                                        
        $sequence_7 = { 6bc20a 8b4d08 33d2 33f6 891401 89740104 }
                                                                                    
        $sequence_8 = { 8b5508 8b440a04 50 8b0c0a 51 e8???????? }
                                                                                    
        $sequence_9 = { 8b4508 8b4cd004 51 8b14d0 52 e8???????? 83c408 }
                                                                                                
    condition:
        7 of them and filesize < 191488
}