rule MALPEDIA_Win_Infy_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "57c24fda-e429-5a88-80d2-235251d4052e"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.infy"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.infy_auto.yar#L1-L122"
    license_url        = "N/A"
    logic_hash         = "97f3b09f4f39ef998f79ec8093433c607a41cb99a12ab0573691bf5dec73bf57"
    score              = 60
    quality            = 45
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0 = { 7e 24 89 45 d4 80 7d e3 00 74 09 8b 45 e4 66 83 38 20 }
    $sequence_1 = { 74 09 8b 13 8b c3 e8 ?? ?? ?? ?? 85 c0 74 05 83 e8 04 }
    $sequence_2 = { 57 33 c9 89 4d f8 89 55 f0 }
    $sequence_3 = { 75 53 83 7e 14 00 74 42 83 7e 1c 00 }
    $sequence_4 = { 66 83 78 f6 02 74 12 6a 00 89 e0 }
    $sequence_5 = { 68 ?? ?? ?? ?? 8d 45 c8 ba 09 00 00 00 e8 ?? ?? ?? ?? 8d 45 ec }
    $sequence_6 = { 80 7d e3 00 74 09 8b 45 e4 66 83 38 20 73 04 33 c0 eb 02 }
    $sequence_7 = { c1 e0 02 03 46 10 f6 40 03 80 0f 94 c2 83 e2 01 89 55 e0 85 d2 }
    $sequence_8 = { e8 ?? ?? ?? ?? 8b d0 81 e2 ff 00 00 00 25 00 ff 00 00 c1 e8 08 83 fa 05 75 05 }
    $sequence_9 = { e8 ?? ?? ?? ?? 83 c4 0c 5b 5d c2 08 00 55 8b ec }

  condition:
    7 of them and filesize < 147456
}