rule rule_crackmapexec_offensive_tool_keyword
{
    meta:
        description = "Detection patterns for the tool 'crackmapexec' taken from the ThreatHunting-Keywords github project"
        author = "@mthcht"
        reference = "https://github.com/mthcht/ThreatHunting-Keywords"
        tool = "crackmapexec"
        rule_category = "offensive_tool_keyword"

    strings:
                        $string1_crackmapexec_offensive_tool_keyword = " cmedb" nocase ascii wide
                        $string2_crackmapexec_offensive_tool_keyword = " empire_exec" nocase ascii wide
                        $string3_crackmapexec_offensive_tool_keyword = " empireadmin" nocase ascii wide
                        $string4_crackmapexec_offensive_tool_keyword = " enum_avproducts" nocase ascii wide
                        $string5_crackmapexec_offensive_tool_keyword = " enum_chrome" nocase ascii wide
                        $string6_crackmapexec_offensive_tool_keyword = " enum_dns" nocase ascii wide
                        $string7_crackmapexec_offensive_tool_keyword = " --force-ps32" nocase ascii wide
                        $string8_crackmapexec_offensive_tool_keyword = " --gen-relay-list " nocase ascii wide
                        $string9_crackmapexec_offensive_tool_keyword = " get_keystrokes" nocase ascii wide
                        $string10_crackmapexec_offensive_tool_keyword = " get_netdomaincontroller" nocase ascii wide
                        $string11_crackmapexec_offensive_tool_keyword = " get_netrdpsession" nocase ascii wide
                        $string12_crackmapexec_offensive_tool_keyword = " get_timedscreenshot" nocase ascii wide
                        $string13_crackmapexec_offensive_tool_keyword = " gpp_autologin" nocase ascii wide
                        $string14_crackmapexec_offensive_tool_keyword = " gpp_password" nocase ascii wide
                        $string15_crackmapexec_offensive_tool_keyword = " invoke_sessiongopher" nocase ascii wide
                        $string16_crackmapexec_offensive_tool_keyword = " invoke_vnc" nocase ascii wide
                        $string17_crackmapexec_offensive_tool_keyword = /\skerberos\.py/ nocase ascii wide
                        $string18_crackmapexec_offensive_tool_keyword = " --local-auth --shares" nocase ascii wide
                        $string19_crackmapexec_offensive_tool_keyword = " --loggedon-users" nocase ascii wide
                        $string20_crackmapexec_offensive_tool_keyword = " -M multirdp" nocase ascii wide
                        $string21_crackmapexec_offensive_tool_keyword = " -M pe_inject" nocase ascii wide
                        $string22_crackmapexec_offensive_tool_keyword = " -M scuffy" nocase ascii wide
                        $string23_crackmapexec_offensive_tool_keyword = " -M shellcode_inject" nocase ascii wide
                        $string24_crackmapexec_offensive_tool_keyword = " -M slinky" nocase ascii wide
                        $string25_crackmapexec_offensive_tool_keyword = " -M tokens" nocase ascii wide
                        $string26_crackmapexec_offensive_tool_keyword = " -M uac" nocase ascii wide
                        $string27_crackmapexec_offensive_tool_keyword = " -M web_delivery" nocase ascii wide
                        $string28_crackmapexec_offensive_tool_keyword = " met_inject" nocase ascii wide
                        $string29_crackmapexec_offensive_tool_keyword = " mimikittenz" nocase ascii wide
                        $string30_crackmapexec_offensive_tool_keyword = " netripper" nocase ascii wide
                        $string31_crackmapexec_offensive_tool_keyword = " --no-bruteforce " nocase ascii wide
                        $string32_crackmapexec_offensive_tool_keyword = " --ntds-history" nocase ascii wide
                        $string33_crackmapexec_offensive_tool_keyword = " --ntds-pwdLastSet" nocase ascii wide
                        $string34_crackmapexec_offensive_tool_keyword = /\s\-p\s.{0,1000}\s\-\-amsi\-bypass\s/ nocase ascii wide
                        $string35_crackmapexec_offensive_tool_keyword = " Pwn3d!" nocase ascii wide
                        $string36_crackmapexec_offensive_tool_keyword = " --rid-brute" nocase ascii wide
                        $string37_crackmapexec_offensive_tool_keyword = " smb -M mimikatz --options" nocase ascii wide
                        $string38_crackmapexec_offensive_tool_keyword = /\ssmb.{0,1000}\s\-u\s\'\'\s\-p\s\'\'/ nocase ascii wide
                        $string39_crackmapexec_offensive_tool_keyword = /\ssmbexec\.py/ nocase ascii wide
                        $string40_crackmapexec_offensive_tool_keyword = /\s\-u\s.{0,1000}\s\-\-local\-auth/ nocase ascii wide
                        $string41_crackmapexec_offensive_tool_keyword = /\s\-u\s.{0,1000}\s\-p\s.{0,1000}\s\-\-lusers/ nocase ascii wide
                        $string42_crackmapexec_offensive_tool_keyword = /\s\-u\s.{0,1000}\s\-p\s.{0,1000}\s\-\-sam/ nocase ascii wide
                        $string43_crackmapexec_offensive_tool_keyword = /\s\-u\s.{0,1000}\s\-p\s.{0,1000}\s\-\-shares/ nocase ascii wide
                        $string44_crackmapexec_offensive_tool_keyword = /\s\-u\s.{0,1000}\s\-p\s.{0,1000}\-\-pass\-pol/ nocase ascii wide
                        $string45_crackmapexec_offensive_tool_keyword = " --wdigest disable" nocase ascii wide
                        $string46_crackmapexec_offensive_tool_keyword = " --wdigest enable" nocase ascii wide
                        $string47_crackmapexec_offensive_tool_keyword = /\swinrm\.py/ nocase ascii wide
                        $string48_crackmapexec_offensive_tool_keyword = /\s\-\-wmi\s.{0,1000}SELECT\s/ nocase ascii wide
                        $string49_crackmapexec_offensive_tool_keyword = /\swmiexec\.py/ nocase ascii wide
                        $string50_crackmapexec_offensive_tool_keyword = /\s\-\-wmi\-namespace\s\'root\\cimv2\'/ nocase ascii wide
                        $string51_crackmapexec_offensive_tool_keyword = /\s\-X\s\'\$PSVersionTable\'\s/ nocase ascii wide
                        $string52_crackmapexec_offensive_tool_keyword = /\s\-X\s\'\[System\.Environment\]\:\:Is64BitProcess\'/ nocase ascii wide
                        $string53_crackmapexec_offensive_tool_keyword = /\$DummyServiceName/ nocase ascii wide
                        $string54_crackmapexec_offensive_tool_keyword = /\$KeePassBinaryPath/ nocase ascii wide
                        $string55_crackmapexec_offensive_tool_keyword = /\$KeePassUser/ nocase ascii wide
                        $string56_crackmapexec_offensive_tool_keyword = /\.Assembly\.GetType\(\'System\.Management\.Automation\.AmsiUtils\'\)\.GetField\(\'amsiInitFailed\'/ nocase ascii wide
                        $string57_crackmapexec_offensive_tool_keyword = /\.exe.{0,1000}\s\-d\slocalhost\s.{0,1000}\s\-u\s.{0,1000}\s\-p\s.{0,1000}\/24/ nocase ascii wide
                        $string58_crackmapexec_offensive_tool_keyword = /\.exe.{0,1000}\s\-u\sadministrator\s\-H\s\:.{0,1000}\-\-shares/ nocase ascii wide
                        $string59_crackmapexec_offensive_tool_keyword = /\/batch_cme_smb\.sh/ nocase ascii wide
                        $string60_crackmapexec_offensive_tool_keyword = /\/bloodhound\.py/ nocase ascii wide
                        $string61_crackmapexec_offensive_tool_keyword = "/cme smb "
                        $string62_crackmapexec_offensive_tool_keyword = "/cme winrm "
                        $string63_crackmapexec_offensive_tool_keyword = "/cmedb" nocase ascii wide
                        $string64_crackmapexec_offensive_tool_keyword = /\/enum_av\.py/ nocase ascii wide
                        $string65_crackmapexec_offensive_tool_keyword = /\/kerberos\.py/ nocase ascii wide
                        $string66_crackmapexec_offensive_tool_keyword = /\/mssqlexec\.py/ nocase ascii wide
                        $string67_crackmapexec_offensive_tool_keyword = /\/nessus\.py/ nocase ascii wide
                        $string68_crackmapexec_offensive_tool_keyword = /\/nmap\.py/ nocase ascii wide
                        $string69_crackmapexec_offensive_tool_keyword = "/obfuscated_scripts/" nocase ascii wide
                        $string70_crackmapexec_offensive_tool_keyword = /\/protocols\/ftp\.py/ nocase ascii wide
                        $string71_crackmapexec_offensive_tool_keyword = /\/protocols\/ldap\.py/ nocase ascii wide
                        $string72_crackmapexec_offensive_tool_keyword = /\/protocols\/mssql\.py/ nocase ascii wide
                        $string73_crackmapexec_offensive_tool_keyword = /\/protocols\/rdp\.py/ nocase ascii wide
                        $string74_crackmapexec_offensive_tool_keyword = /\/protocols\/rdp\.py/ nocase ascii wide
                        $string75_crackmapexec_offensive_tool_keyword = /\/protocols\/smb\.py/ nocase ascii wide
                        $string76_crackmapexec_offensive_tool_keyword = /\/protocols\/ssh\.py/ nocase ascii wide
                        $string77_crackmapexec_offensive_tool_keyword = /\/samruser\.py/ nocase ascii wide
                        $string78_crackmapexec_offensive_tool_keyword = /\/smbexec\.py/ nocase ascii wide
                        $string79_crackmapexec_offensive_tool_keyword = /\/smbldap\.py/ nocase ascii wide
                        $string80_crackmapexec_offensive_tool_keyword = /\/winrm\.py/ nocase ascii wide
                        $string81_crackmapexec_offensive_tool_keyword = /\/wmiexec\.py/ nocase ascii wide
                        $string82_crackmapexec_offensive_tool_keyword = /\/wmiexec\.py/ nocase ascii wide
                        $string83_crackmapexec_offensive_tool_keyword = /\\bin\\cme\.exe/ nocase ascii wide
                        $string84_crackmapexec_offensive_tool_keyword = /\\cme\.exe.{0,1000}\s\-d\s.{0,1000}\s\-u\s.{0,1000}\s\-H\s/ nocase ascii wide
                        $string85_crackmapexec_offensive_tool_keyword = /\\cme\.exe.{0,1000}\s\-d\s.{0,1000}\s\-u\s.{0,1000}\s\-p\s/ nocase ascii wide
                        $string86_crackmapexec_offensive_tool_keyword = /\\cme\.exe.{0,1000}\s\-\-shares/ nocase ascii wide
                        $string87_crackmapexec_offensive_tool_keyword = /\\crackmapexecwin/ nocase ascii wide
                        $string88_crackmapexec_offensive_tool_keyword = /\\Temp\\cme_hosted/ nocase ascii wide
                        $string89_crackmapexec_offensive_tool_keyword = /\\Temp\\whoami\.txt/ nocase ascii wide
                        $string90_crackmapexec_offensive_tool_keyword = /\\Windows\\Temp\\temp\.ps1/ nocase ascii wide
                        $string91_crackmapexec_offensive_tool_keyword = "_enum_vault_creds" nocase ascii wide
                        $string92_crackmapexec_offensive_tool_keyword = "2eb2cc1eb661148109488b8f36aa6b248e88c0f1" nocase ascii wide
                        $string93_crackmapexec_offensive_tool_keyword = /AddKeePassTrigger\.ps1/ nocase ascii wide
                        $string94_crackmapexec_offensive_tool_keyword = /BloodHound\-modified\.ps1/ nocase ascii wide
                        $string95_crackmapexec_offensive_tool_keyword = /cmd\ssmb\s.{0,1000}\-u.{0,1000}\-p/ nocase ascii wide
                        $string96_crackmapexec_offensive_tool_keyword = /cme\s\-d\s.{0,1000}\s\-/ nocase ascii wide
                        $string97_crackmapexec_offensive_tool_keyword = /cme\s\-d\s.{0,1000}localhost/ nocase ascii wide
                        $string98_crackmapexec_offensive_tool_keyword = /cme.{0,1000}\-macOS\-latest\-/ nocase ascii wide
                        $string99_crackmapexec_offensive_tool_keyword = /cme.{0,1000}\-ubuntu\-latest\-/ nocase ascii wide
                        $string100_crackmapexec_offensive_tool_keyword = /cme.{0,1000}\-windows\-latest\-/ nocase ascii wide
                        $string101_crackmapexec_offensive_tool_keyword = /cme\/cme\.conf/ nocase ascii wide
                        $string102_crackmapexec_offensive_tool_keyword = /cme\-macOS\-latest\-.{0,1000}\.zip/ nocase ascii wide
                        $string103_crackmapexec_offensive_tool_keyword = /cme\-ubuntu\-latest\-.{0,1000}\.zip/ nocase ascii wide
                        $string104_crackmapexec_offensive_tool_keyword = /cme\-windows\-latest\-.{0,1000}\.zip/ nocase ascii wide
                        $string105_crackmapexec_offensive_tool_keyword = "crackmapexec" nocase ascii wide
                        $string106_crackmapexec_offensive_tool_keyword = "CrackMapExec" nocase ascii wide
                        $string107_crackmapexec_offensive_tool_keyword = /crackmapexec\.exe/ nocase ascii wide
                        $string108_crackmapexec_offensive_tool_keyword = /crackmapexec\.py/ nocase ascii wide
                        $string109_crackmapexec_offensive_tool_keyword = /DNS\-Enum\-.{0,1000}\-.{0,1000}\.log/ nocase ascii wide
                        $string110_crackmapexec_offensive_tool_keyword = /empire_exec\.py/ nocase ascii wide
                        $string111_crackmapexec_offensive_tool_keyword = /enum_avproducts\.py/ nocase ascii wide
                        $string112_crackmapexec_offensive_tool_keyword = "--exec-method smbexec" nocase ascii wide
                        $string113_crackmapexec_offensive_tool_keyword = /get_keystrokes\.py/ nocase ascii wide
                        $string114_crackmapexec_offensive_tool_keyword = "Get-ComputerDetails" nocase ascii wide
                        $string115_crackmapexec_offensive_tool_keyword = /gpp_autologin\.py/ nocase ascii wide
                        $string116_crackmapexec_offensive_tool_keyword = /gpp_password\.py/ nocase ascii wide
                        $string117_crackmapexec_offensive_tool_keyword = "-H lm-hash:nt-hash" nocase ascii wide
                        $string118_crackmapexec_offensive_tool_keyword = "-H 'LMHASH:NTHASH'" nocase ascii wide
                        $string119_crackmapexec_offensive_tool_keyword = "-H 'NTHASH'" nocase ascii wide
                        $string120_crackmapexec_offensive_tool_keyword = "handle_nessus_file" nocase ascii wide
                        $string121_crackmapexec_offensive_tool_keyword = /handlekatz\.py/ nocase ascii wide
                        $string122_crackmapexec_offensive_tool_keyword = /hook\-lsassy\.py/ nocase ascii wide
                        $string123_crackmapexec_offensive_tool_keyword = /hook\-lsassy\.py/ nocase ascii wide
                        $string124_crackmapexec_offensive_tool_keyword = /hook\-lsassy\.py/ nocase ascii wide
                        $string125_crackmapexec_offensive_tool_keyword = /invoke_sessiongopher\.py/ nocase ascii wide
                        $string126_crackmapexec_offensive_tool_keyword = /keepass_discover\.py/ nocase ascii wide
                        $string127_crackmapexec_offensive_tool_keyword = "lsassy_dump" nocase ascii wide
                        $string128_crackmapexec_offensive_tool_keyword = /lsassy_dump\.py/ nocase ascii wide
                        $string129_crackmapexec_offensive_tool_keyword = /met_inject\.py/ nocase ascii wide
                        $string130_crackmapexec_offensive_tool_keyword = /mimipenguin\.py/ nocase ascii wide
                        $string131_crackmapexec_offensive_tool_keyword = /modules.{0,1000}daclread\.py/ nocase ascii wide
                        $string132_crackmapexec_offensive_tool_keyword = /ntlmv1\.py/ nocase ascii wide
                        $string133_crackmapexec_offensive_tool_keyword = "parse_nessus_file" nocase ascii wide
                        $string134_crackmapexec_offensive_tool_keyword = "parse_nmap_xml" nocase ascii wide
                        $string135_crackmapexec_offensive_tool_keyword = /petitpotam\.py/ nocase ascii wide
                        $string136_crackmapexec_offensive_tool_keyword = /RemoveKeePassTrigger\.ps1/ nocase ascii wide
                        $string137_crackmapexec_offensive_tool_keyword = /RestartKeePass\.ps1/ nocase ascii wide
                        $string138_crackmapexec_offensive_tool_keyword = /smbspider\.py/ nocase ascii wide
                        $string139_crackmapexec_offensive_tool_keyword = /temp.{0,1000}whoami\.txt/ nocase ascii wide
                        $string140_crackmapexec_offensive_tool_keyword = /whoami\.py/ nocase ascii wide
                        $string141_crackmapexec_offensive_tool_keyword = "cme smb " nocase ascii wide
                        $string142_crackmapexec_offensive_tool_keyword = "cme smb -" nocase ascii wide
                        $string143_crackmapexec_offensive_tool_keyword = "cme winrm " nocase ascii wide

    condition:
        any of them
}