rule win_seduploader_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.seduploader."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.seduploader"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { ff763c e8???????? 83c40c 3b4508 }
                                                            
        $sequence_1 = { 50 e8???????? 8b4510 83c6fe 8930 8d4601 50 }
                                                                                                
        $sequence_2 = { 8b4510 83c6fe 8930 8d4601 50 e8???????? }
                                                                                    
        $sequence_3 = { 83c6fe 8930 8d4601 50 e8???????? }
                                                                        
        $sequence_4 = { 8b4510 83c6fe 8930 8d4601 }
                                                            
        $sequence_5 = { e8???????? 8b4510 83c6fe 8930 8d4601 }
                                                                        
        $sequence_6 = { 56 6a3e 8bf1 e8???????? }
                                                            
        $sequence_7 = { 8b4510 83c6fe 8930 8d4601 50 }
                                                                        
        $sequence_8 = { 50 e8???????? 8b4510 83c6fe 8930 }
                                                                        
        $sequence_9 = { 83c6fe 8930 8d4601 50 }
                                                            
    condition:
        7 of them and filesize < 401408
}