rule MALPEDIA_Win_Manjusaka_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "9f188d62-91cb-5093-86fd-1c78b358599b"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.manjusaka"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.manjusaka_auto.yar#L1-L134"
    license_url        = "N/A"
    logic_hash         = "dab9ae475e0b441f3d26af80a0ebc722e21c766bc33599d09d1c1a5353ad7516"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0 = { eb b8 48 8d 05 b7 7a 10 00 48 89 44 24 50 48 c7 44 24 58 01 00 00 00 48 c7 44 24 60 00 00 00 00 48 8d 05 f9 b0 11 00 48 89 44 24 70 }
    $sequence_1 = { 4c 89 bc 24 80 04 00 00 4c 89 39 4c 89 71 08 48 89 59 10 48 c7 41 18 00 80 00 00 0f 11 70 18 48 89 79 30 }
    $sequence_2 = { 79 1d 41 8b 41 28 41 03 41 24 48 63 c8 48 8b c2 48 f7 d8 48 c1 e0 0a }
    $sequence_3 = { 89 41 1c 48 8b 45 d7 2b 45 27 05 fe ff ff 07 89 71 0c 89 41 20 8b 45 db }
    $sequence_4 = { 49 89 f8 e8 ?? ?? ?? ?? 48 ff cb 75 ed 0f 57 f6 48 8d 9c 24 10 01 00 00 0f 29 73 20 }
    $sequence_5 = { 89 8c 24 f8 00 00 00 48 89 6c 24 48 3b 08 0f 8c 21 fd ff ff 4c 8b bc 24 f0 00 00 00 4d 85 f6 74 24 }
    $sequence_6 = { 81 4d 40 02 02 00 00 45 33 c0 48 89 45 00 49 8b cd 83 c8 ff 66 89 45 44 b8 c8 00 00 00 }
    $sequence_7 = { 89 57 3c 48 89 47 40 89 57 50 48 8b 44 2e 60 48 89 47 58 48 8b 44 2e 28 48 8b 48 60 }
    $sequence_8 = { f7 d8 89 4c 24 20 44 8b c5 49 8b cd 1b d2 45 33 c9 83 e2 fc }
    $sequence_9 = { e8 ?? ?? ?? ?? 48 89 d9 e8 ?? ?? ?? ?? 48 8d 4f 70 e8 ?? ?? ?? ?? 48 8d 8f e0 00 00 00 e8 ?? ?? ?? ?? }

  condition:
    7 of them and filesize < 4772864
}