rule rule_redpill_offensive_tool_keyword
{
    meta:
        description = "Detection patterns for the tool 'redpill' taken from the ThreatHunting-Keywords github project"
        author = "@mthcht"
        reference = "https://github.com/mthcht/ThreatHunting-Keywords"
        tool = "redpill"
        rule_category = "offensive_tool_keyword"

    strings:
                        $string1_redpill_offensive_tool_keyword = /\scleantracks\.ps1/ nocase ascii wide
                        $string2_redpill_offensive_tool_keyword = /\sclipboard\.ps1/ nocase ascii wide
                        $string3_redpill_offensive_tool_keyword = /\sDumpLsass\.ps1/ nocase ascii wide
                        $string4_redpill_offensive_tool_keyword = /\sEnumBrowsers\.ps1/ nocase ascii wide
                        $string5_redpill_offensive_tool_keyword = /\sFWUprank\.ps1/ nocase ascii wide
                        $string6_redpill_offensive_tool_keyword = /\sGetPasswords\.ps1/ nocase ascii wide
                        $string7_redpill_offensive_tool_keyword = /\sInvoke\-Dump\.ps1/ nocase ascii wide
                        $string8_redpill_offensive_tool_keyword = /\slocalbrute\.ps1/ nocase ascii wide
                        $string9_redpill_offensive_tool_keyword = " -Mouselogger Start" nocase ascii wide
                        $string10_redpill_offensive_tool_keyword = /\sNoAmsi\.ps1/ nocase ascii wide
                        $string11_redpill_offensive_tool_keyword = /\sNSudo\.exe/ nocase ascii wide
                        $string12_redpill_offensive_tool_keyword = /\spapacat\.bat/ nocase ascii wide
                        $string13_redpill_offensive_tool_keyword = /\spapacat\.bat/ nocase ascii wide
                        $string14_redpill_offensive_tool_keyword = /\spapacat\.ps1/ nocase ascii wide
                        $string15_redpill_offensive_tool_keyword = " -PasswordSpray " nocase ascii wide
                        $string16_redpill_offensive_tool_keyword = /\sPhishCreds\.ps1/ nocase ascii wide
                        $string17_redpill_offensive_tool_keyword = /\sPingSweep\.ps1/ nocase ascii wide
                        $string18_redpill_offensive_tool_keyword = /\spowercat\.ps1/ nocase ascii wide
                        $string19_redpill_offensive_tool_keyword = /\sredpill\.ps1/ nocase ascii wide
                        $string20_redpill_offensive_tool_keyword = /\srevshell\.ps1/ nocase ascii wide
                        $string21_redpill_offensive_tool_keyword = /\sScanning\sEventvwr\sregistry\!\s\.\./ nocase ascii wide
                        $string22_redpill_offensive_tool_keyword = " -SmbLoginSpray " nocase ascii wide
                        $string23_redpill_offensive_tool_keyword = " -TaskName RedPillTask" nocase ascii wide
                        $string24_redpill_offensive_tool_keyword = " -UacMe Elevate -Execute " nocase ascii wide
                        $string25_redpill_offensive_tool_keyword = /\swhoami\s\>\szzz\.txt/ nocase ascii wide
                        $string26_redpill_offensive_tool_keyword = /\sWinBruteLogon\.zip/ nocase ascii wide
                        $string27_redpill_offensive_tool_keyword = /\$DumpLsass\=/ nocase ascii wide
                        $string28_redpill_offensive_tool_keyword = /\$Env\:TMP\\Camera\.ps1/ nocase ascii wide
                        $string29_redpill_offensive_tool_keyword = /\$Env\:TMP\\GetLogs\.ps1/ nocase ascii wide
                        $string30_redpill_offensive_tool_keyword = /\$env\:TMP\\Leaked\.txt/ nocase ascii wide
                        $string31_redpill_offensive_tool_keyword = /\$Env\:TMP\\Screenshot\.ps1/ nocase ascii wide
                        $string32_redpill_offensive_tool_keyword = /\$Env\:TMP\\StartWebServer\.ps1/ nocase ascii wide
                        $string33_redpill_offensive_tool_keyword = /\$Env\:TMP\\Start\-WebServer\.ps1/ nocase ascii wide
                        $string34_redpill_offensive_tool_keyword = /\$Env\:TMP\\tdfr\.log/ nocase ascii wide
                        $string35_redpill_offensive_tool_keyword = /\$Env\:TMP\\Upload\.ps1/ nocase ascii wide
                        $string36_redpill_offensive_tool_keyword = /\$Env\:TMP\\webserver\.ps1\.ps1/ nocase ascii wide
                        $string37_redpill_offensive_tool_keyword = /\$Keylogger\=/ nocase ascii wide
                        $string38_redpill_offensive_tool_keyword = /\$SmbLoginSpray\=/ nocase ascii wide
                        $string39_redpill_offensive_tool_keyword = /\%tmp\%\\void\.zip/ nocase ascii wide
                        $string40_redpill_offensive_tool_keyword = /\.ps1\s\-StartWebServer\sPowershell/ nocase ascii wide
                        $string41_redpill_offensive_tool_keyword = /\.ps1\s\-StartWebServer\sPython/ nocase ascii wide
                        $string42_redpill_offensive_tool_keyword = /\.ps1\s\-WifiPasswords\sDump/ nocase ascii wide
                        $string43_redpill_offensive_tool_keyword = /\/cleantracks\.ps1/ nocase ascii wide
                        $string44_redpill_offensive_tool_keyword = /\/CsOnTheFly\.ps1/ nocase ascii wide
                        $string45_redpill_offensive_tool_keyword = /\/DumpLsass\.ps1/ nocase ascii wide
                        $string46_redpill_offensive_tool_keyword = /\/FWUprank\.ps1/ nocase ascii wide
                        $string47_redpill_offensive_tool_keyword = /\/GetPasswords\.ps1/ nocase ascii wide
                        $string48_redpill_offensive_tool_keyword = /\/NSudo\.exe/ nocase ascii wide
                        $string49_redpill_offensive_tool_keyword = /\/papacat\.bat/ nocase ascii wide
                        $string50_redpill_offensive_tool_keyword = /\/papacat\.ps1/ nocase ascii wide
                        $string51_redpill_offensive_tool_keyword = /\/PhishCreds\.ps1/ nocase ascii wide
                        $string52_redpill_offensive_tool_keyword = /\/powercat\.ps1/ nocase ascii wide
                        $string53_redpill_offensive_tool_keyword = /\/redpill\.ps1/ nocase ascii wide
                        $string54_redpill_offensive_tool_keyword = /\/redpill\/bin\/.{0,1000}\.ps1/
                        $string55_redpill_offensive_tool_keyword = /\/revshell\.ps1/ nocase ascii wide
                        $string56_redpill_offensive_tool_keyword = /\/RunPEinMemory\.exe/ nocase ascii wide
                        $string57_redpill_offensive_tool_keyword = /\/RunPEinMemory64\.exe/ nocase ascii wide
                        $string58_redpill_offensive_tool_keyword = /\/ScanInterception\.ps1/ nocase ascii wide
                        $string59_redpill_offensive_tool_keyword = /\/stext\scredentials\.log/
                        $string60_redpill_offensive_tool_keyword = /\/WinBruteLogon\.zip/ nocase ascii wide
                        $string61_redpill_offensive_tool_keyword = "@Re@mov@e-@MpTh@re@at" nocase ascii wide
                        $string62_redpill_offensive_tool_keyword = "@redpill CS Compiled Executable" nocase ascii wide
                        $string63_redpill_offensive_tool_keyword = /\[START\]\:\sPassword\sspraying\sattack\!/ nocase ascii wide
                        $string64_redpill_offensive_tool_keyword = /\\AdsMasquerade\.ps1/ nocase ascii wide
                        $string65_redpill_offensive_tool_keyword = /\\AppData\\Local\\Temp\\Camera\.ps1/ nocase ascii wide
                        $string66_redpill_offensive_tool_keyword = /\\AppData\\Local\\Temp\\GetLogs\.ps1/ nocase ascii wide
                        $string67_redpill_offensive_tool_keyword = /\\AppData\\Local\\Temp\\Leaked\.txt/ nocase ascii wide
                        $string68_redpill_offensive_tool_keyword = /\\AppData\\Local\\Temp\\Payload\.ps1/ nocase ascii wide
                        $string69_redpill_offensive_tool_keyword = /\\AppData\\Local\\Temp\\Screenshot\.ps1/ nocase ascii wide
                        $string70_redpill_offensive_tool_keyword = /\\AppData\\Local\\Temp\\SSIDump\.zip/ nocase ascii wide
                        $string71_redpill_offensive_tool_keyword = /\\AppData\\Local\\Temp\\Start\-WebServer\.\.ps1/ nocase ascii wide
                        $string72_redpill_offensive_tool_keyword = /\\AppData\\Local\\Temp\\StartWebServer\.ps1/ nocase ascii wide
                        $string73_redpill_offensive_tool_keyword = /\\AppData\\Local\\Temp\\Upload\.ps1/ nocase ascii wide
                        $string74_redpill_offensive_tool_keyword = /\\AppData\\Local\\Temp\\webserver\.ps1/ nocase ascii wide
                        $string75_redpill_offensive_tool_keyword = /\\BrowserEnum\.log/ nocase ascii wide
                        $string76_redpill_offensive_tool_keyword = /\\BrowserLogger\.ps1/ nocase ascii wide
                        $string77_redpill_offensive_tool_keyword = /\\BypassCredGuard\.exe/ nocase ascii wide
                        $string78_redpill_offensive_tool_keyword = /\\C2Prank\.ps1/ nocase ascii wide
                        $string79_redpill_offensive_tool_keyword = /\\cleantracks\.ps1/ nocase ascii wide
                        $string80_redpill_offensive_tool_keyword = /\\CleanTracks\.ps1/ nocase ascii wide
                        $string81_redpill_offensive_tool_keyword = /\\clipboard\.ps1/ nocase ascii wide
                        $string82_redpill_offensive_tool_keyword = /\\Clipboard\.ps1/ nocase ascii wide
                        $string83_redpill_offensive_tool_keyword = /\\ConfuserEx\\Obfuscated\.exe/ nocase ascii wide
                        $string84_redpill_offensive_tool_keyword = /\\Convert\-ROT47\.ps1/ nocase ascii wide
                        $string85_redpill_offensive_tool_keyword = /\\CookieHijack\.ps1/ nocase ascii wide
                        $string86_redpill_offensive_tool_keyword = /\\credentials\.log/ nocase ascii wide
                        $string87_redpill_offensive_tool_keyword = /\\CScrandle_fileless\.cs/ nocase ascii wide
                        $string88_redpill_offensive_tool_keyword = /\\CsOnTheFly\.ps1/ nocase ascii wide
                        $string89_redpill_offensive_tool_keyword = /\\DecryptAutoLogon\.exe/ nocase ascii wide
                        $string90_redpill_offensive_tool_keyword = /\\DeletePSscriptSignning\.bat/ nocase ascii wide
                        $string91_redpill_offensive_tool_keyword = /\\DnSpoof\.ps1/ nocase ascii wide
                        $string92_redpill_offensive_tool_keyword = /\\DumpLsass\.ps1/ nocase ascii wide
                        $string93_redpill_offensive_tool_keyword = /\\enc\-rot13\.ps1/ nocase ascii wide
                        $string94_redpill_offensive_tool_keyword = /\\EnumBrowsers\.ps1/ nocase ascii wide
                        $string95_redpill_offensive_tool_keyword = /\\ETWpatch\\eventK\.exe/ nocase ascii wide
                        $string96_redpill_offensive_tool_keyword = /\\evil\.ps1/ nocase ascii wide
                        $string97_redpill_offensive_tool_keyword = /\\FWUprank\.ps1/ nocase ascii wide
                        $string98_redpill_offensive_tool_keyword = /\\GetAdmin\.log/ nocase ascii wide
                        $string99_redpill_offensive_tool_keyword = /\\GetAdmin\.ps1/ nocase ascii wide
                        $string100_redpill_offensive_tool_keyword = /\\GetPasswords\.ps1/ nocase ascii wide
                        $string101_redpill_offensive_tool_keyword = /\\gfscgsvs\.log/ nocase ascii wide
                        $string102_redpill_offensive_tool_keyword = /\\identify_offencive_tools\.log/ nocase ascii wide
                        $string103_redpill_offensive_tool_keyword = /\\Invoke\-Bypass\.ps1/ nocase ascii wide
                        $string104_redpill_offensive_tool_keyword = /\\Invoke\-Dump\.ps1/ nocase ascii wide
                        $string105_redpill_offensive_tool_keyword = /\\KeyDump\.log/ nocase ascii wide
                        $string106_redpill_offensive_tool_keyword = /\\KeyDump\.log/ nocase ascii wide
                        $string107_redpill_offensive_tool_keyword = /\\lnk_parser_cmd\.exe\s\-r\s/ nocase ascii wide
                        $string108_redpill_offensive_tool_keyword = /\\Lnk\-Sweeper\.ps1/ nocase ascii wide
                        $string109_redpill_offensive_tool_keyword = /\\Lnk\-Sweeper\.txt/ nocase ascii wide
                        $string110_redpill_offensive_tool_keyword = /\\Local\\Temp\\logins\.log/ nocase ascii wide
                        $string111_redpill_offensive_tool_keyword = /\\localbrute\.ps1/ nocase ascii wide
                        $string112_redpill_offensive_tool_keyword = /\\maildump\.txt/ nocase ascii wide
                        $string113_redpill_offensive_tool_keyword = /\\Meterpeter_.{0,1000}\.zip/ nocase ascii wide
                        $string114_redpill_offensive_tool_keyword = /\\MineDownloader\.vbs/ nocase ascii wide
                        $string115_redpill_offensive_tool_keyword = /\\NoAmsi\.ps1/ nocase ascii wide
                        $string116_redpill_offensive_tool_keyword = /\\NSudo\.exe/ nocase ascii wide
                        $string117_redpill_offensive_tool_keyword = /\\OutlookEmails\.log/ nocase ascii wide
                        $string118_redpill_offensive_tool_keyword = /\\papacat\.ps1/ nocase ascii wide
                        $string119_redpill_offensive_tool_keyword = /\\Persiste\.ps1/ nocase ascii wide
                        $string120_redpill_offensive_tool_keyword = /\\Persistence\.vbs/ nocase ascii wide
                        $string121_redpill_offensive_tool_keyword = /\\PhishCreds\.ps1/ nocase ascii wide
                        $string122_redpill_offensive_tool_keyword = /\\PingSweep\.ps1/ nocase ascii wide
                        $string123_redpill_offensive_tool_keyword = /\\powercat\.ps1/ nocase ascii wide
                        $string124_redpill_offensive_tool_keyword = /\\PSexecutionPolicy\.bat/ nocase ascii wide
                        $string125_redpill_offensive_tool_keyword = /\\psgetsys\.ps1/ nocase ascii wide
                        $string126_redpill_offensive_tool_keyword = /\\pysecdump\.exe/ nocase ascii wide
                        $string127_redpill_offensive_tool_keyword = /\\r00t\-3xp10it/ nocase ascii wide
                        $string128_redpill_offensive_tool_keyword = /\\Rat\-x64\.exe/ nocase ascii wide
                        $string129_redpill_offensive_tool_keyword = /\\Rat\-x64\.lnk/ nocase ascii wide
                        $string130_redpill_offensive_tool_keyword = /\\redpill\.ps1/ nocase ascii wide
                        $string131_redpill_offensive_tool_keyword = /\\redpill\.zip/ nocase ascii wide
                        $string132_redpill_offensive_tool_keyword = /\\redpill\.zip/ nocase ascii wide
                        $string133_redpill_offensive_tool_keyword = /\\redpill\\bin\\.{0,1000}\.ps1/ nocase ascii wide
                        $string134_redpill_offensive_tool_keyword = /\\revshell\.ps1/ nocase ascii wide
                        $string135_redpill_offensive_tool_keyword = /\\RunPEinMemory\.exe/ nocase ascii wide
                        $string136_redpill_offensive_tool_keyword = /\\RunPEinMemory64\.exe/ nocase ascii wide
                        $string137_redpill_offensive_tool_keyword = /\\ScanInterception\.ps1/ nocase ascii wide
                        $string138_redpill_offensive_tool_keyword = /\\SelectMyParent\.exe/ nocase ascii wide
                        $string139_redpill_offensive_tool_keyword = /\\sendkeys\.ps1/ nocase ascii wide
                        $string140_redpill_offensive_tool_keyword = /\\SigFlip\.exe/ nocase ascii wide
                        $string141_redpill_offensive_tool_keyword = /\\Smeagol\.log/ nocase ascii wide
                        $string142_redpill_offensive_tool_keyword = /\\Temp\\Wdlogfile\.log/ nocase ascii wide
                        $string143_redpill_offensive_tool_keyword = /\\URL_obfuscated\.log/ nocase ascii wide
                        $string144_redpill_offensive_tool_keyword = /\\void\.log/ nocase ascii wide
                        $string145_redpill_offensive_tool_keyword = /\\WinBruteLogon\.zip/ nocase ascii wide
                        $string146_redpill_offensive_tool_keyword = /\\windows\\temp\\fakefile\.exe/ nocase ascii wide
                        $string147_redpill_offensive_tool_keyword = /\\Xclipboard\.ps1/ nocase ascii wide
                        $string148_redpill_offensive_tool_keyword = /\]\sDumping\sbrowsers\scredentials\s\.\./ nocase ascii wide
                        $string149_redpill_offensive_tool_keyword = /\]\sDumping\smail\sserv\scredentials\s\.\./ nocase ascii wide
                        $string150_redpill_offensive_tool_keyword = /\]\sDumping\smessenger\scredentials\s\.\./ nocase ascii wide
                        $string151_redpill_offensive_tool_keyword = /\]\sSending\scredentials\sto\spastebin\s\.\./ nocase ascii wide
                        $string152_redpill_offensive_tool_keyword = /\]\sto\sdownload\svoid\.zip\susing\sBitsTransfer/ nocase ascii wide
                        $string153_redpill_offensive_tool_keyword = /0evilpwfilter\.dll/ nocase ascii wide
                        $string154_redpill_offensive_tool_keyword = "Administrator privileges required to spoof processes" nocase ascii wide
                        $string155_redpill_offensive_tool_keyword = /amibypass\.exe/ nocase ascii wide
                        $string156_redpill_offensive_tool_keyword = /amsibypass\.exe/ nocase ascii wide
                        $string157_redpill_offensive_tool_keyword = /amsitrigger_x64\.exe/ nocase ascii wide
                        $string158_redpill_offensive_tool_keyword = /bpysecdump\.exe/ nocase ascii wide
                        $string159_redpill_offensive_tool_keyword = /CommandCam\.exe\s\/devlist\s\>\s.{0,1000}\\CC\.log/ nocase ascii wide
                        $string160_redpill_offensive_tool_keyword = /Crandle_Builder\.ps1/ nocase ascii wide
                        $string161_redpill_offensive_tool_keyword = /CScrandle_fileless\.cs/ nocase ascii wide
                        $string162_redpill_offensive_tool_keyword = /DarkRCovery\.exe/ nocase ascii wide
                        $string163_redpill_offensive_tool_keyword = /DecodeRDPCache\.ps1/ nocase ascii wide
                        $string164_redpill_offensive_tool_keyword = /DEL\s\/q\s\/f\s\%appdata\%\\Google\\Chrome\\\\"User\sData\\"\\Default\\.{0,1000}\.tmp/ nocase ascii wide
                        $string165_redpill_offensive_tool_keyword = /DEL\s\/q\s\/f\s\%appdata\%\\Google\\Chrome\\\\"User\sData\\"\\Default\\History\\.{0,1000}\./ nocase ascii wide
                        $string166_redpill_offensive_tool_keyword = /DEL\s\/q\s\/f\s\%appdata\%\\Microsoft\\Windows\\Recent\\.{0,1000}\./ nocase ascii wide
                        $string167_redpill_offensive_tool_keyword = /DEL\s\/q\s\/f\s\%windir\%\\.{0,1000}\.log/ nocase ascii wide
                        $string168_redpill_offensive_tool_keyword = /DEL\s\/q\s\/f\s\%windir\%\\.{0,1000}\.tmp/ nocase ascii wide
                        $string169_redpill_offensive_tool_keyword = /DEL\s\/q\s\/f\s\%windir\%\\Prefetch\\.{0,1000}\.pf/ nocase ascii wide
                        $string170_redpill_offensive_tool_keyword = /DEL\s\/q\s\/f\s\%windir\%\\system\\.{0,1000}\.log/ nocase ascii wide
                        $string171_redpill_offensive_tool_keyword = /DEL\s\/q\s\/f\s\%windir\%\\system\\.{0,1000}\.tmp/ nocase ascii wide
                        $string172_redpill_offensive_tool_keyword = /DEL\s\/q\s\/f\s\%windir\%\\system32\\.{0,1000}\.log/ nocase ascii wide
                        $string173_redpill_offensive_tool_keyword = /DEL\s\/q\s\/f\s\%windir\%\\system32\\.{0,1000}\.tmp/ nocase ascii wide
                        $string174_redpill_offensive_tool_keyword = /DEL\s\/q\s\/f\s\%windir\%\\Temp\\.{0,1000}\.inf/ nocase ascii wide
                        $string175_redpill_offensive_tool_keyword = /DEL\s\/q\s\/f\s\%windir\%\\Temp\\.{0,1000}\.lnk/ nocase ascii wide
                        $string176_redpill_offensive_tool_keyword = /DEL\s\/q\s\/f\s\/s\s\%appdata\%\\Microsoft\\Windows\\Cookies\\.{0,1000}\./ nocase ascii wide
                        $string177_redpill_offensive_tool_keyword = /DEL\s\/q\s\/f\s\/s\s\%appdata\%\\Microsoft\\Windows\\Cookies\\.{0,1000}\./ nocase ascii wide
                        $string178_redpill_offensive_tool_keyword = /DEL\s\/q\s\/f\s\/s\s\%appdata\%\\Microsoft\\Windows\\Recent\\.{0,1000}\./ nocase ascii wide
                        $string179_redpill_offensive_tool_keyword = /DEL\s\/q\s\/f\s\/s\s\%appdata\%\\Mozilla\\Firefox\\Profiles\\.{0,1000}\./ nocase ascii wide
                        $string180_redpill_offensive_tool_keyword = /DEL\s\/q\s\/f\s\/s\s\%userprofile\%\\.{0,1000}\.log/ nocase ascii wide
                        $string181_redpill_offensive_tool_keyword = /DEL\s\/q\s\/f\s\/s\s\%userprofile\%\\.{0,1000}\.tmp/ nocase ascii wide
                        $string182_redpill_offensive_tool_keyword = /DeletePSscriptSignning\.bat/ nocase ascii wide
                        $string183_redpill_offensive_tool_keyword = /DigitalSignature\-Hijack\.ps1/ nocase ascii wide
                        $string184_redpill_offensive_tool_keyword = /Disable\-AMS1\.ps1/ nocase ascii wide
                        $string185_redpill_offensive_tool_keyword = /DisableDefender\.ps1/ nocase ascii wide
                        $string186_redpill_offensive_tool_keyword = /DnsSpoof\.ps1/ nocase ascii wide
                        $string187_redpill_offensive_tool_keyword = /DumpChromePasswords\.ps1/ nocase ascii wide
                        $string188_redpill_offensive_tool_keyword = /Env\:TMP\\ACl\.log/ nocase ascii wide
                        $string189_redpill_offensive_tool_keyword = /eviltree_x64\.exe/ nocase ascii wide
                        $string190_redpill_offensive_tool_keyword = "fail to retrieve SAM hashs!" nocase ascii wide
                        $string191_redpill_offensive_tool_keyword = /FakeCmdLine\.exe/ nocase ascii wide
                        $string192_redpill_offensive_tool_keyword = /Fake\-Cmdline\.exe/ nocase ascii wide
                        $string193_redpill_offensive_tool_keyword = /HarvestBrowserPasswords\.exe/ nocase ascii wide
                        $string194_redpill_offensive_tool_keyword = /HarvestBrowserPasswords\.pdb/ nocase ascii wide
                        $string195_redpill_offensive_tool_keyword = /HiddenUser\.ps1/ nocase ascii wide
                        $string196_redpill_offensive_tool_keyword = /How\-to\-bypass\-UAC\-in\-newer\-Windows\-versions\.html/ nocase ascii wide
                        $string197_redpill_offensive_tool_keyword = /Invoke\-HiveNightmare\.ps1/ nocase ascii wide
                        $string198_redpill_offensive_tool_keyword = /Invoke\-LazySign\.ps1/ nocase ascii wide
                        $string199_redpill_offensive_tool_keyword = "Invoke-Mimikatz" nocase ascii wide
                        $string200_redpill_offensive_tool_keyword = "Invoke-PortScan" nocase ascii wide
                        $string201_redpill_offensive_tool_keyword = "Invoke-PuttyCreds" nocase ascii wide
                        $string202_redpill_offensive_tool_keyword = "Invoke-SAMDump" nocase ascii wide
                        $string203_redpill_offensive_tool_keyword = "Invoke-SendToPasteBin" nocase ascii wide
                        $string204_redpill_offensive_tool_keyword = /Invoke\-WDigest\.ps1/ nocase ascii wide
                        $string205_redpill_offensive_tool_keyword = /Invoke\-WebCamAvi\.ps1/ nocase ascii wide
                        $string206_redpill_offensive_tool_keyword = "Key`logger running in background" nocase ascii wide
                        $string207_redpill_offensive_tool_keyword = /Keylogger\.ps1/ nocase ascii wide
                        $string208_redpill_offensive_tool_keyword = /List\-AllMailboxAndPST\.ps1/ nocase ascii wide
                        $string209_redpill_offensive_tool_keyword = /meterpeter\.ps1/ nocase ascii wide
                        $string210_redpill_offensive_tool_keyword = /Meterpeter_\$RandMe\.zip/ nocase ascii wide
                        $string211_redpill_offensive_tool_keyword = /Mouselogger\.ps1/ nocase ascii wide
                        $string212_redpill_offensive_tool_keyword = /mozlz4\-win32\.exe/ nocase ascii wide
                        $string213_redpill_offensive_tool_keyword = /MpCmdRun\.exe\s\-RemoveDefinitions\s\-All/ nocase ascii wide
                        $string214_redpill_offensive_tool_keyword = /MyMeterpreter\.ps1/ nocase ascii wide
                        $string215_redpill_offensive_tool_keyword = /Out\-PasteBin\.ps1/ nocase ascii wide
                        $string216_redpill_offensive_tool_keyword = /patch\-amsi\-x64\-powershell\.ps1/ nocase ascii wide
                        $string217_redpill_offensive_tool_keyword = /PPIDSpoof\.ps1/ nocase ascii wide
                        $string218_redpill_offensive_tool_keyword = /PrintNotifyPotato\.exe/ nocase ascii wide
                        $string219_redpill_offensive_tool_keyword = /PrintNotifyPotato\-NET2\.exe/ nocase ascii wide
                        $string220_redpill_offensive_tool_keyword = /r00t\-3xp10it\/venom\/master\/bin\/void\.zip/ nocase ascii wide
                        $string221_redpill_offensive_tool_keyword = /Reg\sAdd\s\'HKLM\\Software\\Policies\\Microsoft\\Windows\sDefender\'\s\/v\sDisableAntiSpyware\s\/t\sREG_DWORD\s\/d\s1\s\/f/ nocase ascii wide
                        $string222_redpill_offensive_tool_keyword = /REG\sDELETE\s\\"HKCU\\Software\\Classes\\Local\sSettings\\Software\\Microsoft\\Windows\\Shell\\MuiCache\\"\s\/f/ nocase ascii wide
                        $string223_redpill_offensive_tool_keyword = /REG\sDELETE\s\\"HKCU\\Software\\Microsoft\\Internet\sExplorer\\TypedPaths\\"\s\/f/ nocase ascii wide
                        $string224_redpill_offensive_tool_keyword = /REG\sDELETE\s\\"HKCU\\Software\\Microsoft\\Internet\sExplorer\\TypedURLs\\"\s\/f/ nocase ascii wide
                        $string225_redpill_offensive_tool_keyword = /REG\sDELETE\s\\"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\FeatureUsage\\AppBadgeUpdated\\"\s\/f/ nocase ascii wide
                        $string226_redpill_offensive_tool_keyword = /REG\sDELETE\s\\"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\FeatureUsage\\AppLaunch\\"\s\/f/ nocase ascii wide
                        $string227_redpill_offensive_tool_keyword = /REG\sDELETE\s\\"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\FeatureUsage\\ShowJumpView\\"\s\/f/ nocase ascii wide
                        $string228_redpill_offensive_tool_keyword = /REG\sDELETE\s\\"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\RecentDocs\\"\s\/f/ nocase ascii wide
                        $string229_redpill_offensive_tool_keyword = /REG\sDELETE\s\\"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\RunMRU\\"\s\/f/ nocase ascii wide
                        $string230_redpill_offensive_tool_keyword = /REG\sDELETE\s\\"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\UserAssist\\"\s\/f/ nocase ascii wide
                        $string231_redpill_offensive_tool_keyword = /REG\sDELETE\s\\"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Search\\RecentApps\\"\s\/f/ nocase ascii wide
                        $string232_redpill_offensive_tool_keyword = "-Rem@ov@eDef@ini@tio@ns -@Al@l" nocase ascii wide
                        $string233_redpill_offensive_tool_keyword = /revTCPclient\.ps1/ nocase ascii wide
                        $string234_redpill_offensive_tool_keyword = /RevTcpShell\.exe/ nocase ascii wide
                        $string235_redpill_offensive_tool_keyword = /ScanInterception_x64\.ps1/ nocase ascii wide
                        $string236_redpill_offensive_tool_keyword = "Scanning ConsoleHost_History for creds" nocase ascii wide
                        $string237_redpill_offensive_tool_keyword = "Scanning credential store for creds!" nocase ascii wide
                        $string238_redpill_offensive_tool_keyword = "Scanning registry for winlogon creds" nocase ascii wide
                        $string239_redpill_offensive_tool_keyword = "Scanning Teamviewer for creds!" nocase ascii wide
                        $string240_redpill_offensive_tool_keyword = "Scanning winlogon for crypted creds!" nocase ascii wide
                        $string241_redpill_offensive_tool_keyword = /Sending\sloot\sto\spastebin\swebserver\./ nocase ascii wide
                        $string242_redpill_offensive_tool_keyword = /SendToPasteBin\.ps1/ nocase ascii wide
                        $string243_redpill_offensive_tool_keyword = /ServiceName.{0,1000}CorpVPN/ nocase ascii wide
                        $string244_redpill_offensive_tool_keyword = /SharpGhost\.exe/ nocase ascii wide
                        $string245_redpill_offensive_tool_keyword = /SharpGhosting\.exe/ nocase ascii wide
                        $string246_redpill_offensive_tool_keyword = /Show\-BallonTip\.ps1/ nocase ascii wide
                        $string247_redpill_offensive_tool_keyword = /Show\-BalloonTip\.ps1/ nocase ascii wide
                        $string248_redpill_offensive_tool_keyword = /Sigthief\.py/ nocase ascii wide
                        $string249_redpill_offensive_tool_keyword = /SilenceDefender\.ps1/ nocase ascii wide
                        $string250_redpill_offensive_tool_keyword = /SilenceDefender_ATP\.log/ nocase ascii wide
                        $string251_redpill_offensive_tool_keyword = /SilenceDefender_ATP\.ps1/ nocase ascii wide
                        $string252_redpill_offensive_tool_keyword = /smblogin\.results\.log/ nocase ascii wide
                        $string253_redpill_offensive_tool_keyword = /smblogin\.results\.log/ nocase ascii wide
                        $string254_redpill_offensive_tool_keyword = /smblogin\-spray\.ps1/ nocase ascii wide
                        $string255_redpill_offensive_tool_keyword = /Spray\-Passwords\.ps1/ nocase ascii wide
                        $string256_redpill_offensive_tool_keyword = /Start\-SimpleHTTPServer\.ps1/ nocase ascii wide
                        $string257_redpill_offensive_tool_keyword = /TeamViewerDecrypt\.ps1/ nocase ascii wide
                        $string258_redpill_offensive_tool_keyword = /Temp\\graca\.log/ nocase ascii wide
                        $string259_redpill_offensive_tool_keyword = /TestMyPrivs\.ps1/ nocase ascii wide
                        $string260_redpill_offensive_tool_keyword = "-u SSARedTeam:s3cr3t" nocase ascii wide
                        $string261_redpill_offensive_tool_keyword = /UACBypassCMSTP\.ps1/ nocase ascii wide
                        $string262_redpill_offensive_tool_keyword = /vbs_obfuscator\.vbs/ nocase ascii wide
                        $string263_redpill_offensive_tool_keyword = /vbs_ofuscator\.vbs/ nocase ascii wide
                        $string264_redpill_offensive_tool_keyword = "vssadmin delete shadows /for=%systemdrive% /all /quiet" nocase ascii wide
                        $string265_redpill_offensive_tool_keyword = /WebBrowserPassView\.cfg/ nocase ascii wide
                        $string266_redpill_offensive_tool_keyword = /WebBrowserPassView\.exe/ nocase ascii wide
                        $string267_redpill_offensive_tool_keyword = /WebBrowserPassView\.pdb/ nocase ascii wide
                        $string268_redpill_offensive_tool_keyword = /WifiPasswords\.ps1/ nocase ascii wide
                        $string269_redpill_offensive_tool_keyword = /WinBruteLogon\.exe/ nocase ascii wide
                        $string270_redpill_offensive_tool_keyword = "wtXx6sM1482OWfsMXon6Am4Hi01idvFNgog3jTCsyAA=" nocase ascii wide

    condition:
        any of them
}