rule win_mistpen_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.mistpen."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.mistpen"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 7602 ffc0 4585c0 8bf0 }
                                                            
        $sequence_1 = { 420fb6842090960200 4433d8 45335ffc 4533da 458bd3 45895e20 4533d0 }
                                                                                                
        $sequence_2 = { 4533848460850200 410fb6c3 4533848460750200 400fb6c7 4533848490920200 4533465c 418bc0 }
                                                                                                
        $sequence_3 = { 4403c1 418bcb 410bca 458bc8 23cf 41c1c91b }
                                                                                    
        $sequence_4 = { 4c8d0d74d70000 b919000000 4c8d0564d70000 488d1561d70000 e8???????? 4885c0 7420 }
                                                                                                
        $sequence_5 = { c1e31e 8bcf 410bcd 8bc7 4123cf 4123c5 0bc8 }
                                                                                                
        $sequence_6 = { 458b8c9460810200 4133bc8490920200 418bc0 41337e20 c1e808 0fb6c8 8bc3 }
                                                                                                
        $sequence_7 = { 83f838 7cec 8b4c2458 8bc1 c1e818 884594 8bc1 }
                                                                                                
        $sequence_8 = { 488d45e8 48894de8 488945f0 488d1590d10000 b805000000 894520 }
                                                                                    
        $sequence_9 = { 7e1d 488b5588 4c8d4c2450 458bc4 498bce }
                                                                        
    condition:
        7 of them and filesize < 458752
}