rule win_cryptoshield_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.cryptoshield."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.cryptoshield"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 7405 83f804 751a e8???????? }
                                                            
        $sequence_1 = { ff15???????? 83c40c 8d85b0edffff 50 683f020f00 }
                                                                        
        $sequence_2 = { 75cb 66833a00 8bfa 744d 8d4900 }
                                                                        
        $sequence_3 = { 6a00 8d85e8fbffff 50 6a01 68???????? 56 ff15???????? }
                                                                                                
        $sequence_4 = { 8d85c4f1ffff 68???????? 50 ffd3 }
                                                            
        $sequence_5 = { 50 ffd7 8b45f0 85c0 7506 }
                                                                        
        $sequence_6 = { 0f84a6000000 8d45fc 50 6a01 ff75f8 6810660000 }
                                                                                    
        $sequence_7 = { 6a00 ffd3 85c0 0f84bb000000 6804010000 }
                                                                        
        $sequence_8 = { ff15???????? c745fc00000000 85f6 7407 56 ff15???????? 85ff }
                                                                                                
        $sequence_9 = { 0fb7c0 50 8d45f4 68???????? 50 ffd6 83c40c }
                                                                                                
    condition:
        7 of them and filesize < 131072
}