rule win_madmax_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.madmax."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.madmax"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { f605????????5a 0f85ea000000 95 8883424ceb3e 38af847bb313 8320aa d590 }
                                                                                                
        $sequence_1 = { fa 768b 872a fd 2a4f0e e8???????? b3df }
                                                                                                
        $sequence_2 = { af 2f ac 7cd6 45 98 92 }
                                                                                                
        $sequence_3 = { bf45f19eb2 ac a5 d6 34e2 1117 4c }
                                                                                                
        $sequence_4 = { e6d1 f5 9f 45 7b78 39770f d0de }
                                                                                                
        $sequence_5 = { b4bf 49 95 14c0 393f d8d3 fc }
                                                                                                
        $sequence_6 = { 7135 fd 9e 9d 50 50 9c }
                                                                                                
        $sequence_7 = { c9 09f8 96 67a4 61 52 636e85 }
                                                                                                
        $sequence_8 = { 9d 53 6a03 e8???????? 83c40c 9c f605????????e8 }
                                                                                                
        $sequence_9 = { be492ea060 c14434e19e 46 2f d3f4 fa 6be92a }
                                                                                                
    condition:
        7 of them and filesize < 3227648
}