rule MALPEDIA_Win_Gpcode_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "d8b81e5a-8691-5b0a-9c29-2fe185a250cc"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.gpcode"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.gpcode_auto.yar#L1-L188"
    license_url        = "N/A"
    logic_hash         = "47d13f6f4636c7a610d9f5f6fa6bfc46db8fee0da3e7f134864d9085143c9558"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0  = { e8 ?? ?? ?? ?? a1 ?? ?? ?? ?? a3 ?? ?? ?? ?? 68 00 00 10 00 68 ?? ?? ?? ?? ff 35 ?? ?? ?? ?? }
    $sequence_1  = { 68 ?? ?? ?? ?? e8 ?? ?? ?? ?? 91 6a 00 }
    $sequence_2  = { e8 ?? ?? ?? ?? e8 ?? ?? ?? ?? c7 05 ?? ?? ?? ?? 01 00 00 00 c3 55 8b ec }
    $sequence_3  = { 85 c0 74 79 33 c0 50 50 6a 03 50 }
    $sequence_4  = { ff 35 ?? ?? ?? ?? 68 ?? ?? ?? ?? ff 75 f8 ff 15 ?? ?? ?? ?? 89 45 f4 85 c0 74 25 }
    $sequence_5  = { 89 06 83 c6 08 e2 e6 59 e2 dc }
    $sequence_6  = { 83 c4 0c 8d 45 fc 50 8d 45 0c ff 30 e8 ?? ?? ?? ?? }
    $sequence_7  = { e8 ?? ?? ?? ?? 0b c0 75 04 33 c0 c9 c3 89 45 f0 }
    $sequence_8  = { c6 00 00 2d ?? ?? ?? ?? 50 8d 85 e8 fe ff ff 50 68 ?? ?? ?? ?? }
    $sequence_9  = { 68 ?? ?? ?? ?? 6a 00 e8 ?? ?? ?? ?? 6a 0a 68 ?? ?? ?? ?? 6a 00 e8 ?? ?? ?? ?? }
    $sequence_10 = { e8 ?? ?? ?? ?? 83 f8 ff 75 05 5a }
    $sequence_11 = { 00 14 38 eb 06 80 c1 07 00 0c 38 }
    $sequence_12 = { 00 05 ?? ?? ?? ?? 0f b6 05 ?? ?? ?? ?? 8a d3 8d 80 b8 fe e0 14 }
    $sequence_13 = { 00 16 40 3b c3 72 de }
    $sequence_14 = { 01 45 f0 8b 4d f0 3b 4d 14 0f 82 63 fe ff ff }
    $sequence_15 = { 00 0c 38 40 3b 45 f8 72 e3 }
    $sequence_16 = { 01 44 24 0c 85 f6 7f dd 33 c0 }
    $sequence_17 = { 01 06 eb 94 55 8b ec }
    $sequence_18 = { 00 0e eb 08 02 c9 b2 f9 }

  condition:
    7 of them and filesize < 761856
}