rule MALPEDIA_Win_Rad_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "7146ba59-d944-5b98-95a4-2cbd8d5bc1ff"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.rad"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.rad_auto.yar#L1-L128"
    license_url        = "N/A"
    logic_hash         = "ca5f1a440d85092616999ffada86b8990e8f68350339b252577329abb6a444ee"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0 = { c6 44 24 20 00 e8 ?? ?? ?? ?? 8d 54 24 20 52 8d 8c 24 98 00 00 00 c6 84 24 0c 06 00 00 18 ff 15 ?? ?? ?? ?? }
    $sequence_1 = { 8b 86 80 00 00 00 3b c3 74 1b 8b be 84 00 00 00 e8 ?? ?? ?? ?? 8b 86 80 00 00 00 }
    $sequence_2 = { a1 ?? ?? ?? ?? 33 c4 89 44 24 34 8b 45 08 8b 00 85 c0 75 1a }
    $sequence_3 = { 8b 84 24 1c 01 00 00 50 ff d6 83 c4 04 8b 8c 24 00 06 00 00 64 89 0d 00 00 00 00 }
    $sequence_4 = { 8d 8d 70 ff ff ff ff 25 ?? ?? ?? ?? 8b 85 78 ff ff ff 83 e0 02 0f 84 13 00 00 00 83 a5 78 ff ff ff fd }
    $sequence_5 = { ff d3 8d 8c 24 94 00 00 00 c6 84 24 08 06 00 00 05 ff 15 ?? ?? ?? ?? 8b 4c 24 18 51 8d 8c 24 98 00 00 00 }
    $sequence_6 = { ff 15 ?? ?? ?? ?? 8d 8c 24 94 00 00 00 c6 84 24 08 06 00 00 20 ff 15 ?? ?? ?? ?? b8 ?? ?? ?? ?? 8d 4c 24 20 }
    $sequence_7 = { e8 ?? ?? ?? ?? 8b c7 50 c6 45 fc 02 e8 ?? ?? ?? ?? 8b c8 }
    $sequence_8 = { 72 0a 8b 4c 24 34 51 ff d6 83 c4 04 8d 94 24 a8 00 00 00 52 }
    $sequence_9 = { 8d 7e 04 c6 45 fc 29 8d 4f 04 c7 06 ?? ?? ?? ?? 89 bd 10 fd ff ff ff 15 ?? ?? ?? ?? }

  condition:
    7 of them and filesize < 207872
}