rule win_icedid_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.icedid."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.icedid"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { ff15???????? 85c0 7511 56 57 ff15???????? }
                                                                                    
        $sequence_1 = { 7411 40 50 6a08 ff15???????? }
                                                                        
        $sequence_2 = { 50 ff15???????? 8bf7 8bc6 }
                                                            
        $sequence_3 = { 7413 ff36 6a08 ff15???????? }
                                                            
        $sequence_4 = { 85f6 742c 803e00 7427 6a3b 56 ff15???????? }
                                                                                                
        $sequence_5 = { 85ff 7418 c60700 47 57 ff15???????? }
                                                                                    
        $sequence_6 = { 68???????? 6a00 ff15???????? 33c0 40 }
                                                                        
        $sequence_7 = { 6a3b 56 ff15???????? 8bf8 85ff 7418 }
                                                                                    
        $sequence_8 = { e8???????? 8bf0 8d45fc 50 ff75fc 6a05 }
                                                                                    
        $sequence_9 = { 5f 743f 8d5808 0fb713 }
                                                            
        $sequence_10 = { 03c2 eb5c 8d5004 89542414 8b12 85d2 7454 }
                                                                                                
        $sequence_11 = { 0132 47 83c302 3bfd 72c4 8b542414 }
                                                                                    
        $sequence_12 = { 85d2 7454 8d6af8 d1ed }
                                                            
        $sequence_13 = { 8d5808 0fb713 8954241c 66c16c241c0c }
                                                            
        $sequence_14 = { 8d4508 50 0fb6440b34 50 ff740b28 }
                                                                        
        $sequence_15 = { 2345fc 8be5 5d c3 55 8bec ff7518 }
                                                                                                
        $sequence_16 = { ff15???????? 85c0 750a b8010000c0 e9???????? }
                                                                        
        $sequence_17 = { 8a4173 a808 75f5 a804 }
                                                            
        $sequence_18 = { ff5010 85c0 7407 33c0 e9???????? }
                                                                        
        $sequence_19 = { 89442408 0fb70424 8b4c2408 03c8 }
                                                            
        $sequence_20 = { 48 8b523c e8???????? 48 89433c 48 85c0 }
                                                                                                
        $sequence_21 = { 48 8945b8 48 85c0 0f84db000000 8b4324 48 }
                                                                                                
        $sequence_22 = { 4c 8b15???????? 48 8d442450 44 }
                                                                        
        $sequence_23 = { 49 8943d8 ff15???????? 85c0 }
                                                            
        $sequence_24 = { 4c8bc3 33d2 488bc8 ff15???????? 488bb590020000 }
                                                                        
        $sequence_25 = { 3b7b1c 72d7 8b430c 4803c6 0f845affffff 488bcd }
                                                                                    
        $sequence_26 = { 488d5702 488bce ff15???????? ba22000000 488bce ff15???????? 4885c0 }
                                                                                                
        $sequence_27 = { 4289448440 488b5c2428 4c3b5c2430 7307 4c8b742420 }
                                                                        
        $sequence_28 = { 488bd8 4885c0 0f84cb000000 488bb590020000 41ba01000000 }
                                                                        
        $sequence_29 = { 488bb590020000 488b7c2438 33c9 33d2 }
                                                            
        $sequence_30 = { 80bb8000000040 0f8577ffffff 488d8b81000000 488d542450 e8???????? 85c0 }
                                                                                    
        $sequence_31 = { 75b9 4883c314 e9???????? ff15???????? 33c0 }
                                                                        
    condition:
        7 of them and filesize < 303104
}