rule MALPEDIA_Win_Rokku_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "75b8aef9-2da5-556e-9635-075190f42681"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.rokku"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.rokku_auto.yar#L1-L129"
    license_url        = "N/A"
    logic_hash         = "3a863d12b65613db8f002333dfdefeb5bdf603888d10aa587187b07349134f7e"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0 = { 0f 28 05 ?? ?? ?? ?? 0f 11 45 61 8a c1 02 85 41 ff ff ff 30 84 0d 42 ff ff ff }
    $sequence_1 = { 8b c1 8b 94 24 44 00 03 00 0b c2 0f 84 56 02 00 00 6a 06 }
    $sequence_2 = { 8d 14 1b f7 ea 8b f8 8b da 8b c1 f7 6c 24 70 03 f8 }
    $sequence_3 = { 89 44 24 38 8b 44 24 6c 89 44 24 18 8b 44 24 68 89 44 24 14 8b 44 24 64 89 44 24 44 }
    $sequence_4 = { 8b 0e e8 ?? ?? ?? ?? 33 c9 84 c0 0f 45 4d 08 89 0e eb 1f }
    $sequence_5 = { c7 06 ?? ?? ?? ?? 83 65 fc 00 8b 4e 04 85 c9 74 0d 8b 01 ff 50 10 }
    $sequence_6 = { 13 ea f7 6c 24 54 89 6c 24 20 01 44 24 10 8d 04 36 8b 74 24 60 }
    $sequence_7 = { 8b 7a 18 8b 52 20 33 79 18 33 51 20 23 fd 8b 48 24 23 d5 }
    $sequence_8 = { 89 4d 10 8b 4c 24 14 0f a4 c1 19 8b 4c 24 68 c1 e0 19 2b f0 8b c7 }
    $sequence_9 = { 55 56 57 89 8c 24 ac 00 00 00 8b 02 89 44 24 54 8b 42 04 }

  condition:
    7 of them and filesize < 548864
}