rule MALPEDIA_Win_Zeus_Action_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "65e8f438-ad6b-5cc2-8433-22cd51967cfc"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.zeus_action"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.zeus_action_auto.yar#L1-L132"
    license_url        = "N/A"
    logic_hash         = "d578cc91c04661eaf2cc2ee8b8d1f82a11b119d1521d38f5e03bfba5cd5d37a6"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0 = { 66 89 45 fa 8d 75 f4 a5 a5 a5 83 83 d8 75 00 00 0c 33 f6 }
    $sequence_1 = { 74 17 8b 01 57 51 ff 50 34 8b 4d e8 85 c9 }
    $sequence_2 = { ff 15 ?? ?? ?? ?? b8 00 08 00 00 66 3b 05 ?? ?? ?? ?? 75 10 e8 ?? ?? ?? ?? 84 c0 74 07 }
    $sequence_3 = { 89 45 08 3b f0 74 33 8d 7b 14 85 f6 75 04 33 c0 }
    $sequence_4 = { 0f 84 d0 02 00 00 39 5d f8 0f 84 c7 02 00 00 39 5d f4 0f 84 be 02 00 00 39 5d d0 0f 84 b5 02 00 00 }
    $sequence_5 = { 49 3b c6 75 09 8b 7d d8 89 4d e8 }
    $sequence_6 = { 59 85 c0 0f 84 79 01 00 00 83 7d dc 00 74 0f 53 e8 ?? ?? ?? ?? }
    $sequence_7 = { 83 c0 fb 83 f8 03 77 40 f7 45 d0 00 08 00 00 74 16 03 f9 03 d9 }
    $sequence_8 = { 50 8b 46 18 83 c0 04 50 ff 15 ?? ?? ?? ?? 8b 76 1c 83 c4 0c }
    $sequence_9 = { ff 15 ?? ?? ?? ?? 85 c0 78 17 56 8d 85 f8 fd ff ff 50 8d 85 f0 fb ff ff }

  condition:
    7 of them and filesize < 827392
}