rule MALPEDIA_Win_Industroyer2_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "01c28e59-8cb1-5bf1-9de6-64ce0dd77d4a"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.industroyer2"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.industroyer2_auto.yar#L1-L130"
    license_url        = "N/A"
    logic_hash         = "bbf01a0f560944dbb85cdfc8fdeff74a884348b77c6b1a1a74790ea421be78c4"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0 = { 73 2c 83 7d f8 00 74 26 8b 45 fc 8b 4d f4 8b 14 81 89 55 9c }
    $sequence_1 = { 89 48 0c 8b 55 fc 8b 45 1c 89 42 10 69 4d 18 a0 86 01 00 03 4d 1c }
    $sequence_2 = { eb 07 c7 45 d0 00 00 00 00 8b 45 08 8a 4d d0 88 88 45 00 01 00 }
    $sequence_3 = { 8b 4d 08 e8 ?? ?? ?? ?? 89 45 fc 68 ?? ?? ?? ?? 8b 45 08 50 }
    $sequence_4 = { 88 51 03 8b 45 fc 8b 48 04 8b 55 1c 8b 82 38 00 01 00 89 41 04 8b 4d fc }
    $sequence_5 = { c1 e2 00 8b 45 fc 8b 4d 08 8a 14 11 88 50 05 b8 01 00 00 00 d1 e0 }
    $sequence_6 = { 8b 4d f0 51 ff 15 ?? ?? ?? ?? 85 c0 74 06 c6 45 ff 01 eb 04 }
    $sequence_7 = { c6 40 0c 00 8b 4d fc c6 41 14 0a 6a 04 8b 55 fc 83 c2 10 52 }
    $sequence_8 = { 83 7d f8 00 74 2c 8b 55 fc 8b 45 f4 8b 0c 90 89 8d 78 ff ff ff 8b 95 78 ff ff ff }
    $sequence_9 = { 8b 45 fc 50 e8 ?? ?? ?? ?? 0f b6 c8 85 c9 74 44 68 ?? ?? ?? ?? }

  condition:
    7 of them and filesize < 100352
}