rule win_privateloader_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.privateloader."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.privateloader"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 8bec 83ec1c 894df8 8b45f8 8b4810 894df4 }
                                                                                    
        $sequence_1 = { 8945f4 8b4dfc 83791408 7209 }
                                                            
        $sequence_2 = { 8b55e4 8a45ff 88040a 8b45f8 }
                                                            
        $sequence_3 = { 8b4d08 3b4814 776d 8b55f8 8955f4 8b45f4 8945ec }
                                                                                                
        $sequence_4 = { 8b45d8 8b4ddc 8b55d0 8b75d4 }
                                                            
        $sequence_5 = { 8b4508 8945e4 8b4de8 034de4 8a55ff }
                                                                        
        $sequence_6 = { 8945c8 8955cc 8b45c8 8b55cc 5e }
                                                                        
        $sequence_7 = { 8b55f8 8b45f4 3b4214 736c }
                                                            
        $sequence_8 = { e8???????? 33d2 b93f000000 f7f1 }
                                                            
        $sequence_9 = { 8b4590 8b4d94 8b5588 8b758c }
                                                            
        $sequence_10 = { a3???????? 33c0 5e c3 3b0d???????? }
                                                                        
        $sequence_11 = { e8???????? 83c610 83c002 83ef08 }
                                                            
        $sequence_12 = { 81ec68010000 a1???????? 33c5 8945fc 56 57 }
                                                                                    
        $sequence_13 = { 83c201 8955e0 83d600 8975e4 }
                                                            
        $sequence_14 = { 8b4de0 8b45e4 50 51 52 56 e8???????? }
                                                                                                
        $sequence_15 = { 6a04 8d4310 50 6a06 }
                                                            
        $sequence_16 = { 0bc8 56 57 7529 }
                                                            
        $sequence_17 = { 8b8578ffffff 8b8d7cffffff 8b9570ffffff 8bb574ffffff }
                                                            
        $sequence_18 = { 03d0 8b4d9c 13f1 83c201 }
                                                            
    condition:
        7 of them and filesize < 3670016
}