rule win_unidentified_121_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.unidentified_121."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.unidentified_121"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 8b55fc 8b421c 2540040000 750c }
                                                            
        $sequence_1 = { 8b55fc 8b4218 8945f0 8b4d08 83792800 7405 }
                                                                                    
        $sequence_2 = { 8b55fc 8b421c 50 68???????? 8b4d08 }
                                                                        
        $sequence_3 = { ff15???????? 4c8d4c2438 488b0d???????? 41b804000000 488d1584810100 89c3 e8???????? }
                                                                                                
        $sequence_4 = { 0f8499000000 41b806000000 ba01000000 b902000000 ffd5 488b5320 }
                                                                                    
        $sequence_5 = { 8b55fc 8b421c 2580000000 740c }
                                                            
        $sequence_6 = { 4889d9 48c744245800000000 48c744246000000000 e8???????? 4889d9 ff15???????? }
                                                                                    
        $sequence_7 = { 8944244c 0f85a1000000 83430801 4d89e1 4989e8 }
                                                                        
        $sequence_8 = { 3c54 0f857e000000 e8???????? 4d85ed ba01000000 752f }
                                                                                    
        $sequence_9 = { 8b55fc 8b4218 99 8bc8 }
                                                            
        $sequence_10 = { 85db 0f8589000000 488b5028 4883ea01 4883fafd 777b 4885ed }
                                                                                                
        $sequence_11 = { 7511 8b7004 85f6 7539 488907 48c70300000000 }
                                                                                    
        $sequence_12 = { e8???????? 41f6c404 488b8600010000 4889ae28010000 0f84b7000000 488d5001 483dff000000 }
                                                                                                
        $sequence_13 = { 8b55fc 8b421c 2580020000 8b4df8 }
                                                            
        $sequence_14 = { 8b55fc 8b421c 0d80020000 8b4dfc }
                                                            
        $sequence_15 = { 8b55fc 8b421c 0d00080000 8b4dfc 89411c e9???????? }
                                                                                    
    condition:
        7 of them and filesize < 2419712
}