rule win_portstarter_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.portstarter."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.portstarter"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 4c8b9c24a8010000 4c89442448 7507 4d8b4c2408 }
                                                            
        $sequence_1 = { 4c8b8c24d8000000 4d8b5918 4d8b6318 4d8b6b08 4d8b1b 4d39e5 0f8645050000 }
                                                                                                
        $sequence_2 = { 4c8b9c24b8000000 498d3c03 488b842410010000 4c89d1 4c89c6 90 }
                                                                                    
        $sequence_3 = { 4c8b942468010000 4d21fa 4d09d5 49c1ed3f 4f8d1404 4d01ea }
                                                                                    
        $sequence_4 = { 4c8d6424f0 4d3b6610 0f8660030000 4881ec90000000 4889ac2488000000 488dac2488000000 }
                                                                                    
        $sequence_5 = { 4c8b9424d8000000 4c8ba42400010000 4c896310 4c895318 }
                                                            
        $sequence_6 = { 4c8b9424d8000000 4d39e2 0f8745010000 0f8734010000 }
                                                            
        $sequence_7 = { 4c8d6424d0 4d3b6610 0f8610020000 4881ecb0000000 }
                                                            
        $sequence_8 = { 41b800de1b00 488d15d02f0000 488d4c2420 e8???????? }
                                                            
        $sequence_9 = { 4863442430 486bc010 488d0de3061c00 4803c8 }
                                                            
        $sequence_10 = { 4883ec48 8b442458 89442424 48c744242800000000 41b800de1b00 }
                                                                        
        $sequence_11 = { 488d0de3061c00 4803c8 488bc1 48634c2434 }
                                                            
    condition:
        7 of them and filesize < 14216192
}