rule win_tigerlite_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.tigerlite."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.tigerlite"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 488bf8 4883f8ff 7520 488d15e1c50100 488bce e8???????? }
                                                                                    
        $sequence_1 = { 4885c0 0f84a9010000 488bc8 ff15???????? 488d1520ad0000 }
                                                                        
        $sequence_2 = { 803c0700 75f7 488d4f01 4d8bce }
                                                            
        $sequence_3 = { 2bca 8d95e0f9ffff 8d7201 8a02 42 }
                                                                        
        $sequence_4 = { 50 e8???????? 83c40c c645f400 833d????????00 c745f500000000 }
                                                                                    
        $sequence_5 = { e8???????? 4c8d4530 8d5614 488d0defa70100 897530 e8???????? 8b5530 }
                                                                                                
        $sequence_6 = { ff15???????? 8bf8 e9???????? 8b8528e5ffff 8b0c85489d4100 8b8524e5ffff }
                                                                                    
        $sequence_7 = { 0fbec2 0fbe80d8214100 83e00f eb02 33c0 }
                                                                        
        $sequence_8 = { 8d859cf2ffff 03c1 8b8d24e5ffff 50 8b8528e5ffff 8b0485489d4100 ff3401 }
                                                                                                
        $sequence_9 = { 50 8b0495489d4100 ff3418 ff15???????? 85c0 750a }
                                                                                    
        $sequence_10 = { 488bfa 488bd9 488d0549e90000 488981a0000000 83611000 }
                                                                        
        $sequence_11 = { 8a06 46 88441905 8b45f4 83fa02 7c11 8b0c85489d4100 }
                                                                                                
        $sequence_12 = { ff742414 8b442420 03c6 57 }
                                                            
        $sequence_13 = { 785b 8bc3 2503000080 7d07 }
                                                            
        $sequence_14 = { 0fb605???????? 488bf9 88442428 e8???????? 4885c0 0f8422010000 }
                                                                                    
        $sequence_15 = { c3 33d2 41b800040000 488bc8 }
                                                            
    condition:
        7 of them and filesize < 349184
}