rule MALPEDIA_Win_Fobber_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "ab54349a-7d99-57ef-92f9-d6c817ce7b6a"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.fobber"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.fobber_auto.yar#L1-L175"
    license_url        = "N/A"
    logic_hash         = "16740b1e84557358ab17bd4ccf852daa4c4e1c0339646d5e9060d6d119fab8ab"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0  = { 89 e5 51 8b 45 10 8b 55 08 8b 4d 0c 30 02 c0 c8 03 }
    $sequence_1  = { 89 e5 6a 00 ff 75 0c ff 75 08 e8 ?? ?? ?? ?? }
    $sequence_2  = { 89 e5 31 c0 50 50 ff 75 0c ff 75 08 50 }
    $sequence_3  = { 57 51 8b 7d 08 30 c0 31 c9 f7 d1 fc }
    $sequence_4  = { e3 03 4f 89 f8 5f 59 }
    $sequence_5  = { 8b 75 0c 8b 4d 10 39 f7 76 0e 8d 04 31 39 f8 76 07 }
    $sequence_6  = { 66 0f c1 46 f9 66 85 c0 75 15 0f b6 46 f8 50 0f b7 46 f6 }
    $sequence_7  = { 55 89 e5 68 00 80 00 00 6a 00 }
    $sequence_8  = { 75 0f 0f b7 03 83 f8 61 0f 83 01 fe 00 00 }
    $sequence_9  = { 57 33 71 4b 8a a0 7b 74 ca fc 16 aa 5a }
    $sequence_10 = { 75 27 e8 ?? ?? ?? ?? 83 c0 20 3b f0 0f 84 34 51 01 00 e8 ?? ?? ?? ?? }
    $sequence_11 = { 00 0f 84 3d ?? ?? ?? ?? 32 88 01 00 8b ff 55 8b ec ff 75 14 6a 00 }
    $sequence_12 = { c0 0f 84 40 17 01 00 8b 4d 08 83 60 04 00 }
    $sequence_13 = { 77 06 62 05 ?? ?? ?? ?? 29 4a 75 f2 14 9c 76 74 }
    $sequence_14 = { e8 ?? ?? ?? ?? 85 f6 0f 84 fd 61 01 00 8b 45 d4 }
    $sequence_15 = { 75 08 e8 ?? ?? ?? ?? 59 59 5d c3 53 }

  condition:
    7 of them and filesize < 188416
}