rule MALPEDIA_Win_Klrd_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "f2ac53cd-82a8-55ea-badd-f6f1aae58f93"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.klrd"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.klrd_auto.yar#L1-L127"
    license_url        = "N/A"
    logic_hash         = "0fc6f030ea4bb49d87359f96c6eceeeaeffbdd94bdee42030f76f2d7ec66a19a"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0 = { 8d 85 fc ef ff ff 50 e8 ?? ?? ?? ?? 59 50 }
    $sequence_1 = { 8d 85 fc ef ff ff 50 57 ff 15 ?? ?? ?? ?? 57 ff 15 ?? ?? ?? ?? }
    $sequence_2 = { e8 ?? ?? ?? ?? 59 50 8d 85 fc ef ff ff 50 57 }
    $sequence_3 = { 3c 00 0f 84 85 02 00 00 3c 03 0f 84 7d 02 00 00 3c 09 0f 84 75 02 00 00 3c 08 }
    $sequence_4 = { c6 85 c0 fd ff ff 00 68 ff 00 00 00 6a 00 8d 85 c1 fd ff ff 50 e8 ?? ?? ?? ?? 83 c4 0c }
    $sequence_5 = { 59 59 ff 75 10 ff 75 0c ff 75 08 ff 35 ?? ?? ?? ?? ff 15 ?? ?? ?? ?? }
    $sequence_6 = { eb cc 8a 85 e7 fe ff ff 88 85 ac fc ff ff 80 bd ac fc ff ff 08 74 2f }
    $sequence_7 = { 56 56 6a 04 56 56 68 00 00 00 c0 68 ?? ?? ?? ?? }
    $sequence_8 = { 59 8d 7d ec f3 a5 8b 45 ec 25 ff 00 00 00 88 85 e7 fe ff ff 3c 00 }
    $sequence_9 = { ff b5 b0 fc ff ff ff 15 ?? ?? ?? ?? 89 85 c8 fe ff ff 83 bd c8 fe ff ff 00 75 15 ff 15 ?? ?? ?? ?? }

  condition:
    7 of them and filesize < 40960
}