rule rule_poshc2_offensive_tool_keyword
{
    meta:
        description = "Detection patterns for the tool 'poshc2' taken from the ThreatHunting-Keywords github project"
        author = "@mthcht"
        reference = "https://github.com/mthcht/ThreatHunting-Keywords"
        tool = "poshc2"
        rule_category = "offensive_tool_keyword"

    strings:
                        $string1_poshc2_offensive_tool_keyword = " -c2server " nocase ascii wide
                        $string2_poshc2_offensive_tool_keyword = " -daisyserver " nocase ascii wide
                        $string3_poshc2_offensive_tool_keyword = " -LocalPoshC2ProjectDir " nocase ascii wide
                        $string4_poshc2_offensive_tool_keyword = " -LocalPoshC2ProjectDir " nocase ascii wide
                        $string5_poshc2_offensive_tool_keyword = /\s\-Payload\s.{0,100}\s\-method\ssysprep/ nocase ascii wide
                        $string6_poshc2_offensive_tool_keyword = " PayloadsDirectory" nocase ascii wide
                        $string7_poshc2_offensive_tool_keyword = " PoshC2 " nocase ascii wide
                        $string8_poshc2_offensive_tool_keyword = " -PoshC2Dir " nocase ascii wide
                        $string9_poshc2_offensive_tool_keyword = " -PoshC2Dir " nocase ascii wide
                        $string10_poshc2_offensive_tool_keyword = " SharpSocks " nocase ascii wide
                        $string11_poshc2_offensive_tool_keyword = "/bin/posh"
                        $string12_poshc2_offensive_tool_keyword = /\/C2Server\.py/ nocase ascii wide
                        $string13_poshc2_offensive_tool_keyword = /\/Macro\-Payloads\.py/ nocase ascii wide
                        $string14_poshc2_offensive_tool_keyword = "/nettitude/" nocase ascii wide
                        $string15_poshc2_offensive_tool_keyword = "/opt/PoshC2" nocase ascii wide
                        $string16_poshc2_offensive_tool_keyword = /\/posh\.key/ nocase ascii wide
                        $string17_poshc2_offensive_tool_keyword = "/PoshC2" nocase ascii wide
                        $string18_poshc2_offensive_tool_keyword = "/poshc2-" nocase ascii wide
                        $string19_poshc2_offensive_tool_keyword = "/PoshC2/" nocase ascii wide
                        $string20_poshc2_offensive_tool_keyword = "/posh-config" nocase ascii wide
                        $string21_poshc2_offensive_tool_keyword = "/posh-log" nocase ascii wide
                        $string22_poshc2_offensive_tool_keyword = "/posh-project" nocase ascii wide
                        $string23_poshc2_offensive_tool_keyword = "/posh-server" nocase ascii wide
                        $string24_poshc2_offensive_tool_keyword = "/posh-service" nocase ascii wide
                        $string25_poshc2_offensive_tool_keyword = "/posh-stop-service" nocase ascii wide
                        $string26_poshc2_offensive_tool_keyword = "/posh-update" nocase ascii wide
                        $string27_poshc2_offensive_tool_keyword = /\/SharpHandler\.py/ nocase ascii wide
                        $string28_poshc2_offensive_tool_keyword = /\\jaccdpqnvbrrxlaf/ nocase ascii wide
                        $string29_poshc2_offensive_tool_keyword = /\\PoshC2/ nocase ascii wide
                        $string30_poshc2_offensive_tool_keyword = "_posh-common" nocase ascii wide
                        $string31_poshc2_offensive_tool_keyword = /_Shellcode\.bin/ nocase ascii wide
                        $string32_poshc2_offensive_tool_keyword = "brute-locadmin " nocase ascii wide
                        $string33_poshc2_offensive_tool_keyword = "bypass-amsi" nocase ascii wide
                        $string34_poshc2_offensive_tool_keyword = /C2\.KillDate/ nocase ascii wide
                        $string35_poshc2_offensive_tool_keyword = /C2\.UserAgent/ nocase ascii wide
                        $string36_poshc2_offensive_tool_keyword = "clipboard-monitor " nocase ascii wide
                        $string37_poshc2_offensive_tool_keyword = "createdaisypayload" nocase ascii wide
                        $string38_poshc2_offensive_tool_keyword = "createlinuxpayload"
                        $string39_poshc2_offensive_tool_keyword = "createnewpayload" nocase ascii wide
                        $string40_poshc2_offensive_tool_keyword = "createnewshellcode" nocase ascii wide
                        $string41_poshc2_offensive_tool_keyword = "createpbindpayload" nocase ascii wide
                        $string42_poshc2_offensive_tool_keyword = "createproxypayload -" nocase ascii wide
                        $string43_poshc2_offensive_tool_keyword = "createproxypayload" nocase ascii wide
                        $string44_poshc2_offensive_tool_keyword = "cred-popper " nocase ascii wide
                        $string45_poshc2_offensive_tool_keyword = "dcomexec -" nocase ascii wide
                        $string46_poshc2_offensive_tool_keyword = /dllsearcher\s.{0,100}\.dll/ nocase ascii wide
                        $string47_poshc2_offensive_tool_keyword = "find-allvulns" nocase ascii wide
                        $string48_poshc2_offensive_tool_keyword = "find-interestingfile -" nocase ascii wide
                        $string49_poshc2_offensive_tool_keyword = "fpc -c Seatbelt" nocase ascii wide
                        $string50_poshc2_offensive_tool_keyword = "get_c2_messages" nocase ascii wide
                        $string51_poshc2_offensive_tool_keyword = "get_c2server_all" nocase ascii wide
                        $string52_poshc2_offensive_tool_keyword = "get_cmd_from_task_id" nocase ascii wide
                        $string53_poshc2_offensive_tool_keyword = "get_implants_all" nocase ascii wide
                        $string54_poshc2_offensive_tool_keyword = "get_newimplanturl" nocase ascii wide
                        $string55_poshc2_offensive_tool_keyword = "get_sharpurls" nocase ascii wide
                        $string56_poshc2_offensive_tool_keyword = "get-creditcarddata " nocase ascii wide
                        $string57_poshc2_offensive_tool_keyword = "getdllbaseaddress" nocase ascii wide
                        $string58_poshc2_offensive_tool_keyword = "get-dodgyprocesses" nocase ascii wide
                        $string59_poshc2_offensive_tool_keyword = "getgppgroups  " nocase ascii wide
                        $string60_poshc2_offensive_tool_keyword = "getgpppassword " nocase ascii wide
                        $string61_poshc2_offensive_tool_keyword = "get-implantworkingdirectory" nocase ascii wide
                        $string62_poshc2_offensive_tool_keyword = "Get-KeystrokeData" nocase ascii wide
                        $string63_poshc2_offensive_tool_keyword = "get-keystrokes" nocase ascii wide
                        $string64_poshc2_offensive_tool_keyword = "get-killdate" nocase ascii wide
                        $string65_poshc2_offensive_tool_keyword = "get-netfileserver -domain " nocase ascii wide
                        $string66_poshc2_offensive_tool_keyword = "get-passnotexp" nocase ascii wide
                        $string67_poshc2_offensive_tool_keyword = /get\-process\s.{0,100}amsi\.dll/ nocase ascii wide
                        $string68_poshc2_offensive_tool_keyword = "getremoteprocesslisting" nocase ascii wide
                        $string69_poshc2_offensive_tool_keyword = "get-screenshot" nocase ascii wide
                        $string70_poshc2_offensive_tool_keyword = "get-screenshotallwindows" nocase ascii wide
                        $string71_poshc2_offensive_tool_keyword = "get-wmiregcachedrdpconnection" nocase ascii wide
                        $string72_poshc2_offensive_tool_keyword = "get-wmireglastloggedon" nocase ascii wide
                        $string73_poshc2_offensive_tool_keyword = "get-wmiregmounteddrive" nocase ascii wide
                        $string74_poshc2_offensive_tool_keyword = "hide-implant" nocase ascii wide
                        $string75_poshc2_offensive_tool_keyword = "inject-shellcode " nocase ascii wide
                        $string76_poshc2_offensive_tool_keyword = "installexe-persistence" nocase ascii wide
                        $string77_poshc2_offensive_tool_keyword = "install-persistence" nocase ascii wide
                        $string78_poshc2_offensive_tool_keyword = "install-persistence-cron" nocase ascii wide
                        $string79_poshc2_offensive_tool_keyword = "invoke-aclscanner" nocase ascii wide
                        $string80_poshc2_offensive_tool_keyword = "invoke-arpscan" nocase ascii wide
                        $string81_poshc2_offensive_tool_keyword = "invoke-bloodhound" nocase ascii wide
                        $string82_poshc2_offensive_tool_keyword = "invoke-daisychain" nocase ascii wide
                        $string83_poshc2_offensive_tool_keyword = "invoke-dcompayload" nocase ascii wide
                        $string84_poshc2_offensive_tool_keyword = "invoke-edrchecker" nocase ascii wide
                        $string85_poshc2_offensive_tool_keyword = "invoke-eternalblue" nocase ascii wide
                        $string86_poshc2_offensive_tool_keyword = "invoke-hostenum -" nocase ascii wide
                        $string87_poshc2_offensive_tool_keyword = "invoke-hostscan" nocase ascii wide
                        $string88_poshc2_offensive_tool_keyword = "invoke-kerberoast " nocase ascii wide
                        $string89_poshc2_offensive_tool_keyword = "Invoke-Pbind " nocase ascii wide
                        $string90_poshc2_offensive_tool_keyword = /Invoke\-Pbind\.ps1/ nocase ascii wide
                        $string91_poshc2_offensive_tool_keyword = "invoke-pipekat " nocase ascii wide
                        $string92_poshc2_offensive_tool_keyword = "invoke-psexecpayload" nocase ascii wide
                        $string93_poshc2_offensive_tool_keyword = "Invoke-PsUACme" nocase ascii wide
                        $string94_poshc2_offensive_tool_keyword = "invoke-runaspayload" nocase ascii wide
                        $string95_poshc2_offensive_tool_keyword = "invoke-sharefinder " nocase ascii wide
                        $string96_poshc2_offensive_tool_keyword = "invoke-smbclient " nocase ascii wide
                        $string97_poshc2_offensive_tool_keyword = "invoke-smbexec " nocase ascii wide
                        $string98_poshc2_offensive_tool_keyword = "invoke-smblogin " nocase ascii wide
                        $string99_poshc2_offensive_tool_keyword = "invoke-sniffer " nocase ascii wide
                        $string100_poshc2_offensive_tool_keyword = "invoke-urlcheck -urls" nocase ascii wide
                        $string101_poshc2_offensive_tool_keyword = "invoke-winrmsession" nocase ascii wide
                        $string102_poshc2_offensive_tool_keyword = "invoke-wmiexec " nocase ascii wide
                        $string103_poshc2_offensive_tool_keyword = "invoke-wmijspayload" nocase ascii wide
                        $string104_poshc2_offensive_tool_keyword = "invoke-wmipayload" nocase ascii wide
                        $string105_poshc2_offensive_tool_keyword = "kill-implant" nocase ascii wide
                        $string106_poshc2_offensive_tool_keyword = "label-implant " nocase ascii wide
                        $string107_poshc2_offensive_tool_keyword = "ldap-searcher " nocase ascii wide
                        $string108_poshc2_offensive_tool_keyword = "linuxprivchecker"
                        $string109_poshc2_offensive_tool_keyword = /loadmodule\s.{0,100}\.ps1/ nocase ascii wide
                        $string110_poshc2_offensive_tool_keyword = /loadmodume\s.{0,100}\/modules\/.{0,100}\.ps1/ nocase ascii wide
                        $string111_poshc2_offensive_tool_keyword = /lockless\s.{0,100}\.dat/ nocase ascii wide
                        $string112_poshc2_offensive_tool_keyword = "PayloadCommsHost" nocase ascii wide
                        $string113_poshc2_offensive_tool_keyword = "Posh_v4_dropper_" nocase ascii wide
                        $string114_poshc2_offensive_tool_keyword = /Posh_v4_x64_.{0,100}\.bin/ nocase ascii wide
                        $string115_poshc2_offensive_tool_keyword = /Posh_v4_x86_.{0,100}\.bin/ nocase ascii wide
                        $string116_poshc2_offensive_tool_keyword = /PoshC2\-.{0,100}\.zip/ nocase ascii wide
                        $string117_poshc2_offensive_tool_keyword = /poshc2\.server/ nocase ascii wide
                        $string118_poshc2_offensive_tool_keyword = /poshc2\.service/ nocase ascii wide
                        $string119_poshc2_offensive_tool_keyword = /poshc2\-ansible\-main\.yml/ nocase ascii wide
                        $string120_poshc2_offensive_tool_keyword = "posh-cookie-decryptor" nocase ascii wide
                        $string121_poshc2_offensive_tool_keyword = "posh-delete " nocase ascii wide
                        $string122_poshc2_offensive_tool_keyword = "posh-project " nocase ascii wide
                        $string123_poshc2_offensive_tool_keyword = "posh-project -" nocase ascii wide
                        $string124_poshc2_offensive_tool_keyword = "posh-server -" nocase ascii wide
                        $string125_poshc2_offensive_tool_keyword = "posh-server -" nocase ascii wide
                        $string126_poshc2_offensive_tool_keyword = "posh-update " nocase ascii wide
                        $string127_poshc2_offensive_tool_keyword = "process_mimikatz" nocase ascii wide
                        $string128_poshc2_offensive_tool_keyword = /pslo\s.{0,100}\.ps1/ nocase ascii wide
                        $string129_poshc2_offensive_tool_keyword = "removeexe-persistence" nocase ascii wide
                        $string130_poshc2_offensive_tool_keyword = "remove-persistence" nocase ascii wide
                        $string131_poshc2_offensive_tool_keyword = "remove-persistence-cron" nocase ascii wide
                        $string132_poshc2_offensive_tool_keyword = "runas-netonly " nocase ascii wide
                        $string133_poshc2_offensive_tool_keyword = "run-dll SharpSploit" nocase ascii wide
                        $string134_poshc2_offensive_tool_keyword = "safetydump" nocase ascii wide
                        $string135_poshc2_offensive_tool_keyword = "seatbelt -" nocase ascii wide
                        $string136_poshc2_offensive_tool_keyword = "seatbelt all" nocase ascii wide
                        $string137_poshc2_offensive_tool_keyword = "set-killdate " nocase ascii wide
                        $string138_poshc2_offensive_tool_keyword = "set-pushover-applicationtoken" nocase ascii wide
                        $string139_poshc2_offensive_tool_keyword = "set-pushover-userkeys" nocase ascii wide
                        $string140_poshc2_offensive_tool_keyword = "shadowcopy enum" nocase ascii wide
                        $string141_poshc2_offensive_tool_keyword = /Sharp_v4_x64.{0,100}\.bin/ nocase ascii wide
                        $string142_poshc2_offensive_tool_keyword = /Sharp_v4_x86.{0,100}\.bin/ nocase ascii wide
                        $string143_poshc2_offensive_tool_keyword = "sharpapplocker" nocase ascii wide
                        $string144_poshc2_offensive_tool_keyword = "sharpchromium " nocase ascii wide
                        $string145_poshc2_offensive_tool_keyword = "sharpcookiemonster" nocase ascii wide
                        $string146_poshc2_offensive_tool_keyword = "sharpedrchecker" nocase ascii wide
                        $string147_poshc2_offensive_tool_keyword = "sharphound -" nocase ascii wide
                        $string148_poshc2_offensive_tool_keyword = /sharpps\s\$psversiontable/ nocase ascii wide
                        $string149_poshc2_offensive_tool_keyword = "sharpps get-process" nocase ascii wide
                        $string150_poshc2_offensive_tool_keyword = /sharpsc\s.{0,100}cmd/ nocase ascii wide
                        $string151_poshc2_offensive_tool_keyword = "sharptelnet " nocase ascii wide
                        $string152_poshc2_offensive_tool_keyword = "sharpweb all" nocase ascii wide
                        $string153_poshc2_offensive_tool_keyword = "sharpwmi action=" nocase ascii wide
                        $string154_poshc2_offensive_tool_keyword = "standin --asrep" nocase ascii wide
                        $string155_poshc2_offensive_tool_keyword = "standin --dc" nocase ascii wide
                        $string156_poshc2_offensive_tool_keyword = "standin --delegation" nocase ascii wide
                        $string157_poshc2_offensive_tool_keyword = /standin\s\-\-group\s.{0,100}Domain\sAdmins/ nocase ascii wide
                        $string158_poshc2_offensive_tool_keyword = "standin --object " nocase ascii wide
                        $string159_poshc2_offensive_tool_keyword = "standin --spn" nocase ascii wide
                        $string160_poshc2_offensive_tool_keyword = "startanotherimplant" nocase ascii wide
                        $string161_poshc2_offensive_tool_keyword = "startdaisy" nocase ascii wide
                        $string162_poshc2_offensive_tool_keyword = "start-keystrokes" nocase ascii wide
                        $string163_poshc2_offensive_tool_keyword = "start-keystrokes-writefile" nocase ascii wide
                        $string164_poshc2_offensive_tool_keyword = /start\-process\sntdsutil\.exe\s.{0,100}create\sfull/ nocase ascii wide
                        $string165_poshc2_offensive_tool_keyword = "stopdaisy" nocase ascii wide
                        $string166_poshc2_offensive_tool_keyword = "stop-keystrokes" nocase ascii wide
                        $string167_poshc2_offensive_tool_keyword = "sweetpotato -p" nocase ascii wide
                        $string168_poshc2_offensive_tool_keyword = /temp\\pbind\.exe/ nocase ascii wide
                        $string169_poshc2_offensive_tool_keyword = "timestomp c:" nocase ascii wide
                        $string170_poshc2_offensive_tool_keyword = "unhide-implant" nocase ascii wide
                        $string171_poshc2_offensive_tool_keyword = /XOR\-Payloads\.py/ nocase ascii wide
        $metadata_regex_import = /\bimport\s+[a-zA-Z0-9_.]+\b/ nocase
        $metadata_regex_function = /function\s+[a-zA-Z_][a-zA-Z0-9_]*\(/ nocase ascii
        $metadata_regex_php = /<\?php/ nocase ascii
        $metadata_regex_createobject = /(CreateObject|WScript\.)/ nocase ascii
        $metadata_regex_script = /<script\b/ nocase ascii
        $metadata_regex_javascript = /(let\s|const\s|function\s|document\.|console\.)/ nocase ascii
        $metadata_regex_powershell = /(Write-Host|Get-[a-zA-Z]+|Invoke-|param\(|\.SYNOPSIS)/ nocase ascii
        $metadata_regex_batch = /@(echo\s|call\s|set\s|goto\s|if\s|for\s|rem\s)/ nocase ascii
        $metadata_regex_shebang = /^#!\// nocase ascii

    condition:
        ((filesize < 20MB and (
            uint16(0) == 0x5a4d or             uint16(0) == 0x457f or             uint32be(0) == 0x7f454c46 or uint16(0) == 0xfeca or uint16(0) == 0xfacf or uint32(0) == 0xbebafeca or             uint32(0) == 0x504B0304 or             uint32(0) == 0xCAFEBABE or             uint32(0) == 0x4D534346 or             uint32(0) == 0xD0CF11E0 or             uint16(0) == 0x2321 or             uint16(0) == 0x3c3f         )) and 2 of ($string*)) or
        (filesize < 2MB and
        (
            2 of ($string*) and
            for any of ($metadata_regex_*) : ( @ <= 20000 )
        ))
}