rule win_makloader_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.makloader."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.makloader"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 6bca00 8b440dbc 8b540dc0 b127 }
                                                            
        $sequence_1 = { c7857cebffff00000000 c78580ebffff00000000 8d8554e5ffff 898584ebffff c78588ebffff00000000 8d8d74ebffff }
                                                                                    
        $sequence_2 = { 33d2 8b45fc 83c003 8810 8b45fc 8be5 }
                                                                                    
        $sequence_3 = { a1???????? 33c5 8945fc c745c000100000 }
                                                            
        $sequence_4 = { 8b94d530fdffff b103 e8???????? 0bd8 8b8520fdffff 0bc2 33f3 }
                                                                                                
        $sequence_5 = { e8???????? 8818 ebbf 6a09 8b4df8 83c101 e8???????? }
                                                                                                
        $sequence_6 = { 8b540dc0 b122 e8???????? 8bd8 }
                                                            
        $sequence_7 = { 89856ce6ffff 33d2 899514e5ffff 899518e5ffff }
                                                            
        $sequence_8 = { 8b08 8b55cc 52 8b410c }
                                                            
        $sequence_9 = { 884130 ba01000000 6bc230 8b4d08 0fb61401 52 8b4dfc }
                                                                                                
    condition:
        7 of them and filesize < 335872
}