rule win_keyboy_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.keyboy."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.keyboy"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 51 ff75d8 6a00 ff75c0 }
                                                            
        $sequence_1 = { 6a00 8945f2 8d45f8 50 6a0e }
                                                                        
        $sequence_2 = { 5d c3 3b0d???????? f27502 f2c3 f2e953030000 }
                                                                                    
        $sequence_3 = { c705????????dbd99823 c705????????d468bcb5 c705????????2086e659 c705????????eec45abf c705????????bbee2bd1 c705????????3e20f129 }
                                                                                    
        $sequence_4 = { c705????????0caa6c89 c705????????a856701f c705????????597e743c c705????????0a9769e0 c705????????c4b85363 }
                                                                        
        $sequence_5 = { c705????????0a9769e0 c705????????c4b85363 c705????????3abf261f c705????????890e9944 c705????????dbd99823 c705????????d468bcb5 c705????????2086e659 }
                                                                                                
        $sequence_6 = { 57 68cc020000 8d852cfdffff 8bf2 6a00 50 89b528fdffff }
                                                                                                
        $sequence_7 = { 24a0 3ca0 7518 b800080000 }
                                                            
        $sequence_8 = { 2408 f6d8 1ac0 24dd 88474e }
                                                                        
        $sequence_9 = { 7207 b901000000 eb0f 3cfe 7509 }
                                                                        
        $sequence_10 = { 6683f809 740a 6683f806 7404 32c9 eb02 }
                                                                                    
        $sequence_11 = { 7905 49 83c9f8 41 8a043e 0fbe4c8de0 3401 }
                                                                                                
        $sequence_12 = { 0fbe4c8de0 3401 0fbec0 0fafc8 80f185 880c3e }
                                                                                    
        $sequence_13 = { e8???????? 85c0 755e 83ff20 }
                                                            
        $sequence_14 = { f7d9 85db 0f44c2 23c8 }
                                                            
        $sequence_15 = { c705????????1671e665 c705????????f3106cb3 c705????????526c1ed0 c705????????5d05606c }
                                                            
        $sequence_16 = { ffd0 e9???????? bbfeffffff eb05 }
                                                            
        $sequence_17 = { 84c0 75f0 8d55ec c745ec5c417070 c745f06c655c55 }
                                                                        
        $sequence_18 = { e8???????? 8b75c0 8bce 8b15???????? a3???????? e8???????? 8b15???????? }
                                                                                                
        $sequence_19 = { 8d46d6 99 83e23f 03c2 }
                                                            
        $sequence_20 = { ff15???????? 8bf8 c745f447646933 8d45f4 66c745f83200 50 }
                                                                                    
        $sequence_21 = { c745f06c655c55 8bf2 c745f470646174 66c745f86500 8a02 }
                                                                        
    condition:
        7 of them and filesize < 2170880
}