rule win_zeus_openssl_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.zeus_openssl."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.zeus_openssl"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 8bf8 05fffeffff 4e 03c6 }
                                                            
        $sequence_1 = { 0181a8160000 837de000 7419 8b75e0 8b45f0 0fb7443002 8b75f8 }
                                                                                                
        $sequence_2 = { 2bc3 8bda 8b55c4 83c005 894304 8b45f0 2bd6 }
                                                                                                
        $sequence_3 = { 6a1c 8945f0 8845ff 8bfa 32c0 59 }
                                                                                    
        $sequence_4 = { 8bec 83ec10 53 56 57 8b3d???????? 33db }
                                                                                                
        $sequence_5 = { 83ec0c 56 57 8bf2 8bf9 e8???????? }
                                                                                    
        $sequence_6 = { 83c408 8b87bc160000 894df8 83f810 7530 8b4f14 }
                                                                                    
        $sequence_7 = { 743b 83ef50 7412 83ef75 742a }
                                                                        
        $sequence_8 = { 89475c e8???????? 8b0f 33c0 394110 5f }
                                                                                    
        $sequence_9 = { 8b45fc 48 50 8d9694000000 8bce }
                                                                        
    condition:
        7 of them and filesize < 4546560
}