rule MALPEDIA_Win_Afrodita_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "a57e10f8-454f-5804-9e05-9ca06675125c"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.afrodita"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.afrodita_auto.yar#L1-L127"
    license_url        = "N/A"
    logic_hash         = "5b27d8ca339092e6723ab16dacd8e13cc60f1f330873451b2d099d87287bfb55"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0 = { 83 e6 15 83 ce 02 89 71 0c 23 c6 74 a5 a8 04 74 0a }
    $sequence_1 = { e8 ?? ?? ?? ?? 56 8d 85 58 ff ff ff c7 45 fc 05 00 00 00 57 83 cb 08 50 }
    $sequence_2 = { e8 ?? ?? ?? ?? eb 02 33 ff 8b b5 7c ff ff ff c7 45 fc ff ff ff ff 8b 4e 2c 85 c9 }
    $sequence_3 = { 8d 4f 10 e8 ?? ?? ?? ?? 8b 0f 8b 49 04 03 cf 85 c0 74 54 }
    $sequence_4 = { 0f 10 40 c0 0f 11 49 a0 0f 10 4c 30 c0 8b 75 e8 66 0f ef c8 0f 10 40 d0 0f 11 4c 30 c0 }
    $sequence_5 = { 89 73 04 c6 43 08 01 53 8d 4d e4 }
    $sequence_6 = { 8b 4b 08 8b 7b 0c 89 7d f8 89 4d fc 3b ce }
    $sequence_7 = { e8 ?? ?? ?? ?? 83 c4 0c c7 44 be 04 00 00 00 00 c7 04 be 00 00 00 00 5e 5b }
    $sequence_8 = { 50 8b cb ff 57 20 03 75 d4 8b ce e8 ?? ?? ?? ?? }
    $sequence_9 = { 89 4f 04 8b c7 e9 ?? ?? ?? ?? 83 f8 54 0f 8f dc 01 00 00 83 f8 53 0f 8d ea 02 00 00 }

  condition:
    7 of them and filesize < 2334720
}