rule MALPEDIA_Win_Cerber_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "1b1175b4-aaae-5323-bbb6-472b8daa3220"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.cerber"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.cerber_auto.yar#L1-L101"
    license_url        = "N/A"
    logic_hash         = "90183139badfe5f943ec4dd7b3bc0305f6ea2215a75a5dc8603646346366cf36"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0 = { 4a 79 f6 5f 8b c6 }
    $sequence_1 = { 85 c0 75 0c 8b 33 e8 ?? ?? ?? ?? 83 23 00 eb 0e 8b 4d fc }
    $sequence_2 = { 33 f9 8b 88 e0 00 00 00 89 4d d0 8b 88 e4 00 00 00 89 98 64 01 00 00 8b 5d d8 }
    $sequence_3 = { 4a 79 e6 47 3b 7d 0c }
    $sequence_4 = { 51 53 56 8b f0 57 85 f6 75 08 }
    $sequence_5 = { 4a b8 00 00 00 80 83 e9 04 eb 02 }
    $sequence_6 = { 89 5d f4 33 c9 83 fa 08 0f 9d c1 85 4d f4 75 15 }
    $sequence_7 = { 33 f9 8b 88 e8 fe ff ff 23 48 08 89 98 fc 00 00 00 8b 58 74 }

  condition:
    7 of them and filesize < 573440
}