rule MALPEDIA_Win_Ketrican_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "03c6cec7-6d12-51a2-b1a9-8239f834bf9b"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.ketrican"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.ketrican_auto.yar#L1-L227"
    license_url        = "N/A"
    logic_hash         = "c6a0e9c9ef6d7c9c9c9505df3e47863f2b32a94701647f7dc167a7885087d327"
    score              = 75
    quality            = 71
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0  = { 89 65 f0 33 db 89 5d fc 33 c0 }
    $sequence_1  = { 74 17 6a 0a 6a 1f 68 ?? ?? ?? ?? }
    $sequence_2  = { e8 ?? ?? ?? ?? 83 c0 10 89 06 c3 56 }
    $sequence_3  = { 8b d1 e8 ?? ?? ?? ?? 5f 5e c3 55 8b ec }
    $sequence_4  = { 8b 06 5d c2 04 00 55 8b ec 8b 45 08 89 45 08 }
    $sequence_5  = { 8b c1 89 45 f0 83 4d fc ff e8 ?? ?? ?? ?? }
    $sequence_6  = { 89 01 5b 5d c2 08 00 68 0e 00 07 80 e8 ?? ?? ?? ?? cc }
    $sequence_7  = { 68 0e 00 07 80 e8 ?? ?? ?? ?? cc 8b 06 83 e8 10 8b 08 }
    $sequence_8  = "HtEHt:H"
    $sequence_9  = { 88 46 03 83 c6 04 83 45 f8 04 8b 45 f8 5f }
    $sequence_10 = { 58 66 89 45 d8 6a 72 58 }
    $sequence_11 = { 6a 00 8d 85 f1 fb ff ff 50 e8 ?? ?? ?? ?? 83 c4 0c 68 00 04 00 00 }
    $sequence_12 = { ff 75 08 53 53 ff d6 5f 5e }
    $sequence_13 = { 74 0a 48 75 4a e8 ?? ?? ?? ?? }
    $sequence_14 = { 83 c0 02 66 3b d3 75 f5 2b c1 d1 f8 8d 70 01 68 00 08 02 00 }
    $sequence_15 = { e8 ?? ?? ?? ?? 8b 8a 8c 2f 00 00 33 c8 e8 ?? ?? ?? ?? b8 ?? ?? ?? ?? }
    $sequence_16 = { ff 15 ?? ?? ?? ?? 68 ?? ?? ?? ?? c7 05 ?? ?? ?? ?? 98 82 41 00 a3 ?? ?? ?? ?? }
    $sequence_17 = { 8d 42 0c 8b 4a e8 33 c8 e8 ?? ?? ?? ?? 8b 8a 4c 01 00 00 }
    $sequence_18 = { 33 c8 e8 ?? ?? ?? ?? 8b 8a e8 08 00 00 33 c8 e8 ?? ?? ?? ?? }
    $sequence_19 = { 8d 4d d0 e9 ?? ?? ?? ?? 8d 4d e0 e9 ?? ?? ?? ?? 8d 4d b8 e9 ?? ?? ?? ?? 8d 4d dc }
    $sequence_20 = { b8 ?? ?? ?? ?? e9 ?? ?? ?? ?? 8b 54 24 08 8d 42 0c 8b 8a a4 fe ff ff 33 c8 }
    $sequence_21 = { c7 05 ?? ?? ?? ?? 98 82 41 00 a3 ?? ?? ?? ?? c6 05 ?? ?? ?? ?? 00 e8 ?? ?? ?? ?? 59 }
    $sequence_22 = { 8b 8a 54 ff ff ff 33 c8 e8 ?? ?? ?? ?? 8b 8a dc 09 00 00 33 c8 e8 ?? ?? ?? ?? }

  condition:
    7 of them and filesize < 1449984
}