rule win_teleport_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.teleport."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.teleport"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 68???????? 894768 893d???????? ff15???????? }
                                                            
        $sequence_1 = { 894824 c6401c01 894dfc 8d85d0feffff b912000000 eb50 }
                                                                                    
        $sequence_2 = { 8b04bde83e4300 ff743018 ff15???????? 85c0 0f95c0 5f 5e }
                                                                                                
        $sequence_3 = { 8b01 6a01 ff10 8b4608 8d7e08 8b08 8900 }
                                                                                                
        $sequence_4 = { 83c404 8b4dc0 0f1003 0f110401 83c010 8945c8 eb06 }
                                                                                                
        $sequence_5 = { 8b45ec c1e810 0fb6c0 330c85a0fe4200 0fb6c2 330c85a0f64200 334fe8 }
                                                                                                
        $sequence_6 = { 3bf0 745a 0f1f440000 68???????? 8bcf e8???????? 837e1c08 }
                                                                                                
        $sequence_7 = { 8b4104 8987a4000000 8b5108 8945f8 8bc2 8997a8000000 8b590c }
                                                                                                
        $sequence_8 = { 894820 894824 c6401c01 8d45c0 c745fc08000000 be00100000 }
                                                                                    
        $sequence_9 = { 0fb6c3 8b5de8 331485a0f64200 3357ac 8bc2 c1e808 0fb6c8 }
                                                                                                
    condition:
        7 of them and filesize < 458752
}