rule MALPEDIA_Win_Dmsniff_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "16f341e6-77a3-5816-ba96-baf125c04244"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.dmsniff"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.dmsniff_auto.yar#L1-L124"
    license_url        = "N/A"
    logic_hash         = "97dafc3ba62eb5e1ea05a655f64eed9d043aae4b3733a53f196189f18ab4ea03"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0 = { 83 c6 61 89 f3 88 1d ?? ?? ?? ?? 8d 04 bf }
    $sequence_1 = { 50 d9 3c 24 66 81 0c 24 00 03 d9 2c 24 83 c4 04 6a 00 6a 00 }
    $sequence_2 = { 53 56 57 8b 5d 0c 8b 75 10 }
    $sequence_3 = { 89 fe 46 89 b5 fc fe ff ff 89 9c bd 00 ff ff ff 8d 85 f0 fe ff ff 50 6a 00 }
    $sequence_4 = { eb 15 47 39 f7 72 d3 ff 45 fc 8b 45 f4 39 45 fc }
    $sequence_5 = { 56 57 89 65 e8 50 d9 3c 24 }
    $sequence_6 = { eb 18 68 ?? ?? ?? ?? e8 ?? ?? ?? ?? 50 68 ?? ?? ?? ?? e8 ?? ?? ?? ?? 83 c4 0c }
    $sequence_7 = { e8 ?? ?? ?? ?? 50 68 ?? ?? ?? ?? e8 ?? ?? ?? ?? 83 c4 0c eb 18 }
    $sequence_8 = { e8 ?? ?? ?? ?? 83 c4 0c eb 18 68 ?? ?? ?? ?? e8 ?? ?? ?? ?? 50 }
    $sequence_9 = { 73 16 8b bd fc fe ff ff 89 fe 46 89 b5 fc fe ff ff 89 9c bd 00 ff ff ff }

  condition:
    7 of them and filesize < 131072
}