rule MALPEDIA_Win_Httpbrowser_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "86ed1f1e-9c83-5189-8446-3be88e9701cf"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.httpbrowser"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.httpbrowser_auto.yar#L1-L178"
    license_url        = "N/A"
    logic_hash         = "5b5149262889d64634c3067408a546cd5b0c2e08f2004303b6cf9132eb7eeb82"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0  = { 50 ff 75 08 6a 00 53 ff d6 8b 45 fc 33 c9 }
    $sequence_1  = { 50 89 5d e0 ff 56 04 89 45 f0 85 db 0f 84 89 01 00 00 }
    $sequence_2  = { 33 c5 89 45 fc 53 56 57 8d 85 9c fe ff ff 33 ff }
    $sequence_3  = { 8d 85 f0 fd ff ff 50 8d 85 d0 f5 ff ff 50 ff 15 ?? ?? ?? ?? }
    $sequence_4  = { 56 6a 03 68 00 00 00 40 8d 85 f4 fd ff ff 50 ff 15 ?? ?? ?? ?? }
    $sequence_5  = { e8 ?? ?? ?? ?? 83 c4 0c 33 c0 56 66 89 85 c8 f3 ff ff 8d 85 ca f3 ff ff }
    $sequence_6  = { 83 c4 38 ff 15 ?? ?? ?? ?? 8d 85 f4 fd ff ff 50 53 57 }
    $sequence_7  = { ff b5 f4 ed ff ff 8d 85 fc fd ff ff ff b5 f8 ed ff ff 68 ?? ?? ?? ?? 50 }
    $sequence_8  = { e8 ?? ?? ?? ?? 68 c2 0d df 13 56 a3 ?? ?? ?? ?? e8 ?? ?? ?? ?? 83 c4 38 }
    $sequence_9  = { 6a 00 68 10 04 00 00 ff 15 ?? ?? ?? ?? 8b f0 57 6a 0e 56 }
    $sequence_10 = { 83 c4 14 c7 45 ec 00 00 00 00 68 ?? ?? ?? ?? 50 9c b8 0a 00 00 00 51 }
    $sequence_11 = { b9 05 00 00 00 8d b5 24 ff ff ff 8d bd a4 fe ff ff 89 45 e4 }
    $sequence_12 = { 33 c0 8d bd 26 ff ff ff 66 89 95 24 ff ff ff f3 ab 89 55 e8 89 55 f8 89 55 fc }
    $sequence_13 = { 40 00 68 ae 22 40 00 50 b8 22 01 00 00 }
    $sequence_14 = { 88 95 a0 c5 ff ff f3 ab aa b9 1f 00 00 00 33 c0 8d bd 4a ff ff ff 66 89 95 48 ff ff ff }
    $sequence_15 = { 8b 15 ?? ?? ?? ?? 89 45 d8 a1 ?? ?? ?? ?? 89 4d dc 66 8b 0d ?? ?? ?? ?? }

  condition:
    7 of them and filesize < 188416
}