rule win_rms_auto {
  meta:
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    date               = "2020-10-14"
    version            = "1"
    description        = "autogenerated rule brought to you by yara-signator"
    tool               = "yara-signator v0.5.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.rms"
    malpedia_rule_date = "20201014"
    malpedia_hash      = "a7e3bd57eaf12bf3ea29a863c041091ba3af9ac9"
    malpedia_version   = "20201014"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"
  

  strings:
    $sequence_0 = { eb 13 8b 45 f8 8b 50 7c 8b 45 0c 8b 00 8b 40 48 e8 ?? ?? ?? ?? }
                                    $sequence_1 = { f7 da 8d 45 cc e8 ?? ?? ?? ?? 8b 45 f8 e8 ?? ?? ?? ?? 50 e8 ?? ?? ?? ?? }
                                    $sequence_2 = { eb 03 c6 03 00 5f 5e 5b 8b e5 5d }
                                    $sequence_3 = { e8 ?? ?? ?? ?? e9 ?? ?? ?? ?? 8b 45 08 e8 ?? ?? ?? ?? 50 56 8b 45 fc }
                                    $sequence_4 = { e8 ?? ?? ?? ?? ff b5 58 ff ff ff 8d 85 60 ff ff ff ba 03 00 00 00 e8 ?? ?? ?? ?? 8b 85 60 ff ff ff e8 ?? ?? ?? ?? }
                                    $sequence_5 = { a1 ?? ?? ?? ?? e8 ?? ?? ?? ?? 43 4e 0f 85 34 fd ff ff 33 c0 5a }
                                    $sequence_6 = { eb 74 6a 00 6a 00 6a 00 8b 45 ec 50 6a 01 }
                                    $sequence_7 = { f6 c3 10 74 0b 8b c6 e8 ?? ?? ?? ?? 84 c0 75 04 33 c0 }
                                    $sequence_8 = { e8 ?? ?? ?? ?? ff b5 5c ff ff ff 68 ?? ?? ?? ?? 8d 85 58 ff ff ff e8 ?? ?? ?? ?? ff b5 58 ff ff ff 8d 85 60 ff ff ff }
                                    $sequence_9 = { e8 ?? ?? ?? ?? 8b 45 fc e8 ?? ?? ?? ?? ff 75 0c ff 75 08 8d 55 d0 8b 45 fc }
                
  condition:
    7 of them and filesize < 35323904
}