rule win_concealment_troy_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.concealment_troy."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.concealment_troy"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { c744244000000000 ff15???????? 85c0 0f844cffffff 8b542424 }
                                                                        
        $sequence_1 = { 7530 8b54240c 52 ff15???????? 53 }
                                                                        
        $sequence_2 = { 8bc8 83e103 f3a4 8d542418 8d8c2430090000 e8???????? 85c0 }
                                                                                                
        $sequence_3 = { 3acb 75f6 6804010000 8d8c2424010000 53 }
                                                                        
        $sequence_4 = { f3a5 66a5 83c40c a4 8d4c2418 8d642400 8a01 }
                                                                                                
        $sequence_5 = { 85c0 0f8476ffffff 6a00 6a08 6a00 }
                                                                        
        $sequence_6 = { e8???????? 83c414 ebd0 8bc8 c1f905 8d3c8da0774100 }
                                                                                    
        $sequence_7 = { 8d8c2470050000 68???????? 51 e8???????? 8d842478050000 83c418 8d5001 }
                                                                                                
        $sequence_8 = { b87c130000 e8???????? a1???????? 33c4 89842478130000 53 }
                                                                                    
        $sequence_9 = { 52 889c242c010000 e8???????? 6807020000 8d842441090000 53 }
                                                                                    
    condition:
        7 of them and filesize < 229376
}