rule rule_viperc2_offensive_tool_keyword
{
    meta:
        description = "Detection patterns for the tool 'viperc2' taken from the ThreatHunting-Keywords github project"
        author = "@mthcht"
        reference = "https://github.com/mthcht/ThreatHunting-Keywords"
        tool = "viperc2"
        rule_category = "offensive_tool_keyword"

    strings:
                        $string1_viperc2_offensive_tool_keyword = /\/\.msf4\// nocase ascii wide
                        $string2_viperc2_offensive_tool_keyword = /\/hackerid\.py/ nocase ascii wide
                        $string3_viperc2_offensive_tool_keyword = /\/loot_default\/.{0,1000}\.exe/ nocase ascii wide
                        $string4_viperc2_offensive_tool_keyword = /\/loot_default\/.{0,1000}\.ps1/ nocase ascii wide
                        $string5_viperc2_offensive_tool_keyword = /\/loot_default\/.{0,1000}\.py/ nocase ascii wide
                        $string6_viperc2_offensive_tool_keyword = /\/RGPerson\.py/ nocase ascii wide
                        $string7_viperc2_offensive_tool_keyword = "/root/viper/" nocase ascii wide
                        $string8_viperc2_offensive_tool_keyword = "/root/viper/dist"
                        $string9_viperc2_offensive_tool_keyword = "/SHELLCODELOADER" nocase ascii wide
                        $string10_viperc2_offensive_tool_keyword = /\/stinger_client\.py/ nocase ascii wide
                        $string11_viperc2_offensive_tool_keyword = /\/viper\.py/ nocase ascii wide
                        $string12_viperc2_offensive_tool_keyword = /\/viper\.sln/ nocase ascii wide
                        $string13_viperc2_offensive_tool_keyword = "/viper/Docker/" nocase ascii wide
                        $string14_viperc2_offensive_tool_keyword = "/viper/Docker/nginxconfig/htpasswd"
                        $string15_viperc2_offensive_tool_keyword = "/vipermsf" nocase ascii wide
                        $string16_viperc2_offensive_tool_keyword = "/viperpython"
                        $string17_viperc2_offensive_tool_keyword = /\/viperpython\.git/ nocase ascii wide
                        $string18_viperc2_offensive_tool_keyword = /_GetNetLoggedon\.py/ nocase ascii wide
                        $string19_viperc2_offensive_tool_keyword = "a7469955bff5e489d2270d9b389064e1" nocase ascii wide
                        $string20_viperc2_offensive_tool_keyword = /auto_pass_the_hash\./ nocase ascii wide
                        $string21_viperc2_offensive_tool_keyword = /Bot_MSF_Exp_.{0,1000}\.py/ nocase ascii wide
                        $string22_viperc2_offensive_tool_keyword = /Bot_Python_Poc_Log4j2_VMwareHorizon\.py/ nocase ascii wide
                        $string23_viperc2_offensive_tool_keyword = /BrowserBookmarkDiscovery_BrowserHistory\.py/ nocase ascii wide
                        $string24_viperc2_offensive_tool_keyword = /BrowserGhost\-N.{0,1000}\.exe/ nocase ascii wide
                        $string25_viperc2_offensive_tool_keyword = "cd40dbcdae84b1c8606f29342066547069ed5a33" nocase ascii wide
                        $string26_viperc2_offensive_tool_keyword = /Collection_ArchiveCollectedData_ArchiveViaCustomMethod\.py/ nocase ascii wide
                        $string27_viperc2_offensive_tool_keyword = /Collection_ArchiveCollectedData_ArchiveViaCustomMethod_7z\.py/ nocase ascii wide
                        $string28_viperc2_offensive_tool_keyword = /CommandAndControl_.{0,1000}\.py/ nocase ascii wide
                        $string29_viperc2_offensive_tool_keyword = /CredentialAccess_CredentialDumping_BrowserDataCSharp\.py/ nocase ascii wide
                        $string30_viperc2_offensive_tool_keyword = /CredentialAccess_CredentialDumping_KiwiOnLocal\.py/ nocase ascii wide
                        $string31_viperc2_offensive_tool_keyword = /CredentialAccess_CredentialDumping_SunLogin\.py/ nocase ascii wide
                        $string32_viperc2_offensive_tool_keyword = /CredentialAccess_CredentialDumping_WindowsHashDump\.py/ nocase ascii wide
                        $string33_viperc2_offensive_tool_keyword = /CredentialAccess_CredentialDumping_WindowsWDigestEnable\.py/ nocase ascii wide
                        $string34_viperc2_offensive_tool_keyword = /CredentialAccess_CredentialInFiles_BrowserData\.py/ nocase ascii wide
                        $string35_viperc2_offensive_tool_keyword = /CredentialAccess_CredentialInFiles_WindowsSoftware\.py/ nocase ascii wide
                        $string36_viperc2_offensive_tool_keyword = /CredentialAccess_InputCapture_CredUIPromptForWindowsCredentialsW\.py/ nocase ascii wide
                        $string37_viperc2_offensive_tool_keyword = /DefenseEvasion_CodeSigning_PeSigningAuthHijack\.py/ nocase ascii wide
                        $string38_viperc2_offensive_tool_keyword = /DefenseEvasion_CodeSigning_StolenMircosoftWindowsSignature\.py/ nocase ascii wide
                        $string39_viperc2_offensive_tool_keyword = /DefenseEvasion_ProcessInjection_CobaltStrikeOnline\.py/ nocase ascii wide
                        $string40_viperc2_offensive_tool_keyword = /DefenseEvasion_ProcessInjection_CsharpAssemblyLoader\.py/ nocase ascii wide
                        $string41_viperc2_offensive_tool_keyword = /DefenseEvasion_ProcessInjection_CsharpAssemblyLoaderPlus\.py/ nocase ascii wide
                        $string42_viperc2_offensive_tool_keyword = /DefenseEvasion_ProcessInjection_ExampleModule\.py/ nocase ascii wide
                        $string43_viperc2_offensive_tool_keyword = /DefenseEvasion_ProcessInjection_PeLoader\.py/ nocase ascii wide
                        $string44_viperc2_offensive_tool_keyword = /DefenseEvasion_ProcessInjection_PowershellRunInMem\.py/ nocase ascii wide
                        $string45_viperc2_offensive_tool_keyword = /DefenseEvasion_ProcessInjection_ProcessHandle\.py/ nocase ascii wide
                        $string46_viperc2_offensive_tool_keyword = /DefenseEvasion_ProcessInjection_PythonRunInMem\.py/ nocase ascii wide
                        $string47_viperc2_offensive_tool_keyword = /DefenseEvasion_ProcessInjection_SessionClone\.py/ nocase ascii wide
                        $string48_viperc2_offensive_tool_keyword = /DefenseEvasion_ProcessInjection_ShellcodeLoader\.py/ nocase ascii wide
                        $string49_viperc2_offensive_tool_keyword = /DefenseEvasion_ProcessInjection_WindowsSystem\.py/ nocase ascii wide
                        $string50_viperc2_offensive_tool_keyword = /DefenseEvasion_SubvertTrustControls_CloneSSLPem\.py/ nocase ascii wide
                        $string51_viperc2_offensive_tool_keyword = /Discovery_AccountDiscovery_GetNetDomainUser\.py/ nocase ascii wide
                        $string52_viperc2_offensive_tool_keyword = /Discovery_AccountDiscovery_PowerView\.py/ nocase ascii wide
                        $string53_viperc2_offensive_tool_keyword = /Discovery_ApplicationWindowDiscovery_EnumApplication\.py/ nocase ascii wide
                        $string54_viperc2_offensive_tool_keyword = /Discovery_Microphone_CallInfo\.py/ nocase ascii wide
                        $string55_viperc2_offensive_tool_keyword = /Discovery_Microphone_camera\.py/ nocase ascii wide
                        $string56_viperc2_offensive_tool_keyword = /Discovery_Microphone_record_mic\.py/ nocase ascii wide
                        $string57_viperc2_offensive_tool_keyword = /Discovery_NetworkServiceScanning_ARPScan\.py/ nocase ascii wide
                        $string58_viperc2_offensive_tool_keyword = /Discovery_NetworkServiceScanning_NbtScanByPython\.py/ nocase ascii wide
                        $string59_viperc2_offensive_tool_keyword = /Discovery_NetworkServiceScanning_NextnetByPE\.py/ nocase ascii wide
                        $string60_viperc2_offensive_tool_keyword = /Discovery_NetworkServiceScanning_PingByPython\.py/ nocase ascii wide
                        $string61_viperc2_offensive_tool_keyword = /Discovery_NetworkServiceScanning_PortScanByPython\.py/ nocase ascii wide
                        $string62_viperc2_offensive_tool_keyword = /Discovery_NetworkServiceScanning_PortScanWithServiceByPython\.py/ nocase ascii wide
                        $string63_viperc2_offensive_tool_keyword = /Discovery_NetworkShareDiscovery_PowerView\.py/ nocase ascii wide
                        $string64_viperc2_offensive_tool_keyword = /Discovery_PermissionGroupsDiscovery_PowerView\.py/ nocase ascii wide
                        $string65_viperc2_offensive_tool_keyword = /Discovery_QueryRegistry_GetDotNetVersions\.py/ nocase ascii wide
                        $string66_viperc2_offensive_tool_keyword = /Discovery_QueryRegistry_GetRDPPort\.py/ nocase ascii wide
                        $string67_viperc2_offensive_tool_keyword = /Discovery_RemoteSystemDiscovery_GetDomainIPAddress\.py/ nocase ascii wide
                        $string68_viperc2_offensive_tool_keyword = /Discovery_RemoteSystemDiscovery_GetNetComputer\.py/ nocase ascii wide
                        $string69_viperc2_offensive_tool_keyword = /Discovery_RemoteSystemDiscovery_GetNetDomain\.py/ nocase ascii wide
                        $string70_viperc2_offensive_tool_keyword = /Discovery_RemoteSystemDiscovery_GetNetDomainController\.py/ nocase ascii wide
                        $string71_viperc2_offensive_tool_keyword = /Discovery_SecuritySoftwareDiscovery_ListAVByTasklist\.py/ nocase ascii wide
                        $string72_viperc2_offensive_tool_keyword = /Discovery_SystemNetworkConnectionsDiscovery_GetPublicIP\.py/ nocase ascii wide
                        $string73_viperc2_offensive_tool_keyword = /Discovery_SystemUserDiscovery_GetLastLoggedOn\.py/ nocase ascii wide
                        $string74_viperc2_offensive_tool_keyword = /Discovery_SystemUserDiscovery_GetLoggedOnLocal\.py/ nocase ascii wide
                        $string75_viperc2_offensive_tool_keyword = /DomainTrustDiscovery_PowerView\.py/ nocase ascii wide
                        $string76_viperc2_offensive_tool_keyword = /dswmiexec\.exe/ nocase ascii wide
                        $string77_viperc2_offensive_tool_keyword = /EfsPotato\-.{0,1000}\.exe/ nocase ascii wide
                        $string78_viperc2_offensive_tool_keyword = /Eternalblue\-.{0,1000}\.exe/ nocase ascii wide
                        $string79_viperc2_offensive_tool_keyword = /Execution_CommandAndScriptingInterpreter_UploadAndExec\.py/ nocase ascii wide
                        $string80_viperc2_offensive_tool_keyword = /Execution_UserExecution_CallbackCreateThreadpoolWait\.py/ nocase ascii wide
                        $string81_viperc2_offensive_tool_keyword = /Execution_UserExecution_CallbackCreateTimerQueue\.py/ nocase ascii wide
                        $string82_viperc2_offensive_tool_keyword = /Execution_UserExecution_CallbackEnumChildWindows\.py/ nocase ascii wide
                        $string83_viperc2_offensive_tool_keyword = /Execution_UserExecution_CallbackEnumWindows\.py/ nocase ascii wide
                        $string84_viperc2_offensive_tool_keyword = /Execution_UserExecution_DirectConnectReverseHTTPS\.py/ nocase ascii wide
                        $string85_viperc2_offensive_tool_keyword = /Execution_UserExecution_DirectConnectReverseTCPRc4\.py/ nocase ascii wide
                        $string86_viperc2_offensive_tool_keyword = /Execution_UserExecution_FakePPID\.py/ nocase ascii wide
                        $string87_viperc2_offensive_tool_keyword = /Execution_UserExecution_LinuxBaseShellcodeLoader\.py/
                        $string88_viperc2_offensive_tool_keyword = /Execution_UserExecution_LinuxSelfGuardLoader\.py/
                        $string89_viperc2_offensive_tool_keyword = /Execution_UserExecution_NtCreateSection\.py/ nocase ascii wide
                        $string90_viperc2_offensive_tool_keyword = /Execution_UserExecution_Syscall_inject\.py/ nocase ascii wide
                        $string91_viperc2_offensive_tool_keyword = /Execution_UserExecution_VSSyscallProject\.py/ nocase ascii wide
                        $string92_viperc2_offensive_tool_keyword = /FakePPID\./ nocase ascii wide
                        $string93_viperc2_offensive_tool_keyword = /filemsf\.py/ nocase ascii wide
                        $string94_viperc2_offensive_tool_keyword = "GeneratesShellcodeFromPEorDll" nocase ascii wide
                        $string95_viperc2_offensive_tool_keyword = /GetWindowsCredentials\.exe/ nocase ascii wide
                        $string96_viperc2_offensive_tool_keyword = "http://vpsip:28888" nocase ascii wide
                        $string97_viperc2_offensive_tool_keyword = /HttpProxyScan_Log4J2\.py/ nocase ascii wide
                        $string98_viperc2_offensive_tool_keyword = /InitialAccess_SpearphishingAttachment_FakeWordDoc\.py/ nocase ascii wide
                        $string99_viperc2_offensive_tool_keyword = /InitialAccess_SpearphishingAttachment_Windows\.py/ nocase ascii wide
                        $string100_viperc2_offensive_tool_keyword = /Invoke\-S4U\-persistence\.ps1/ nocase ascii wide
                        $string101_viperc2_offensive_tool_keyword = /Invoke\-Service\-persistence\.ps1/ nocase ascii wide
                        $string102_viperc2_offensive_tool_keyword = /Ladon\-N20\.exe/ nocase ascii wide
                        $string103_viperc2_offensive_tool_keyword = /Ladon\-N40\.exe/ nocase ascii wide
                        $string104_viperc2_offensive_tool_keyword = /LateralMovement_.{0,1000}_Exploit.{0,1000}\.py/ nocase ascii wide
                        $string105_viperc2_offensive_tool_keyword = /LateralMovement_ExploitationOfRemoteServices_AuxiliaryMs17010\.py/ nocase ascii wide
                        $string106_viperc2_offensive_tool_keyword = /LateralMovement_ExploitationOfRemoteServices_MS17010\.py/ nocase ascii wide
                        $string107_viperc2_offensive_tool_keyword = /LateralMovement_Other_Ladon\.py/ nocase ascii wide
                        $string108_viperc2_offensive_tool_keyword = /LateralMovement_PassTheHash_ByInvokeWMIExec\.py/ nocase ascii wide
                        $string109_viperc2_offensive_tool_keyword = /LateralMovement_PassTheHash_ByWmi\.py/ nocase ascii wide
                        $string110_viperc2_offensive_tool_keyword = /LateralMovement_PassTheTicket_ByPsexec\.py/ nocase ascii wide
                        $string111_viperc2_offensive_tool_keyword = /LateralMovement_PassTheTicket_BySharpwmi\.py/ nocase ascii wide
                        $string112_viperc2_offensive_tool_keyword = /LateralMovement_PassTheTicket_ByWmi\.py/ nocase ascii wide
                        $string113_viperc2_offensive_tool_keyword = /laZagne\.exe/ nocase ascii wide
                        $string114_viperc2_offensive_tool_keyword = /MDSDLL_x64\.dll/ nocase ascii wide
                        $string115_viperc2_offensive_tool_keyword = /MDSDLL_x86\.dll/ nocase ascii wide
                        $string116_viperc2_offensive_tool_keyword = /mimikatz_x64\.exe/ nocase ascii wide
                        $string117_viperc2_offensive_tool_keyword = /mimikatz_x86\.exe/ nocase ascii wide
                        $string118_viperc2_offensive_tool_keyword = /MimikatzByPowerShellForDomain\.py/ nocase ascii wide
                        $string119_viperc2_offensive_tool_keyword = /MimikatzOnLocal\.py/ nocase ascii wide
                        $string120_viperc2_offensive_tool_keyword = "mitmdump -" nocase ascii wide
                        $string121_viperc2_offensive_tool_keyword = /msf\-json\-rpc\./ nocase ascii wide
                        $string122_viperc2_offensive_tool_keyword = "MsfModule" nocase ascii wide
                        $string123_viperc2_offensive_tool_keyword = /msfmodule\.py/ nocase ascii wide
                        $string124_viperc2_offensive_tool_keyword = "MsfModuleAsFunction" nocase ascii wide
                        $string125_viperc2_offensive_tool_keyword = /nextnet\.exe/ nocase ascii wide
                        $string126_viperc2_offensive_tool_keyword = /Persistence_AccountManipulation_Windows\.py/ nocase ascii wide
                        $string127_viperc2_offensive_tool_keyword = /Persistence_Guard_Windows\.py/ nocase ascii wide
                        $string128_viperc2_offensive_tool_keyword = /Persistence_LogonScripts_Windows\.py/ nocase ascii wide
                        $string129_viperc2_offensive_tool_keyword = /Persistence_NewService_Windows\.py/ nocase ascii wide
                        $string130_viperc2_offensive_tool_keyword = /Persistence_OfficeApplicationStartup_OfficeTest\.py/ nocase ascii wide
                        $string131_viperc2_offensive_tool_keyword = /Persistence_Other_WindowsLibraryMs\.py/ nocase ascii wide
                        $string132_viperc2_offensive_tool_keyword = /Persistence_RegistryRunKeys_SharpHide\.py/ nocase ascii wide
                        $string133_viperc2_offensive_tool_keyword = /Persistence_RegistryRunKeys_Windows\.py/ nocase ascii wide
                        $string134_viperc2_offensive_tool_keyword = /Persistence_ScheduledTask_Windows\.py/ nocase ascii wide
                        $string135_viperc2_offensive_tool_keyword = /Persistence_WinlogonHelperDLL_Windows\.py/ nocase ascii wide
                        $string136_viperc2_offensive_tool_keyword = /portScanWithService\.py/ nocase ascii wide
                        $string137_viperc2_offensive_tool_keyword = /portScanWithService\.py/ nocase ascii wide
                        $string138_viperc2_offensive_tool_keyword = /PostMulitDomainSpider\.py/ nocase ascii wide
                        $string139_viperc2_offensive_tool_keyword = /PostMulitMsfGetDomainInfoByBloodHound\.py/ nocase ascii wide
                        $string140_viperc2_offensive_tool_keyword = /PostPowershellPowerViewAddNetUser\.py/ nocase ascii wide
                        $string141_viperc2_offensive_tool_keyword = /PostPowershellPowerViewGetNetGroup\.py/ nocase ascii wide
                        $string142_viperc2_offensive_tool_keyword = /PostPowershellPowerViewGetNetGroupMember\.py/ nocase ascii wide
                        $string143_viperc2_offensive_tool_keyword = /PostPowershellPowerViewGetNetProcess\.py/ nocase ascii wide
                        $string144_viperc2_offensive_tool_keyword = /PostPowershellPowerViewUserHunter\.py/ nocase ascii wide
                        $string145_viperc2_offensive_tool_keyword = /PostRewMsfAuxiliaryCVE.{0,1000}\.py/ nocase ascii wide
                        $string146_viperc2_offensive_tool_keyword = /PostRewMsfExample\.py/ nocase ascii wide
                        $string147_viperc2_offensive_tool_keyword = /PostRewMsfPostConfInfos\.py/ nocase ascii wide
                        $string148_viperc2_offensive_tool_keyword = /PowerView_dev\.ps1/ nocase ascii wide
                        $string149_viperc2_offensive_tool_keyword = /PrivilegeEscalation_BypassUserAccountControl_Windows\.py/ nocase ascii wide
                        $string150_viperc2_offensive_tool_keyword = /PrivilegeEscalation_EnumPatchExample_Windows\.py/ nocase ascii wide
                        $string151_viperc2_offensive_tool_keyword = /PrivilegeEscalation_ExploitationForPrivilegeEscalation_CVE_2021_40449\.py/ nocase ascii wide
                        $string152_viperc2_offensive_tool_keyword = /PrivilegeEscalation_ExploitationForPrivilegeEscalation_EfsPotato\.py/ nocase ascii wide
                        $string153_viperc2_offensive_tool_keyword = /PrivilegeEscalation_ExploitationForPrivilegeEscalation_SweetPotato\.py/ nocase ascii wide
                        $string154_viperc2_offensive_tool_keyword = /PrivilegeEscalation_ExploitationForPrivilegeEscalation_Windows\.py/ nocase ascii wide
                        $string155_viperc2_offensive_tool_keyword = /PrivilegeEscalation_ProcessInjection_Getsystem\.py/ nocase ascii wide
                        $string156_viperc2_offensive_tool_keyword = /ResourceDevelopment_EstablishAccounts_RGPerson\.py/ nocase ascii wide
                        $string157_viperc2_offensive_tool_keyword = /ResourceDevelopment_Server_DNSLog\.py/ nocase ascii wide
                        $string158_viperc2_offensive_tool_keyword = /ResourceDevelopment_Server_LDAPServer\.py/ nocase ascii wide
                        $string159_viperc2_offensive_tool_keyword = /ResourceDevelopment_WebServices_TencentAPIGateway\.py/ nocase ascii wide
                        $string160_viperc2_offensive_tool_keyword = /SharpHide\-N.{0,1000}\.exe/ nocase ascii wide
                        $string161_viperc2_offensive_tool_keyword = /SharpHound\.exe/ nocase ascii wide
                        $string162_viperc2_offensive_tool_keyword = /SharpHound\.ps1/ nocase ascii wide
                        $string163_viperc2_offensive_tool_keyword = /SharpKatz\.exe/ nocase ascii wide
                        $string164_viperc2_offensive_tool_keyword = /SharpSploit\.dll/ nocase ascii wide
                        $string165_viperc2_offensive_tool_keyword = /sharpwmi\-N.{0,1000}\.exe/ nocase ascii wide
                        $string166_viperc2_offensive_tool_keyword = /sigthief\.py/ nocase ascii wide
                        $string167_viperc2_offensive_tool_keyword = /SSHBruteForce\.py/ nocase ascii wide
                        $string168_viperc2_offensive_tool_keyword = /SweetPotato\.exe/ nocase ascii wide
                        $string169_viperc2_offensive_tool_keyword = /SweetPotato\-N.{0,1000}\.exe/ nocase ascii wide
                        $string170_viperc2_offensive_tool_keyword = /VbulletinWidgetTemplateRce\.py/ nocase ascii wide
                        $string171_viperc2_offensive_tool_keyword = /viper\/.{0,1000}\.sock/ nocase ascii wide
                        $string172_viperc2_offensive_tool_keyword = /viper\-dev\.conf/ nocase ascii wide
                        $string173_viperc2_offensive_tool_keyword = "viperpython-dev" nocase ascii wide
                        $string174_viperc2_offensive_tool_keyword = "viperpython-main" nocase ascii wide
                        $string175_viperc2_offensive_tool_keyword = /viperzip\.exe/ nocase ascii wide

    condition:
        any of them
}