rule MALPEDIA_Win_Touchmove_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "a88e9c25-4116-5e49-8a2c-fef3336f0802"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.touchmove"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.touchmove_auto.yar#L1-L124"
    license_url        = "N/A"
    logic_hash         = "519a7e3bd048a6a0769391087a62b1ec389f7202cc576a740e9eb0fb3d43844d"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0 = { 41 b8 00 04 00 00 48 8d 8c 24 52 01 00 00 e8 ?? ?? ?? ?? 4c 8d 44 24 48 48 8d 15 2d f9 00 00 }
    $sequence_1 = { 48 8d 15 7a f7 00 00 48 8d 8d 90 00 00 00 e8 ?? ?? ?? ?? 4c 8d 85 90 00 00 00 33 d2 33 c9 }
    $sequence_2 = { 75 28 48 83 3d ?? ?? ?? ?? 00 74 1e 48 8d 0d 49 9f 00 00 e8 ?? ?? ?? ?? 85 c0 }
    $sequence_3 = { 41 b8 ee 00 00 00 48 8d 8d 92 43 00 00 e8 ?? ?? ?? ?? c6 85 80 44 00 00 00 33 d2 41 b8 ff 00 00 00 48 8d 8d 81 44 00 00 }
    $sequence_4 = { ff 15 ?? ?? ?? ?? 48 8d 44 24 50 48 89 44 24 20 45 8b ce 45 33 c0 48 8d 95 80 41 00 00 48 c7 c1 02 00 00 80 }
    $sequence_5 = { 0f 85 14 01 00 00 4c 8d 2d 36 cd 00 00 41 b8 04 01 00 00 66 89 35 ?? ?? ?? ?? 49 8b d5 ff 15 ?? ?? ?? ?? 41 8d 7c 24 e7 }
    $sequence_6 = { 48 83 3d ?? ?? ?? ?? 00 0f 84 4d 04 00 00 48 83 3d ?? ?? ?? ?? 00 0f 84 3f 04 00 00 }
    $sequence_7 = { 83 3d ?? ?? ?? ?? 00 75 05 e8 ?? ?? ?? ?? 48 8d 3d 40 e0 00 00 41 b8 04 01 00 00 }
    $sequence_8 = { 48 8b fb 48 8b f3 48 c1 fe 05 4c 8d 25 be bd 00 00 83 e7 1f 48 6b ff 58 }
    $sequence_9 = { 8b c8 e8 ?? ?? ?? ?? eb c9 48 8b cb 48 8b c3 48 8d 15 97 e4 00 00 48 c1 f8 05 }

  condition:
    7 of them and filesize < 224256
}