rule win_jasus_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.jasus."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.jasus"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 663915???????? 0f8730020000 663915???????? 0f8723020000 663915???????? 0f8716020000 663915???????? }
                                                                                                
        $sequence_1 = { 740f 50 68???????? 56 e8???????? 83c40c 8b45f0 }
                                                                                                
        $sequence_2 = { e8???????? 8b54241c 8bf0 80bb8000000000 c6432d00 7412 }
                                                                                    
        $sequence_3 = { 8bcb 2b4e14 2bc2 3bc8 744e 8b4df8 85c9 }
                                                                                                
        $sequence_4 = { 8d7b1e e8???????? 84c0 7437 a1???????? 8b55f8 }
                                                                                    
        $sequence_5 = { c3 56 33f6 85db 0f889d000000 57 8bf8 }
                                                                                                
        $sequence_6 = { 7474 833b00 756f f644242c01 668954242e 750a }
                                                                                    
        $sequence_7 = { 8b8534feffff 668955c4 8b958cfeffff 6a02 }
                                                            
        $sequence_8 = { c1f905 8b0c8d809d4300 c1e006 8d440104 800820 8b4df4 b8000000c0 }
                                                                                                
        $sequence_9 = { 68???????? e8???????? 8b8df8feffff 83c448 51 ff15???????? 83c404 }
                                                                                                
    condition:
        7 of them and filesize < 507904
}