rule win_ligsterac_auto {
  meta:
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    date               = "2020-10-14"
    version            = "1"
    description        = "autogenerated rule brought to you by yara-signator"
    tool               = "yara-signator v0.5.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.ligsterac"
    malpedia_rule_date = "20201014"
    malpedia_hash      = "a7e3bd57eaf12bf3ea29a863c041091ba3af9ac9"
    malpedia_version   = "20201014"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"
  

  strings:
    $sequence_0 = { e8 ?? ?? ?? ?? 89 07 83 3f 00 74 2f 6a 00 8d 44 24 04 }
                                $sequence_1 = { 47 80 7d f6 12 75 b5 e9 ?? ?? ?? ?? 80 45 f6 02 33 c0 8a 45 f6 }
                                    $sequence_2 = { 8b 7d 18 33 c0 55 68 ?? ?? ?? ?? 64 ff 30 64 89 20 8d 9d fc ef ff ff }
                                    $sequence_3 = { 42 80 7d f6 14 75 bd 80 3e 12 0f 82 9f 01 00 00 8b 45 f8 c7 00 00 00 00 00 }
                                    $sequence_4 = { 58 77 0d e9 ?? ?? ?? ?? 5a 58 0f 8e be 00 00 00 }
                                $sequence_5 = { eb 0f b3 01 eb 0b ba ?? ?? ?? ?? 92 e8 ?? ?? ?? ?? b2 01 }
                                    $sequence_6 = { 6a 26 6a 04 6a 00 6a 01 68 00 00 00 40 56 e8 ?? ?? ?? ?? }
                                    $sequence_7 = { eb 05 c6 44 24 1f 00 6a 05 33 c9 8a 4c 24 22 8d 54 24 28 8b 07 }
                                    $sequence_8 = { e8 ?? ?? ?? ?? 6a 00 6a 00 8d 55 f8 52 6a 00 50 }
                                    $sequence_9 = { 89 44 24 0c a1 ?? ?? ?? ?? 03 05 ?? ?? ?? ?? 2b c6 d1 f8 79 03 83 d0 00 }
                
  condition:
    7 of them and filesize < 149504
}