rule win_moker_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.moker."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.moker"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 0302 8945d4 8b4dd4 83c102 }
                                                            
        $sequence_1 = { 0301 8945e0 e8???????? 8b55e8 }
                                                            
        $sequence_2 = { 0100 83c414 85c0 7502 eb0a }
                                                                        
        $sequence_3 = { 0302 8945e8 eb09 8b45e8 }
                                                            
        $sequence_4 = { 0302 8945dc 8b45dc 83c002 }
                                                            
        $sequence_5 = { 0302 8945e8 8b4df8 8b55fc }
                                                            
        $sequence_6 = { 6a00 8b15???????? 52 6a1e 6a3c }
                                                                        
        $sequence_7 = { 0302 50 e8???????? 83c404 3b450c 750b 8b4df0 }
                                                                                                
        $sequence_8 = { 034508 8078fe5c 740d c6005c c6400100 }
                                                                        
        $sequence_9 = { 50 6800800000 6a00 ff7508 ff15???????? e8???????? 9d }
                                                                                                
        $sequence_10 = { 39f7 7410 fc 39fe }
                                                            
        $sequence_11 = { 730c 8b420c 29c6 8b4214 01c6 eb06 83c228 }
                                                                                                
        $sequence_12 = { eb82 8b86b8000000 40 8d5002 83aec400000004 }
                                                                        
        $sequence_13 = { 75eb 59 5e 5f c9 c21000 }
                                                                                    
        $sequence_14 = { 51 8b4510 48 ff4514 }
                                                            
        $sequence_15 = { 8d5001 52 8d5580 52 e42b }
                                                                        
    condition:
        7 of them and filesize < 1761280
}