rule cstealer
{
    meta:
        description = "Detection patterns for the tool 'cstealer' taken from the ThreatHunting-Keywords github project"
        author = "@mthcht"
        reference = "https://github.com/mthcht/ThreatHunting-Keywords"
        tool = "cstealer"
        rule_category = "offensive_tool_keyword"

    strings:
                        $string1 = /\scstealer\.py/ nocase ascii wide
                        $string2 = /\sNiceRAT\.py/ nocase ascii wide
                        $string3 = /\/cstealer\.git/ nocase ascii wide
                        $string4 = /\/cstealer\.py/ nocase ascii wide
                        $string5 = /\/NiceRAT\.git/ nocase ascii wide
                        $string6 = /\/NiceRAT\.py/ nocase ascii wide
                        $string7 = /\/NiceRAT\-1\.0\.0\.zip/ nocase ascii wide
                        $string8 = /\/t\.me\/NicestRAT/ nocase ascii wide
                        $string9 = /\\cstealer\.py/ nocase ascii wide
                        $string10 = /\\NiceRAT\.py/ nocase ascii wide
                        $string11 = /\\NiceRAT\-1\.0\.0\.zip/ nocase ascii wide
                        $string12 = /\\NiceRAT\-main\\/ nocase ascii wide
                        $string13 = "0x00G/NiceRAT" nocase ascii wide
                        $string14 = "3ec41c041f4c5b1c1c781ddcd9d0286a0a920253783edb27a8fc8085d9ecb6f8" nocase ascii wide
                        $string15 = "7f5ac429cd84d6ac935855b8a7656b830a6eefa1884f7fddd8c7c893c6b09ca4" nocase ascii wide
                        $string16 = "aeachknmefphepccionboohckonoeemg" nocase ascii wide
                        $string17 = "afbcbjpbpfadlkmhmclhkeeodmamcflc" nocase ascii wide
                        $string18 = "agoakfejjabomempkjlepdflaleeobhb" nocase ascii wide
                        $string19 = "aholpfdialjgjfhomihkjbmgjidlcdno" nocase ascii wide
                        $string20 = "aiifbnbfobpmeekipheeijimdpnlpgpp" nocase ascii wide
                        $string21 = "amkmjjmmflddogmhpjloimipbofnfjih" nocase ascii wide
                        $string22 = "aodkkagnadcbobfpggfnjeongemjbjca" nocase ascii wide
                        $string23 = "bfnaelmomeimhlpmgjnjophhpkkoljpa" nocase ascii wide
                        $string24 = "bhghoamapcdpbohphigoooaddinpkbai" nocase ascii wide
                        $string25 = "bhhhlbepdkbapadjdnnojkbgioiodbic" nocase ascii wide
                        $string26 = /C4RD\sN4M3\:\s.{0,1000}\|\sNUMB3R\:/ nocase ascii wide
                        $string27 = "can-kat/cstealer" nocase ascii wide
                        $string28 = "cgeeodpfagjceefieflmdfphplkenlfk" nocase ascii wide
                        $string29 = /CH3CK70K3N\(/ nocase ascii wide
                        $string30 = "cjelfplplebdjjenllpjcblmjkfcffne" nocase ascii wide
                        $string31 = /crcreditcards\.txt/ nocase ascii wide
                        $string32 = /CrealPasswords\.txt/ nocase ascii wide
                        $string33 = /crpasswords\.txt/ nocase ascii wide
                        $string34 = "CStealer Builder ~ " nocase ascii wide
                        $string35 = /CStealer_assets\\/ nocase ascii wide
                        $string36 = /curl\s\-F\s.{0,1000}\shttps\:\/\/.{0,1000}\.gofile\.io\/uploadFile/ nocase ascii wide
                        $string37 = /D3CrYP7V41U3\(/ nocase ascii wide
                        $string38 = "db7d3e12a58a102b76c1f6e041d0a464ccbffc346dbc338a8cb4a7e5ec508b6c" nocase ascii wide
                        $string39 = "dngmlblcodfobpdpecaadgfbcggfjfnm" nocase ascii wide
                        $string40 = "ebfidpplhabeedpnhjnobghokpiioolj" nocase ascii wide
                        $string41 = "efbglgofoippbgcjepnhiblaibcnclgk" nocase ascii wide
                        $string42 = "egjidjbpglichdcondbcbdnbeeppgdph" nocase ascii wide
                        $string43 = "eigblbgjknlfbajkfhopmcojidlgcehm" nocase ascii wide
                        $string44 = "ejbalbakoplchlghecdalmeeeajnimhm" nocase ascii wide
                        $string45 = "ejjladinnckdgjemekebdpeokbikhfci" nocase ascii wide
                        $string46 = "ffnbelfdoeiohenkjibnmadjiehjhajb" nocase ascii wide
                        $string47 = "fhbohimaelbohpjbbldcngcnapndodjp" nocase ascii wide
                        $string48 = "fhilaheimglignddkjgofkcbgekhenbh" nocase ascii wide
                        $string49 = "fnjhmkhhmkbjkkabndcnnogagogbneec" nocase ascii wide
                        $string50 = "fnnegphlobjdpkhecapkijjdkgcjhkib" nocase ascii wide
                        $string51 = /G374U70F111\(/ nocase ascii wide
                        $string52 = /G3770K3N\(/ nocase ascii wide
                        $string53 = /G3770K3N1NF0\(/ nocase ascii wide
                        $string54 = /G37800KM4rK5\(/ nocase ascii wide
                        $string55 = /G3781111N6\(/ nocase ascii wide
                        $string56 = /G3784D63\(/ nocase ascii wide
                        $string57 = /G378r0W53r5\(br0W53rP47H5\)/ nocase ascii wide
                        $string58 = /G37C00K13\(/ nocase ascii wide
                        $string59 = /G37C0D35\(/ nocase ascii wide
                        $string60 = /G37CC5\(/ nocase ascii wide
                        $string61 = /G37D15C0rD\(/ nocase ascii wide
                        $string62 = /G37D474\(/ nocase ascii wide
                        $string63 = /G37H1570rY\(/ nocase ascii wide
                        $string64 = /G37P455W\(/ nocase ascii wide
                        $string65 = /G37UHQ6U11D5\(/ nocase ascii wide
                        $string66 = /G37UHQFr13ND5\(/ nocase ascii wide
                        $string67 = /G37W3851735\(/ nocase ascii wide
                        $string68 = /G47H3rZ1P5\(/ nocase ascii wide
                        $string69 = "hmeobnfnfcmdkdcmlblgagmfpfboieaf" nocase ascii wide
                        $string70 = "hnfanknocfeofbddgcijnmhnfnkdnaad" nocase ascii wide
                        $string71 = "hpglfhgfnhbgpjdenjgmdgoeiappafln" nocase ascii wide
                        $string72 = /https\:\/\/ptb\.discord\.com\/api\/webhooks\/1226217588959215726\/AZaNnD4TIN\-9sV\-t0rsveiQxcROYaCVziI8BUa6CNPsUxdnW9mdHu7HnuQ55kQPXZ8_5/ nocase ascii wide
                        $string73 = "ibnejdfjmmkpcnlpebklmnkoeoihofec" nocase ascii wide
                        $string74 = "jblndlipeogpafnldhgmapagcccfchpi" nocase ascii wide
                        $string75 = /K1W1F01D3r\(/ nocase ascii wide
                        $string76 = /K1W1F113\(/ nocase ascii wide
                        $string77 = "kncchdigobghenbbaddojjnnaogfppfj" nocase ascii wide
                        $string78 = "kpfopkelmapcoipemfendmdcghnegimn" nocase ascii wide
                        $string79 = /L04DUr118\(h00k/ nocase ascii wide
                        $string80 = "lgmpcpglpngdoalbgeoldeajfclnhafa" nocase ascii wide
                        $string81 = "lpfcbjknijpeeillifnkikgncikgfhdo" nocase ascii wide
                        $string82 = "mfgccjchihfkkindfppnaooecgfneiii" nocase ascii wide
                        $string83 = "mgffkfbidihjpoaomajlbgchddlicgpn" nocase ascii wide
                        $string84 = "nanjmdknhkinifnkgdcggcfnhdaammmj" nocase ascii wide
                        $string85 = /NiceRAT\s\|\s.{0,1000}\sStealer/ nocase ascii wide
                        $string86 = /NiceRAT\-main\.zip/ nocase ascii wide
                        $string87 = "nkbihfbeogaeaoehlefnkodbefgpgknn" nocase ascii wide
                        $string88 = "nkddgncdjgjfcddamfgcmfnlhccnimig" nocase ascii wide
                        $string89 = "nlbmnnijcnlegkjjpcfjclmcfggfefdm" nocase ascii wide
                        $string90 = "ojggmchlghnjlapmfbnjholfjkiidbch" nocase ascii wide
                        $string91 = "ookjlbkiijinhpmnjffcofjonbfbgaoc" nocase ascii wide
                        $string92 = "opcgpfmipidbgpenhmajoajpbobppdil" nocase ascii wide
                        $string93 = "pdadjkfkgcafgbceimcpbkalnfnepbnk" nocase ascii wide
                        $string94 = "phkbamefinggmakgklpkljjmgibohnba" nocase ascii wide
                        $string95 = /r3F0rM47\(listt/ nocase ascii wide
                        $string96 = /S74r77Hr34D\(/ nocase ascii wide
                        $string97 = /s74r787Hr34D\(/ nocase ascii wide
                        $string98 = /SQ17H1N6\(/ nocase ascii wide
                        $string99 = /TrU57\(C00K13s\)/ nocase ascii wide
                        $string100 = /UP104D7060F113\(/ nocase ascii wide
                        $string101 = /UP104D70K3N\(/ nocase ascii wide
                        $string102 = /Wr173F0rF113\(/ nocase ascii wide
                        $string103 = /www\.nicerat\.com/ nocase ascii wide
                        $string104 = /Z1P73136r4M\(/ nocase ascii wide
                        $string105 = /Z1P7H1N65\(/ nocase ascii wide
                        $string106 = /Z1PF01D3r\(/ nocase ascii wide

    condition:
        any of them
}