rule win_suppobox_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.suppobox."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.suppobox"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 7e10 a1???????? 0305???????? a3???????? }
                                                            
        $sequence_1 = { 3bc8 7d10 a1???????? 2b05???????? a3???????? }
                                                                        
        $sequence_2 = { 890d???????? e8???????? 8bf0 e8???????? 03f0 }
                                                                        
        $sequence_3 = { 8945f0 a1???????? 83e801 a3???????? }
                                                            
        $sequence_4 = { 7412 8b0d???????? 030d???????? 890d???????? }
                                                            
        $sequence_5 = { 7d10 a1???????? 0b05???????? a3???????? }
                                                            
        $sequence_6 = { 7f10 a1???????? 2305???????? a3???????? }
                                                            
        $sequence_7 = { 01c6 39fe 0f8d2f020000 80bc2ef4f7ffff0a }
                                                            
        $sequence_8 = { 019dacf7ffff 83c40c 299dc4f7ffff e9???????? }
                                                            
        $sequence_9 = { 8d48ff 2d9b507602 8985dcfdffff db85dcfdffff }
                                                            
        $sequence_10 = { 01c6 39fe 0f8d7e010000 80bc2ef4f7ffff0a }
                                                            
        $sequence_11 = { 8d48ff 2d9696ca2f 39c2 66898d92feffff 0f8dbbfcffff }
                                                                        
        $sequence_12 = { 01bdacf7ffff 83c40c 83bdc8f7ffff00 8b95c8f7ffff }
                                                            
        $sequence_13 = { 01d8 3b85b0f7ffff 7e2f 8b95c8f7ffff }
                                                            
        $sequence_14 = { 8d48ff 39c2 890d???????? 0f8e93240000 }
                                                            
        $sequence_15 = { 8d48ff 2de13d1921 8985e0f8ffff db85e0f8ffff }
                                                            
        $sequence_16 = { 01d7 68???????? 57 e8???????? }
                                                            
        $sequence_17 = { 8d48ff 39c2 898db4f8ffff 0f8e3d0f0000 }
                                                            
        $sequence_18 = { 01c6 ebdb ff7510 57 }
                                                            
        $sequence_19 = { 01c9 4a 79f2 833b54 }
                                                            
        $sequence_20 = { 8d48ff 2dbb4fb754 39c2 66890d???????? }
                                                            
        $sequence_21 = { 8d48ff 39c2 898dc8feffff 0f8ebb010000 }
                                                            
    condition:
        7 of them and filesize < 1875968
}