rule win_soundbill_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.soundbill."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.soundbill"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 55 56 4881ecb0030000 488b05???????? 4833c4 4889842470030000 488b8424f0030000 }
                                                                                                
        $sequence_1 = { 488b8da0000000 e8???????? 4883c420 5d c3 488d8a70000000 e9???????? }
                                                                                                
        $sequence_2 = { 750e 85c9 0f95c0 8806 83f901 760c eb03 }
                                                                                                
        $sequence_3 = { 48894a08 488d4808 e8???????? 488d0579b00200 488903 488bc3 4883c420 }
                                                                                                
        $sequence_4 = { f20f5ce9 f2410f1004c1 488d15562b0100 f20f1014c2 }
                                                            
        $sequence_5 = { c644243001 44397c2440 7f10 ff442434 4885c9 7426 c644243c01 }
                                                                                                
        $sequence_6 = { 483305???????? 488d1516b70200 488bcb 488905???????? ff15???????? 483305???????? }
                                                                                    
        $sequence_7 = { ffd7 4c8bf0 4885c0 751e 498bcf ff15???????? 488bce }
                                                                                                
        $sequence_8 = { 418d542416 488d0d3f4b0100 e8???????? 488b0b 66443921 488bcb 744d }
                                                                                                
        $sequence_9 = { 8b4018 25c0010000 83f840 0f84e7010000 }
                                                            
    condition:
        7 of them and filesize < 973824
}