rule MALPEDIA_Win_Dnespy_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "70dfc3a2-0802-5571-8c6e-dca5ba3f52dd"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.dnespy"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.dnespy_auto.yar#L1-L132"
    license_url        = "N/A"
    logic_hash         = "5f9d7d06b9dad4ee82945ca7222951c2d8150747511ca4dc6b623794062c6006"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0 = { 83 ec 18 8d 45 08 8b cc 50 e8 ?? ?? ?? ?? ba 01 00 00 00 8d 4d c8 }
    $sequence_1 = { f3 0f 7e 45 94 8b 45 9c 66 0f d6 45 a4 89 45 ac 72 09 8b 0e 8b c1 }
    $sequence_2 = { 8b f1 89 54 24 0c 57 8b 7d 08 89 44 24 14 83 7e 4c 00 74 71 }
    $sequence_3 = { 74 e7 83 f8 0d 74 e2 40 83 f8 7e 0f 87 8b 01 00 00 }
    $sequence_4 = { 6a 50 66 89 45 e8 ff 15 ?? ?? ?? ?? 66 89 45 ea 8d 45 e8 6a 10 }
    $sequence_5 = { 0f 84 f0 00 00 00 8b c8 e8 ?? ?? ?? ?? 8b d0 c7 45 e0 00 00 00 00 8b ca c7 45 e4 0f 00 00 00 }
    $sequence_6 = { 6a 00 6a 00 8d 85 e0 cf ff ff 50 6a 00 ff 15 ?? ?? ?? ?? ff b5 a0 cf ff ff }
    $sequence_7 = { 8a 18 3a 19 75 0a 40 41 3b c2 75 f0 }
    $sequence_8 = { 74 4b 8d 45 f4 c7 45 f0 00 00 00 00 50 8d 45 f8 c7 45 f8 00 00 00 00 50 }
    $sequence_9 = { c6 85 eb fe ff ff 00 c6 85 ec fe ff ff 0f c6 85 ed fe ff ff 0a c6 85 ee fe ff ff 03 8a 85 dc fe ff ff c6 85 ef fe ff ff 00 0f 1f 44 00 00 }

  condition:
    7 of them and filesize < 794624
}