rule MALPEDIA_Win_Lazarloader_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "eeec4f28-0f22-51be-ae2e-de44f3255986"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.lazarloader"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.lazarloader_auto.yar#L1-L124"
    license_url        = "N/A"
    logic_hash         = "2c7bcf20b8b4c12e652b091953d52f7cafa589f18b8b9e18e7eefdba4a60b648"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0 = { 48 3b 0d ?? ?? ?? ?? 74 17 48 8d 05 9c 4f 01 00 48 3b c8 }
    $sequence_1 = { 75 28 48 83 3d ?? ?? ?? ?? 00 74 1e 48 8d 0d 30 a8 01 00 e8 ?? ?? ?? ?? 85 c0 74 0e }
    $sequence_2 = { 8b c2 48 8d 15 42 41 ff ff c1 e8 03 89 44 24 38 44 8b e0 89 44 24 40 85 c0 }
    $sequence_3 = { 48 8d 05 63 81 00 00 48 8b d9 48 3b c8 74 17 8b 81 5c 01 00 00 }
    $sequence_4 = { 48 89 54 24 10 48 89 4c 24 08 57 48 81 ec e0 08 00 00 33 c0 66 89 84 24 a0 00 00 00 48 8d 84 24 a2 00 00 00 }
    $sequence_5 = { 4c 8b ea 4b 8b 8c f7 70 c1 01 00 4c 8b 15 ?? ?? ?? ?? 48 83 cf ff 41 8b c2 49 8b d2 48 33 d1 }
    $sequence_6 = { 8b cf e8 ?? ?? ?? ?? 48 8b d7 4c 8d 05 fe cd 00 00 83 e2 3f 48 8b cf 48 c1 f9 06 }
    $sequence_7 = { 48 89 70 18 48 89 78 20 41 56 33 ed 4c 8d 35 e6 90 00 00 44 8b d5 48 8b f1 }
    $sequence_8 = { e8 ?? ?? ?? ?? 48 8b d7 4c 8d 05 fe cd 00 00 83 e2 3f }
    $sequence_9 = { 48 8b da 4c 8d 0d 6b ad 00 00 8b f9 48 8d 15 a2 93 00 00 b9 06 00 00 00 }

  condition:
    7 of them and filesize < 364544
}