rule MALPEDIA_Win_Gup_Proxy_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "5c3bfea3-920f-5316-9eb6-180474d2cca9"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.gup_proxy"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.gup_proxy_auto.yar#L1-L123"
    license_url        = "N/A"
    logic_hash         = "d81f0061756179ec05e7cc548d81d0721d972a5a55f0d637cdd705d25b38ea90"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0 = { c7 44 24 44 00 00 00 00 c6 44 24 34 00 e8 ?? ?? ?? ?? c7 84 24 20 02 00 00 00 00 00 00 8d 4c 24 44 6a 00 }
    $sequence_1 = { c1 e6 06 03 34 85 10 97 41 00 33 db 39 5e 08 }
    $sequence_2 = { 8b 04 bd 10 97 41 00 83 0c 06 ff 33 c0 eb 16 e8 ?? ?? ?? ?? c7 00 09 00 00 00 }
    $sequence_3 = { c1 f8 05 c1 e6 06 8b 04 85 10 97 41 00 80 64 30 04 fd 8b 45 f8 8b 55 fc 5f }
    $sequence_4 = { c7 85 88 fe ff ff c2 2e ab 48 50 8b ce e8 ?? ?? ?? ?? 8b c3 88 9d 88 fe ff ff c1 e8 18 }
    $sequence_5 = { c3 b8 ?? ?? ?? ?? c7 05 ?? ?? ?? ?? 61 98 40 00 a3 ?? ?? ?? ?? c7 05 ?? ?? ?? ?? f2 98 40 00 c7 05 ?? ?? ?? ?? 4c 99 40 00 c7 05 ?? ?? ?? ?? d1 99 40 00 }
    $sequence_6 = { c7 84 24 20 02 00 00 00 00 00 00 8d 4c 24 44 6a 00 68 ?? ?? ?? ?? c7 44 24 60 0f 00 00 00 c7 44 24 5c 00 00 00 00 c6 44 24 4c 00 }
    $sequence_7 = { eb b4 c7 45 e4 d8 a0 41 00 a1 ?? ?? ?? ?? eb 1a c7 45 e4 d4 a0 41 00 a1 ?? ?? ?? ?? }
    $sequence_8 = { ff 15 ?? ?? ?? ?? 8b 04 bd 10 97 41 00 83 0c 06 ff 33 c0 }
    $sequence_9 = { 53 ff 15 ?? ?? ?? ?? 83 f8 ff 75 2a 32 c0 }

  condition:
    7 of them and filesize < 247808
}