rule win_aveo_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.aveo."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.aveo"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 894804 894808 89480c b9???????? 8d7901 8a11 41 }
                                                                                                
        $sequence_1 = { 68???????? e8???????? 83c404 899df4fdffff eb06 89b5f4fdffff 68???????? }
                                                                                                
        $sequence_2 = { 52 50 8d9df8feffff e8???????? }
                                                            
        $sequence_3 = { 8d8dfcefffff 51 8bf8 e8???????? 33ff 39bdf4efffff }
                                                                                    
        $sequence_4 = { e8???????? 83c40c 8d842418010000 50 8d8c241c030000 }
                                                                        
        $sequence_5 = { b9???????? 8d7901 8a11 41 84d2 75f9 2bcf }
                                                                                                
        $sequence_6 = { 8db590fdffff 898574fdffff e8???????? be00100000 }
                                                            
        $sequence_7 = { 50 e8???????? 8d8df4f9ffff 51 8d95f4feffff 52 }
                                                                                    
        $sequence_8 = { 6803800000 50 ff15???????? 8b4de8 6a00 6a05 }
                                                                                    
        $sequence_9 = { 51 e8???????? 8b4df8 83c404 5f }
                                                                        
    condition:
        7 of them and filesize < 180224
}