rule win_grabbot_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.grabbot."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.grabbot"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 83f85a 770b 83f841 7206 83c020 0fb7c0 83c202 }
                                                                                                
        $sequence_1 = { 83f85a 770d 83f841 7208 83c020 }
                                                                        
        $sequence_2 = { 50 6a04 ff75e8 ff75dc }
                                                            
        $sequence_3 = { 813850450000 7523 0fb75004 bb64860000 663bd3 7506 }
                                                                                    
        $sequence_4 = { b905000000 3907 7707 83c704 e2f7 }
                                                                        
        $sequence_5 = { 663907 7566 8b473c 03c7 813850450000 }
                                                                        
        $sequence_6 = { c3 68d0035c09 e8???????? 50 e8???????? ffe0 }
                                                                                    
        $sequence_7 = { e8???????? 59 81c480000000 50 8bf1 e8???????? e8???????? }
                                                                                                
        $sequence_8 = { 56 ffd0 33c9 66894c37fe }
                                                            
        $sequence_9 = { 7428 8b0d???????? 8908 8b0d???????? 894804 8b0d???????? }
                                                                                    
        $sequence_10 = { 894808 8b0d???????? 89480c e9???????? 33c0 }
                                                                        
        $sequence_11 = { 8d45f0 99 52 50 8b451c 99 }
                                                                                    
        $sequence_12 = { 57 8d7c000c 57 e8???????? }
                                                            
        $sequence_13 = { e8???????? 85c0 56 0f9fc3 e8???????? 83c414 }
                                                                                    
        $sequence_14 = { 50 ff15???????? a3???????? 85c0 7505 83c8ff }
                                                                                    
        $sequence_15 = { 8bf0 85f6 741d 8d4601 }
                                                            
    condition:
        7 of them and filesize < 1335296
}