rule win_nosu_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.nosu."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.nosu"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 0f8455010000 8d442438 50 8d442424 50 6a02 6a01 }
                                                                                                
        $sequence_1 = { 50 6a00 8d54246c e8???????? 83c40c 84c0 0f8477020000 }
                                                                                                
        $sequence_2 = { 33d2 8bcb ff742420 55 56 ff74242c 56 }
                                                                                                
        $sequence_3 = { 8844240a 84c0 7416 b201 8bce e8???????? 8b4514 }
                                                                                                
        $sequence_4 = { 399688010000 7432 3996d8050000 742a 8b8ef8070000 ff7514 }
                                                                                    
        $sequence_5 = { 8d86e0020000 85c0 740d 6a5c 59 }
                                                                        
        $sequence_6 = { 89b658080000 50 56 b201 8bcf e8???????? 83c414 }
                                                                                                
        $sequence_7 = { 83c520 55 6a08 ff15???????? 50 ff15???????? }
                                                                                    
        $sequence_8 = { c9 c3 57 8bfa 3b4c2408 740d 8bd1 }
                                                                                                
        $sequence_9 = { 83c01e 03c7 0101 ff414c 8d4c2418 e8???????? 5f }
                                                                                                
    condition:
        7 of them and filesize < 513024
}