rule win_onliner_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.onliner."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.onliner"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { ff15???????? 8bf0 85f6 0f85ab000000 8b45f8 8945f4 e9???????? }
                                                                                                
        $sequence_1 = { 58 e8???????? 0f8436010000 a1???????? e8???????? 3c01 7412 }
                                                                                                
        $sequence_2 = { 058a4c2a8d ba14000000 e8???????? 03c7 8bf0 8bc7 33c6 }
                                                                                                
        $sequence_3 = { 8910 33c0 8ac3 8d448604 8b17 e8???????? 8b17 }
                                                                                                
        $sequence_4 = { e8???????? ff75ec 8b45fc e8???????? 0fb7c0 8d55e4 e8???????? }
                                                                                                
        $sequence_5 = { eb41 83c0bf 83e81a 7225 83c0fa 83e81a }
                                                                                    
        $sequence_6 = { 837df800 750f 8bc3 8b55fc e8???????? e9???????? 8b45f8 }
                                                                                                
        $sequence_7 = { 8bd7 e8???????? 8b0424 833800 742e 8b0424 }
                                                                                    
        $sequence_8 = { 8993b4010000 8d8398000000 e8???????? 8d9398000000 8b83b4010000 e8???????? 8bc3 }
                                                                                                
        $sequence_9 = { 8bcf 83e11f c1e106 8b048560f94c00 c644080401 57 e8???????? }
                                                                                                
    condition:
        7 of them and filesize < 1736704
}