rule win_cuegoe_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.cuegoe."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.cuegoe"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 8985500c0000 8b432c 8b4b24 57 }
                                                            
        $sequence_1 = { 57 8db55c030000 e8???????? 53 57 8db59c030000 e8???????? }
                                                                                                
        $sequence_2 = { 8bff 8b4500 83780400 0f84961a0000 8b30 0fb636 8b551c }
                                                                                                
        $sequence_3 = { 894740 8b454c 894744 8b4550 894748 8b4554 89474c }
                                                                                                
        $sequence_4 = { 0f8554020000 57 83ec18 8bc4 89654c 53 50 }
                                                                                                
        $sequence_5 = { 8b149580cf0310 c1e006 8d440224 802080 884dfd 8065fd48 884dff }
                                                                                                
        $sequence_6 = { 894310 5e 5f c20400 6a04 }
                                                                        
        $sequence_7 = { b8???????? e8???????? 8b7508 8365f000 c706???????? c746581c520310 }
                                                                                    
        $sequence_8 = { ff5004 0fb7c0 6a01 50 ff7528 8d758c ff7524 }
                                                                                                
        $sequence_9 = { 897dc4 50 c745fc02000000 e8???????? 33c0 c745c401000000 c745ec07000000 }
                                                                                                
    condition:
        7 of them and filesize < 540672
}