rule MALPEDIA_Win_Contopee_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "77374f1e-6c89-5026-9b9e-741c43271a9e"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.contopee"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.contopee_auto.yar#L1-L123"
    license_url        = "N/A"
    logic_hash         = "887c3d1e6d8d0ed992ba95d9f863595a093876d8864d3c96b3a6d6d4a8e08fbb"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0 = { c3 8b ac 24 4c 02 00 00 55 6a 00 }
    $sequence_1 = { 83 c4 1c eb 35 8b 56 14 8b 44 24 30 6a 00 6a ff 42 }
    $sequence_2 = { 68 80 00 00 00 50 8d 8e 6a 05 00 00 68 80 00 00 00 51 }
    $sequence_3 = { 66 89 6c 24 0c 8d 84 24 14 02 00 00 50 57 ff 15 ?? ?? ?? ?? }
    $sequence_4 = { 75 10 ff 15 ?? ?? ?? ?? 5f 5d 5b 81 c4 dc 04 00 00 c3 }
    $sequence_5 = { 8b f8 eb c8 ff 15 ?? ?? ?? ?? 8b f8 eb d1 5f }
    $sequence_6 = { 74 32 6a 0f 51 50 e8 ?? ?? ?? ?? 8b f0 }
    $sequence_7 = { 8b d8 8b 46 08 83 f8 02 8b 44 24 2c 0f 85 8e 00 00 00 eb 04 8b 7c 24 18 }
    $sequence_8 = { 68 ?? ?? ?? ?? 51 ff 15 ?? ?? ?? ?? 8b 84 24 3c 02 00 00 8d 54 24 28 52 50 }
    $sequence_9 = { 52 e8 ?? ?? ?? ?? 83 c4 30 5f 5e }

  condition:
    7 of them and filesize < 180224
}