rule win_unidentified_003_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.unidentified_003."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.unidentified_003"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { b8???????? 2b05???????? ff7006 50 50 8d442464 50 }
                                                                                                
        $sequence_1 = { 7561 6a00 68???????? 8d45f0 e8???????? }
                                                                        
        $sequence_2 = { 0f8312020000 8dbdf1fdffff 2bf9 8a11 88140f 41 84d2 }
                                                                                                
        $sequence_3 = { 85c0 75b5 8d45f4 50 8d85e3fbffff 50 }
                                                                                    
        $sequence_4 = { 395de0 0f8421010000 8b45e0 8b08 50 }
                                                                        
        $sequence_5 = { bb01000080 53 ff15???????? 6a22 58 668985f0fbffff 33c0 }
                                                                                                
        $sequence_6 = { 3bc3 7468 3d00100400 741c 3d10100400 7415 3d00100600 }
                                                                                                
        $sequence_7 = { ff45fc 8b45fc 8145f80c020000 81c718040000 3b45f0 0f8238ffffff eb07 }
                                                                                                
        $sequence_8 = { 8b45a4 3bc3 7464 8945d8 33c0 8d7dac ab }
                                                                                                
        $sequence_9 = { 56 e8???????? 59 59 85c0 7408 c60000 }
                                                                                                
    condition:
        7 of them and filesize < 57344
}