rule pupy
{
    meta:
        description = "Detection patterns for the tool 'pupy' taken from the ThreatHunting-Keywords github project"
        author = "@mthcht"
        reference = "https://github.com/mthcht/ThreatHunting-Keywords"
        tool = "pupy"
        rule_category = "offensive_tool_keyword"

    strings:
                        $string1 = /\sclear_logs\.py/ nocase ascii wide
                        $string2 = /\screddump\.py/ nocase ascii wide
                        $string3 = /\sdomcachedump\.py/ nocase ascii wide
                        $string4 = /\sdomcachedump\.py/ nocase ascii wide
                        $string5 = /\sexploit_suggester\.py/ nocase ascii wide
                        $string6 = " gen -f client -O windows -A x64" nocase ascii wide
                        $string7 = " gen -S -f client -O windows -A x64" nocase ascii wide
                        $string8 = /\simpacket\./ nocase ascii wide
                        $string9 = /\sinteractive_shell\.py/ nocase ascii wide
                        $string10 = " keylogger " nocase ascii wide
                        $string11 = /\slinux_stealth\.py/
                        $string12 = " memorpy " nocase ascii wide
                        $string13 = /\smimipy\.py\s/ nocase ascii wide
                        $string14 = /\smouselogger\.py/ nocase ascii wide
                        $string15 = /\snbnsspoof\.py/ nocase ascii wide
                        $string16 = " --oneliner-nothidden" nocase ascii wide
                        $string17 = " persist_hkcu_run" nocase ascii wide
                        $string18 = /\sport_scan\.py/ nocase ascii wide
                        $string19 = " PupyCredentials" nocase ascii wide
                        $string20 = /\spupylib\./ nocase ascii wide
                        $string21 = /\spupysh\.py/ nocase ascii wide
                        $string22 = /\spupysh\.sh/ nocase ascii wide
                        $string23 = " PupySocketStream" nocase ascii wide
                        $string24 = " PupyTCPClient" nocase ascii wide
                        $string25 = " PupyTCPServer" nocase ascii wide
                        $string26 = " PupyWebServer" nocase ascii wide
                        $string27 = " PupyWebSocketClient" nocase ascii wide
                        $string28 = " PupyWebSocketServer" nocase ascii wide
                        $string29 = /\spupyx64\.dll/ nocase ascii wide
                        $string30 = /\spupyx64\.exe/ nocase ascii wide
                        $string31 = /\spupyx64\.lin/ nocase ascii wide
                        $string32 = /\spupyx86\.dll/ nocase ascii wide
                        $string33 = /\spupyx86\.exe/ nocase ascii wide
                        $string34 = " push_payload" nocase ascii wide
                        $string35 = /\spwdump\.py/ nocase ascii wide
                        $string36 = /\ssocks5proxy\.py/ nocase ascii wide
                        $string37 = " start_hidden_process" nocase ascii wide
                        $string38 = /\/all\/pupyutils\/.{0,100}\.py/ nocase ascii wide
                        $string39 = "/android/pupydroid/" nocase ascii wide
                        $string40 = /\/beroot\.py/ nocase ascii wide
                        $string41 = "/bin/pupysh"
                        $string42 = /\/clear_logs\.py/
                        $string43 = /\/creddump\.py/ nocase ascii wide
                        $string44 = "/creddump7/" nocase ascii wide
                        $string45 = /\/dnscnc\.py/ nocase ascii wide
                        $string46 = /\/domcachedump\.py/ nocase ascii wide
                        $string47 = /\/exploit_suggester\.py/ nocase ascii wide
                        $string48 = /\/interactive_shell\.py/ nocase ascii wide
                        $string49 = "/LaZagne/Windows/" nocase ascii wide
                        $string50 = /\/linux_stealth\.py/
                        $string51 = /\/memory_exec\.py/ nocase ascii wide
                        $string52 = /\/mimipy\.py/ nocase ascii wide
                        $string53 = /\/mouselogger\.py/ nocase ascii wide
                        $string54 = "/n1nj4sec/pupy" nocase ascii wide
                        $string55 = /\/nbnsspoof\.py/ nocase ascii wide
                        $string56 = /\/netcreds\.py/ nocase ascii wide
                        $string57 = /\/netcreds\.py/ nocase ascii wide
                        $string58 = /\/obfs3\/obfs3\.py/ nocase ascii wide
                        $string59 = /\/port_scan\.py/ nocase ascii wide
                        $string60 = /\/powerloader\.py/ nocase ascii wide
                        $string61 = /\/ps1_oneliner\.py/ nocase ascii wide
                        $string62 = /\/pupwinutils\/.{0,100}\.py/ nocase ascii wide
                        $string63 = /\/pupy\/.{0,100}\.py/ nocase ascii wide
                        $string64 = "/pupy/commands/" nocase ascii wide
                        $string65 = "/pupy/external/creddump7"
                        $string66 = "/pupy/memimporter/" nocase ascii wide
                        $string67 = /\/pupy\/output\/pupyx64.{0,100}\.exe/ nocase ascii wide
                        $string68 = /\/pupy\/pupygen\.py/ nocase ascii wide
                        $string69 = /\/pupy_load\./ nocase ascii wide
                        $string70 = /\/PupyCmd\.py/ nocase ascii wide
                        $string71 = /\/PupyCompile\.py/ nocase ascii wide
                        $string72 = /\/pupygen\.py/ nocase ascii wide
                        $string73 = "/pupylib/payloads/" nocase ascii wide
                        $string74 = /\/PupyOffload\.py/ nocase ascii wide
                        $string75 = /\/pupyps\.py/ nocase ascii wide
                        $string76 = /\/PupyServer\.py/ nocase ascii wide
                        $string77 = /\/PupyService\.py/ nocase ascii wide
                        $string78 = /\/pupysh\.py/ nocase ascii wide
                        $string79 = /\/pupysh\.sh/
                        $string80 = /\/PupyTriggers\.py/ nocase ascii wide
                        $string81 = /\/PupyWeb\.py/ nocase ascii wide
                        $string82 = /\/pupyx64\.dll/ nocase ascii wide
                        $string83 = /\/pupyx64\.exe/ nocase ascii wide
                        $string84 = /\/pupyx64d\.exe/ nocase ascii wide
                        $string85 = /\/pupyx86\.exe/ nocase ascii wide
                        $string86 = /\/pupyx86d\.exe/ nocase ascii wide
                        $string87 = /\/pwdump\.py/ nocase ascii wide
                        $string88 = /\/py_oneliner\.py/ nocase ascii wide
                        $string89 = /\/Python\-dynload\-os\.h/ nocase ascii wide
                        $string90 = /\/share_enum\.py/ nocase ascii wide
                        $string91 = /\/shell_exec\.py/ nocase ascii wide
                        $string92 = /\/smbspider\.py/ nocase ascii wide
                        $string93 = /\/socks5proxy\.py/ nocase ascii wide
                        $string94 = /\/transports\/scramblesuit\/.{0,100}\.py/ nocase ascii wide
                        $string95 = /\/usniper\.py/ nocase ascii wide
                        $string96 = /\/utils\/obfuscate\.py/ nocase ascii wide
                        $string97 = "/WinPwnage" nocase ascii wide
                        $string98 = /\[\+\]\sBuild\spupysh\senvironment\s/ nocase ascii wide
                        $string99 = /\\clear_logs\.py/ nocase ascii wide
                        $string100 = /\\creddump\.py/ nocase ascii wide
                        $string101 = /\\dns\-dump\.ps1/ nocase ascii wide
                        $string102 = /\\domcachedump\.py/ nocase ascii wide
                        $string103 = /\\domcachedump\.py/ nocase ascii wide
                        $string104 = /\\exploit_suggester\.py/ nocase ascii wide
                        $string105 = /\\mimipy\.py/ nocase ascii wide
                        $string106 = /\\mouselogger\.py/ nocase ascii wide
                        $string107 = /\\nbnsspoof\.py/ nocase ascii wide
                        $string108 = /\\netcreds\.py/ nocase ascii wide
                        $string109 = /\\port_scan\.py/ nocase ascii wide
                        $string110 = /\\pupwinutils\\/ nocase ascii wide
                        $string111 = /\\pupy\\external\\creddump7/ nocase ascii wide
                        $string112 = /\\pupyx64\.dll/ nocase ascii wide
                        $string113 = /\\pupyx64\.exe/ nocase ascii wide
                        $string114 = /\\pupyx64d\.exe/ nocase ascii wide
                        $string115 = /\\pupyx86\.dll/ nocase ascii wide
                        $string116 = /\\pupyx86\.exe/ nocase ascii wide
                        $string117 = /\\pupyx86d\.exe/ nocase ascii wide
                        $string118 = /\\pwdump\.py/ nocase ascii wide
                        $string119 = /\\socks5proxy\.py/ nocase ascii wide
                        $string120 = /\\windows\\all\\winpwnage/ nocase ascii wide
                        $string121 = /\\windows\\creddump/ nocase ascii wide
                        $string122 = "_generate_bind_payloads_password" nocase ascii wide
                        $string123 = "_generate_scramblesuit_passwd" nocase ascii wide
                        $string124 = "_METERPRETER_BASE_INJECT_H" nocase ascii wide
                        $string125 = "07aa565057af859bc4956df913246b3b5fe39e86823666d6ba77aa98a697b02a" nocase ascii wide
                        $string126 = "10de4ed7588b4a7e75d01bb69f0b602b0c298a2f9f993a6a8f4e2248031699fb" nocase ascii wide
                        $string127 = "18eeee347539926baae88b3bec52025a00b404301f60a8cbf4d77156fcfaf782" nocase ascii wide
                        $string128 = "237f52a3509094464bb92f82a4908a60c7a4cc9db9748f0cc254e75311bb8b0d" nocase ascii wide
                        $string129 = "2a8b77cd55cc43d79d9c4475cc9287360f6fd3dc47a07f83ff33853de1652f7d" nocase ascii wide
                        $string130 = "3000b91468e3961b4e1a9ecd07007bfe02f50033d0d4a71dfb4e5b1de778bd13" nocase ascii wide
                        $string131 = "335628fdb196d750906961db6ce9ec4c35fb7c16f6883c441c6c620468e273c1" nocase ascii wide
                        $string132 = "35678541d1d3a394875f58f3add9b097f445dc15de0a720318da1db4d1de06e8" nocase ascii wide
                        $string133 = "63dcdf6e5eb8252ec73b58bde6249db9d38272dc6870074d2569f7431a1ab32f" nocase ascii wide
                        $string134 = "6b6aede14ee7f52374cf3fbc5d790afa32f23dc0791514ce26306514e4a22ee4" nocase ascii wide
                        $string135 = "7c6f4b0023b62103aa803d4ddfe2736ed80f2911f7556ef16abc3be04674697b" nocase ascii wide
                        $string136 = "aa3939fc357723135870d5036b12a67097b03309" nocase ascii wide
                        $string137 = "b501b1a7f5d1ca09fa28d4c2d9e839a5d7e8a9f336d3698c947cac13b02a599a" nocase ascii wide
                        $string138 = "bcfe13901d4207db340d957052cd5175e24481a5e2c5fc15d119fadedc664755" nocase ascii wide
                        $string139 = /bypassuac_registry\./ nocase ascii wide
                        $string140 = /bypassuac_token_imp\./ nocase ascii wide
                        $string141 = "c439db633c51838ba79ec999e0f5b4533379b94d2afeb5944fd15250fa5a86de" nocase ascii wide
                        $string142 = /cachedump\.py\s\// nocase ascii wide
                        $string143 = "ce70b1200ce76360dec6129189daa260779901d01f150868c9f19ec6cea77b36" nocase ascii wide
                        $string144 = /Collect\ssecurity\stokens\sfrom\spipe\sserver\s\(\\\\\\\\\.\\\\pipe\\\\catcher\)/ nocase ascii wide
                        $string145 = "compress_encode_obfs" nocase ascii wide
                        $string146 = "ConvertFrom-UACValue" nocase ascii wide
                        $string147 = /create\-workspace\.py\s\-E\sdocker\s\-P.{0,100}\/pupyws/ nocase ascii wide
                        $string148 = /creddump\.py/ nocase ascii wide
                        $string149 = "d02161cdc91cdee273f8b6e47f98a322756847ae3b5f4efe6d439fa5e13f9039" nocase ascii wide
                        $string150 = "dotnet_serve_payload" nocase ascii wide
                        $string151 = "eb6a95c5c92ae3923ae07b80feac9e215f68eaff1289303063fa575a92c27967" nocase ascii wide
                        $string152 = "eb87d686b9a040238e563add68fb05c2776f52332c4798cae372638af3c7fca0" nocase ascii wide
                        $string153 = /echo\:iex\(\[System\.Text\.Encoding\]\:\:ASCII\.GetString\(/ nocase ascii wide
                        $string154 = "exploit_suggester  " nocase ascii wide
                        $string155 = /exploit_suggester\.py/ nocase ascii wide
                        $string156 = "exposed_get_password" nocase ascii wide
                        $string157 = "fa7eba4a7edb75f644eace116b7072d9edddfa0af672bd99091d9035b974ba21" nocase ascii wide
                        $string158 = "Find-GPOComputerAdmin" nocase ascii wide
                        $string159 = "Find-InterestingFile" nocase ascii wide
                        $string160 = "Find-LocalAdminAccess" nocase ascii wide
                        $string161 = "Find-LocalAdminAccess" nocase ascii wide
                        $string162 = "gen -f py bind --port" nocase ascii wide
                        $string163 = "gen -f py_oneliner connect " nocase ascii wide
                        $string164 = "generate_loader_cmd" nocase ascii wide
                        $string165 = "generateInjectBinFile" nocase ascii wide
                        $string166 = "Get-ExploitableSystem" nocase ascii wide
                        $string167 = /Get\-ExploitableSystem\./ nocase ascii wide
                        $string168 = "import PupyConfig" nocase ascii wide
                        $string169 = "Import-DllImports -PEInfo " nocase ascii wide
                        $string170 = "Import-DllInRemoteProcess" nocase ascii wide
                        $string171 = "Invoke-ACLScanner" nocase ascii wide
                        $string172 = "Invoke-DowngradeAccount" nocase ascii wide
                        $string173 = "Invoke-EnumerateLocalAdmin" nocase ascii wide
                        $string174 = "Invoke-EnumerateLocalAdmin" nocase ascii wide
                        $string175 = "Invoke-EnumerateLocalAdmin" nocase ascii wide
                        $string176 = "Invoke-EventHunter" nocase ascii wide
                        $string177 = "Invoke-FileFinder" nocase ascii wide
                        $string178 = "Invoke-ProcessHunter" nocase ascii wide
                        $string179 = "Invoke-ReflectivePEInjection" nocase ascii wide
                        $string180 = "Invoke-ReflectivePEInjection" nocase ascii wide
                        $string181 = /Invoke\-ReflectivePEInjection\./ nocase ascii wide
                        $string182 = "Invoke-ShareFinder" nocase ascii wide
                        $string183 = "Invoke-StealthUserHunter" nocase ascii wide
                        $string184 = "Invoke-StealthUserHunter" nocase ascii wide
                        $string185 = "Invoke-UserHunter" nocase ascii wide
                        $string186 = /loot_memory\.py/ nocase ascii wide
                        $string187 = /nbnsspoof\.py/ nocase ascii wide
                        $string188 = "New-GPOImmediateTask" nocase ascii wide
                        $string189 = "pack_py_payload" nocase ascii wide
                        $string190 = "privesc_checker" nocase ascii wide
                        $string191 = /privesc_checker\.py/ nocase ascii wide
                        $string192 = /privesc_checker\.py/ nocase ascii wide
                        $string193 = /pupwinutils\.shellcode/ nocase ascii wide
                        $string194 = /pupy.{0,100}\/checkvm\.py/ nocase ascii wide
                        $string195 = "pupy/external/Inveigh" nocase ascii wide
                        $string196 = "pupy/external/LaZagne" nocase ascii wide
                        $string197 = "pupy/external/linux-exploit-suggester"
                        $string198 = "pupy/external/mimipy" nocase ascii wide
                        $string199 = "pupy/external/pyopus" nocase ascii wide
                        $string200 = "pupy/external/pywerview" nocase ascii wide
                        $string201 = "pupy/external/winpty" nocase ascii wide
                        $string202 = "pupy/external/WinPwnage" nocase ascii wide
                        $string203 = "pupy/payload_" nocase ascii wide
                        $string204 = "pupy/pupy/external/BeRoot" nocase ascii wide
                        $string205 = "PupyCmdLoop" nocase ascii wide
                        $string206 = /PupyCredentials\.py/ nocase ascii wide
                        $string207 = /PupyDnsCnc\.py/ nocase ascii wide
                        $string208 = "PupyDnsCommandServerHandler" nocase ascii wide
                        $string209 = /pupygen\.py\s/ nocase ascii wide
                        $string210 = "PupyKCPSocketStream" nocase ascii wide
                        $string211 = /pupylib\.payloads\.ps1/ nocase ascii wide
                        $string212 = /PupyLoaderTemplate\./ nocase ascii wide
                        $string213 = "PupyOffloadDNS" nocase ascii wide
                        $string214 = "PupyOffloadSocket" nocase ascii wide
                        $string215 = /PupySocketStream\.py/ nocase ascii wide
                        $string216 = /PupyVirtualStream\.py/ nocase ascii wide
                        $string217 = "pyexec -c " nocase ascii wide
                        $string218 = "pyexec --file" nocase ascii wide
                        $string219 = /ReflectiveDllInjection\./ nocase ascii wide
                        $string220 = /ReflectiveLoader\.c/ nocase ascii wide
                        $string221 = /ReflectiveLoader\.h/ nocase ascii wide
                        $string222 = "registry_hijacking_eventvwr" nocase ascii wide
                        $string223 = "registry_hijacking_fodhelper" nocase ascii wide
                        $string224 = /rubber_ducky\.py/ nocase ascii wide
                        $string225 = /run\s.{0,100}\spyshell/ nocase ascii wide
                        $string226 = "run android_cam " nocase ascii wide
                        $string227 = "run --bg shell_exec" nocase ascii wide
                        $string228 = "run interactive_shell" nocase ascii wide
                        $string229 = "run keylogger" nocase ascii wide
                        $string230 = /run\smemory_exec\s.{0,100}\./ nocase ascii wide
                        $string231 = "run mouselogger" nocase ascii wide
                        $string232 = "run pyexec " nocase ascii wide
                        $string233 = "run shell_exec " nocase ascii wide
                        $string234 = "run shellcode_exec" nocase ascii wide
                        $string235 = "send_ps1_payload" nocase ascii wide
                        $string236 = "serve_ps1_payload" nocase ascii wide
                        $string237 = /shellcode_exec\.py/ nocase ascii wide
                        $string238 = "smbspider " nocase ascii wide
                        $string239 = "start_nbnsspoof" nocase ascii wide
                        $string240 = "webcamsnap -v" nocase ascii wide
                        $string241 = /winpwnage\.functions/ nocase ascii wide
        $metadata_regex_import = /\bimport\s+[a-zA-Z0-9_.]+\b/ nocase
        $metadata_regex_function = /function\s+[a-zA-Z_][a-zA-Z0-9_]*\(/ nocase ascii
        $metadata_regex_php = /<\?php/ nocase ascii
        $metadata_regex_createobject = /(CreateObject|WScript\.)/ nocase ascii
        $metadata_regex_script = /<script\b/ nocase ascii
        $metadata_regex_javascript = /(let\s|const\s|function\s|document\.|console\.)/ nocase ascii
        $metadata_regex_powershell = /(Write-Host|Get-[a-zA-Z]+|Invoke-|param\(|\.SYNOPSIS)/ nocase ascii
        $metadata_regex_batch = /@(echo\s|call\s|set\s|goto\s|if\s|for\s|rem\s)/ nocase ascii
        $metadata_regex_shebang = /^#!\// nocase ascii

    condition:
        ((filesize < 20MB and (
            uint16(0) == 0x5a4d or             uint16(0) == 0x457f or             uint32be(0) == 0x7f454c46 or uint16(0) == 0xfeca or uint16(0) == 0xfacf or uint32(0) == 0xbebafeca or             uint32(0) == 0x504B0304 or             uint32(0) == 0xCAFEBABE or             uint32(0) == 0x4D534346 or             uint32(0) == 0xD0CF11E0 or             uint16(0) == 0x2321 or             uint16(0) == 0x3c3f         )) and 2 of ($string*)) or
        (filesize < 2MB and
        (
            2 of ($string*) and
            for any of ($metadata_regex_*) : ( @ <= 20000 )
        ))
}