rule MALPEDIA_Win_Flowershop_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "8ec68082-5d4c-584e-ad88-66456b2a097b"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.flowershop"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.flowershop_auto.yar#L1-L134"
    license_url        = "N/A"
    logic_hash         = "f019e2c8acff91329c227db3e65589276d7267039537efb349a1a4ca0b28047b"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0 = { 0f 85 7d 03 00 00 e9 ?? ?? ?? ?? 83 25 ?? ?? ?? ?? 00 8b 15 ?? ?? ?? ?? 85 d2 76 0b 8b ca }
    $sequence_1 = { ff 75 0c ff 15 ?? ?? ?? ?? 8b f0 d1 e6 0f b7 c6 50 8d 47 0a }
    $sequence_2 = { 33 f6 85 c0 76 1e bb ?? ?? ?? ?? 53 57 e8 ?? ?? ?? ?? }
    $sequence_3 = { 8b 45 f0 8b 3d ?? ?? ?? ?? 8d b0 08 01 00 00 56 6a 08 ff d7 50 }
    $sequence_4 = { 33 ff 80 24 01 00 21 7d fc 8d 45 0c 50 8d 45 08 50 }
    $sequence_5 = { 85 c0 74 0a 3b 45 14 77 05 6a 01 58 eb 02 }
    $sequence_6 = { c3 89 51 04 c3 56 8b 74 24 08 57 8b 46 04 }
    $sequence_7 = { e8 ?? ?? ?? ?? 33 c0 eb 7b 6a 01 5e 83 7c 24 10 05 7c 5e }
    $sequence_8 = { 33 c0 5f 2b d1 c7 45 08 24 00 00 00 3b 7d 0c 77 12 8b 5c 0a fc }
    $sequence_9 = { 33 f6 eb 4b 8b 7d 08 3b 7d fc 74 1c 8d 45 fc 50 }

  condition:
    7 of them and filesize < 829440
}