rule win_hemigate_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.hemigate."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.hemigate"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 85f6 0f8597000000 8bd3 8d4ddc e8???????? 8bf0 85f6 }
                                                                                                
        $sequence_1 = { c1e208 0bd1 0fb64f06 3155a8 0fb65707 c1e208 0bd1 }
                                                                                                
        $sequence_2 = { c3 ff75f4 ff36 ff15???????? 8bf0 83c408 85f6 }
                                                                                                
        $sequence_3 = { 8b550c 8d45d4 50 8d8fa8000000 e8???????? 8b55cc 8d8fb8110100 }
                                                                                                
        $sequence_4 = { 83f801 0f85b8000000 ffb55cf7ffff ffd3 0fb7c0 8d9554f7ffff 6a02 }
                                                                                                
        $sequence_5 = { c1c919 33c8 8b75ec 8bc7 8b7de8 c1c806 33c8 }
                                                                                                
        $sequence_6 = { c1e903 f7e1 56 c1ea03 33f6 8d0492 03c0 }
                                                                                                
        $sequence_7 = { eb48 b840000000 8bfb 2bc1 3bd8 0f43f8 8d462c }
                                                                                                
        $sequence_8 = { 0f84a4f4ffff 8b45c8 0345c4 53 50 51 e8???????? }
                                                                                                
        $sequence_9 = { 8d742418 8bf8 f3a5 8143080c020000 e9???????? 8d4c2418 51 }
                                                                                                
    condition:
        7 of them and filesize < 991232
}