rule MALPEDIA_Win_7Ev3N_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "cf231267-d18f-5fab-bbdf-ab3bf00ba51c"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.7ev3n"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.7ev3n_auto.yar#L1-L130"
    license_url        = "N/A"
    logic_hash         = "3d3793244c4ff8a9f87ce7ce50051977c17fdc03ef0f8a315973a688f14f4ceb"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0 = { 8d 8d d0 cd ff ff e8 ?? ?? ?? ?? 8b ce 2b cf 3b c1 0f 84 02 b1 00 00 }
    $sequence_1 = { 8b d4 89 a5 0c f9 ff ff c7 42 14 07 00 00 00 c7 42 10 00 00 00 00 66 89 02 66 39 85 60 ff ff ff 75 04 }
    $sequence_2 = { 89 41 04 a0 ?? ?? ?? ?? 88 41 08 6a 00 8d 85 04 ff ff ff 50 }
    $sequence_3 = { c7 85 e4 fd ff ff 00 00 00 00 6a 00 c7 85 e0 fd ff ff d0 a5 45 00 ff 15 ?? ?? ?? ?? 33 c0 c7 05 ?? ?? ?? ?? 07 00 00 00 }
    $sequence_4 = { 8d 85 ac ef ff ff 50 8d 8d d0 cd ff ff e8 ?? ?? ?? ?? 8b ce 2b cf }
    $sequence_5 = { 6a 00 8d 85 fc fe ff ff 50 8d 8d d0 cd ff ff e8 ?? ?? ?? ?? 8b ce 2b cb }
    $sequence_6 = { 8d bd 38 f1 ff ff 8d 4f 02 0f 1f 84 00 00 00 00 00 66 8b 07 83 c7 02 66 85 c0 75 f5 }
    $sequence_7 = { 8b 0c 8d 20 93 45 00 80 64 31 28 fd 5f 5e 8b e5 5d c3 }
    $sequence_8 = { f3 0f 7e 05 ?? ?? ?? ?? 66 0f d6 85 64 e6 ff ff 0f b7 05 ?? ?? ?? ?? 66 89 85 6c e6 ff ff f3 0f 7e 05 ?? ?? ?? ?? 66 0f d6 85 58 e6 ff ff 0f b7 05 ?? ?? ?? ?? }
    $sequence_9 = { 0f 84 72 4c 00 00 8d bd a0 dd ff ff 8d 4f 02 0f 1f 84 00 00 00 00 00 66 8b 07 83 c7 02 66 85 c0 }

  condition:
    7 of them and filesize < 803840
}