rule win_misha_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.misha."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.misha"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 0d19000200 50 8b4318 0508010000 50 }
                                                                        
        $sequence_1 = { 6a08 59 8bc3 c1e310 0bc3 6a18 8bfa }
                                                                                                
        $sequence_2 = { ff75c8 8b4314 83c070 50 8b8578ffffff 48 48 }
                                                                                                
        $sequence_3 = { 50 8b4314 05d8000000 50 ff75ec 8b7308 }
                                                                                    
        $sequence_4 = { 50 8b4318 0508020000 50 ff730c e8???????? }
                                                                                    
        $sequence_5 = { 8945e8 8b4510 8b00 8945e4 8d45fc }
                                                                        
        $sequence_6 = { c78550feffff18181818 c78554feffff18181818 c78558feffff18181819 c7855cfeffff19191919 c78560feffff19191919 c78564feffff19191919 c78568feffff19191919 }
                                                                                                
        $sequence_7 = { 6a00 e8???????? 83c40c 8b45f4 8a4d0c 884818 8b45f4 }
                                                                                                
        $sequence_8 = { 8d85f8f9ffff 50 8d85e0f9ffff e8???????? 83c40c 0fb6c0 }
                                                                                    
        $sequence_9 = { 8d8568ffffff 50 6a01 6a02 8b4314 83c008 50 }
                                                                                                
    condition:
        7 of them and filesize < 710656
}