rule win_wormhole_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.wormhole."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.wormhole"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 56 e8???????? 83c408 8d542410 6aff 6a01 52 }
                                                                                                
        $sequence_1 = { 0f85c1000000 8b15???????? 8d4c2408 51 52 }
                                                                        
        $sequence_2 = { 6a00 6a00 ffd3 8b1d???????? 6aff 8d4c2414 6a00 }
                                                                                                
        $sequence_3 = { a1???????? 85c0 7531 8b35???????? e8???????? 85c0 7519 }
                                                                                                
        $sequence_4 = { 897c2438 8974243c ffd3 6a00 6a00 89442418 }
                                                                                    
        $sequence_5 = { 6a00 6a00 ff15???????? 85c0 a3???????? 7404 }
                                                                                    
        $sequence_6 = { 6a00 52 68???????? 6a00 6a00 89742430 }
                                                                                    
        $sequence_7 = { 6685c0 743f a1???????? 85c0 7531 }
                                                                        
        $sequence_8 = { 68c8000000 6a00 56 e8???????? 83c410 83f8ff }
                                                                                    
        $sequence_9 = { 6a01 52 6a02 ffd3 8b35???????? }
                                                                        
    condition:
        7 of them and filesize < 99576
}