rule win_sys10_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.sys10."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.sys10"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 50 ffd7 8b4b08 51 }
                                                            
        $sequence_1 = { 7511 6810270000 ff15???????? 33c0 }
                                                            
        $sequence_2 = { ffd3 6a00 6a00 6a00 6a00 8bf8 }
                                                                                    
        $sequence_3 = { 7407 53 ff15???????? 8b06 50 }
                                                                        
        $sequence_4 = { 53 52 e8???????? 83c42c 85c0 }
                                                                        
        $sequence_5 = { ffd7 8b4304 50 ffd7 8b4b08 51 }
                                                                                    
        $sequence_6 = { 52 ffd7 8b4308 50 }
                                                            
        $sequence_7 = { 57 8d542438 53 52 e8???????? }
                                                                        
        $sequence_8 = { 6a00 897c2434 894c242c 89742438 }
                                                            
        $sequence_9 = { 52 6a05 50 ffd6 8b5308 }
                                                                        
    condition:
        7 of them and filesize < 286720
}