rule MALPEDIA_Win_Deadwood_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "5f00cc5a-9602-50e1-9261-d675303486e9"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.deadwood"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.deadwood_auto.yar#L1-L134"
    license_url        = "N/A"
    logic_hash         = "ea97d4cccc4d6a9b5e482bbc380fcc6fbef419bedaf1f051b13240e62ed24277"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0 = { 51 e8 ?? ?? ?? ?? 83 c4 04 33 db be 0f 00 00 00 89 b4 24 18 01 00 00 89 9c 24 14 01 00 00 }
    $sequence_1 = { 73 03 8d 45 08 8b 55 18 52 50 8b 41 10 50 }
    $sequence_2 = { 74 64 8b f0 8b 48 14 89 4c 24 24 3b cb 75 04 89 5c 24 28 }
    $sequence_3 = { 6a 01 8d 44 24 14 50 8d 4c 24 3c 89 7c 24 7c c7 44 24 18 78 f4 45 00 e8 ?? ?? ?? ?? }
    $sequence_4 = { 8b f8 85 ff 0f 84 84 00 00 00 53 53 53 53 }
    $sequence_5 = { ff 15 ?? ?? ?? ?? 68 04 01 00 00 8d 8d f4 fd ff ff 51 50 ff 15 ?? ?? ?? ?? 33 d2 }
    $sequence_6 = { e8 ?? ?? ?? ?? 8b 54 24 60 c7 44 24 40 e4 ba 45 00 bb ?? ?? ?? ?? 89 5c 24 54 8b 42 04 c7 44 04 60 c8 ba 45 00 }
    $sequence_7 = { 8b 07 8b 48 04 83 7c 39 0c 00 0f 94 c1 88 4d d8 c7 45 fc 01 00 00 00 84 c9 }
    $sequence_8 = { 74 ed 89 45 0c 8b 13 80 7a 1d 00 74 04 8b 3e eb 13 }
    $sequence_9 = { 8b b5 10 ff ff ff e9 ?? ?? ?? ?? c3 8d 8d 34 ff ff ff e9 ?? ?? ?? ?? 8d 8d 18 ff ff ff e9 ?? ?? ?? ?? }

  condition:
    7 of them and filesize < 1055744
}