rule ldap_md5_hashed_default_creds_netgear
{
    meta:
        version = "1.0"
        status = "RELEASED"
        sharing = "TLP:WHITE"
        source = "NDAAL GESELLSCHAFT FÜR SICHERHEIT INDER INFORMATIONSTECHNIK MBH & CO KG"
        author = "Alaa Jubakhanji@ndaal Gesellschaft fürSicherheit in der Informationstechnik mbH & Co KG"
        description = "Hashed values of default credentials for netgear."
        category = "INFO"
        info = "LDAP_MD5"
        reference = "https://gitlab.com/ndaal_open_source/ndaal_yara_passwords_default/-/tree/main/yara_rules"

strings:
    $a0="{MD5}X03MO1qnZdYdgyfeuILPmQ=="
    $a1="{MD5}ISMvKXpXpadDiUoOSoAfww=="
    $a2="{MD5}gdyb21LQTcIANtvYMT7QVQ=="
    $a3="{MD5}2LWPe/ziju/MHN1blcO2Yw=="
    $a4="{MD5}lH8BMxqw2xsIak/JHnvakw=="
    $a5="{MD5}JXwtGgQjpqfBCGMqj5Y5Mg=="
    $a6="{MD5}gdyb21LQTcIANtvYMT7QVQ=="
    $a7="{MD5}ISMvKXpXpadDiUoOSoAfww=="
    $a8="{MD5}geX4Hbd8WWSS5vGlp5LtUw=="
    $a9="{MD5}ISMvKXpXpadDiUoOSoAfww=="
    $a10="{MD5}ISMvKXpXpadDiUoOSoAfww=="
    $a11="{MD5}ISMvKXpXpadDiUoOSoAfww=="
    $a12="{MD5}gdyb21LQTcIANtvYMT7QVQ=="
    $a13="{MD5}46/tAEewgFnQ+toQ9ADB5Q=="
    $a14="{MD5}sLCghXSLW1Ryjfi2QhDw2Q=="
    $a15="{MD5}ISMvKXpXpadDiUoOSoAfww=="
    $a16="{MD5}ADJLI/Wf7HK2zailPqNDvw=="
    $a17="{MD5}ISMvKXpXpadDiUoOSoAfww=="
    $a18="{MD5}TeEX8KoS8PauScxZRafAKQ=="
    $a19="{MD5}GzIxZVzrt6H3g+3fJ9JUyg=="
    $a20="{MD5}GTBiZ+vhDUwS+fqY4iFfog=="
    $a21="{MD5}hNlhVoplBzo7zw6yFrKldg=="
    $a22="{MD5}nif5osQfxW6SN5ap5tlroQ=="
    $a23="{MD5}ISMvKXpXpadDiUoOSoAfww=="
    $a24="{MD5}OrJ7hMwwln3w6/sVUe/Iyg=="
    $a25="{MD5}rRbAHUtvTDkyFYSjJPENGQ=="
    $a26="{MD5}3GR+tl5nEeFVN1IYISs5ZA=="
    $a27="{MD5}ISMvKXpXpadDiUoOSoAfww=="
    $a28="{MD5}X03MO1qnZdYdgyfeuILPmQ=="
    $a29="{MD5}46/tAEewgFnQ+toQ9ADB5Q=="
    $a30="{MD5}oPhIlCzoY89TwPpsxoQAfQ=="
    $a31="{MD5}ISMvKXpXpadDiUoOSoAfww=="
condition:
    ($a0 and $a1) or ($a2 and $a3) or ($a4 and $a5) or ($a6 and $a7) or ($a8 and $a9) or ($a10 and $a11) or ($a12 and $a13) or ($a14 and $a15) or ($a16 and $a17) or ($a18 and $a19) or ($a20 and $a21) or ($a22 and $a23) or ($a24 and $a25) or ($a26 and $a27) or ($a28 and $a29) or ($a30 and $a31)
}