rule MALPEDIA_Win_Simplefilemover_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "21ae03b9-45c9-58fd-b17b-9f1c4dcf7bf7"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.simplefilemover"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.simplefilemover_auto.yar#L1-L219"
    license_url        = "N/A"
    logic_hash         = "81c6919dbb4aaa2e054461ca67f688251b4ccec2baef13a001955aba375181dd"
    score              = 75
    quality            = 73
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0  = { 8b fc f3 a5 e8 ?? ?? ?? ?? 81 c4 20 02 00 00 }
    $sequence_1  = { 33 c0 e9 ?? ?? ?? ?? 68 20 02 00 00 ff 15 ?? ?? ?? ?? }
    $sequence_2  = { 81 c4 20 02 00 00 85 c0 74 07 68 ?? ?? ?? ?? eb 05 68 ?? ?? ?? ?? ff 15 ?? ?? ?? ?? }
    $sequence_3  = { b9 88 00 00 00 8b f3 8b fc f3 a5 }
    $sequence_4  = { 33 ff 88 4c 24 08 3b f7 88 54 24 24 89 7c 24 10 }
    $sequence_5  = { 75 03 8b fa 46 66 8b 41 02 83 c1 02 42 }
    $sequence_6  = { 8b 8d 54 fa ff ff 51 ff 15 ?? ?? ?? ?? 6a 00 68 00 20 00 00 8d 95 54 da ff ff }
    $sequence_7  = { 8b 85 54 fa ff ff 50 ff 15 ?? ?? ?? ?? 85 c0 }
    $sequence_8  = { 8b 74 24 1c 57 8a 88 00 01 00 00 8a 90 01 01 00 00 33 ff }
    $sequence_9  = { eb c2 eb c0 eb be eb bc eb ba eb b8 }
    $sequence_10 = { e8 ?? ?? ?? ?? 81 c4 20 02 00 00 85 c0 74 10 68 ?? ?? ?? ?? ff 15 ?? ?? ?? ?? }
    $sequence_11 = { 8b 4c 24 14 8d 44 7b 02 50 51 }
    $sequence_12 = { 5f 88 90 00 01 00 00 88 88 01 01 00 00 5e 83 c4 10 c3 }
    $sequence_13 = { e9 ?? ?? ?? ?? 80 7d 08 67 0f 84 8f 02 00 00 80 7d 08 70 0f 85 13 04 00 00 }
    $sequence_14 = { 83 bd 08 da ff ff ff 74 09 83 bd 08 da ff ff 00 75 0f c7 85 08 da ff ff 00 00 00 00 e9 ?? ?? ?? ?? 6a 04 }
    $sequence_15 = { 47 89 7c 24 18 0f bf ff 3b fb 0f 8c 54 ff ff ff 8a 4c 24 2c }
    $sequence_16 = { 6a 64 ff 15 ?? ?? ?? ?? ff 4d e0 39 5d e0 7f d4 }
    $sequence_17 = { 52 8d 85 5c fa ff ff 50 8d 8d 60 da ff ff 51 }
    $sequence_18 = { 8d 85 b0 dd ff ff 50 e8 ?? ?? ?? ?? 8d 45 dc 57 50 8b 45 f4 }
    $sequence_19 = { 50 ff 76 10 6a 00 6a 00 ff d7 ff 75 08 8d 43 02 }
    $sequence_20 = { 8b 4c 24 08 8b 74 24 24 53 81 e1 ff 00 00 00 }
    $sequence_21 = { 53 52 ff 15 ?? ?? ?? ?? 83 c4 08 5f 5e }

  condition:
    7 of them and filesize < 57344
}