rule MALPEDIA_Win_Rook_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "18a58274-365f-5d90-8056-28a56db76f76"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.rook"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.rook_auto.yar#L1-L129"
    license_url        = "N/A"
    logic_hash         = "8b05af9f0d6f5102cdf2e062676438cba9dcdb9d6b25adc560d5025ee81a7b52"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0 = { 48 8d 05 47 8d 02 00 c7 47 08 01 00 00 00 48 c7 47 10 03 00 00 00 48 89 47 48 48 8d 05 c5 9e 02 00 }
    $sequence_1 = { 0f 85 21 ff ff ff 44 88 2b eb 7b 48 8b 95 40 07 00 00 4c 8d 05 97 9e 00 00 49 8b ce }
    $sequence_2 = { 85 c0 0f 85 f5 02 00 00 48 8b 8d 08 08 00 00 48 8d 85 f8 07 00 00 4c 89 a4 24 c0 08 00 00 48 8d 15 ff b9 04 00 }
    $sequence_3 = { ff 15 ?? ?? ?? ?? 48 8b d3 48 8d 0d 82 ac 04 00 44 8b c0 e8 ?? ?? ?? ?? 48 8b 0d ?? ?? ?? ?? 4c 8b c3 }
    $sequence_4 = { 44 33 d0 41 8b c1 48 c1 e8 08 0f b6 c8 41 c1 e2 08 42 0f b6 84 31 70 99 05 00 44 33 d0 }
    $sequence_5 = { 48 8d 85 f8 07 00 00 4c 89 a4 24 c0 08 00 00 48 8d 15 ff b9 04 00 48 89 44 24 28 4c 8d 25 d3 45 05 00 4c 89 ac 24 b8 08 00 00 }
    $sequence_6 = { 48 8d 54 24 60 48 8d 0d 1c 38 05 00 e8 ?? ?? ?? ?? 48 8d 95 10 02 00 00 49 8b cc ff 15 ?? ?? ?? ?? 48 39 bd 10 02 00 00 }
    $sequence_7 = { 48 89 47 60 48 8d 05 35 98 02 00 c7 47 50 01 00 00 00 48 c7 47 58 04 00 00 00 48 89 47 78 48 8d 05 0b 71 03 00 c7 47 68 01 00 00 00 }
    $sequence_8 = { 48 98 4d 8d 34 46 83 ed 01 75 86 48 85 f6 0f 84 d3 00 00 00 48 8b ce }
    $sequence_9 = { 4c 8d 05 f7 14 03 00 48 89 86 b0 00 00 00 48 8d 8e 98 00 00 00 e8 ?? ?? ?? ?? 8b d8 85 c0 0f 85 17 ff ff ff }

  condition:
    7 of them and filesize < 843776
}