rule MALPEDIA_Win_Doppelpaymer_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "f239cfc1-7cb1-5c3d-a2a9-bf2ad44d0856"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.doppelpaymer"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.doppelpaymer_auto.yar#L1-L181"
    license_url        = "N/A"
    logic_hash         = "6c7514bbe70399e920b266dcf23ab956c2fd28d40abc6464ad39f41a291bdfca"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0  = { 80 79 06 00 75 23 80 79 02 64 75 1d }
    $sequence_1  = { 80 79 05 61 75 17 80 79 03 61 75 11 80 79 04 74 }
    $sequence_2  = { e8 ?? ?? ?? ?? 8b 08 e8 ?? ?? ?? ?? 3d b6 38 90 96 }
    $sequence_3  = { 83 ec 28 68 00 00 20 02 6a 00 6a 01 }
    $sequence_4  = { 80 79 02 64 75 1d 80 79 05 61 75 17 }
    $sequence_5  = { ba ff ff ff 7f 43 e8 ?? ?? ?? ?? 3b d8 }
    $sequence_6  = { 8d 8c 24 50 01 00 00 e8 ?? ?? ?? ?? 89 bc 24 5c 01 00 00 8d 44 24 04 }
    $sequence_7  = { e8 ?? ?? ?? ?? 8d 8c 24 24 03 00 00 e8 ?? ?? ?? ?? 6a 10 }
    $sequence_8  = { c2 04 00 8b 4e 44 8b 41 10 5e }
    $sequence_9  = { 89 55 ec e8 ?? ?? ?? ?? 8d 0d 6f 30 2b 00 89 04 24 89 4c 24 04 e8 ?? ?? ?? ?? 8d 0d 34 30 2b 00 }
    $sequence_10 = { 89 0c 24 89 45 c8 e8 ?? ?? ?? ?? 8b 4d e8 89 0c 24 89 45 c4 }
    $sequence_11 = { c3 8b 45 e8 b9 90 54 c8 37 8a 55 f3 80 c2 c9 2b 4d f4 }
    $sequence_12 = { 83 ec 08 8b 45 08 8b 40 54 89 e1 89 41 04 }
    $sequence_13 = { 89 45 c4 74 d0 e9 ?? ?? ?? ?? 31 c0 8b 4d b8 83 c1 04 }
    $sequence_14 = { 5b 5d c3 b8 e2 f4 9a 29 2b 45 ec 8b 4d cc 81 c1 ff ff 00 00 }
    $sequence_15 = { e8 ?? ?? ?? ?? 8b 4d e8 8b 55 d8 89 51 28 8b 75 c4 89 71 14 }
    $sequence_16 = { a1 ?? ?? ?? ?? ff d0 89 45 bc 31 c0 8b 4d e8 83 c1 54 8b 55 e8 }
    $sequence_17 = { c2 04 00 8b 40 0c 8b 48 10 56 8b 70 0c 57 }

  condition:
    7 of them and filesize < 7266304
}