rule win_akdoortea_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.akdoortea."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.akdoortea"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 006118 40 007019 40 00411a }
                                                                        
        $sequence_1 = { 7641 8d85f0feffff 8d5001 0f1f8000000000 8a08 }
                                                                        
        $sequence_2 = { 8d8df0f9ffff 8d5002 e8???????? 8bf0 83c420 85f6 }
                                                                                    
        $sequence_3 = { 8bec 83ec0c 53 8bda 56 8bf1 57 }
                                                                                                
        $sequence_4 = { 50 8b04bdf8204200 ff741818 ff15???????? 85c0 0f95c0 eb02 }
                                                                                                
        $sequence_5 = { 7439 8d56ff 8a4201 8d5201 84c0 75f6 }
                                                                                    
        $sequence_6 = { 90 85f6 740b 83feff 0f859a000000 eb6c 8b1c8d10a24100 }
                                                                                                
        $sequence_7 = { e8???????? 83c414 ebe1 8b55ec 8b4de8 8b0495f8204200 807c082800 }
                                                                                                
        $sequence_8 = { 83c418 c745f803010000 8d45f8 50 8d4304 50 ff15???????? }
                                                                                                
        $sequence_9 = { ffd6 68f4010000 8bf0 ff15???????? 85ff 740e }
                                                                                    
    condition:
        7 of them and filesize < 305152
}