rule rule_RemotePC_greyware_tool_keyword
{
    meta:
        description = "Detection patterns for the tool 'RemotePC' taken from the ThreatHunting-Keywords github project"
        author = "@mthcht"
        reference = "https://github.com/mthcht/ThreatHunting-Keywords"
        tool = "RemotePC"
        rule_category = "greyware_tool_keyword"

    strings:
                        $string1_RemotePC_greyware_tool_keyword = " /f /im RemotePCS" nocase ascii wide
                        $string2_RemotePC_greyware_tool_keyword = " create RPCService start=" nocase ascii wide
                        $string3_RemotePC_greyware_tool_keyword = " create ViewerService start=auto" nocase ascii wide
                        $string4_RemotePC_greyware_tool_keyword = /\s\-i\sremotepc\.deb/ nocase ascii wide
                        $string5_RemotePC_greyware_tool_keyword = /\sRemotePC\.exe/ nocase ascii wide
                        $string6_RemotePC_greyware_tool_keyword = " RemotePCAttendedService " nocase ascii wide
                        $string7_RemotePC_greyware_tool_keyword = /\sremotepclauncher\.exe/ nocase ascii wide
                        $string8_RemotePC_greyware_tool_keyword = /\sremotepcuiu\.exe/ nocase ascii wide
                        $string9_RemotePC_greyware_tool_keyword = /\sRemotePCViewer\.msi/ nocase ascii wide
                        $string10_RemotePC_greyware_tool_keyword = /\srpcdownloader\.exe/ nocase ascii wide
                        $string11_RemotePC_greyware_tool_keyword = /\srpcperfviewer\.exe/ nocase ascii wide
                        $string12_RemotePC_greyware_tool_keyword = /\sRPCWinXP\.exe/ nocase ascii wide
                        $string13_RemotePC_greyware_tool_keyword = "\"RemotePCAttendedService\"" nocase ascii wide
                        $string14_RemotePC_greyware_tool_keyword = /\.remotepc\.com/ nocase ascii wide
                        $string15_RemotePC_greyware_tool_keyword = /\.remotepc\.com/ nocase ascii wide
                        $string16_RemotePC_greyware_tool_keyword = /\/AttendedUDP\.zip/ nocase ascii wide
                        $string17_RemotePC_greyware_tool_keyword = /\/remotepc\.deb/ nocase ascii wide
                        $string18_RemotePC_greyware_tool_keyword = /\/remotepc\.deb/ nocase ascii wide
                        $string19_RemotePC_greyware_tool_keyword = /\/RemotePC\.exe/ nocase ascii wide
                        $string20_RemotePC_greyware_tool_keyword = /\/RemotePC\.exe/ nocase ascii wide
                        $string21_RemotePC_greyware_tool_keyword = /\/RemotePC\.lnk/ nocase ascii wide
                        $string22_RemotePC_greyware_tool_keyword = /\/RemotePC\.tmp/ nocase ascii wide
                        $string23_RemotePC_greyware_tool_keyword = /\/remotepc\-attended\.deb/ nocase ascii wide
                        $string24_RemotePC_greyware_tool_keyword = /\/RemotePCAttended\.dmg/ nocase ascii wide
                        $string25_RemotePC_greyware_tool_keyword = /\/remotepclauncher\.exe/ nocase ascii wide
                        $string26_RemotePC_greyware_tool_keyword = /\/RemotePCSuite\.dmg/ nocase ascii wide
                        $string27_RemotePC_greyware_tool_keyword = /\/remotepcuiu\.exe/ nocase ascii wide
                        $string28_RemotePC_greyware_tool_keyword = /\/RemotePCViewer\.msi/ nocase ascii wide
                        $string29_RemotePC_greyware_tool_keyword = /\/RpcDND_Console\.exe/ nocase ascii wide
                        $string30_RemotePC_greyware_tool_keyword = /\/rpcdownloader\.exe/ nocase ascii wide
                        $string31_RemotePC_greyware_tool_keyword = /\/RPCFireWallRule\.exe/ nocase ascii wide
                        $string32_RemotePC_greyware_tool_keyword = /\/rpcperfviewer\.exe/ nocase ascii wide
                        $string33_RemotePC_greyware_tool_keyword = /\/RPCProxyLatency\.exe/ nocase ascii wide
                        $string34_RemotePC_greyware_tool_keyword = /\/viewerhostkeypopup\.exe/ nocase ascii wide
                        $string35_RemotePC_greyware_tool_keyword = /\\AttendedServiceRemove\.exe/ nocase ascii wide
                        $string36_RemotePC_greyware_tool_keyword = /\\AttendedUDP\.zip/ nocase ascii wide
                        $string37_RemotePC_greyware_tool_keyword = /\\BSUtility\.exe/ nocase ascii wide
                        $string38_RemotePC_greyware_tool_keyword = /\\Control\\Print\\Monitors\\REMOTEPCPRINTER/ nocase ascii wide
                        $string39_RemotePC_greyware_tool_keyword = /\\CurrentVersion\\App\sPaths\\RemotePCPerformance/ nocase ascii wide
                        $string40_RemotePC_greyware_tool_keyword = /\\CurrentVersion\\Devices\\RemotePC\sPrinter/ nocase ascii wide
                        $string41_RemotePC_greyware_tool_keyword = /\\InventoryApplicationFile\\rpcattendedadmin/ nocase ascii wide
                        $string42_RemotePC_greyware_tool_keyword = /\\Print\\Printers\\RemotePC\sPrinter\\/ nocase ascii wide
                        $string43_RemotePC_greyware_tool_keyword = /\\Program\sFiles\s\(x86\)\\RemotePC\\/ nocase ascii wide
                        $string44_RemotePC_greyware_tool_keyword = /\\program\sfiles\s\(x86\)\\remotepc\\remotepcperformance\\/ nocase ascii wide
                        $string45_RemotePC_greyware_tool_keyword = /\\ProgramData\\RemotePC/ nocase ascii wide
                        $string46_RemotePC_greyware_tool_keyword = /\\RemotePC\s\(1\)\.exe/ nocase ascii wide
                        $string47_RemotePC_greyware_tool_keyword = /\\RemotePC\sAttended\.lnk/ nocase ascii wide
                        $string48_RemotePC_greyware_tool_keyword = /\\RemotePC\sAttended\\/ nocase ascii wide
                        $string49_RemotePC_greyware_tool_keyword = /\\RemotePC\sPerformance\sHost\\/ nocase ascii wide
                        $string50_RemotePC_greyware_tool_keyword = /\\RemotePC\.Common\.dll/ nocase ascii wide
                        $string51_RemotePC_greyware_tool_keyword = /\\RemotePC\.exe/ nocase ascii wide
                        $string52_RemotePC_greyware_tool_keyword = /\\RemotePC\.exe/ nocase ascii wide
                        $string53_RemotePC_greyware_tool_keyword = /\\RemotePC\.lnk/ nocase ascii wide
                        $string54_RemotePC_greyware_tool_keyword = /\\RemotePC\.tmp/ nocase ascii wide
                        $string55_RemotePC_greyware_tool_keyword = /\\RemotePC\.tmp/ nocase ascii wide
                        $string56_RemotePC_greyware_tool_keyword = /\\RemotePC\\.{0,1000}\.dll/ nocase ascii wide
                        $string57_RemotePC_greyware_tool_keyword = /\\RemotePCAttended\.dmg/ nocase ascii wide
                        $string58_RemotePC_greyware_tool_keyword = /\\RemotePCCopyPaste\.txt/ nocase ascii wide
                        $string59_RemotePC_greyware_tool_keyword = /\\RemotePCDDriver\.cat/ nocase ascii wide
                        $string60_RemotePC_greyware_tool_keyword = /\\RemotePCDDriver\.inf/ nocase ascii wide
                        $string61_RemotePC_greyware_tool_keyword = /\\RemotePCDDriverumode1_0\.dll/ nocase ascii wide
                        $string62_RemotePC_greyware_tool_keyword = /\\RemotePCDDriverumode1_2\.dll/ nocase ascii wide
                        $string63_RemotePC_greyware_tool_keyword = /\\RemotePCDesktop\.txt/ nocase ascii wide
                        $string64_RemotePC_greyware_tool_keyword = /\\RemotePCDnD\.dll/ nocase ascii wide
                        $string65_RemotePC_greyware_tool_keyword = /\\RemotePCDnDLauncher\.exe/ nocase ascii wide
                        $string66_RemotePC_greyware_tool_keyword = /\\RemotePCHDDesktop\.txt/ nocase ascii wide
                        $string67_RemotePC_greyware_tool_keyword = /\\RemotePCHDService\.txt/ nocase ascii wide
                        $string68_RemotePC_greyware_tool_keyword = /\\remotepclauncher\.exe/ nocase ascii wide
                        $string69_RemotePC_greyware_tool_keyword = /\\RemotePCModules\.log/ nocase ascii wide
                        $string70_RemotePC_greyware_tool_keyword = /\\RemotePCPDF\.conf/ nocase ascii wide
                        $string71_RemotePC_greyware_tool_keyword = /\\RemotePCPerformancePlugins\.exe/ nocase ascii wide
                        $string72_RemotePC_greyware_tool_keyword = /\\RemotePCPrinter\.exe/ nocase ascii wide
                        $string73_RemotePC_greyware_tool_keyword = /\\RemotePCPrinter\.exe\.config/ nocase ascii wide
                        $string74_RemotePC_greyware_tool_keyword = /\\RemotePCPrinter\.pdb/ nocase ascii wide
                        $string75_RemotePC_greyware_tool_keyword = /\\RemotePCPrinterCore\.dll/ nocase ascii wide
                        $string76_RemotePC_greyware_tool_keyword = /\\RemotePCPrinterCore\.pdb/ nocase ascii wide
                        $string77_RemotePC_greyware_tool_keyword = /\\RemotePCProxys\.dat/ nocase ascii wide
                        $string78_RemotePC_greyware_tool_keyword = /\\RemotePCPS5UI\.DLL/ nocase ascii wide
                        $string79_RemotePC_greyware_tool_keyword = /\\RemotePCPS5UI\.DLL/ nocase ascii wide
                        $string80_RemotePC_greyware_tool_keyword = /\\RemotePCPSCRIPT\./ nocase ascii wide
                        $string81_RemotePC_greyware_tool_keyword = /\\RemotePCPSCRIPT\.HLP/ nocase ascii wide
                        $string82_RemotePC_greyware_tool_keyword = /\\RemotePCPSCRIPT\.NTF/ nocase ascii wide
                        $string83_RemotePC_greyware_tool_keyword = /\\RemotePCPSCRIPT5\.DLL/ nocase ascii wide
                        $string84_RemotePC_greyware_tool_keyword = /\\RemotePCService\.exe/ nocase ascii wide
                        $string85_RemotePC_greyware_tool_keyword = /\\RemotePCService\.txt/ nocase ascii wide
                        $string86_RemotePC_greyware_tool_keyword = /\\RemotePCService_2\.txt/ nocase ascii wide
                        $string87_RemotePC_greyware_tool_keyword = /\\RemotePCSuite\.dmg/ nocase ascii wide
                        $string88_RemotePC_greyware_tool_keyword = /\\RemotePCUDE\.cat/ nocase ascii wide
                        $string89_RemotePC_greyware_tool_keyword = /\\RemotePCUDE\.inf/ nocase ascii wide
                        $string90_RemotePC_greyware_tool_keyword = /\\RemotePCUDE\.sys/ nocase ascii wide
                        $string91_RemotePC_greyware_tool_keyword = /\\RemotePCUDEHost\.cat/ nocase ascii wide
                        $string92_RemotePC_greyware_tool_keyword = /\\RemotePCUDEHost\.inf/ nocase ascii wide
                        $string93_RemotePC_greyware_tool_keyword = /\\RemotePCUDEHost\.sys/ nocase ascii wide
                        $string94_RemotePC_greyware_tool_keyword = /\\RemotePCUIA\.exe/ nocase ascii wide
                        $string95_RemotePC_greyware_tool_keyword = /\\RemotePCUIU\.exe/ nocase ascii wide
                        $string96_RemotePC_greyware_tool_keyword = /\\remotepcuiu\.exe/ nocase ascii wide
                        $string97_RemotePC_greyware_tool_keyword = /\\RemotePCViewer\.msi/ nocase ascii wide
                        $string98_RemotePC_greyware_tool_keyword = /\\RpcAccessPermissionNotifier\.exe/ nocase ascii wide
                        $string99_RemotePC_greyware_tool_keyword = /\\RpcApp\\RPCCodecEngine\.exe/ nocase ascii wide
                        $string100_RemotePC_greyware_tool_keyword = /\\RpcApp\\Tools\\Chat\.exe/ nocase ascii wide
                        $string101_RemotePC_greyware_tool_keyword = /\\RpcApp\\Tools\\TransferServer\.exe/ nocase ascii wide
                        $string102_RemotePC_greyware_tool_keyword = /\\RPCAppLauncherLogFile\.txt/ nocase ascii wide
                        $string103_RemotePC_greyware_tool_keyword = /\\RPCAttended\.log/ nocase ascii wide
                        $string104_RemotePC_greyware_tool_keyword = /\\RPCAttendedAdmin\.exe/ nocase ascii wide
                        $string105_RemotePC_greyware_tool_keyword = /\\RPCCertificate\.log/ nocase ascii wide
                        $string106_RemotePC_greyware_tool_keyword = /\\RPCClipboard\.exe/ nocase ascii wide
                        $string107_RemotePC_greyware_tool_keyword = /\\RPCClipboardAttended\.exe/ nocase ascii wide
                        $string108_RemotePC_greyware_tool_keyword = /\\RPCConfig\.ini/ nocase ascii wide
                        $string109_RemotePC_greyware_tool_keyword = /\\RPCCoreViewer\.exe/ nocase ascii wide
                        $string110_RemotePC_greyware_tool_keyword = /\\RpcDND_Console\.exe/ nocase ascii wide
                        $string111_RemotePC_greyware_tool_keyword = /\\RPCDownloader\.exe/ nocase ascii wide
                        $string112_RemotePC_greyware_tool_keyword = /\\RPCDownloaderLogFile\.txt/ nocase ascii wide
                        $string113_RemotePC_greyware_tool_keyword = /\\RPCDragDrop\.txt/ nocase ascii wide
                        $string114_RemotePC_greyware_tool_keyword = /\\RPCFirewallAttended\.exe/ nocase ascii wide
                        $string115_RemotePC_greyware_tool_keyword = /\\RPCFireWallRule\.exe/ nocase ascii wide
                        $string116_RemotePC_greyware_tool_keyword = /\\RPCFireWallRulelogfile\.txt/ nocase ascii wide
                        $string117_RemotePC_greyware_tool_keyword = /\\RPCKeyMouseHandler\.txt/ nocase ascii wide
                        $string118_RemotePC_greyware_tool_keyword = /\\RPCOTABootstrapper\.exe/ nocase ascii wide
                        $string119_RemotePC_greyware_tool_keyword = /\\RPCOTADesktop\.exe/ nocase ascii wide
                        $string120_RemotePC_greyware_tool_keyword = /\\RPCOTADesktopUAC\.exe/ nocase ascii wide
                        $string121_RemotePC_greyware_tool_keyword = /\\RpcOTADND_Console\.exe/ nocase ascii wide
                        $string122_RemotePC_greyware_tool_keyword = /\\RPCOTAElevator\.exe/ nocase ascii wide
                        $string123_RemotePC_greyware_tool_keyword = /\\RPCOTAFTHost\.exe/ nocase ascii wide
                        $string124_RemotePC_greyware_tool_keyword = /\\RPCOTAKillService\.exe/ nocase ascii wide
                        $string125_RemotePC_greyware_tool_keyword = /\\RPCOTARelauncher\.exe/ nocase ascii wide
                        $string126_RemotePC_greyware_tool_keyword = /\\RPCOTAService\.exe/ nocase ascii wide
                        $string127_RemotePC_greyware_tool_keyword = /\\RPCOTAServiceUAC\.exe/ nocase ascii wide
                        $string128_RemotePC_greyware_tool_keyword = /\\RPCOTAUtilityHost\.exe/ nocase ascii wide
                        $string129_RemotePC_greyware_tool_keyword = /\\RPCOTAViewerHostKeyPopup\.exe/ nocase ascii wide
                        $string130_RemotePC_greyware_tool_keyword = /\\RPCPerformanceService\.exe/ nocase ascii wide
                        $string131_RemotePC_greyware_tool_keyword = /\\RPCPerformanceService\.log/ nocase ascii wide
                        $string132_RemotePC_greyware_tool_keyword = /\\RPCPerfViewer\.exe/ nocase ascii wide
                        $string133_RemotePC_greyware_tool_keyword = /\\rpcperfviewer\.exe/ nocase ascii wide
                        $string134_RemotePC_greyware_tool_keyword = /\\RPCPerfViewer\.log/ nocase ascii wide
                        $string135_RemotePC_greyware_tool_keyword = /\\RPCPing\.txt/ nocase ascii wide
                        $string136_RemotePC_greyware_tool_keyword = /\\RPCPreUninstall\.log/ nocase ascii wide
                        $string137_RemotePC_greyware_tool_keyword = /\\RPCPreUninstall\.log/ nocase ascii wide
                        $string138_RemotePC_greyware_tool_keyword = /\\RPCPrinterDownloader\.exe/ nocase ascii wide
                        $string139_RemotePC_greyware_tool_keyword = /\\RPCPrinterDownloader\.txt/ nocase ascii wide
                        $string140_RemotePC_greyware_tool_keyword = /\\RPCProxyLatency\.exe/ nocase ascii wide
                        $string141_RemotePC_greyware_tool_keyword = /\\RPCProxyLatencyAttended\.exe/ nocase ascii wide
                        $string142_RemotePC_greyware_tool_keyword = /\\RPCSettings\.ini/ nocase ascii wide
                        $string143_RemotePC_greyware_tool_keyword = /\\RpcStickyNotes\.exe/ nocase ascii wide
                        $string144_RemotePC_greyware_tool_keyword = /\\RPCSuite_.{0,1000}_Inc\.log/ nocase ascii wide
                        $string145_RemotePC_greyware_tool_keyword = /\\RPCsuiteLaunch\.txt/ nocase ascii wide
                        $string146_RemotePC_greyware_tool_keyword = /\\Schedule\\TaskCache\\Tree\\RemotePC/ nocase ascii wide
                        $string147_RemotePC_greyware_tool_keyword = /\\Services\\RemotePCAttendedService/ nocase ascii wide
                        $string148_RemotePC_greyware_tool_keyword = /\\Tools\\Ninja\.WebSockets\.dll/ nocase ascii wide
                        $string149_RemotePC_greyware_tool_keyword = /\\Tracing\\RemotePCLauncher_/ nocase ascii wide
                        $string150_RemotePC_greyware_tool_keyword = /\\Tracing\\RemotePCUIU/ nocase ascii wide
                        $string151_RemotePC_greyware_tool_keyword = /\\TransferClient\.exe\.config/ nocase ascii wide
                        $string152_RemotePC_greyware_tool_keyword = /\\TransferServer\.exe\.config/ nocase ascii wide
                        $string153_RemotePC_greyware_tool_keyword = /\\ViewerHostKeyPopup\.exe/ nocase ascii wide
                        $string154_RemotePC_greyware_tool_keyword = /\\ViewerHostKeyPopup\.exe/ nocase ascii wide
                        $string155_RemotePC_greyware_tool_keyword = /\\WOW6432Node\\RemotePC/ nocase ascii wide
                        $string156_RemotePC_greyware_tool_keyword = /AppData\\Local\\Temp\\RemotePC\sAttended/ nocase ascii wide
                        $string157_RemotePC_greyware_tool_keyword = /download\.remotepc\.com/ nocase ascii wide
                        $string158_RemotePC_greyware_tool_keyword = /HKCR\\REMOTEPC/ nocase ascii wide
                        $string159_RemotePC_greyware_tool_keyword = /https\:\/\/login\.remotepc\.com\/rpcnew/ nocase ascii wide
                        $string160_RemotePC_greyware_tool_keyword = /ip\.remotepc\.com/ nocase ascii wide
                        $string161_RemotePC_greyware_tool_keyword = /login\.remotepc\.com/ nocase ascii wide
                        $string162_RemotePC_greyware_tool_keyword = "net start RPCPerformanceService" nocase ascii wide
                        $string163_RemotePC_greyware_tool_keyword = /program\sfiles\s\(x86\)\\remotepc\\/ nocase ascii wide
                        $string164_RemotePC_greyware_tool_keyword = /ProgramData\\RemotePC\sPerformance/ nocase ascii wide
                        $string165_RemotePC_greyware_tool_keyword = /ProgramData\\RemotePC/ nocase ascii wide
                        $string166_RemotePC_greyware_tool_keyword = /RemotePC\s\(1\)\.exe/ nocase ascii wide
                        $string167_RemotePC_greyware_tool_keyword = /RemotePC\sPerformance\sPrinter\.url/ nocase ascii wide
                        $string168_RemotePC_greyware_tool_keyword = /RemotePC.{0,1000}\s\-\sA\snew\scomputer\shas\sbeen\sadded\sto\syour\saccount/ nocase ascii wide
                        $string169_RemotePC_greyware_tool_keyword = /RemotePC\.exe\s/ nocase ascii wide
                        $string170_RemotePC_greyware_tool_keyword = /RemotePC\.WebSockets\.dll/ nocase ascii wide
                        $string171_RemotePC_greyware_tool_keyword = /RemotePC\\REMOTE\~2\.DLL/ nocase ascii wide
                        $string172_RemotePC_greyware_tool_keyword = /RemotePCAttended\.exe/ nocase ascii wide
                        $string173_RemotePC_greyware_tool_keyword = "RemotePCAttendedService" nocase ascii wide
                        $string174_RemotePC_greyware_tool_keyword = /RemotePCBlackScreenApp\.exe/ nocase ascii wide
                        $string175_RemotePC_greyware_tool_keyword = /RemotePCCopyPaste\.txt/ nocase ascii wide
                        $string176_RemotePC_greyware_tool_keyword = /RemotePCDesktop\.exe/ nocase ascii wide
                        $string177_RemotePC_greyware_tool_keyword = /RemotePCDesktop\.txt/ nocase ascii wide
                        $string178_RemotePC_greyware_tool_keyword = /RemotePCHDDesktop\.txt/ nocase ascii wide
                        $string179_RemotePC_greyware_tool_keyword = /RemotePCHDService\.txt/ nocase ascii wide
                        $string180_RemotePC_greyware_tool_keyword = /remotepclauncher\.exe\s/ nocase ascii wide
                        $string181_RemotePC_greyware_tool_keyword = /RemotePCModules\.log/ nocase ascii wide
                        $string182_RemotePC_greyware_tool_keyword = /RemotePCPerformanceWebLauncher\.exe/ nocase ascii wide
                        $string183_RemotePC_greyware_tool_keyword = /RemotePCPerformanceWebLauncher\.log/ nocase ascii wide
                        $string184_RemotePC_greyware_tool_keyword = /RemotePCPrinter\.exe\.config/ nocase ascii wide
                        $string185_RemotePC_greyware_tool_keyword = /RemotePCPrinting\.exe/ nocase ascii wide
                        $string186_RemotePC_greyware_tool_keyword = /RemotePCPrintView\.exe/ nocase ascii wide
                        $string187_RemotePC_greyware_tool_keyword = /RemotePCProxys\.dat/ nocase ascii wide
                        $string188_RemotePC_greyware_tool_keyword = /RemotePCService\.exe/ nocase ascii wide
                        $string189_RemotePC_greyware_tool_keyword = /RemotePCService\.txt/ nocase ascii wide
                        $string190_RemotePC_greyware_tool_keyword = /RemotePCService_2\.txt/ nocase ascii wide
                        $string191_RemotePC_greyware_tool_keyword = /RemotePCShortcut\.exe/ nocase ascii wide
                        $string192_RemotePC_greyware_tool_keyword = /RemotePCSuite\.Model\.dll/ nocase ascii wide
                        $string193_RemotePC_greyware_tool_keyword = /RemotePCSuite\.Service\.dll/ nocase ascii wide
                        $string194_RemotePC_greyware_tool_keyword = /remotepcuiu\.exe\s/ nocase ascii wide
                        $string195_RemotePC_greyware_tool_keyword = /RpcApp.{0,1000}TransferClient\.exe/ nocase ascii wide
                        $string196_RemotePC_greyware_tool_keyword = /RpcApp.{0,1000}TransferServer\.exe/ nocase ascii wide
                        $string197_RemotePC_greyware_tool_keyword = /RpcApp\\Tools\\TransferClient\.exe/ nocase ascii wide
                        $string198_RemotePC_greyware_tool_keyword = /RPCAttendedInstaller\.log/ nocase ascii wide
                        $string199_RemotePC_greyware_tool_keyword = /rpcdownloader\.exe\s/ nocase ascii wide
                        $string200_RemotePC_greyware_tool_keyword = /RPCDownloaderLogFile\.txt/ nocase ascii wide
                        $string201_RemotePC_greyware_tool_keyword = /RPCFireWallRule\.exe/ nocase ascii wide
                        $string202_RemotePC_greyware_tool_keyword = /RPCFireWallRulelogfile\.txt/ nocase ascii wide
                        $string203_RemotePC_greyware_tool_keyword = /RPCKeyMouseHandler\.txt/ nocase ascii wide
                        $string204_RemotePC_greyware_tool_keyword = "RPCPerformanceHealthCheck" nocase ascii wide
                        $string205_RemotePC_greyware_tool_keyword = /rpcperformanceservice\.exe/ nocase ascii wide
                        $string206_RemotePC_greyware_tool_keyword = /RPCPerformanceService\.exe/ nocase ascii wide
                        $string207_RemotePC_greyware_tool_keyword = /rpcperfviewer\.exe\s/ nocase ascii wide
                        $string208_RemotePC_greyware_tool_keyword = /RPCPerfViewer\.log/ nocase ascii wide
                        $string209_RemotePC_greyware_tool_keyword = /rpcprinterdownloader\.exe/ nocase ascii wide
                        $string210_RemotePC_greyware_tool_keyword = /RPCProxyLatency\.exe\s/ nocase ascii wide
                        $string211_RemotePC_greyware_tool_keyword = /RPCsuiteLaunch\.txt/ nocase ascii wide
                        $string212_RemotePC_greyware_tool_keyword = "rule name=\"TransferServer\"" nocase ascii wide
                        $string213_RemotePC_greyware_tool_keyword = "sc  delete \"RPCService\"" nocase ascii wide
                        $string214_RemotePC_greyware_tool_keyword = "sc  start \"RPCService\"" nocase ascii wide
                        $string215_RemotePC_greyware_tool_keyword = "sc  stop \"RPCService\"" nocase ascii wide
                        $string216_RemotePC_greyware_tool_keyword = "sc create RPCService start=auto" nocase ascii wide
                        $string217_RemotePC_greyware_tool_keyword = "sc create RPCService" nocase ascii wide
                        $string218_RemotePC_greyware_tool_keyword = "sc delete \"RPCService\"" nocase ascii wide
                        $string219_RemotePC_greyware_tool_keyword = "sc delete ViewerService" nocase ascii wide
                        $string220_RemotePC_greyware_tool_keyword = "sc start ViewerService" nocase ascii wide
                        $string221_RemotePC_greyware_tool_keyword = "sc stop \"RPCService\"" nocase ascii wide
                        $string222_RemotePC_greyware_tool_keyword = "sc stop ViewerService" nocase ascii wide
                        $string223_RemotePC_greyware_tool_keyword = "StartRPCPerformanceService" nocase ascii wide
                        $string224_RemotePC_greyware_tool_keyword = "StartRPCPerformanceServiceOnStart" nocase ascii wide
                        $string225_RemotePC_greyware_tool_keyword = /static\.remotepc\.com/ nocase ascii wide
                        $string226_RemotePC_greyware_tool_keyword = /Uninstall\sRemotePC\.lnk/ nocase ascii wide
                        $string227_RemotePC_greyware_tool_keyword = /viewerhostkeypopup\.exe\s/ nocase ascii wide
                        $string228_RemotePC_greyware_tool_keyword = /web1\.remotepc\.com/ nocase ascii wide
                        $string229_RemotePC_greyware_tool_keyword = /www1\.remotepc\.com/ nocase ascii wide

    condition:
        any of them
}