rule MALPEDIA_Win_Icondown_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "5fb05a25-c3d8-5c59-95d8-0506e8a3c86e"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.icondown"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.icondown_auto.yar#L1-L123"
    license_url        = "N/A"
    logic_hash         = "0c8c45a1ce9a6284204f7a9a1969d67da5f4271a6aa51c70c6faebd789509deb"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0 = { 89 44 24 20 8b 47 1c d1 ee 52 50 83 e6 01 }
    $sequence_1 = { 5f 5e 5d b8 01 00 00 00 5b c2 04 00 8b 46 1c }
    $sequence_2 = { 3b c5 7c 10 5f 5e 5d b8 fe ff ff ff 5b }
    $sequence_3 = { 8b 46 1c 85 c0 0f 84 76 01 00 00 8b 86 8c 00 00 00 }
    $sequence_4 = { 0f b6 da f6 83 c1 1c 45 00 04 74 06 88 16 46 40 ff 01 }
    $sequence_5 = { b8 1f 85 eb 51 f7 e9 c1 fa 05 8b ca b8 1f 85 eb 51 c1 e9 1f }
    $sequence_6 = { 56 8b f1 33 db 57 89 75 f0 89 5d ec c7 45 e8 a4 ff 43 00 }
    $sequence_7 = { e8 ?? ?? ?? ?? c7 46 28 44 d0 43 00 83 3d ?? ?? ?? ?? 00 74 16 }
    $sequence_8 = { c3 33 c0 5e c3 8b 44 24 04 c7 40 50 f0 b9 44 00 }
    $sequence_9 = { c7 45 f0 20 d0 43 00 c7 45 e8 10 00 00 00 e8 ?? ?? ?? ?? 85 c0 74 03 }

  condition:
    7 of them and filesize < 5505024
}