rule MALPEDIA_Win_Sysget_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "950c6328-1de5-5d85-b009-d36eceeda441"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.sysget"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.sysget_auto.yar#L1-L126"
    license_url        = "N/A"
    logic_hash         = "98d11ad376be93c301b2c1f8309ca9e93b58254eeadefcb865a1a57e18934a28"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0 = { 56 6a 20 8d 45 cc 50 53 53 }
    $sequence_1 = { f3 a5 33 f6 8d 44 35 f0 8a 08 f6 d1 80 f1 5f }
    $sequence_2 = { 58 6a 00 ff 15 ?? ?? ?? ?? 6a 01 8d 85 ec f9 ff ff 50 8d 85 ec f1 ff ff }
    $sequence_3 = { 89 85 c8 f9 ff ff 83 c0 32 50 66 a5 e8 ?? ?? ?? ?? 83 c4 28 }
    $sequence_4 = { 33 f6 8d 44 35 f0 8a 08 f6 d1 80 f1 5f 46 }
    $sequence_5 = { 75 f5 8d bd ec fe ff ff 2b c2 83 ef 02 66 8b 4f 02 83 c7 02 66 85 c9 }
    $sequence_6 = { 83 c4 24 68 00 01 00 00 ff b5 f8 fe ff ff c1 e3 06 8d 84 1d fc fe ff ff 50 ff 15 ?? ?? ?? ?? }
    $sequence_7 = { 6a 50 68 ?? ?? ?? ?? 50 ff 15 ?? ?? ?? ?? a3 ?? ?? ?? ?? a1 ?? ?? ?? ?? }
    $sequence_8 = { 51 ff 36 89 7d 0c 50 53 }
    $sequence_9 = { 8d 45 9c 50 56 56 6a 20 53 }

  condition:
    7 of them and filesize < 352256
}