rule win_etumbot_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.etumbot."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.etumbot"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 8a00 02c2 0fb6c0 8a8405fcfeffff }
                                                            
        $sequence_1 = { 0fb6c0 8a8405fcfeffff 320437 8806 46 }
                                                                        
        $sequence_2 = { c745b063726f73 c745b46f66745c c745b85c57696e c745bc646f7773 c745c05c5c4375 c745c47272656e }
                                                                                    
        $sequence_3 = { f7d1 23c1 42 4e 75df }
                                                                        
        $sequence_4 = { 8d45f4 6820a10700 50 68???????? 68???????? }
                                                                        
        $sequence_5 = { c745cc73696f6e c745d05c5c496e c745d47465726e c745d865742053 }
                                                            
        $sequence_6 = { 03c1 8bc8 81e1000000f0 7407 8bf9 }
                                                                        
        $sequence_7 = { 7407 8bf9 c1ef18 33c7 f7d1 23c1 }
                                                                                    
        $sequence_8 = { c745d47465726e c745d865742053 c745dc65747469 c745e06e677300 }
                                                            
        $sequence_9 = { 53 56 57 8b3d???????? ffd7 8b7508 8bd8 }
                                                                                                
        $sequence_10 = { 57 0fbe38 33f6 33db }
                                                            
        $sequence_11 = { c745c47272656e c745c874566572 c745cc73696f6e c745d05c5c496e }
                                                            
        $sequence_12 = { ffd7 2bc3 3bc6 72ed 5f 5e }
                                                                                    
        $sequence_13 = { 8b45f4 0345f0 8b4d08 034dec 8a11 8810 }
                                                                                    
        $sequence_14 = { c645bf69 c645c062 c645c16c c645c265 c645c33b c645c420 c645c54d }
                                                                                                
        $sequence_15 = { 8b4d08 83c101 894d08 8b550c 83ea03 }
                                                                        
        $sequence_16 = { 83c204 3b5514 7608 83c8ff }
                                                            
        $sequence_17 = { 80e10f c0e102 c0eb06 02cb }
                                                            
        $sequence_18 = { c644242c45 8854242f 884c2431 c644243273 88542434 }
                                                                        
        $sequence_19 = { 83c404 8bd1 c1e902 f3ab 8bca }
                                                                        
        $sequence_20 = { 6a00 68???????? 6a00 6a00 6a00 51 68???????? }
                                                                                                
        $sequence_21 = { e8???????? 8d45fc 50 8d85bcfeffff 50 e8???????? }
                                                                                    
        $sequence_22 = { 8b0c8d20cf4000 8a44c104 83e040 c3 56 8b742408 85f6 }
                                                                                                
        $sequence_23 = { b9ff000000 33c0 8dbda6fbffff f3ab }
                                                            
        $sequence_24 = { c645d673 c645d720 c645d84e c645d954 }
                                                            
        $sequence_25 = { 83c104 3b4d14 7608 83c8ff }
                                                            
        $sequence_26 = { 50 8d85c4eaffff 50 e8???????? 8d85ecfdffff }
                                                                        
        $sequence_27 = { 59 50 8d8504ffffff e9???????? 6a18 }
                                                                        
        $sequence_28 = { c645c33b c645c420 c645c54d c645c653 c645c749 c645c845 c645c920 }
                                                                                                
        $sequence_29 = { 8b4508 8365f800 898184110000 8d45f4 6a00 }
                                                                        
        $sequence_30 = { 83c404 85c0 7429 8b442454 0fbe38 40 85ff }
                                                                                                
        $sequence_31 = { 89442428 f3ab 88542414 89542444 }
                                                            
        $sequence_32 = { c645d057 c645d169 c645d26e c645d364 }
                                                            
        $sequence_33 = { c645cd31 c645ce3b c645cf20 c645d057 c645d169 }
                                                                        
        $sequence_34 = { 52 e8???????? 83c404 e9???????? 6a05 }
                                                                        
        $sequence_35 = { c645fa74 c645fb2e c645fc64 c645fd6c }
                                                            
        $sequence_36 = { c645f569 c645f66e c645f769 c645f86e }
                                                            
        $sequence_37 = { 8b4df4 034df0 8b5508 0355ec }
                                                            
        $sequence_38 = { 50 8b4dbc 51 8b952ce6ffff 8b4210 ffd0 85c0 }
                                                                                                
        $sequence_39 = { c685dcefffff45 c685ddefffff20 c685deefffff35 c685dfefffff2e c685e0efffff30 }
                                                                        
    condition:
        7 of them and filesize < 450560
}