rule rule_WinPwn_offensive_tool_keyword
{
    meta:
        description = "Detection patterns for the tool 'WinPwn' taken from the ThreatHunting-Keywords github project"
        author = "@mthcht"
        reference = "https://github.com/mthcht/ThreatHunting-Keywords"
        tool = "WinPwn"
        rule_category = "offensive_tool_keyword"

    strings:
                        $string1_WinPwn_offensive_tool_keyword = /\s\-command\s.{0,100}\.exe.{0,100}\s\-technique\sccmstp/ nocase ascii wide
                        $string2_WinPwn_offensive_tool_keyword = " -consoleoutput -browsercredentials" nocase ascii wide
                        $string3_WinPwn_offensive_tool_keyword = " -consoleoutput -DomainRecon" nocase ascii wide
                        $string4_WinPwn_offensive_tool_keyword = " -consoleoutput -Localrecon" nocase ascii wide
                        $string5_WinPwn_offensive_tool_keyword = "/LocalPrivEsc/" nocase ascii wide
                        $string6_WinPwn_offensive_tool_keyword = "/WinPwn" nocase ascii wide
                        $string7_WinPwn_offensive_tool_keyword = /\/WinPwn\.git/ nocase ascii wide
                        $string8_WinPwn_offensive_tool_keyword = "/WinPwn_Repo" nocase ascii wide
                        $string9_WinPwn_offensive_tool_keyword = /\\DomainRecon\\.{0,100}\.txt/ nocase ascii wide
                        $string10_WinPwn_offensive_tool_keyword = /\\LocalPrivEsc\\/ nocase ascii wide
                        $string11_WinPwn_offensive_tool_keyword = /\\Passwordfiles\.txt/ nocase ascii wide
                        $string12_WinPwn_offensive_tool_keyword = /\\Seatbelt\.txt/ nocase ascii wide
                        $string13_WinPwn_offensive_tool_keyword = /\\SQLInfoDumps/ nocase ascii wide
                        $string14_WinPwn_offensive_tool_keyword = /\\temp\\dump\.txt/ nocase ascii wide
                        $string15_WinPwn_offensive_tool_keyword = /\\temp\\pwned\.trx/ nocase ascii wide
                        $string16_WinPwn_offensive_tool_keyword = /\\Users_Nochangedpassword\.txt/ nocase ascii wide
                        $string17_WinPwn_offensive_tool_keyword = /\\WritebleRegistryKeys\.txt/ nocase ascii wide
                        $string18_WinPwn_offensive_tool_keyword = /ADCS_Maybe_ESC8_HTTPS_Vulnerable\.txt/ nocase ascii wide
                        $string19_WinPwn_offensive_tool_keyword = /AllowDelegationUsers\.txt/ nocase ascii wide
                        $string20_WinPwn_offensive_tool_keyword = /AllowDelegationUsers_samaccountnames_only\.txt/ nocase ascii wide
                        $string21_WinPwn_offensive_tool_keyword = "asreproast /" nocase ascii wide
                        $string22_WinPwn_offensive_tool_keyword = /ASreproasting\.txt/ nocase ascii wide
                        $string23_WinPwn_offensive_tool_keyword = /breviaries\s\-Properties\sDnsHostName.{0,100}ms\-Mcs\-AdmPwd/ nocase ascii wide
                        $string24_WinPwn_offensive_tool_keyword = /\-command\s.{0,100}\.exe.{0,100}\s\-technique\sccmstp/ nocase ascii wide
                        $string25_WinPwn_offensive_tool_keyword = "-consoleoutput -DomainRecon" nocase ascii wide
                        $string26_WinPwn_offensive_tool_keyword = "-consoleoutput -Localrecon" nocase ascii wide
                        $string27_WinPwn_offensive_tool_keyword = "decryptteamviewer" nocase ascii wide
                        $string28_WinPwn_offensive_tool_keyword = "Discover-PSInterestingServices" nocase ascii wide
                        $string29_WinPwn_offensive_tool_keyword = "Domainpassspray" nocase ascii wide
                        $string30_WinPwn_offensive_tool_keyword = /DomainRecon\\ADCSServer\.txt/ nocase ascii wide
                        $string31_WinPwn_offensive_tool_keyword = /DomainRecon\\DC\-IPs\.txt/ nocase ascii wide
                        $string32_WinPwn_offensive_tool_keyword = /DomainRecon\\ExploitableSystems\.txt/ nocase ascii wide
                        $string33_WinPwn_offensive_tool_keyword = /DomainRecon\\OxidBindings\.txt/ nocase ascii wide
                        $string34_WinPwn_offensive_tool_keyword = /DomainRecon\\Windows_Servers\.txt/ nocase ascii wide
                        $string35_WinPwn_offensive_tool_keyword = "dumplsass" nocase ascii wide
                        $string36_WinPwn_offensive_tool_keyword = /Enabled_Users1\.txt/ nocase ascii wide
                        $string37_WinPwn_offensive_tool_keyword = "Generalrecon -noninteractive" nocase ascii wide
                        $string38_WinPwn_offensive_tool_keyword = /Get_WinPwn_Repo\.sh/ nocase ascii wide
                        $string39_WinPwn_offensive_tool_keyword = /GPO\-RemoteAccess\.txt/ nocase ascii wide
                        $string40_WinPwn_offensive_tool_keyword = /GPP_Passwords\.txt/ nocase ascii wide
                        $string41_WinPwn_offensive_tool_keyword = "Invoke-ADCSTemplateRecon" nocase ascii wide
                        $string42_WinPwn_offensive_tool_keyword = "Invoke-BlockETW" nocase ascii wide
                        $string43_WinPwn_offensive_tool_keyword = "Invoke-Certify" nocase ascii wide
                        $string44_WinPwn_offensive_tool_keyword = "Invoke-DomainPasswordSpray" nocase ascii wide
                        $string45_WinPwn_offensive_tool_keyword = "Invoke-Get-RBCD-Threaded" nocase ascii wide
                        $string46_WinPwn_offensive_tool_keyword = "Invoke-Grouper2" nocase ascii wide
                        $string47_WinPwn_offensive_tool_keyword = "Invoke-Grouper3" nocase ascii wide
                        $string48_WinPwn_offensive_tool_keyword = "Invoke-HandleKatz" nocase ascii wide
                        $string49_WinPwn_offensive_tool_keyword = "Invoke-Handlekatz" nocase ascii wide
                        $string50_WinPwn_offensive_tool_keyword = "Invoke-Internalmonologue" nocase ascii wide
                        $string51_WinPwn_offensive_tool_keyword = "Invoke-Inveigh" nocase ascii wide
                        $string52_WinPwn_offensive_tool_keyword = "Invoke-InveighRelay" nocase ascii wide
                        $string53_WinPwn_offensive_tool_keyword = "Invoke-JuicyPotato" nocase ascii wide
                        $string54_WinPwn_offensive_tool_keyword = "Invoke-LdapSignCheck" nocase ascii wide
                        $string55_WinPwn_offensive_tool_keyword = "Invoke-MalSCCM" nocase ascii wide
                        $string56_WinPwn_offensive_tool_keyword = "Invoke-MS16" nocase ascii wide
                        $string57_WinPwn_offensive_tool_keyword = "Invoke-NanoDump" nocase ascii wide
                        $string58_WinPwn_offensive_tool_keyword = "Invoke-Nightmare" nocase ascii wide
                        $string59_WinPwn_offensive_tool_keyword = "Invoke-Oxidresolver" nocase ascii wide
                        $string60_WinPwn_offensive_tool_keyword = "Invoke-OxidResolver" nocase ascii wide
                        $string61_WinPwn_offensive_tool_keyword = "Invoke-PowerDump" nocase ascii wide
                        $string62_WinPwn_offensive_tool_keyword = "Invoke-Privesc" nocase ascii wide
                        $string63_WinPwn_offensive_tool_keyword = "Invoke-RBDC" nocase ascii wide
                        $string64_WinPwn_offensive_tool_keyword = "Invoke-RBDC-over-DAVRPC" nocase ascii wide
                        $string65_WinPwn_offensive_tool_keyword = "Invoke-Reg1c1de" nocase ascii wide
                        $string66_WinPwn_offensive_tool_keyword = "Invoke-Rubeus" nocase ascii wide
                        $string67_WinPwn_offensive_tool_keyword = "Invoke-S3ssionGoph3r" nocase ascii wide
                        $string68_WinPwn_offensive_tool_keyword = "Invoke-Seatbelt" nocase ascii wide
                        $string69_WinPwn_offensive_tool_keyword = "Invoke-SharpCloud" nocase ascii wide
                        $string70_WinPwn_offensive_tool_keyword = "Invoke-Sharpcradle" nocase ascii wide
                        $string71_WinPwn_offensive_tool_keyword = "Invoke-SharpGPO" nocase ascii wide
                        $string72_WinPwn_offensive_tool_keyword = "Invoke-Sharphound" nocase ascii wide
                        $string73_WinPwn_offensive_tool_keyword = "Invoke-Sharphound4" nocase ascii wide
                        $string74_WinPwn_offensive_tool_keyword = "Invoke-SharpImpersonation" nocase ascii wide
                        $string75_WinPwn_offensive_tool_keyword = "Invoke-SharpLdapRelayScan" nocase ascii wide
                        $string76_WinPwn_offensive_tool_keyword = "Invoke-SharpPrinter" nocase ascii wide
                        $string77_WinPwn_offensive_tool_keyword = "Invoke-SharpSCCM" nocase ascii wide
                        $string78_WinPwn_offensive_tool_keyword = "Invoke-SharpUp" nocase ascii wide
                        $string79_WinPwn_offensive_tool_keyword = "Invoke-Sharpweb" nocase ascii wide
                        $string80_WinPwn_offensive_tool_keyword = "Invoke-SMBClient" nocase ascii wide
                        $string81_WinPwn_offensive_tool_keyword = "Invoke-SMBEnum" nocase ascii wide
                        $string82_WinPwn_offensive_tool_keyword = "Invoke-SMBExec" nocase ascii wide
                        $string83_WinPwn_offensive_tool_keyword = "Invoke-SMBNegotiate -ComputerName localhost" nocase ascii wide
                        $string84_WinPwn_offensive_tool_keyword = "Invoke-SMBNegotiate" nocase ascii wide
                        $string85_WinPwn_offensive_tool_keyword = "Invoke-Snaffler" nocase ascii wide
                        $string86_WinPwn_offensive_tool_keyword = "Invoke-SpoolSample" nocase ascii wide
                        $string87_WinPwn_offensive_tool_keyword = "Invoke-SprayEmptyPassword" nocase ascii wide
                        $string88_WinPwn_offensive_tool_keyword = "Invoke-SQLAudit" nocase ascii wide
                        $string89_WinPwn_offensive_tool_keyword = "Invoke-SQLDumpInfo" nocase ascii wide
                        $string90_WinPwn_offensive_tool_keyword = "Invoke-SQLUncPathInjection" nocase ascii wide
                        $string91_WinPwn_offensive_tool_keyword = "Invoke-TheKatz" nocase ascii wide
                        $string92_WinPwn_offensive_tool_keyword = "Invoke-Vulmap" nocase ascii wide
                        $string93_WinPwn_offensive_tool_keyword = "Invoke-VulnerableADCSTemplates" nocase ascii wide
                        $string94_WinPwn_offensive_tool_keyword = "Invoke-watson" nocase ascii wide
                        $string95_WinPwn_offensive_tool_keyword = "Invoke-WCMDump" nocase ascii wide
                        $string96_WinPwn_offensive_tool_keyword = "Invoke-winPEAS" nocase ascii wide
                        $string97_WinPwn_offensive_tool_keyword = "Invoke-Zerologon" nocase ascii wide
                        $string98_WinPwn_offensive_tool_keyword = "itm4nprivesc" nocase ascii wide
                        $string99_WinPwn_offensive_tool_keyword = "kerberoast /" nocase ascii wide
                        $string100_WinPwn_offensive_tool_keyword = "Kittielocal -" nocase ascii wide
                        $string101_WinPwn_offensive_tool_keyword = /LapsAllowedAdminGroups\.txt/ nocase ascii wide
                        $string102_WinPwn_offensive_tool_keyword = /LapsPasswords\.txt/ nocase ascii wide
                        $string103_WinPwn_offensive_tool_keyword = /Lazagne.{0,100}Passwords\.txt/ nocase ascii wide
                        $string104_WinPwn_offensive_tool_keyword = "localreconmodules" nocase ascii wide
                        $string105_WinPwn_offensive_tool_keyword = "lsassdumps" nocase ascii wide
                        $string106_WinPwn_offensive_tool_keyword = /MS\-RPNVulnerableDC\.txt/ nocase ascii wide
                        $string107_WinPwn_offensive_tool_keyword = "NanoDumpChoose" nocase ascii wide
                        $string108_WinPwn_offensive_tool_keyword = /nc\.exe\s127\.0\.0\.1\s4444/ nocase ascii wide
                        $string109_WinPwn_offensive_tool_keyword = "obfuskittiedump" nocase ascii wide
                        $string110_WinPwn_offensive_tool_keyword = /Offline_WinPwn\.ps1/ nocase ascii wide
                        $string111_WinPwn_offensive_tool_keyword = /passhunt\.exe/ nocase ascii wide
                        $string112_WinPwn_offensive_tool_keyword = /password\|passwort\|passwd\|/ nocase ascii wide
                        $string113_WinPwn_offensive_tool_keyword = /Passwords_in_description\.txt/ nocase ascii wide
                        $string114_WinPwn_offensive_tool_keyword = /pwned_x64\/notepad\.exe/ nocase ascii wide
                        $string115_WinPwn_offensive_tool_keyword = /Pwned\-creds_Domainpasswordspray\.txt/ nocase ascii wide
                        $string116_WinPwn_offensive_tool_keyword = /RBCD_Petitpotam_VulnerableServers\.txt/ nocase ascii wide
                        $string117_WinPwn_offensive_tool_keyword = /RottenPotatoVulnerable\.txt/ nocase ascii wide
                        $string118_WinPwn_offensive_tool_keyword = /SCCM_DLLSiteloading\.txt/ nocase ascii wide
                        $string119_WinPwn_offensive_tool_keyword = /Sensitivelocalfiles\.txt/ nocase ascii wide
                        $string120_WinPwn_offensive_tool_keyword = "shareenumeration" nocase ascii wide
                        $string121_WinPwn_offensive_tool_keyword = "SharpLdapRelayScan" nocase ascii wide
                        $string122_WinPwn_offensive_tool_keyword = /Sherlock_Vulns\.txt/ nocase ascii wide
                        $string123_WinPwn_offensive_tool_keyword = /SQLServer_Accessible_PotentialSensitiveData\.txt/ nocase ascii wide
                        $string124_WinPwn_offensive_tool_keyword = /SQLServer_DefaultLogin\.txt/ nocase ascii wide
                        $string125_WinPwn_offensive_tool_keyword = /System32fileWritePermissions\.txt/ nocase ascii wide
                        $string126_WinPwn_offensive_tool_keyword = /temp\\stager\.exe/ nocase ascii wide
                        $string127_WinPwn_offensive_tool_keyword = "UACBypass -" nocase ascii wide
                        $string128_WinPwn_offensive_tool_keyword = "uacm4gic" nocase ascii wide
                        $string129_WinPwn_offensive_tool_keyword = /Unconstrained_Delegation_Systems\.txt/ nocase ascii wide
                        $string130_WinPwn_offensive_tool_keyword = /UsernameAsPasswordCreds\.txt/ nocase ascii wide
                        $string131_WinPwn_offensive_tool_keyword = /WCMCredentials\.txt/ nocase ascii wide
                        $string132_WinPwn_offensive_tool_keyword = /whoami\s\/priv\s\|\sfindstr\s\/i\s\/C\:.{0,100}SeImpersonatePrivilege/ nocase ascii wide
                        $string133_WinPwn_offensive_tool_keyword = /WinCreds\.exe/ nocase ascii wide
                        $string134_WinPwn_offensive_tool_keyword = /winPEAS\.txt/ nocase ascii wide
                        $string135_WinPwn_offensive_tool_keyword = "WinPwn -" nocase ascii wide
                        $string136_WinPwn_offensive_tool_keyword = /WinPwn\.exe/ nocase ascii wide
                        $string137_WinPwn_offensive_tool_keyword = /WinPwn\.ps1/ nocase ascii wide
                        $string138_WinPwn_offensive_tool_keyword = /WriteDLLPermission\.txt/ nocase ascii wide
                        $string139_WinPwn_offensive_tool_keyword = /\-\-ZipFileName\s\$TrustedDomain\.zip/ nocase ascii wide
        $metadata_regex_import = /\bimport\s+[a-zA-Z0-9_.]+\b/ nocase
        $metadata_regex_function = /function\s+[a-zA-Z_][a-zA-Z0-9_]*\(/ nocase ascii
        $metadata_regex_php = /<\?php/ nocase ascii
        $metadata_regex_createobject = /(CreateObject|WScript\.)/ nocase ascii
        $metadata_regex_script = /<script\b/ nocase ascii
        $metadata_regex_javascript = /(let\s|const\s|function\s|document\.|console\.)/ nocase ascii
        $metadata_regex_powershell = /(Write-Host|Get-[a-zA-Z]+|Invoke-|param\(|\.SYNOPSIS)/ nocase ascii
        $metadata_regex_batch = /@(echo\s|call\s|set\s|goto\s|if\s|for\s|rem\s)/ nocase ascii
        $metadata_regex_shebang = /^#!\// nocase ascii

    condition:
        ((filesize < 20MB and (
            uint16(0) == 0x5a4d or             uint16(0) == 0x457f or             uint32be(0) == 0x7f454c46 or uint16(0) == 0xfeca or uint16(0) == 0xfacf or uint32(0) == 0xbebafeca or             uint32(0) == 0x504B0304 or             uint32(0) == 0xCAFEBABE or             uint32(0) == 0x4D534346 or             uint32(0) == 0xD0CF11E0 or             uint16(0) == 0x2321 or             uint16(0) == 0x3c3f         )) and 2 of ($string*)) or
        (filesize < 2MB and
        (
            2 of ($string*) and
            for any of ($metadata_regex_*) : ( @ <= 20000 )
        ))
}