rule win_anchor_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.anchor."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.anchor"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { c6400365 eb0a 66c74001646c c640036c }
                                                            
        $sequence_1 = { 740c 66c740016578 c6400365 eb0a }
                                                            
        $sequence_2 = { 8bf8 f7e6 0f90c1 f7d9 0bc8 51 e8???????? }
                                                                                                
        $sequence_3 = { c1e102 51 6a00 50 a3???????? e8???????? }
                                                                                    
        $sequence_4 = { b001 5d c3 e9???????? 6a0c 68???????? e8???????? }
                                                                                                
        $sequence_5 = { 66894818 33c9 8b4608 6689581a 8b4608 5b }
                                                                                    
        $sequence_6 = { 33c9 8b461c 6689781a 8b461c 5f }
                                                                        
        $sequence_7 = { 50 56 e8???????? 83bde8feffff10 8d85d4feffff }
                                                                        
        $sequence_8 = { b101 e8???????? e8???????? 84c0 }
                                                            
        $sequence_9 = { 0bc1 4898 488d0d12920200 488b5528 }
                                                            
        $sequence_10 = { 4889842440140000 488bd9 4c63d2 498bc2 418be9 48c1f806 488d0db8020100 }
                                                                                                
        $sequence_11 = { 03c2 c1f802 6bc003 894504 }
                                                            
        $sequence_12 = { 034524 3b8520010000 760c c785f400000001000000 }
                                                            
        $sequence_13 = { 4881e9c0000000 48c1e108 4803c8 8bc1 488d9405bf090000 eb0c 8bc7 }
                                                                                                
        $sequence_14 = { 0bc1 488b4d48 8801 488b4548 }
                                                            
        $sequence_15 = { 03c8 8bc1 8985a4000000 488d8da8010000 }
                                                            
        $sequence_16 = { 498bcf e8???????? 498bc7 488b8d90000000 }
                                                            
        $sequence_17 = { 7ce8 488b4350 4903d1 b945000000 66890c50 }
                                                                        
        $sequence_18 = { 488bfa 7203 488b3a ba20000000 488bcf e8???????? 33db }
                                                                                                
        $sequence_19 = { 00040f 830905 0000 83bd641a0000ff }
                                                            
        $sequence_20 = { 05e0930400 894544 8b5544 488b4508 }
                                                            
        $sequence_21 = { 0000 83bd641a0000ff 0f85fc040000 c6859412000000 }
                                                            
    condition:
        7 of them and filesize < 778240
}