rule MALPEDIA_Win_Sakula_Rat_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "877a5bc8-1502-5d2d-ac89-d1f9991b4673"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.sakula_rat"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.sakula_rat_auto.yar#L1-L234"
    license_url        = "N/A"
    logic_hash         = "5566117feff4531b6238852b1dd267d13dd172e7c51c8c4e9976cadb5e493558"
    score              = 75
    quality            = 73
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0  = { 6a 00 68 00 01 00 00 6a 00 6a 00 68 ?? ?? ?? ?? }
    $sequence_1  = { 8b f0 56 6a 01 57 53 }
    $sequence_2  = { 57 56 e8 ?? ?? ?? ?? 8d 7e 10 8a d8 57 8b c7 }
    $sequence_3  = { 33 c9 85 f6 7e 15 8a 04 11 84 c0 74 09 }
    $sequence_4  = { 53 e8 ?? ?? ?? ?? 83 c4 0c 6a 00 6a 00 57 53 }
    $sequence_5  = { 8b c7 e8 ?? ?? ?? ?? 83 c4 08 83 3e 01 }
    $sequence_6  = { 50 e8 ?? ?? ?? ?? 83 c4 04 32 c0 5d }
    $sequence_7  = { 53 e8 ?? ?? ?? ?? 56 e8 ?? ?? ?? ?? 83 c4 1c 5f 5b }
    $sequence_8  = { 66 89 5d b0 48 89 5c 24 50 48 89 44 24 58 48 89 44 24 60 }
    $sequence_9  = { ff 15 ?? ?? ?? ?? 33 d2 48 8b cb ff 15 ?? ?? ?? ?? e8 ?? ?? ?? ?? 33 c9 ff 15 ?? ?? ?? ?? }
    $sequence_10 = { 8b 45 d8 8b 5d e0 01 d8 89 45 e0 6a 01 e8 ?? ?? ?? ?? }
    $sequence_11 = { 4c 8b c6 33 d2 33 c9 44 8b c8 89 7c 24 28 48 89 5c 24 20 ff 15 ?? ?? ?? ?? }
    $sequence_12 = { 0f 85 16 01 00 00 48 8d 15 e6 1c 00 00 41 b8 04 01 00 00 48 89 0d ?? ?? ?? ?? ff 15 ?? ?? ?? ?? ff 15 ?? ?? ?? ?? 83 f8 01 }
    $sequence_13 = { 74 59 68 ?? ?? ?? ?? 68 ?? ?? ?? ?? e8 ?? ?? ?? ?? 83 f8 00 }
    $sequence_14 = { 89 45 e4 83 f8 00 0f 84 3c 01 00 00 6a 00 6a 00 ff 75 ec }
    $sequence_15 = { e8 ?? ?? ?? ?? 50 ff 75 f4 e8 ?? ?? ?? ?? 58 eb 02 31 c0 }
    $sequence_16 = { 8a 03 3c 00 74 14 b2 1a }
    $sequence_17 = { ff 15 ?? ?? ?? ?? 33 d2 48 8d 4d eb 44 8d 42 6c }
    $sequence_18 = { ff 15 ?? ?? ?? ?? 48 8b ce 48 8b d8 ff 15 ?? ?? ?? ?? 48 83 64 24 38 00 48 83 64 24 30 00 }
    $sequence_19 = { e9 ?? ?? ?? ?? 31 c0 74 02 31 c0 50 ff 75 fc e8 ?? ?? ?? ?? }
    $sequence_20 = { ff 90 80 00 00 00 3b c6 74 1b 48 8b 4d c7 48 8b 01 }
    $sequence_21 = { 68 04 01 00 00 ff 75 fc 6a 00 e8 ?? ?? ?? ?? ff 75 fc }
    $sequence_22 = { 33 d2 ff 15 ?? ?? ?? ?? 3b c6 74 5f 4c 8d 4d cf }

  condition:
    7 of them and filesize < 229376
}