rule win_fobber_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.fobber."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.fobber"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 8b750c 8b4d10 39f7 760e }
                                                            
        $sequence_1 = { 57 51 8b7d08 30c0 31c9 f7d1 }
                                                                                    
        $sequence_2 = { 8d0431 39f8 7607 49 01cf }
                                                                        
        $sequence_3 = { 57 e8???????? 85c0 740f 89c1 }
                                                                        
        $sequence_4 = { 8d4d08 51 ff31 ffd0 }
                                                            
        $sequence_5 = { 55 89e5 ff750c 6800300000 }
                                                            
        $sequence_6 = { 0453 42 e2f6 59 }
                                                            
        $sequence_7 = { f2ae 31c0 e303 4f }
                                                            
        $sequence_8 = { 8981efc00700 0081efe82300 0081c7371300 0081c7546900 0081c7397d00 00e9 }
                                                                                    
        $sequence_9 = { 0f85196e0100 807dfc00 7407 8b4df8 836170fd 5e }
                                                                                    
        $sequence_10 = { 4d fc 02e9 5a a2???????? 92 b4ff }
                                                                                                
        $sequence_11 = { 0f8423050000 ff7508 e8???????? 59 59 8b4508 }
                                                                                    
        $sequence_12 = { 43 7706 6205???????? 294a75 f2149c }
                                                                        
        $sequence_13 = { 6a52 686bb7ade9 e8???????? 83c408 }
                                                            
        $sequence_14 = { 3bc3 7524 8b451c 3bc3 }
                                                            
        $sequence_15 = { 33db 57 3bcb 0f8499840100 3bf3 0f84a2840100 }
                                                                                    
    condition:
        7 of them and filesize < 188416
}