rule win_cmstar_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.cmstar."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.cmstar"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 53 56 bb04010000 57 53 }
                                                                        
        $sequence_1 = { 8b45e8 ff75e0 ff30 e8???????? 8b4df8 }
                                                                        
        $sequence_2 = { 8b4dec c1e802 6a04 52 8d0481 50 e8???????? }
                                                                                                
        $sequence_3 = { ff15???????? 8bc6 e9???????? 6a10 }
                                                            
        $sequence_4 = { ff15???????? 6a04 e8???????? be00040000 }
                                                            
        $sequence_5 = { 8b45d8 836dfc10 ff75fc 8945e0 8b45dc 83c310 8945e4 }
                                                                                                
        $sequence_6 = { ff15???????? 6a03 58 5f 5e 5b c9 }
                                                                                                
        $sequence_7 = { 85c0 7504 6a03 eb0d 803b4d }
                                                                        
        $sequence_8 = { 888204420010 83c9ff 33c0 42 f2ae f7d1 49 }
                                                                                                
        $sequence_9 = { 8bf0 85f6 74b2 817c240cc8000000 741c a1???????? 33f6 }
                                                                                                
        $sequence_10 = { 81ec08060000 53 55 56 57 33db b9ff000000 }
                                                                                                
        $sequence_11 = { a1???????? 8b10 52 53 }
                                                            
        $sequence_12 = { 49 8d7c2418 8bc1 83c9ff 89442410 }
                                                                        
        $sequence_13 = { a1???????? 85c0 7505 a1???????? 6a00 6a00 6a03 }
                                                                                                
        $sequence_14 = { be01000000 8b4c2420 51 ff15???????? 3beb 7409 55 }
                                                                                                
        $sequence_15 = { 64890d00000000 81c4c0120000 c3 8b8c24d0120000 33db 3bcb 741c }
                                                                                                
    condition:
        7 of them and filesize < 4268032
}