rule win_zebrocy_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.zebrocy."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.zebrocy"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { c605????????03 c705????????04000000 c605????????11 c705????????00000000 }
                                                            
        $sequence_1 = { e8???????? 84c0 8b4de0 7507 }
                                                            
        $sequence_2 = { 50 8d45f4 64a300000000 6aff 33ff c745fc01000000 }
                                                                                    
        $sequence_3 = { 8be5 5d c21000 8b4d14 51 56 }
                                                                                    
        $sequence_4 = { e8???????? 83c41c 83ec1c 8bcc 89a5f4f4ffff }
                                                                        
        $sequence_5 = { ff25???????? ebb5 55 b9???????? 89e5 }
                                                                        
        $sequence_6 = { f2ae 89c8 f7d0 8d5402ff }
                                                            
        $sequence_7 = { 8bd8 3bc7 7e63 8d642400 6a02 }
                                                                        
        $sequence_8 = { 397de0 7f57 8b03 85c0 }
                                                            
        $sequence_9 = { 8d45f4 64a300000000 33db 897d90 895d94 6aff c745fc01000000 }
                                                                                                
        $sequence_10 = { 89d8 e8???????? 8d9510fcffff 89c6 8d8500fcffff 89d7 }
                                                                                    
        $sequence_11 = { 89c7 eb2f 89f2 89d9 e8???????? }
                                                                        
        $sequence_12 = { 325032 7032 7c32 9c 32a432ac32c432 d432 e8???????? }
                                                                                                
        $sequence_13 = { 33c0 894e14 894710 894714 c645fc00 837de810 720c }
                                                                                                
        $sequence_14 = { 66c705????????6046 8915???????? ba???????? a3???????? e8???????? }
                                                                        
        $sequence_15 = { 89b5c4f7ffff 899dc0f7ffff 889db0f7ffff 39bd38f7ffff }
                                                            
    condition:
        7 of them and filesize < 393216
}