rule win_cerber_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.cerber."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.cerber"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 8345fc04 8901 ff45f8 8b45f8 }
                                                            
        $sequence_1 = { 8b5508 2bd7 8955f4 8975fc }
                                                            
        $sequence_2 = { 59 84c0 7413 8b450c 56 ff7508 8b7510 }
                                                                                                
        $sequence_3 = { 833c8100 7505 85c0 75f1 c3 40 }
                                                                                    
        $sequence_4 = { 8b550c 8b4510 b900100000 2b8e7c3b0000 33db 2b55fc 1bc3 }
                                                                                                
        $sequence_5 = { 7709 39450c 0f86dc000000 8b550c 8b4510 }
                                                                        
        $sequence_6 = { 6a00 50 e8???????? 8b4df0 83c40c 85c9 7e58 }
                                                                                                
        $sequence_7 = { 7433 8b7d0c 8b5508 2bd7 8955f4 8975fc }
                                                                                    
        $sequence_8 = { 762e 85d2 7838 8b4508 8b04b8 83651400 837d1420 }
                                                                                                
        $sequence_9 = { 3b7d0c 72d2 85d2 780a }
                                                            
    condition:
        7 of them and filesize < 573440
}