rule MALPEDIA_Win_Bootwreck_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "7e23b82b-3bdc-58cd-906f-3ab5825b9ffb"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.bootwreck"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.bootwreck_auto.yar#L1-L130"
    license_url        = "N/A"
    logic_hash         = "49dbec8ae0163fe1b10f7b427af3210b6bbd81884139d209319f2b77e78ba995"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0 = { 33 ff 89 7d fc 3b 1c fd e0 c1 81 00 74 09 47 89 7d fc }
    $sequence_1 = { 8d 64 24 28 0f 84 09 00 00 00 66 0f be c2 86 c7 8b 45 10 55 66 0f b6 da }
    $sequence_2 = { 85 b1 78 37 3e 03 02 5a d9 7e fa 99 18 c7 7e 55 }
    $sequence_3 = { c7 44 24 14 7d 97 83 00 68 2d ed fc aa 9c 89 44 24 18 9c 9c ff 74 24 20 }
    $sequence_4 = { ee 5b 7f 3f 99 68 e4 3b 3f a7 6c }
    $sequence_5 = { 87 6c 24 28 66 89 1c 24 68 81 06 ab 60 89 6c 24 28 5d 66 89 6c 24 04 bd ?? ?? ?? ?? }
    $sequence_6 = { 89 55 fc f9 8d 9b 00 00 00 00 30 e1 37 d4 b7 8b 4d 08 }
    $sequence_7 = { ff 46 38 88 c3 66 f7 d6 b3 7c 5b 66 0f b6 f9 5f }
    $sequence_8 = { c2 54 00 c7 04 24 00 00 00 00 60 87 74 24 1c 8d 64 24 1c 0f 81 03 50 05 00 }
    $sequence_9 = { 8d 04 1f f7 c5 03 6c 87 b2 99 84 ed f8 60 66 81 fb 74 4d }

  condition:
    7 of them and filesize < 10821632
}