rule MALPEDIA_Win_Yakuza_Ransomware_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "11a15f28-8d6d-50f2-ab84-992f1017bc03"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.yakuza_ransomware"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.yakuza_ransomware_auto.yar#L1-L134"
    license_url        = "N/A"
    logic_hash         = "f6b4887f1e5f8fb585f51d15a1308ea3aa15725a1e02d02f26222a8f601e98de"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0 = { 8b d1 d1 ea b8 ff ff ff 1f 2b c2 3b c8 76 07 8b c3 }
    $sequence_1 = { e8 ?? ?? ?? ?? 3b 78 0c 73 0e 8b 40 08 8b 34 b8 85 f6 0f 85 d7 00 00 00 }
    $sequence_2 = { d1 f8 83 7e 14 08 72 02 8b 36 50 ff 75 08 8b ce }
    $sequence_3 = { 6a 01 6a 01 57 8d 4d 80 e8 ?? ?? ?? ?? 8b 45 80 8d 4d 80 }
    $sequence_4 = { 8d 70 18 83 c0 30 8b 11 03 c7 50 03 f7 56 }
    $sequence_5 = { c7 45 fc ff ff ff ff 56 8b 4d e0 41 51 53 8b cf }
    $sequence_6 = { 8b 4f 14 8b 56 14 85 c9 74 3e 85 c0 75 0d e8 ?? ?? ?? ?? }
    $sequence_7 = { eb 17 0f b7 46 44 8d 4e 24 50 e8 ?? ?? ?? ?? 6a 2d 8d 4e 24 }
    $sequence_8 = { 8b 06 6a 02 51 53 8d 8d 50 ff ff ff 51 8b ce }
    $sequence_9 = { c7 45 f0 00 00 00 00 c7 46 10 00 00 00 00 c7 46 14 07 00 00 00 66 89 06 89 45 fc 8b c3 c7 45 f0 01 00 00 00 }

  condition:
    7 of them and filesize < 2811904
}