rule MALPEDIA_Win_Crypmic_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "50202601-a687-564d-add6-7e6f376e5e2e"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.crypmic"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.crypmic_auto.yar#L1-L117"
    license_url        = "N/A"
    logic_hash         = "9041d9d560914890b77f3fcac1afa5aa11364ed26eb5680a449dc6f4542c2153"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0 = { 39 58 18 76 4a 8b 78 20 03 f9 }
    $sequence_1 = { 2b c1 74 ec 46 3b 75 fc 77 0b 8b 55 f8 }
    $sequence_2 = { 8b 4d e4 89 4f 04 8b 4d e8 89 4f 08 66 8b 4d f0 66 89 4f 0c 66 8b 45 f2 }
    $sequence_3 = { 33 d2 8d 64 24 00 8d 40 01 66 89 0c 17 }
    $sequence_4 = { 50 8b 46 08 6a 08 ff 76 04 ff d0 }
    $sequence_5 = { 33 c0 8b cf 66 89 43 02 e8 ?? ?? ?? ?? }
    $sequence_6 = { 43 83 c7 04 3b 58 18 72 bb 5f }
    $sequence_7 = { 55 8b ec 83 ec 0c 8b 41 3c 53 8b 44 08 78 03 c1 }
    $sequence_8 = { 5d c2 08 00 8b 55 fc 8b 42 24 8d 04 58 0f b7 0c 08 8b 42 1c }
    $sequence_9 = { 8b 44 08 78 03 c1 89 45 fc 39 58 18 }

  condition:
    7 of them and filesize < 81920
}