rule win_pocodown_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.pocodown."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.pocodown"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 8b8c2488000000 e8???????? 85c0 0f849d010000 }
                                                            
        $sequence_1 = { 8b8c2488000000 e8???????? 03442460 89842488000000 }
                                                            
        $sequence_2 = { 8b8c2488000000 8d840801fcffff 8944244c 837c244c00 }
                                                            
        $sequence_3 = { 8b8c2488000000 e8???????? 89842488000000 488b442478 }
                                                            
        $sequence_4 = { 8b8c2488000000 8d8401f33e706d 89842488000000 ba05000000 }
                                                            
        $sequence_5 = { 8b8c2488000000 e8???????? 4885c0 7529 }
                                                            
        $sequence_6 = { 8b8c2488000000 e8???????? 4883bc249000000000 741a }
                                                            
        $sequence_7 = { 8b8c2488000000 ff15???????? 85c0 7519 }
                                                            
    condition:
        7 of them and filesize < 6703104
}