rule MALPEDIA_Win_Virtualgate_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "5ab8135e-3bbe-5abd-acc2-717daf53613e"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.virtualgate"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.virtualgate_auto.yar#L1-L120"
    license_url        = "N/A"
    logic_hash         = "5ca5297d10bab80aa59720f493a7b89d0ffff3ac0eaaf62e59c4e5ea64ea6f84"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0 = { 41 57 48 83 ec 38 4c 63 e9 48 8b f2 49 8b c5 48 8d 0d c7 f1 00 00 }
    $sequence_1 = { 4b 87 94 fe d0 2a 02 00 eb 2d 4c 8b 15 ?? ?? ?? ?? eb b8 4c 8b 15 ?? ?? ?? ?? 41 8b c2 b9 40 00 00 00 }
    $sequence_2 = { 8d 58 b0 49 8b ce 44 8b c3 48 8d 15 80 bd 00 00 e8 ?? ?? ?? ?? 85 c0 74 29 }
    $sequence_3 = { ff 15 ?? ?? ?? ?? c7 05 ?? ?? ?? ?? 00 00 10 00 eb 26 41 83 f8 02 }
    $sequence_4 = { 48 8b c8 ff 15 ?? ?? ?? ?? 3b 05 ?? ?? ?? ?? 48 8b cb 89 44 24 50 76 08 }
    $sequence_5 = { 48 89 45 27 49 8b c0 48 ff c0 41 38 14 07 75 f7 49 8b c8 48 ff c1 }
    $sequence_6 = { 4c 8d 05 b4 d3 00 00 48 8d 15 b1 d3 00 00 e8 ?? ?? ?? ?? 48 85 c0 74 16 }
    $sequence_7 = { 48 8b f5 48 03 d2 49 8b 94 d7 50 b5 01 00 e8 ?? ?? ?? ?? 85 c0 }
    $sequence_8 = { 4c 8d 05 8d be 01 00 48 8b d5 48 c1 fa 06 4c 89 34 03 48 8b c5 }
    $sequence_9 = { 48 8b 8c 24 20 80 02 00 48 33 cc e8 ?? ?? ?? ?? 48 8b 9c 24 50 80 02 00 }

  condition:
    7 of them and filesize < 323584
}