rule win_remcos_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.remcos."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.remcos"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 85c0 7410 6a00 ff35???????? }
                                                            
        $sequence_1 = { ff15???????? 50 ff15???????? 8d45f0 33f6 }
                                                                        
        $sequence_2 = { 51 51 8d45f8 c745f808000000 50 ff15???????? ff15???????? }
                                                                                                
        $sequence_3 = { ff15???????? 50 ff15???????? 8d45f0 33f6 50 }
                                                                                    
        $sequence_4 = { 85c0 7410 6a00 ff35???????? ff15???????? }
                                                                        
        $sequence_5 = { 50 6a28 ff15???????? 50 ff15???????? 8d45f0 33f6 }
                                                                                                
        $sequence_6 = { 7410 6a00 ff35???????? ff15???????? }
                                                            
        $sequence_7 = { 8d45f8 50 ff15???????? ff7508 }
                                                            
        $sequence_8 = { 51 8d45f8 c745f808000000 50 ff15???????? ff15???????? }
                                                                                    
        $sequence_9 = { 8d45f8 50 ff15???????? ff7508 ff15???????? }
                                                                        
    condition:
        7 of them and filesize < 1054720
}