rule MALPEDIA_Win_Advisorsbot_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "4423ed68-193a-5b69-9a0c-e4a68868d775"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.advisorsbot"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.advisorsbot_auto.yar#L1-L169"
    license_url        = "N/A"
    logic_hash         = "63e408f2b85153604b6cbce7b119689dceb4fed854cd697bc92427d51dad5ae1"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0  = { 8b c1 2b c2 d1 e8 03 c2 c1 e8 08 }
    $sequence_1  = { 8b c2 33 d2 c1 e8 09 f7 f1 }
    $sequence_2  = { 8b c2 33 d2 c1 e8 08 f7 f1 }
    $sequence_3  = { b8 9b 01 a3 11 f7 e1 2b ca d1 e9 03 ca }
    $sequence_4  = { d1 e8 03 c2 33 d2 c1 e8 09 }
    $sequence_5  = { 8b c2 c1 e8 09 33 d2 f7 f1 }
    $sequence_6  = { 8b 44 24 08 8b 4c 24 08 33 d2 f7 f1 }
    $sequence_7  = { d1 e9 03 ca 33 d2 c1 e9 09 }
    $sequence_8  = { d1 e9 03 ca c1 e9 07 2b c1 }
    $sequence_9  = { b8 39 81 13 38 f7 e1 8b c1 2b c2 }
    $sequence_10 = { d1 e9 03 ca c1 e9 09 33 c8 }
    $sequence_11 = { 8b c2 33 d2 c1 e8 04 f7 f1 }
    $sequence_12 = { 8b ca f7 e2 8b c1 2b c2 }
    $sequence_13 = { 66 8b 4c 24 10 5f 5e 5d }
    $sequence_14 = { 0f b7 c1 0f b7 ca 33 d2 f7 f1 }
    $sequence_15 = { 0f b7 c0 0f b7 c9 33 d2 f7 f1 }
    $sequence_16 = { 0f b6 c0 0f b6 c9 33 d2 f7 f1 }
    $sequence_17 = { 8b 44 24 14 8b 4c 24 14 33 d2 f7 f1 }
    $sequence_18 = { 5e 5d 0f b7 c2 5b }

  condition:
    7 of them and filesize < 434176
}