rule MALPEDIA_Win_Unidentified_003_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "078af5cf-1960-57c1-ad2f-834d23801cf0"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.unidentified_003"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.unidentified_003_auto.yar#L1-L124"
    license_url        = "N/A"
    logic_hash         = "44e97183e244c5496d21c90ef879a2c3ae0327847947e2b5ee30ab46305a46ce"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0 = { 89 45 ec a1 ?? ?? ?? ?? 0f b7 50 6f 0f b7 40 6d c1 e2 10 0b d0 }
    $sequence_1 = { c6 85 64 ff ff ff 01 33 c0 8a 88 c2 10 09 00 88 8c 05 66 ff ff ff 40 }
    $sequence_2 = { e8 ?? ?? ?? ?? 83 c4 0c 8b 07 5d c3 55 8b ec }
    $sequence_3 = { a1 ?? ?? ?? ?? ff 75 f0 ff 70 28 ff 15 ?? ?? ?? ?? eb 0a }
    $sequence_4 = { 39 5d a0 74 0f ff 75 a4 ff 15 ?? ?? ?? ?? 89 5d a0 }
    $sequence_5 = { 3b fe 75 02 8b fb 39 74 24 10 }
    $sequence_6 = { 59 85 c0 74 17 47 81 c6 14 01 00 00 3b 3d ?? ?? ?? ?? 72 c8 }
    $sequence_7 = { 8b ec 81 ec 20 08 00 00 53 56 57 8d 85 e0 fd ff ff 89 45 ec }
    $sequence_8 = { 75 75 38 5d 6e 74 3b 39 bd 5c ff ff ff 75 0a c7 05 ?? ?? ?? ?? 07 00 00 00 39 9d 5c ff ff ff }
    $sequence_9 = { ff 15 ?? ?? ?? ?? 85 c0 0f 88 b4 01 00 00 8b 45 e4 3b c3 0f 84 a9 01 00 00 8b 08 }

  condition:
    7 of them and filesize < 57344
}