rule win_latrodectus_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.latrodectus."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.latrodectus"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 488b4c2430 8801 488b442430 48ffc0 4889442430 8b44242c }
                                                                                    
        $sequence_1 = { 33c0 6689842430010000 ba18000000 488d8c24d0000000 e8???????? 488d8424d0000000 }
                                                                                    
        $sequence_2 = { 33c9 ff15???????? 488905???????? 48833d????????00 7414 }
                                                                        
        $sequence_3 = { 488b542458 488d4c2428 e8???????? 488b4c2458 e8???????? 488b442420 }
                                                                                    
        $sequence_4 = { 488b00 488b4818 e8???????? 488b442430 488b00 4883782000 }
                                                                                    
        $sequence_5 = { 89442420 8b442420 4883f825 7336 8b442420 486bc018 }
                                                                                    
        $sequence_6 = { 488bc1 488b4c2450 0fb709 488d0488 4889442438 488b442438 }
                                                                                    
        $sequence_7 = { e8???????? 89442420 ba68000000 488d4c2430 e8???????? c744243068000000 }
                                                                                    
        $sequence_8 = { 4883e808 4883f81f 0f87ab000000 e8???????? 488bc3 488b8dd0050000 }
                                                                                    
        $sequence_9 = { 410fb6f0 e9???????? 80fb05 7405 80fb0b 7508 }
                                                                                    
        $sequence_10 = { 480f474d70 488b8580000000 4889442430 48894c2428 4889542420 4c8d05fd2d0600 }
                                                                                    
        $sequence_11 = { 4833c4 4889842448010000 498bf1 4d8bf0 8bfa 4c89442458 }
                                                                                    
        $sequence_12 = { 41b826000000 488d1591b10b00 488d4c2430 e8???????? 90 488b7c2440 }
                                                                                    
        $sequence_13 = { 4883ec30 488b442460 498bf9 492bf8 488bf2 482bf1 }
                                                                                    
        $sequence_14 = { 0f87dc030000 0faee8 e8???????? 660f6f05???????? f30f7f442478 664489642468 }
                                                                                    
        $sequence_15 = { 0fb605???????? 884130 c6413100 0f57c0 0f11442438 488d3da9630d00 }
                                                                                    
    condition:
        7 of them and filesize < 2467840
}