name: ispconfig
description: Detect ISPConfig
uuid: e16dc003-e651-5d4b-ace4-6e1f7f43904f
query: http_favicon_mmhash:483383992
tags:
- proto:http
- product:ispconfig
- vendor:ispconfig
version: 20260918T053418Z