rule MALPEDIA_Win_Oski_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "e23300f3-24c2-58db-ad53-9ccc894ba178"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.oski"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.oski_auto.yar#L1-L187"
    license_url        = "N/A"
    logic_hash         = "32e88579dcf8b669972c260572f27190a2af2a9bf4eb835092b7f8cb9a6a6e17"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0  = { 50 a1 ?? ?? ?? ?? 50 8d 8d f0 fe ff ff 51 e8 ?? ?? ?? ?? }
    $sequence_1  = { 25 ff 7f 00 00 c3 8b ff 55 8b ec 83 ec 14 ff 75 10 }
    $sequence_2  = { e8 ?? ?? ?? ?? 83 c4 0c e8 ?? ?? ?? ?? 50 a1 ?? ?? ?? ?? 50 }
    $sequence_3  = { 89 75 f0 e8 ?? ?? ?? ?? cc 8b ff 55 8b ec 8b 55 0c }
    $sequence_4  = { 74 08 39 b5 ac fe ff ff 77 87 68 03 01 00 00 8d 95 ed fe ff ff 56 }
    $sequence_5  = { 83 43 18 10 66 89 85 68 fb ff ff 8b 43 14 85 c0 75 77 8b 8d 84 fb ff ff 51 }
    $sequence_6  = { 6a 00 6a 1a 6a 00 89 85 ec ee ff ff 89 8d f0 ee ff ff }
    $sequence_7  = { 53 68 ?? ?? ?? ?? 8d 8d e4 fe ff ff 51 53 }
    $sequence_8  = { e8 ?? ?? ?? ?? 83 c4 04 56 8d 85 ec fe ff ff 50 8d 8d d0 fc ff ff }
    $sequence_9  = { f3 c3 e9 ?? ?? ?? ?? 8b ff 55 8b ec 83 ec 1c a1 ?? ?? ?? ?? }
    $sequence_10 = { e8 ?? ?? ?? ?? 83 c4 04 8b 0d ?? ?? ?? ?? 51 ff 15 ?? ?? ?? ?? a3 ?? ?? ?? ?? 83 3d ?? ?? ?? ?? 00 }
    $sequence_11 = { 8b 55 08 52 a1 ?? ?? ?? ?? 50 8d 8d e8 fd ff ff }
    $sequence_12 = { 83 c4 04 8b 55 f8 89 55 f4 8b 45 f4 50 e8 ?? ?? ?? ?? }
    $sequence_13 = { 50 8d 4d f8 51 68 00 02 00 00 8b 55 f4 52 ff 15 ?? ?? ?? ?? }
    $sequence_14 = { 6a 00 e8 ?? ?? ?? ?? 83 c4 0c 89 85 e4 fd ff ff }
    $sequence_15 = { 8d 55 f4 52 6a 00 68 ?? ?? ?? ?? ff 15 ?? ?? ?? ?? 89 45 f0 }
    $sequence_16 = { 83 c2 20 52 6a 00 6a 00 ff 15 ?? ?? ?? ?? }

  condition:
    7 of them and filesize < 423936
}