rule win_roopirs_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.roopirs."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.roopirs"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 51 ff15???????? 50 8d55d0 52 ff15???????? 8d4dc8 }
                                                                                                
        $sequence_1 = { 7433 c745fc3e000000 8b4dd8 51 68???????? }
                                                                        
        $sequence_2 = { ff15???????? 898544ffffff e9???????? c745fc07000000 8d5584 52 8b45dc }
                                                                                                
        $sequence_3 = { 8d45b8 50 ff15???????? 8bd0 8d4dd0 }
                                                                        
        $sequence_4 = { 51 8b5508 8b4234 8b4d08 8b5134 8b0a 50 }
                                                                                                
        $sequence_5 = { 8d4dcc ff15???????? c745fc0d000000 6aff ff15???????? c745fc0e000000 }
                                                                                    
        $sequence_6 = { 8d4db8 ff15???????? 0fbf55b0 85d2 7433 c745fc2f000000 }
                                                                                    
        $sequence_7 = { 52 8b45b0 50 ff15???????? 898570ffffff eb0a c78570ffffff00000000 }
                                                                                                
        $sequence_8 = { ff15???????? 8d4db8 ff15???????? c745fc16000000 8b55d8 }
                                                                        
        $sequence_9 = { 8b550c 8d4dd8 ff15???????? c745fc02000000 6a01 8b45d8 50 }
                                                                                                
    condition:
        7 of them and filesize < 344064
}