rule win_dorkbot_ngrbot_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.dorkbot_ngrbot."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.dorkbot_ngrbot"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 85c0 740c 8b8cb51cffffff 51 ffd0 eb0d 8b94b51cffffff }
                                                                                                
        $sequence_1 = { 85f6 0f84a8020000 6a00 6800040000 8d9578fbffff }
                                                                        
        $sequence_2 = { ff15???????? 85c0 0f8c9f000000 8b4508 85c0 0f8494000000 8b4dfc }
                                                                                                
        $sequence_3 = { e8???????? 8bf0 83c408 85f6 0f84dc000000 6a06 68???????? }
                                                                                                
        $sequence_4 = { 51 7416 68???????? 52 50 e8???????? 83c410 }
                                                                                                
        $sequence_5 = { 8b4d0c 51 50 6a00 ff15???????? 50 ff15???????? }
                                                                                                
        $sequence_6 = { 8d85f1feffff 6a00 50 c685f0feffff00 e8???????? 8b4d14 83c40c }
                                                                                                
        $sequence_7 = { 8d8500f8ffff 50 ff15???????? 8b550c 8b4508 8d8d00f8ffff 51 }
                                                                                                
        $sequence_8 = { 8d55f0 52 68???????? e8???????? 83c40c 85c0 7530 }
                                                                                                
        $sequence_9 = { b8???????? 5b 8be5 5d c3 ff15???????? 5e }
                                                                                                
    condition:
        7 of them and filesize < 638976
}