rule win_oceansalt_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.oceansalt."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.oceansalt"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 56 8b7508 57 6a00 6804020000 8d85f8f9ffff 50 }
                                                                                                
        $sequence_1 = { 0f8492000000 53 6a00 6a00 6a00 6802000008 }
                                                                                    
        $sequence_2 = { 50 56 ffd3 6a00 6880000000 6a02 }
                                                                                    
        $sequence_3 = { 8b4508 6a00 52 57 50 }
                                                                        
        $sequence_4 = { 6a07 8d45f4 50 56 c645f400 ff15???????? 6a00 }
                                                                                                
        $sequence_5 = { 85c9 7e0d 80b405fcfdffff77 40 3bc1 7cf3 56 }
                                                                                                
        $sequence_6 = { 85ff 743c 6a00 56 }
                                                            
        $sequence_7 = { 83c404 85c0 75ce 8b8dc4fdffff }
                                                            
        $sequence_8 = { 8be8 85c0 0f841e010000 48899c24a8010000 }
                                                            
        $sequence_9 = { 442b44247c 41c1e80a e8???????? f644246010 740a }
                                                                        
        $sequence_10 = { 4c8d0d2ba3ffff 41bb00020000 408a2f 413aea 0f8524f9ffff 4438942490000000 }
                                                                                    
        $sequence_11 = { bb00080000 3918 0f4c18 bf01000000 3bcb 0f8d8d000000 4c8d35f4c60000 }
                                                                                                
        $sequence_12 = { 4883c440 5d c3 4055 4883ec20 488bea 488b01 }
                                                                                                
        $sequence_13 = { eb4e 488b0d???????? 488d542434 e8???????? eb3b }
                                                                        
        $sequence_14 = { e8???????? 4c8d9c2470060000 498b6b20 498b7328 498be3 }
                                                                        
        $sequence_15 = { 488d0d54e30000 f6410820 7417 33d2 }
                                                            
    condition:
        7 of them and filesize < 212992
}