rule osx_coldroot_rat_auto {
  meta:
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    date               = "2020-10-14"
    version            = "1"
    description        = "autogenerated rule brought to you by yara-signator"
    tool               = "yara-signator v0.5.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/osx.coldroot_rat"
    malpedia_rule_date = "20201014"
    malpedia_hash      = "a7e3bd57eaf12bf3ea29a863c041091ba3af9ac9"
    malpedia_version   = "20201014"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"
  

  strings:
    $sequence_0 = { e8 ?? ?? ?? ?? 89 45 f4 e9 ?? ?? ?? ?? c7 45 f4 03 00 00 00 e9 ?? ?? ?? ?? 8b 45 fc e8 ?? ?? ?? ?? }
                                    $sequence_1 = { eb 0a 8b 55 f4 8b 45 f0 0f b3 42 28 8b 45 f4 e8 ?? ?? ?? ?? 84 c0 }
                                    $sequence_2 = { e8 ?? ?? ?? ?? 89 c7 89 d6 66 8b 5d fc 66 85 db 74 4a c7 04 24 00 00 00 00 }
                                    $sequence_3 = { e8 ?? ?? ?? ?? 89 45 e0 89 55 e4 d9 45 e0 df 7d e0 9b 8b 55 fc }
                                    $sequence_4 = { e8 ?? ?? ?? ?? 8d 45 fc e8 ?? ?? ?? ?? 8b 45 0c e8 ?? ?? ?? ?? 8b 45 cc 85 c0 }
                                    $sequence_5 = { 8b 0c 24 8d 91 3b ff ff ff 89 50 0c 8b 0c 24 8d 91 5b ff ff ff 89 50 10 8b 0c 24 }
                                    $sequence_6 = { eb 05 b9 02 00 00 00 8b 44 24 04 8b 40 0c 8a 50 02 88 54 24 48 8b 54 24 4c }
                                    $sequence_7 = { 8d 45 f8 89 04 24 8b 83 f9 26 16 00 89 44 24 04 e8 ?? ?? ?? ?? 8b 5d f4 89 ec }
                                    $sequence_8 = { ff 53 40 8b 47 08 8b 55 fc b1 01 e8 ?? ?? ?? ?? 89 c6 85 f6 }
                                    $sequence_9 = { e8 ?? ?? ?? ?? 89 c3 ba 00 00 00 00 89 d8 8b 0b ff 91 a8 00 00 00 8b 45 fc }
                
  condition:
    7 of them and filesize < 6585656
}