rule MALPEDIA_Win_Slingshot_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "bf558dcd-c863-525d-b34a-1a56d33f94ec"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.slingshot"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.slingshot_auto.yar#L1-L218"
    license_url        = "N/A"
    logic_hash         = "1e413348df71e72118297c6913e2a6da9548aa658d39b7dcd425460f21f929c0"
    score              = 75
    quality            = 73
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0  = { 50 33 db 53 ff 15 ?? ?? ?? ?? 8b f0 3b f3 }
    $sequence_1  = { 3b cb 75 12 ff 77 08 ff 37 }
    $sequence_2  = { 48 8b f0 66 89 58 04 66 89 78 06 85 ed }
    $sequence_3  = { e8 ?? ?? ?? ?? e8 ?? ?? ?? ?? 89 45 d8 89 55 dc 3b c3 7d 09 52 }
    $sequence_4  = { e8 ?? ?? ?? ?? ff 70 04 8d 74 24 20 ff 30 e8 ?? ?? ?? ?? 39 5c 24 1c 75 23 }
    $sequence_5  = { 8b e8 49 3b c6 75 0f ba ec 04 00 00 b9 0e 00 07 80 }
    $sequence_6  = { e8 ?? ?? ?? ?? 59 8d 75 a4 e8 ?? ?? ?? ?? 8d 75 94 }
    $sequence_7  = { 3b cb 74 42 39 5d fc 74 14 }
    $sequence_8  = { 3b cb 75 04 6a 08 eb 7a }
    $sequence_9  = { 39 19 74 0a 48 83 c1 02 48 83 e8 01 75 f0 }
    $sequence_10 = { 83 3d ?? ?? ?? ?? 00 75 46 b9 18 00 00 00 e8 ?? ?? ?? ?? 48 }
    $sequence_11 = { 0f 84 8a 05 00 00 45 33 e4 0f b7 4c 24 48 83 e9 61 }
    $sequence_12 = { 3b cb 75 52 dd 45 f0 dd 47 20 }
    $sequence_13 = { 8b ce 49 3b fe 74 1a }
    $sequence_14 = { 59 c2 04 00 8b 46 08 83 f8 ff }
    $sequence_15 = { 3b cb 74 61 8b 01 83 f8 07 }
    $sequence_16 = { 3b cb 75 3c ff 77 08 eb 28 }
    $sequence_17 = { eb 29 48 8d 4c 24 48 e8 ?? ?? ?? ?? }
    $sequence_18 = { e9 ?? ?? ?? ?? 8d 85 d0 fd ff ff 50 ff 15 ?? ?? ?? ?? }
    $sequence_19 = { 89 4c 9a 08 8b 5d f8 03 cb 8b 5d 0c 23 c8 }
    $sequence_20 = { ff 75 08 ff d7 85 c0 75 16 ff 15 ?? ?? ?? ?? 68 43 45 8a 04 }
    $sequence_21 = { 0d 00 00 07 80 89 06 e8 ?? ?? ?? ?? 48 8b d6 48 }
    $sequence_22 = { 3b cb 74 3b 6a fe 58 89 01 }

  condition:
    7 of them and filesize < 663552
}