rule MALPEDIA_Win_Parallax_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "3331f8f9-ca97-5323-a8b7-4a2a5bd3b734"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.parallax"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.parallax_auto.yar#L1-L123"
    license_url        = "N/A"
    logic_hash         = "2375ab4fbfb357ff0388c05531234fe1711b2c1ab93377989bbf9dcbb0552a8e"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0 = { 8d bf 8c 00 00 00 b9 34 00 00 00 f3 a4 5e 56 ff 75 08 }
    $sequence_1 = { ff 75 08 ff 96 98 01 00 00 5e 5d c2 14 00 55 8b ec }
    $sequence_2 = { 8b 52 34 83 c2 34 89 15 ?? ?? ?? ?? 83 be 18 01 00 00 00 75 45 83 be 18 01 00 00 00 74 01 }
    $sequence_3 = { ff 76 3c 68 3c 80 00 00 ff 35 ?? ?? ?? ?? ff 92 e0 01 00 00 6a 00 }
    $sequence_4 = { 74 11 8b 75 ec 8b 7d e0 8b 4d e8 f3 a4 }
    $sequence_5 = { 85 c0 74 18 8b f8 8b 35 ?? ?? ?? ?? b8 ff ff ff ff f0 87 47 04 50 }
    $sequence_6 = { 6a 00 ff 96 28 01 00 00 6a 04 68 ?? ?? ?? ?? }
    $sequence_7 = { e9 ?? ?? ?? ?? 3d 34 80 00 00 75 0d ff 75 14 ff 75 10 e8 ?? ?? ?? ?? eb 6d }
    $sequence_8 = { 8b 56 34 83 c2 34 52 52 }
    $sequence_9 = { 83 e9 34 8b 47 34 83 c0 34 8b 15 ?? ?? ?? ?? 50 51 ff 92 dc 00 00 00 }

  condition:
    7 of them and filesize < 352256
}