rule MALPEDIA_Win_Upatre_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "1628c1f9-1d48-5501-a98b-2c8f976e35eb"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.upatre"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.upatre_auto.yar#L1-L164"
    license_url        = "N/A"
    logic_hash         = "ec286f640db5a5b7bffd2eededa524e0947ea3452d78b30e2aeb2f315c32ce53"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0  = { 66 ab 33 c0 66 ab bb ff 0f 00 00 8b 75 f0 }
    $sequence_1  = { 89 45 fc 8b d8 03 c1 8b f8 33 c0 }
    $sequence_2  = { 89 4d 90 8b 4d 8c 85 c9 75 01 c3 57 }
    $sequence_3  = { 74 14 4e 56 ff 75 f0 }
    $sequence_4  = { 04 30 66 ab 81 c6 0e 01 00 00 ac }
    $sequence_5  = { 89 45 ec 6a 00 8d 4d c0 51 ff 75 e0 ff 75 bc ff 75 ec }
    $sequence_6  = { 89 5d 98 8b fb 03 d8 b9 1c 01 00 00 }
    $sequence_7  = { b9 00 10 00 00 03 c1 89 45 f0 03 c1 }
    $sequence_8  = { 83 c0 08 89 45 bc 8b 4d bc 8b 51 04 52 }
    $sequence_9  = { 8b 55 d4 8b 44 0a 1c 89 45 f4 8b 4d f0 }
    $sequence_10 = { 0f 94 c0 85 c0 74 36 8b 4d d8 83 c1 02 2b 4d e8 }
    $sequence_11 = { e3 c9 1b b6 ae ac a8 44 bb cd cc 70 e8 73 9c d4 ef }
    $sequence_12 = { eb 2b 8b 4d f4 8b 51 0c 52 e8 ?? ?? ?? ?? 83 c4 04 0f b7 c0 }
    $sequence_13 = { 8b 45 08 03 45 f0 0f be 08 8b 55 10 0f af 55 f8 0f af 55 f0 33 ca }
    $sequence_14 = { 89 45 dc 8b 4d dc 66 8b 11 66 89 55 f0 0f b7 45 f0 }
    $sequence_15 = { 89 4d f4 8b 55 f4 3b 55 0c 7d 28 }

  condition:
    7 of them and filesize < 294912
}