rule win_vanhelsing_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.vanhelsing."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.vanhelsing"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 5d c3 55 8bec 81ec9c000000 8b450c 53 }
                                                                                                
        $sequence_1 = { 8b4518 0f1000 0f1145cc 0f104010 8b01 8b4904 8945ec }
                                                                                                
        $sequence_2 = { 660f380035???????? 0f57c8 660f38000d???????? 0f29b520ffffff 0f294df0 0f28c6 660fd4c3 }
                                                                                                
        $sequence_3 = { 8b45e4 8b048598485600 8b4de0 f644082801 7515 e8???????? c70009000000 }
                                                                                                
        $sequence_4 = { 85c9 7410 8a80b4d44800 8806 46 41 897590 }
                                                                                                
        $sequence_5 = { 6a00 6a00 6800000008 ff15???????? 6a03 6a00 6a00 }
                                                                                                
        $sequence_6 = { 888570fbffff 240f 884580 8a06 888571fbffff 240f 884581 }
                                                                                                
        $sequence_7 = { 039d48ffffff 8b4dc8 138de8feffff 039df0feffff 898530ffffff 8bc3 138ddcfeffff }
                                                                                                
        $sequence_8 = { 7f4f 8d4608 50 8d85d8fbffff 68???????? 50 e8???????? }
                                                                                                
        $sequence_9 = { 0fb6cb c1e803 83e107 0fb67405dc 8d8514ffffff d3ee 83e601 }
                                                                                                
    condition:
        7 of them and filesize < 2981888
}