SecRule ARGS_COMBINED_SIZE "@gt %{tx.total_arg_length}"          "t:none,         setvar:'tx.inbound_anomaly_score_pl1=+%{tx.critical_anomaly_score}'"


#
# -- File upload limits --
#
# Individual file size is limited