rule win_atlas_agent_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.atlas_agent."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.atlas_agent"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 0fb60c0a 83e13c c1f902 03c1 }
                                                            
        $sequence_1 = { 8bc1 99 b903000000 f7f9 c1e002 }
                                                                        
        $sequence_2 = { 8a80c0ba0410 84c0 7f1f 8bce }
                                                            
        $sequence_3 = { 8a55fe 8810 8d4508 50 }
                                                            
        $sequence_4 = { 8a55f3 8855f1 0fb645f1 85c0 746c 68???????? 8d4dd8 }
                                                                                                
        $sequence_5 = { 8a5de3 8b0495e0b50410 885c012e 8b0495e0b50410 }
                                                            
        $sequence_6 = { 57 4883ec20 8bfa 4c8d0d517f0100 }
                                                            
        $sequence_7 = { 57 4883ec20 488d1daf180300 488d3da8180300 eb12 488b03 }
                                                                                    
        $sequence_8 = { 57 4883ec20 8bda 4c8d0d35810100 }
                                                            
        $sequence_9 = { 57 4883ec20 8bf9 e8???????? 4885c0 7509 488d0533ed0200 }
                                                                                                
        $sequence_10 = { 8a55ff 8810 8b45ec 83c001 }
                                                            
        $sequence_11 = { 57 4883ec20 4c8bda 488d2d5737fdff }
                                                            
        $sequence_12 = { 8a55ff 8811 8b45f4 50 e8???????? 83c404 8945f0 }
                                                                                                
        $sequence_13 = { 57 4883ec20 488d1ddb180300 488d3dd4180300 }
                                                            
    condition:
        7 of them and filesize < 857088
}