rule MALPEDIA_Win_Mars_Stealer_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "d22235ef-5968-5e10-be47-3cfb22c5f1b3"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.mars_stealer"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.mars_stealer_auto.yar#L1-L116"
    license_url        = "N/A"
    logic_hash         = "b25b9578c7efb2902b746c00b6410a6cd2ad1c64e90ea264af3674a130d6b800"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0 = { 33 04 95 08 67 41 00 89 45 08 8b 4d 0c 83 c1 01 89 4d 0c 8b 55 0c }
    $sequence_1 = { 8b 51 18 52 8b 85 3c fb ff ff 8b 48 14 }
    $sequence_2 = { 89 85 64 e6 ff ff 83 bd 64 e6 ff ff 00 0f 84 05 03 00 00 6a 00 }
    $sequence_3 = { a1 ?? ?? ?? ?? 50 8b 4d 08 51 e8 ?? ?? ?? ?? 83 c4 10 6a 04 }
    $sequence_4 = { 8b 55 08 c1 ea 08 33 14 8d 08 67 41 00 89 55 08 8b 45 0c }
    $sequence_5 = { 52 8d 85 e8 fe ff ff 50 68 ?? ?? ?? ?? 8b 4d f8 51 }
    $sequence_6 = { 83 7d f8 20 0f 8d 61 03 00 00 68 04 01 00 00 8d 8d e8 fe ff ff 51 e8 ?? ?? ?? ?? }
    $sequence_7 = { 2b 4d 08 c6 81 40 7c 41 00 00 8b 55 0c 89 55 f8 }
    $sequence_8 = { 8b 95 3c fb ff ff 8b 42 14 83 c0 20 50 6a 00 }
    $sequence_9 = { 52 8b 85 fc fb ff ff 50 ff 15 ?? ?? ?? ?? 89 85 7c de ff ff }

  condition:
    7 of them and filesize < 219136
}