rule MALPEDIA_Win_Protonbot_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "b19d2c4d-3d72-5fe6-aaaa-c0b323237a91"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.protonbot"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.protonbot_auto.yar#L1-L123"
    license_url        = "N/A"
    logic_hash         = "9f42d2358a0490651f249ec756eecbb8cc6207cec8ace7f179285ca0a209261c"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0 = { 0f 43 45 50 6a 00 6a 00 6a 00 }
    $sequence_1 = { 8b 36 8d 44 24 08 50 56 e8 ?? ?? ?? ?? 83 c4 08 83 f8 08 }
    $sequence_2 = { e8 ?? ?? ?? ?? 8d 8d d4 fe ff ff e8 ?? ?? ?? ?? 83 c4 18 c6 45 fc 01 }
    $sequence_3 = { 89 9d f8 ff fe ff e8 ?? ?? ?? ?? 83 c4 10 8b f8 }
    $sequence_4 = { 8b f1 6a 04 c7 45 fc 01 00 00 00 e8 ?? ?? ?? ?? 83 c4 04 8b f8 }
    $sequence_5 = { 83 7f 14 10 72 02 8b 3f 57 50 e8 ?? ?? ?? ?? ff b5 d4 fe ff ff }
    $sequence_6 = { 7f 8d 5e 5f 33 c0 5b 8b 4d fc }
    $sequence_7 = { 50 8d 45 f4 64 a3 00 00 00 00 8b da 8b f9 8d 8d d8 fe ff ff }
    $sequence_8 = { 8d 85 b8 fb ff ff 0f 43 85 b8 fb ff ff 50 8d 85 d0 fb ff ff 68 ff 00 00 00 50 e8 ?? ?? ?? ?? }
    $sequence_9 = { b9 01 00 00 00 8b c2 c1 e8 1e 33 c2 69 d0 65 89 07 6c 03 d1 89 94 8d 54 ec ff ff }

  condition:
    7 of them and filesize < 1073152
}