rule MALPEDIA_Win_Rtm_Locker_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "a8f49436-bcde-542d-92ad-a9016371f8b8"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.rtm_locker"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.rtm_locker_auto.yar#L1-L127"
    license_url        = "N/A"
    logic_hash         = "61d8b5fbf492d5b9d06c2052f9a6a3111c4e3f003fd0450ca27ee699de4151fc"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0 = { 8d 8d 2c fe ff ff e8 ?? ?? ?? ?? 0f 10 8d 64 fc ff ff 33 c9 0f 10 95 74 fc ff ff 0f 10 9d 84 fc ff ff 0f 10 a5 94 fc ff ff }
    $sequence_1 = { 0f 10 46 30 66 0f ef d0 0f 10 06 66 0f ef c8 0f 11 0f 0f 11 67 10 0f 11 5f 20 }
    $sequence_2 = { 0f 29 44 24 70 0f 28 84 24 70 01 00 00 0f 29 84 24 20 01 00 00 0f 28 84 24 80 01 00 00 89 44 24 58 83 c0 04 89 4c 24 5c }
    $sequence_3 = { e8 ?? ?? ?? ?? 8d 8d 68 ff ff ff e8 ?? ?? ?? ?? 0f 10 85 68 ff ff ff be 18 00 00 00 0f 11 85 c8 fe ff ff }
    $sequence_4 = { 0f be 80 98 07 42 00 40 89 45 cc 2b 45 dc 89 45 d4 3b c2 0f 8f 10 02 00 00 }
    $sequence_5 = { 50 6a f5 eb 03 50 6a f6 ff 15 ?? ?? ?? ?? 8b 04 bd 50 0f 42 00 }
    $sequence_6 = { c1 f9 10 88 4e 02 8b 4d e0 0a c1 88 46 03 8b c1 c1 f8 08 }
    $sequence_7 = { 89 7d fc 89 7d b8 89 45 08 85 c0 0f 8f 3f fe ff ff }
    $sequence_8 = { 8d 44 24 30 50 ff 15 ?? ?? ?? ?? 8b f0 83 fe ff 74 31 }
    $sequence_9 = { 8b 0c 85 50 0f 42 00 8b 45 f8 80 7c 01 28 00 7d 46 }

  condition:
    7 of them and filesize < 598016
}