rule MALPEDIA_Win_Wipbot_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "2dc6790b-0815-56da-b4e1-b1ab1c837c71"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.wipbot"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.wipbot_auto.yar#L1-L133"
    license_url        = "N/A"
    logic_hash         = "b4a431b5982e86b4c79c71104a1485b7ef9ede4d9bcd19d6e305251f54be5168"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0 = { eb 05 b8 ?? ?? ?? ?? e8 ?? ?? ?? ?? 89 da 83 c9 ff e8 ?? ?? ?? ?? }
    $sequence_1 = { 5b 5d e9 ?? ?? ?? ?? 5a 31 c0 5b 5d }
    $sequence_2 = { 4c 8d 44 24 28 ba ff 01 0f 00 48 89 d9 ff d0 48 }
    $sequence_3 = { b9 11 00 00 00 31 c0 c6 44 24 5e 2e 31 d2 f3 aa c6 44 24 5f 0b c6 44 24 60 1f }
    $sequence_4 = { 85 c0 48 89 c6 0f 94 c2 48 85 db 0f 94 c0 }
    $sequence_5 = { 8d 44 24 5f 88 d1 48 01 d0 48 ff c2 32 08 }
    $sequence_6 = { eb 7d 48 89 4c 24 38 e8 ?? ?? ?? ?? 01 c0 ba 9a d6 5f b0 b9 8a 75 8b 1f }
    $sequence_7 = { 8d 55 f4 89 54 24 08 8d 55 f0 c7 44 24 0c 00 80 00 00 89 54 24 04 c7 04 24 ff ff ff ff ff d0 }
    $sequence_8 = { 89 cb b9 1d 00 00 00 c6 44 24 22 2e f3 aa c6 44 24 23 79 c6 44 24 24 46 31 c0 }
    $sequence_9 = { 89 44 24 0c 8b 45 a8 83 c0 20 89 04 24 ff d2 85 c0 0f 9f c0 }

  condition:
    7 of them and filesize < 253952
}