rule RedPeanut
{
    meta:
        description = "Detection patterns for the tool 'RedPeanut' taken from the ThreatHunting-Keywords github project"
        author = "@mthcht"
        reference = "https://github.com/mthcht/ThreatHunting-Keywords"
        tool = "RedPeanut"
        rule_category = "offensive_tool_keyword"

    strings:
                        $string1 = " EvilClippyManager" nocase ascii wide
                        $string2 = /\/C2\/Http\/.{0,1000}\.cs/ nocase ascii wide
                        $string3 = /\/C2\/SmbListener\./ nocase ascii wide
                        $string4 = /\/C2Manager\.cs/ nocase ascii wide
                        $string5 = /\/DonutCS\/Donut\.cs/ nocase ascii wide
                        $string6 = "/EvilClippy" nocase ascii wide
                        $string7 = /\/redpeanut\.cer/ nocase ascii wide
                        $string8 = /\/RedPeanut\.git/ nocase ascii wide
                        $string9 = /\/RedPeanut\.html/ nocase ascii wide
                        $string10 = "/RedPeanutAgent/" nocase ascii wide
                        $string11 = "/RedPeanutRP/" nocase ascii wide
                        $string12 = /\\EvilClippy/ nocase ascii wide
                        $string13 = /ahsten\.run\s\\.{0,1000}powershell\.exe/ nocase ascii wide
                        $string14 = "AssmblyLoader" nocase ascii wide
                        $string15 = "AutoCompletionHandlerC2ServerManager" nocase ascii wide
                        $string16 = "b4rtik/RedPeanut" nocase ascii wide
                        $string17 = "b4rtik/RedPeanut" nocase ascii wide
                        $string18 = /C2\/C2Server\./ nocase ascii wide
                        $string19 = /C2Server\.cs/ nocase ascii wide
                        $string20 = "CreateC2Server" nocase ascii wide
                        $string21 = /donut\s\-f\s.{0,1000}\.dll\s\-c\s.{0,1000}\s\-m\sRunProcess/ nocase ascii wide
                        $string22 = /donut\s\-f\sc2\.dll/ nocase ascii wide
                        $string23 = /DonutLoader\.cs/ nocase ascii wide
                        $string24 = "evilclippy " nocase ascii wide
                        $string25 = /EvilClippy\.exe/ nocase ascii wide
                        $string26 = /EvilClippyManager\./ nocase ascii wide
                        $string27 = "EvilClippyMenu" nocase ascii wide
                        $string28 = /execute\-assembly.{0,1000}Seatbelt/ nocase ascii wide
                        $string29 = "GenerateDllBase64Hta" nocase ascii wide
                        $string30 = "GenerateExeBase64" nocase ascii wide
                        $string31 = "GetC2Server" nocase ascii wide
                        $string32 = "Get-CompressedAgent" nocase ascii wide
                        $string33 = /Get\-CompressedAgent\.ps1/ nocase ascii wide
                        $string34 = "Get-CompressedShellcode" nocase ascii wide
                        $string35 = /Get\-CompressedShellcode\.ps1/ nocase ascii wide
                        $string36 = /HtaPowershellGenerator\./ nocase ascii wide
                        $string37 = /HtaVBSGenerator\./ nocase ascii wide
                        $string38 = "HttpEvilClippyController" nocase ascii wide
                        $string39 = "Import powerview" nocase ascii wide
                        $string40 = /Keylogger\.cs/ nocase ascii wide
                        $string41 = /Mimikatz\.cs/ nocase ascii wide
                        $string42 = /MSOfficeManipulator\.cs/ nocase ascii wide
                        $string43 = /PersAutorun\.cs/ nocase ascii wide
                        $string44 = /PersCLRInstall\.cs/ nocase ascii wide
                        $string45 = /PersStartup\.cs/ nocase ascii wide
                        $string46 = /PowershellAgentGenerator\./ nocase ascii wide
                        $string47 = "PowershellAmsiGenerator" nocase ascii wide
                        $string48 = /PowershellCradleGenerator\./ nocase ascii wide
                        $string49 = /PowerShellExecuter\.cs/ nocase ascii wide
                        $string50 = /PrivEscManager\.cs/ nocase ascii wide
                        $string51 = /PsExecMenu\(/ nocase ascii wide
                        $string52 = "RedPeanut Smb server started" nocase ascii wide
                        $string53 = /RedPeanut\.Models/ nocase ascii wide
                        $string54 = /redpeanut\.pfx/ nocase ascii wide
                        $string55 = /RedPeanut\.Resources\..{0,1000}\.txt/ nocase ascii wide
                        $string56 = /RedPeanut\.Utility/ nocase ascii wide
                        $string57 = /RedPeanutAgent\.C2/ nocase ascii wide
                        $string58 = /RedPeanutAgent\.Core/ nocase ascii wide
                        $string59 = /RedPeanutAgent\.cs/ nocase ascii wide
                        $string60 = /RedPeanutAgent\.Evasion/ nocase ascii wide
                        $string61 = /RedPeanutAgent\.Execution/ nocase ascii wide
                        $string62 = /RedPeanutAgent\.Program/ nocase ascii wide
                        $string63 = "RedPeanutC2" nocase ascii wide
                        $string64 = "RedPeanutCLI" nocase ascii wide
                        $string65 = "RedPeanutDBContext" nocase ascii wide
                        $string66 = "RedPeanutDBInitializer" nocase ascii wide
                        $string67 = "RedPeanutHtaPowerShellScript" nocase ascii wide
                        $string68 = /RedPeanutHtaScript\.hta/ nocase ascii wide
                        $string69 = /RedPeanutInstallUtil\.cs/ nocase ascii wide
                        $string70 = /RedPeanutManager\.cs/ nocase ascii wide
                        $string71 = /RedPeanutMigrate\.cs/ nocase ascii wide
                        $string72 = /RedPeanutMSBuildScript\.xml/ nocase ascii wide
                        $string73 = "RedPeanutPowershellScriptS" nocase ascii wide
                        $string74 = /RedPeanutRP\.cs/ nocase ascii wide
                        $string75 = /RedPeanutShooter\./ nocase ascii wide
                        $string76 = /RedPeanutSpawn\.cs/ nocase ascii wide
                        $string77 = /RedPeanutSpawnTikiTorch\.cs/ nocase ascii wide
                        $string78 = /RedPeanutVBAMacro\.vba/ nocase ascii wide
                        $string79 = /rubeus\.txt/ nocase ascii wide
                        $string80 = "RubeusAskTgtMenu" nocase ascii wide
                        $string81 = "RubeusASREPRoastManager" nocase ascii wide
                        $string82 = "RubeusChangePwManager" nocase ascii wide
                        $string83 = "RubeusCreateNetOnlyManager" nocase ascii wide
                        $string84 = "RubeusDescribeManager" nocase ascii wide
                        $string85 = "RubeusDumpManager" nocase ascii wide
                        $string86 = "RubeusDumpMenu" nocase ascii wide
                        $string87 = "RubeusHarvestManager" nocase ascii wide
                        $string88 = "RubeusHarvestMenu" nocase ascii wide
                        $string89 = "RubeusHashManager" nocase ascii wide
                        $string90 = "RubeusKerberoastManager" nocase ascii wide
                        $string91 = "RubeusKerberoastMenu" nocase ascii wide
                        $string92 = "RubeusKlistManager" nocase ascii wide
                        $string93 = "RubeusManager" nocase ascii wide
                        $string94 = "RubeusMonitorManager" nocase ascii wide
                        $string95 = "RubeusMonitorMenu" nocase ascii wide
                        $string96 = "RubeusPttManager" nocase ascii wide
                        $string97 = "RubeusPttMenu" nocase ascii wide
                        $string98 = "RubeusPurgeManager" nocase ascii wide
                        $string99 = "RubeusPurgeMenu" nocase ascii wide
                        $string100 = "RubeusRenewManager" nocase ascii wide
                        $string101 = "RubeusRenewMenu" nocase ascii wide
                        $string102 = "RubeusS4UManager" nocase ascii wide
                        $string103 = "RubeusS4UMenu" nocase ascii wide
                        $string104 = "RubeusTgtDelegManager" nocase ascii wide
                        $string105 = "RubeusTgtDelegMenu" nocase ascii wide
                        $string106 = "RubeusTriageManager" nocase ascii wide
                        $string107 = /SafetyKatz\.Program/ nocase ascii wide
                        $string108 = /safetykatz\.txt/ nocase ascii wide
                        $string109 = "SafetyKatzManager" nocase ascii wide
                        $string110 = /sharpadidnsdump\./ nocase ascii wide
                        $string111 = "SharpAdidnsdumpManager" nocase ascii wide
                        $string112 = "SharpAdidnsdumpMenu" nocase ascii wide
                        $string113 = /SharpCOMManager\.cs/ nocase ascii wide
                        $string114 = "SharpDPAPI" nocase ascii wide
                        $string115 = /SharpDPAPIMachine.{0,1000}\.cs/ nocase ascii wide
                        $string116 = "SharpGPOAddComputer" nocase ascii wide
                        $string117 = "SharpGPOAddLocalAdmin" nocase ascii wide
                        $string118 = /SharpGPOAddUser.{0,1000}Manager/ nocase ascii wide
                        $string119 = "Sharpkatz" nocase ascii wide
                        $string120 = "SharpkatzManager" nocase ascii wide
                        $string121 = "SharpMiniDump" nocase ascii wide
                        $string122 = "SharpMiniDumpManager" nocase ascii wide
                        $string123 = "sharppsexec" nocase ascii wide
                        $string124 = "SharpPsExecManager" nocase ascii wide
                        $string125 = /SharpPsExecService\./ nocase ascii wide
                        $string126 = /SharpSpawner\.cs/ nocase ascii wide
                        $string127 = "SharpSploitDomainRecon" nocase ascii wide
                        $string128 = "SharpSploitDomainReconImpl" nocase ascii wide
                        $string129 = "SharpUpManager" nocase ascii wide
                        $string130 = /SharpUpMenu\(/ nocase ascii wide
                        $string131 = /SharpWebManager\.cs/ nocase ascii wide
                        $string132 = /SharpWMI\.Program/ nocase ascii wide
                        $string133 = "SharpWmiManager" nocase ascii wide
                        $string134 = /SpawnAsAgentManager\.cs/ nocase ascii wide
                        $string135 = "spawnasshellcode" nocase ascii wide
                        $string136 = "SpawnAsShellcodeManager" nocase ascii wide
                        $string137 = "SpawnPPIDAgentManager" nocase ascii wide
                        $string138 = /SpawnShellcode\.cs/ nocase ascii wide
                        $string139 = "SpawnShellcodeManager" nocase ascii wide
                        $string140 = "SSploitEnumeration" nocase ascii wide
                        $string141 = "SSploitEnumerationDomain" nocase ascii wide
                        $string142 = "SSploitExecution_DynamicInvoke" nocase ascii wide
                        $string143 = "SSploitExecution_Injection" nocase ascii wide
                        $string144 = "SSploitLateralMovement" nocase ascii wide
                        $string145 = "SSploitPersistence" nocase ascii wide
                        $string146 = "SSploitPrivilegeEscalation" nocase ascii wide
                        $string147 = /UACTokenManipulationManager\.cs/ nocase ascii wide
                        $string148 = "using donutCS" nocase ascii wide
                        $string149 = "We had a woodoo" nocase ascii wide

    condition:
        any of them
}