rule MALPEDIA_Win_Tflower_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "b4660b68-51d0-51ac-bbdd-acf4449bc6d1"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.tflower"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.tflower_auto.yar#L1-L158"
    license_url        = "N/A"
    logic_hash         = "82eb88790bbfb711d9ea01573d045bd4c38f5ceb308c5ccacf5ea018abeab10b"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0  = { 00 01 02 00 01 03 03 03 }
    $sequence_1  = { 00 01 77 08 00 f3 76 08 }
    $sequence_2  = { 00 02 74 08 00 f7 73 08 }
    $sequence_3  = { 00 1a 0c 05 00 3c 0c 05 00 4e 0c 05 }
    $sequence_4  = { 00 08 74 08 00 02 74 08 }
    $sequence_5  = { c1 e1 04 0f b6 d0 8b 84 24 8c 00 00 00 c1 e2 04 8b aa 40 6f 4f 00 }
    $sequence_6  = { 00 0f 77 08 00 01 77 08 }
    $sequence_7  = { c7 40 54 20 16 46 00 eb 5e 57 e8 ?? ?? ?? ?? }
    $sequence_8  = { 3b f7 72 e3 5b 5f b0 01 5e }
    $sequence_9  = { 00 10 74 0b 00 21 74 0b }
    $sequence_10 = { 0f b6 c0 33 0c 85 c0 fe 4e 00 0f b6 c3 8b 5f 28 33 0c 85 c0 fa 4e 00 33 f1 8d 04 11 }
    $sequence_11 = { 8b 75 fc 8b 7d f4 c6 03 01 eb 06 8b 75 fc 8b 7d f4 }
    $sequence_12 = { 89 4c 24 48 74 36 8b 44 24 10 8d 90 c8 79 50 00 }
    $sequence_13 = { 33 0c 85 20 dd 4e 00 8b 44 24 14 c1 e8 18 33 0c 85 20 d9 4e 00 8b 44 24 2c 0f b6 c0 }
    $sequence_14 = { 6a 35 eb 2b 8b fb eb 04 8b 44 24 14 ff 74 24 20 }
    $sequence_15 = { 00 0b 86 05 ?? ?? ?? ?? 00 78 85 05 00 78 86 05 }

  condition:
    7 of them and filesize < 6578176
}