rule win_rover_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.rover."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.rover"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 7478 8b4c2474 8d442434 50 68ff3f0000 8d83f4050000 50 }
                                                                                                
        $sequence_1 = { eb03 83c604 56 ff15???????? 33c9 83c404 84c0 }
                                                                                                
        $sequence_2 = { 8b0d???????? 50 51 6a02 6a1c 8d9424dc000000 52 }
                                                                                                
        $sequence_3 = { 8b5b10 8b44241c 8d4bfc 3bc1 745c 8928 83c004 }
                                                                                                
        $sequence_4 = { eb6a 80bc241d01000000 7409 51 ff15???????? eb57 80bc241e01000000 }
                                                                                                
        $sequence_5 = { 85c0 740c 8b0d???????? 8b5140 50 ffd2 8d442428 }
                                                                                                
        $sequence_6 = { 83beb000000000 0f846d030000 83bb5802000000 742c 83bb4087000000 7523 8b8e94000000 }
                                                                                                
        $sequence_7 = { 33ff 837d3805 89442410 894c2414 897c240c 750e 8bc6 }
                                                                                                
        $sequence_8 = { 897c2424 83ffff 0f84e8060000 8b2d???????? }
                                                            
        $sequence_9 = { ff25???????? 8d8d48ffffff ff25???????? 8b542408 8d8230ffffff 8b8a2cffffff 33c8 }
                                                                                                
    condition:
        7 of them and filesize < 704512
}