rule MALPEDIA_Win_Boldmove_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "ede55e68-ab48-582c-bf7e-2cb826551211"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.boldmove"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.boldmove_auto.yar#L1-L129"
    license_url        = "N/A"
    logic_hash         = "d529b7724e2e647d4848b38aca8e76a61b2caa5c4bf1c77fa8242a3dc71a9c2d"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0 = { 0f b6 55 e4 d3 e2 8b 8b 24 30 00 00 09 d0 88 04 31 31 c0 }
    $sequence_1 = { 89 1c 24 e8 ?? ?? ?? ?? 89 34 24 e8 ?? ?? ?? ?? 8b 44 24 34 85 c0 }
    $sequence_2 = { 0f 85 cf 06 00 00 c7 44 24 68 00 00 00 00 8b 4c 24 34 b8 01 00 00 00 85 c9 0f 4f c1 89 84 24 9c 00 00 00 }
    $sequence_3 = { 83 cd 02 89 44 24 48 e9 ?? ?? ?? ?? 8d 47 01 83 cd 08 89 44 24 48 }
    $sequence_4 = { e8 ?? ?? ?? ?? 89 c5 8b 44 24 38 89 2c 24 89 44 24 04 e8 ?? ?? ?? ?? 8b 4c 24 24 }
    $sequence_5 = { 8b 44 24 20 89 fb 8b 10 e9 ?? ?? ?? ?? 85 f6 7e 03 83 ee 01 }
    $sequence_6 = { 8b 83 14 10 00 00 31 d2 39 d0 74 0c 39 b4 93 18 10 00 00 74 18 42 }
    $sequence_7 = { 85 db 0f 84 56 1d 00 00 81 fe 00 04 00 00 b8 00 04 00 00 0f 4e c6 89 04 24 89 44 24 40 }
    $sequence_8 = { 8d 4f 04 74 15 83 7c 24 28 01 0f 84 73 05 00 00 83 7c 24 28 05 75 03 0f be c0 }
    $sequence_9 = { 8b 83 10 08 00 00 31 d2 39 d0 74 0c 39 b4 93 14 08 00 00 }

  condition:
    7 of them and filesize < 242688
}