rule win_rising_sun_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.rising_sun."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.rising_sun"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { e8???????? 488d8c2420080000 e9???????? 483b05???????? 750a e8???????? }
                                                                                    
        $sequence_1 = { 488b05???????? 4833c4 48898424a0080000 488bd9 488d8c24a1020000 33d2 41b8fb050000 }
                                                                                                
        $sequence_2 = { 7905 83c8ff eb28 498bc6 4c3b7710 720b b957000780 }
                                                                                                
        $sequence_3 = { 42890421 488b442428 83c30f 4863cb 83c308 4a890421 }
                                                                                    
        $sequence_4 = { e8???????? 48c744247000010000 4c89642448 4c89642450 488bfe 4c89642420 4885ff }
                                                                                                
        $sequence_5 = { 488b8828010000 488b01 8a08 880a 33c9 4c8d058e760000 388c2498000000 }
                                                                                                
        $sequence_6 = { 488985e0080000 448bea 488bd9 c744245018d32263 c744245407137a55 c744245883e85ad2 c744245cee3ed142 }
                                                                                                
        $sequence_7 = { 4c89642458 4c89642460 4c89642468 4c89642470 4c89642478 44896580 4489642440 }
                                                                                                
        $sequence_8 = { c74538a9bcad89 c7453ca6ac81a6 c74540a1bca1a9 c74544a4a1b2ad c745489ba1acc8 c7454cc8c8c8c8 }
                                                                                    
        $sequence_9 = { eb39 6683f93f 0f8510040000 4883c002 }
                                                            
    condition:
        7 of them and filesize < 409600
}