rule MALPEDIA_Win_Yoddos_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "731c8af4-0cfb-5784-8919-5690671f4ddf"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.yoddos"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.yoddos_auto.yar#L1-L126"
    license_url        = "N/A"
    logic_hash         = "ffa9bd7fe378e38b72240a0efe08e70cc8c93f69e8ec293489b47b5a90d316d8"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0 = { ff 15 ?? ?? ?? ?? 85 c0 0f 84 e0 01 00 00 8d 85 84 fc ff ff 56 50 }
    $sequence_1 = { 66 89 5d d8 66 89 5d da 6a 0e e8 ?? ?? ?? ?? 59 8a 84 85 a4 ec ff ff 88 45 dc }
    $sequence_2 = { 74 0c ff b5 c0 fc ff ff ff 15 ?? ?? ?? ?? b8 63 00 00 00 90 b8 9d ff ff ff }
    $sequence_3 = { c6 45 8e 65 c6 45 8f 6e c6 45 90 55 c6 45 91 72 c6 45 92 6c c6 45 93 41 }
    $sequence_4 = { b8 9d ff ff ff 90 33 db 89 1d ?? ?? ?? ?? b8 63 00 00 00 90 b8 9d ff ff ff }
    $sequence_5 = { 0c 01 c1 f9 05 83 e6 1f 88 45 0b 8d 3c 8d 00 76 41 00 c1 e6 03 }
    $sequence_6 = { 89 5d fc c7 85 38 ff ff ff 62 00 00 00 68 ?? ?? ?? ?? 50 e8 ?? ?? ?? ?? ff 75 08 8d 85 24 fe ff ff }
    $sequence_7 = { 57 ff 75 08 e8 ?? ?? ?? ?? 8b f8 56 03 7d 08 }
    $sequence_8 = { 0f b7 75 0c 66 83 f9 7e 75 02 33 c9 0f b7 d1 8a 94 55 04 ff ff ff 30 10 }
    $sequence_9 = { eb 28 8d 4d f0 6a 10 51 }

  condition:
    7 of them and filesize < 557056
}