rule MALPEDIA_Win_Oddjob_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "05ff5b48-0b07-5c37-b3fa-78979fc46d1b"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.oddjob"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.oddjob_auto.yar#L1-L124"
    license_url        = "N/A"
    logic_hash         = "cba635f9b22031c02deb6504fbb70476906689529cb50c775ead5481738df2df"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0 = { e8 ?? ?? ?? ?? 59 8d 95 30 ff ff ff 6a 01 8b cb 8b c2 }
    $sequence_1 = { c6 85 52 fb ff ff 43 c6 85 53 fb ff ff 5e c6 85 54 fb ff ff 5b c6 85 55 fb ff ff 8b c6 85 56 fb ff ff 4b }
    $sequence_2 = { 66 3d 36 00 75 1f 66 83 7f 02 34 75 18 }
    $sequence_3 = { 50 bf ?? ?? ?? ?? 57 6a 04 53 68 ?? ?? ?? ?? ff d6 }
    $sequence_4 = { 8b c3 4b 85 c0 0f 84 98 00 00 00 0f b7 c1 83 f8 41 7c 05 }
    $sequence_5 = { c6 85 96 fa ff ff 24 c6 85 97 fa ff ff 08 c6 85 98 fa ff ff 8b c6 85 99 fa ff ff 43 }
    $sequence_6 = { c6 85 f8 f9 ff ff 40 c6 85 f9 f9 ff ff 68 88 9d fa f9 ff ff c6 85 fb f9 ff ff 10 88 9d fc f9 ff ff 88 9d fd f9 ff ff c6 85 fe f9 ff ff 51 }
    $sequence_7 = { 88 9d 12 f8 ff ff 88 9d 13 f8 ff ff 88 9d 14 f8 ff ff 88 9d 15 f8 ff ff 88 9d 16 f8 ff ff 88 9d 17 f8 ff ff 88 9d 18 f8 ff ff }
    $sequence_8 = { 85 c0 75 03 89 7d fc 39 7d e8 74 09 ff 75 e8 ff 15 ?? ?? ?? ?? }
    $sequence_9 = { 53 68 ?? ?? ?? ?? ff d6 85 c0 74 1c 8d 85 a0 94 ff ff }

  condition:
    7 of them and filesize < 221184
}