rule win_miniblindingcan_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.miniblindingcan."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.miniblindingcan"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { e9???????? 81fbba470000 7513 488d0511350000 488905???????? e9???????? 81fb63450000 }
                                                                                                
        $sequence_1 = { 488bc6 488d1523dd0100 83e11f 48c1f805 486bc958 48030cc2 eb07 }
                                                                                                
        $sequence_2 = { 48893d???????? eb1b 488b0d???????? 488d15bf980100 ff15???????? 488905???????? 4183fc0a }
                                                                                                
        $sequence_3 = { 7478 488b03 83e20f 488907 488b4308 4803de 48894708 }
                                                                                                
        $sequence_4 = { 8bc0 41890c86 498b0c24 490fafc8 48c1e934 8bc9 418b048e }
                                                                                                
        $sequence_5 = { 8d4af3 ff15???????? 41be4c000000 498bcf 488bd0 458bc6 488be8 }
                                                                                                
        $sequence_6 = { 488b8a50000000 e9???????? 4055 4883ec40 488bea 488d4540 4889442430 }
                                                                                                
        $sequence_7 = { b835000000 0f05 c3 4c8bd1 b836000000 0f05 }
                                                                                    
        $sequence_8 = { 448bc7 488bce 488bd0 4c8be0 e8???????? 3bc5 7412 }
                                                                                                
        $sequence_9 = { 488b4c2458 c744244802000000 488d442454 4889442440 }
                                                            
    condition:
        7 of them and filesize < 453632
}