rule win_mozart_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.mozart."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.mozart"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 33f6 c644241800 eb26 8d4c2418 51 }
                                                                        
        $sequence_1 = { 8b542468 41 3bca 736e 8bd0 }
                                                                        
        $sequence_2 = { 7c19 3c39 7f15 bd01000000 eb08 3c30 7c36 }
                                                                                                
        $sequence_3 = { 7471 c1e006 0bc7 a900000001 7425 }
                                                                        
        $sequence_4 = { 0f84a0010000 48 0f84e6000000 48 0f85fd010000 85ed 7544 }
                                                                                                
        $sequence_5 = { 0fbe0a 8a89c8924000 0fb6f9 8bcf 42 83e940 }
                                                                                    
        $sequence_6 = { 8a08 40 84c9 75f9 8b8c2420100000 }
                                                                        
        $sequence_7 = { 90 8a82e0ba4000 3a841420010000 751f b8???????? }
                                                                        
        $sequence_8 = { 83fe10 7409 33f6 c644241800 eb39 80fb3d 740e }
                                                                                                
        $sequence_9 = { 3bd0 72e2 5e 32c0 }
                                                            
    condition:
        7 of them and filesize < 114688
}