rule win_nestegg_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.nestegg."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.nestegg"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 8d4c2420 33ed 89442444 51 }
                                                            
        $sequence_1 = { 6a08 ff15???????? 8be8 b988000000 33c0 8dbc24a8020000 c78424a402000024020000 }
                                                                                                
        $sequence_2 = { 89742410 e8???????? 6a00 6800200000 8d8e2c040000 c744245800000000 }
                                                                                    
        $sequence_3 = { 2bc3 8bce 50 e8???????? 8b8f28040000 }
                                                                        
        $sequence_4 = { 5f 5e 59 c20c00 ff15???????? }
                                                                        
        $sequence_5 = { b907000000 f7f9 42 89542410 8b5500 }
                                                                        
        $sequence_6 = { 7530 50 50 8b44240c 25ffff0000 50 68???????? }
                                                                                                
        $sequence_7 = { 81e1ffff0000 c744243400000000 d1e1 85c9 }
                                                            
    condition:
        7 of them and filesize < 221184
}