name: abilis-network-automation
description: Detect Abilis (Network/Automation)
uuid: 4cc1002e-697e-50bf-9d07-0f20327cae85
query: http_favicon_mmhash:-166151761
tags:
- proto:http
- product:abilis-network-automation
- vendor:abilis
version: 20260918T053418Z