rule win_tflower_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.tflower."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.tflower"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 0001 0200 0103 0303 }
                                                            
        $sequence_1 = { 000f 7708 0001 7708 }
                                                            
        $sequence_2 = { 0002 7408 00f7 7308 }
                                                            
        $sequence_3 = { 89442414 8b06 83f804 0f8728010000 ff2485249d4a00 6a02 6a01 }
                                                                                                
        $sequence_4 = { 001a 0c05 003c0c 05004e0c05 }
                                                            
        $sequence_5 = { 8b148dc0064f00 331485c0024f00 8bc3 c1e808 }
                                                            
        $sequence_6 = { 83fa07 8b542410 775e 8b6c2414 ff24ad9ce34600 0fb679ff }
                                                                                    
        $sequence_7 = { 000b 8605???????? 007885 0500788605 }
                                                            
        $sequence_8 = { 33148520c54e00 33f2 2bde d3c3 8bc3 }
                                                                        
        $sequence_9 = { 0010 740b 0021 740b }
                                                            
        $sequence_10 = { c745e0787f4b00 e9???????? c745e0647f4b00 e9???????? c745dc02000000 }
                                                                        
        $sequence_11 = { 0001 7708 00f3 7608 }
                                                            
        $sequence_12 = { 0008 7408 0002 7408 }
                                                            
        $sequence_13 = { c1e818 8b4d2c c1eb10 03148520c14e00 0fb6c3 8b5d28 }
                                                                                    
        $sequence_14 = { 0fb6c0 8b0c8d20ed4e00 330c8520f14e00 8bc3 c1e818 c1eb10 }
                                                                                    
        $sequence_15 = { 0fbec0 8d89f8feffff 8d0c48 3b0c95788f4f00 }
                                                            
    condition:
        7 of them and filesize < 6578176
}