rule redpill
{
    meta:
        description = "Detection patterns for the tool 'redpill' taken from the ThreatHunting-Keywords github project"
        author = "@mthcht"
        reference = "https://github.com/mthcht/ThreatHunting-Keywords"
        tool = "redpill"
        rule_category = "offensive_tool_keyword"

    strings:
                        $string1 = /\scleantracks\.ps1/ nocase ascii wide
                        $string2 = /\sclipboard\.ps1/ nocase ascii wide
                        $string3 = /\sDumpLsass\.ps1/ nocase ascii wide
                        $string4 = /\sEnumBrowsers\.ps1/ nocase ascii wide
                        $string5 = /\sFWUprank\.ps1/ nocase ascii wide
                        $string6 = /\sGetPasswords\.ps1/ nocase ascii wide
                        $string7 = /\sInvoke\-Dump\.ps1/ nocase ascii wide
                        $string8 = /\slocalbrute\.ps1/ nocase ascii wide
                        $string9 = " -Mouselogger Start" nocase ascii wide
                        $string10 = /\sNoAmsi\.ps1/ nocase ascii wide
                        $string11 = /\sNSudo\.exe/ nocase ascii wide
                        $string12 = /\spapacat\.bat/ nocase ascii wide
                        $string13 = /\spapacat\.bat/ nocase ascii wide
                        $string14 = /\spapacat\.ps1/ nocase ascii wide
                        $string15 = " -PasswordSpray " nocase ascii wide
                        $string16 = /\sPhishCreds\.ps1/ nocase ascii wide
                        $string17 = /\sPingSweep\.ps1/ nocase ascii wide
                        $string18 = /\spowercat\.ps1/ nocase ascii wide
                        $string19 = /\sredpill\.ps1/ nocase ascii wide
                        $string20 = /\srevshell\.ps1/ nocase ascii wide
                        $string21 = /\sScanning\sEventvwr\sregistry\!\s\.\./ nocase ascii wide
                        $string22 = " -SmbLoginSpray " nocase ascii wide
                        $string23 = " -TaskName RedPillTask" nocase ascii wide
                        $string24 = " -UacMe Elevate -Execute " nocase ascii wide
                        $string25 = /\swhoami\s\>\szzz\.txt/ nocase ascii wide
                        $string26 = /\sWinBruteLogon\.zip/ nocase ascii wide
                        $string27 = /\$DumpLsass\=/ nocase ascii wide
                        $string28 = /\$Env\:TMP\\Camera\.ps1/ nocase ascii wide
                        $string29 = /\$Env\:TMP\\GetLogs\.ps1/ nocase ascii wide
                        $string30 = /\$env\:TMP\\Leaked\.txt/ nocase ascii wide
                        $string31 = /\$Env\:TMP\\Screenshot\.ps1/ nocase ascii wide
                        $string32 = /\$Env\:TMP\\StartWebServer\.ps1/ nocase ascii wide
                        $string33 = /\$Env\:TMP\\Start\-WebServer\.ps1/ nocase ascii wide
                        $string34 = /\$Env\:TMP\\tdfr\.log/ nocase ascii wide
                        $string35 = /\$Env\:TMP\\Upload\.ps1/ nocase ascii wide
                        $string36 = /\$Env\:TMP\\webserver\.ps1\.ps1/ nocase ascii wide
                        $string37 = /\$Keylogger\=/ nocase ascii wide
                        $string38 = /\$SmbLoginSpray\=/ nocase ascii wide
                        $string39 = /\%tmp\%\\void\.zip/ nocase ascii wide
                        $string40 = /\.ps1\s\-StartWebServer\sPowershell/ nocase ascii wide
                        $string41 = /\.ps1\s\-StartWebServer\sPython/ nocase ascii wide
                        $string42 = /\.ps1\s\-WifiPasswords\sDump/ nocase ascii wide
                        $string43 = /\/cleantracks\.ps1/ nocase ascii wide
                        $string44 = /\/CsOnTheFly\.ps1/ nocase ascii wide
                        $string45 = /\/DumpLsass\.ps1/ nocase ascii wide
                        $string46 = /\/FWUprank\.ps1/ nocase ascii wide
                        $string47 = /\/GetPasswords\.ps1/ nocase ascii wide
                        $string48 = /\/NSudo\.exe/ nocase ascii wide
                        $string49 = /\/papacat\.bat/ nocase ascii wide
                        $string50 = /\/papacat\.ps1/ nocase ascii wide
                        $string51 = /\/PhishCreds\.ps1/ nocase ascii wide
                        $string52 = /\/powercat\.ps1/ nocase ascii wide
                        $string53 = /\/redpill\.ps1/ nocase ascii wide
                        $string54 = /\/redpill\/bin\/.{0,1000}\.ps1/
                        $string55 = /\/revshell\.ps1/ nocase ascii wide
                        $string56 = /\/RunPEinMemory\.exe/ nocase ascii wide
                        $string57 = /\/RunPEinMemory64\.exe/ nocase ascii wide
                        $string58 = /\/ScanInterception\.ps1/ nocase ascii wide
                        $string59 = /\/stext\scredentials\.log/
                        $string60 = /\/WinBruteLogon\.zip/ nocase ascii wide
                        $string61 = "@Re@mov@e-@MpTh@re@at" nocase ascii wide
                        $string62 = "@redpill CS Compiled Executable" nocase ascii wide
                        $string63 = /\[START\]\:\sPassword\sspraying\sattack\!/ nocase ascii wide
                        $string64 = /\\AdsMasquerade\.ps1/ nocase ascii wide
                        $string65 = /\\AppData\\Local\\Temp\\Camera\.ps1/ nocase ascii wide
                        $string66 = /\\AppData\\Local\\Temp\\GetLogs\.ps1/ nocase ascii wide
                        $string67 = /\\AppData\\Local\\Temp\\Leaked\.txt/ nocase ascii wide
                        $string68 = /\\AppData\\Local\\Temp\\Payload\.ps1/ nocase ascii wide
                        $string69 = /\\AppData\\Local\\Temp\\Screenshot\.ps1/ nocase ascii wide
                        $string70 = /\\AppData\\Local\\Temp\\SSIDump\.zip/ nocase ascii wide
                        $string71 = /\\AppData\\Local\\Temp\\Start\-WebServer\.\.ps1/ nocase ascii wide
                        $string72 = /\\AppData\\Local\\Temp\\StartWebServer\.ps1/ nocase ascii wide
                        $string73 = /\\AppData\\Local\\Temp\\Upload\.ps1/ nocase ascii wide
                        $string74 = /\\AppData\\Local\\Temp\\webserver\.ps1/ nocase ascii wide
                        $string75 = /\\BrowserEnum\.log/ nocase ascii wide
                        $string76 = /\\BrowserLogger\.ps1/ nocase ascii wide
                        $string77 = /\\BypassCredGuard\.exe/ nocase ascii wide
                        $string78 = /\\C2Prank\.ps1/ nocase ascii wide
                        $string79 = /\\cleantracks\.ps1/ nocase ascii wide
                        $string80 = /\\CleanTracks\.ps1/ nocase ascii wide
                        $string81 = /\\clipboard\.ps1/ nocase ascii wide
                        $string82 = /\\Clipboard\.ps1/ nocase ascii wide
                        $string83 = /\\ConfuserEx\\Obfuscated\.exe/ nocase ascii wide
                        $string84 = /\\Convert\-ROT47\.ps1/ nocase ascii wide
                        $string85 = /\\CookieHijack\.ps1/ nocase ascii wide
                        $string86 = /\\credentials\.log/ nocase ascii wide
                        $string87 = /\\CScrandle_fileless\.cs/ nocase ascii wide
                        $string88 = /\\CsOnTheFly\.ps1/ nocase ascii wide
                        $string89 = /\\DecryptAutoLogon\.exe/ nocase ascii wide
                        $string90 = /\\DeletePSscriptSignning\.bat/ nocase ascii wide
                        $string91 = /\\DnSpoof\.ps1/ nocase ascii wide
                        $string92 = /\\DumpLsass\.ps1/ nocase ascii wide
                        $string93 = /\\enc\-rot13\.ps1/ nocase ascii wide
                        $string94 = /\\EnumBrowsers\.ps1/ nocase ascii wide
                        $string95 = /\\ETWpatch\\eventK\.exe/ nocase ascii wide
                        $string96 = /\\evil\.ps1/ nocase ascii wide
                        $string97 = /\\FWUprank\.ps1/ nocase ascii wide
                        $string98 = /\\GetAdmin\.log/ nocase ascii wide
                        $string99 = /\\GetAdmin\.ps1/ nocase ascii wide
                        $string100 = /\\GetPasswords\.ps1/ nocase ascii wide
                        $string101 = /\\gfscgsvs\.log/ nocase ascii wide
                        $string102 = /\\identify_offencive_tools\.log/ nocase ascii wide
                        $string103 = /\\Invoke\-Bypass\.ps1/ nocase ascii wide
                        $string104 = /\\Invoke\-Dump\.ps1/ nocase ascii wide
                        $string105 = /\\KeyDump\.log/ nocase ascii wide
                        $string106 = /\\KeyDump\.log/ nocase ascii wide
                        $string107 = /\\lnk_parser_cmd\.exe\s\-r\s/ nocase ascii wide
                        $string108 = /\\Lnk\-Sweeper\.ps1/ nocase ascii wide
                        $string109 = /\\Lnk\-Sweeper\.txt/ nocase ascii wide
                        $string110 = /\\Local\\Temp\\logins\.log/ nocase ascii wide
                        $string111 = /\\localbrute\.ps1/ nocase ascii wide
                        $string112 = /\\maildump\.txt/ nocase ascii wide
                        $string113 = /\\Meterpeter_.{0,1000}\.zip/ nocase ascii wide
                        $string114 = /\\MineDownloader\.vbs/ nocase ascii wide
                        $string115 = /\\NoAmsi\.ps1/ nocase ascii wide
                        $string116 = /\\NSudo\.exe/ nocase ascii wide
                        $string117 = /\\OutlookEmails\.log/ nocase ascii wide
                        $string118 = /\\papacat\.ps1/ nocase ascii wide
                        $string119 = /\\Persiste\.ps1/ nocase ascii wide
                        $string120 = /\\Persistence\.vbs/ nocase ascii wide
                        $string121 = /\\PhishCreds\.ps1/ nocase ascii wide
                        $string122 = /\\PingSweep\.ps1/ nocase ascii wide
                        $string123 = /\\powercat\.ps1/ nocase ascii wide
                        $string124 = /\\PSexecutionPolicy\.bat/ nocase ascii wide
                        $string125 = /\\psgetsys\.ps1/ nocase ascii wide
                        $string126 = /\\pysecdump\.exe/ nocase ascii wide
                        $string127 = /\\r00t\-3xp10it/ nocase ascii wide
                        $string128 = /\\Rat\-x64\.exe/ nocase ascii wide
                        $string129 = /\\Rat\-x64\.lnk/ nocase ascii wide
                        $string130 = /\\redpill\.ps1/ nocase ascii wide
                        $string131 = /\\redpill\.zip/ nocase ascii wide
                        $string132 = /\\redpill\.zip/ nocase ascii wide
                        $string133 = /\\redpill\\bin\\.{0,1000}\.ps1/ nocase ascii wide
                        $string134 = /\\revshell\.ps1/ nocase ascii wide
                        $string135 = /\\RunPEinMemory\.exe/ nocase ascii wide
                        $string136 = /\\RunPEinMemory64\.exe/ nocase ascii wide
                        $string137 = /\\ScanInterception\.ps1/ nocase ascii wide
                        $string138 = /\\SelectMyParent\.exe/ nocase ascii wide
                        $string139 = /\\sendkeys\.ps1/ nocase ascii wide
                        $string140 = /\\SigFlip\.exe/ nocase ascii wide
                        $string141 = /\\Smeagol\.log/ nocase ascii wide
                        $string142 = /\\Temp\\Wdlogfile\.log/ nocase ascii wide
                        $string143 = /\\URL_obfuscated\.log/ nocase ascii wide
                        $string144 = /\\void\.log/ nocase ascii wide
                        $string145 = /\\WinBruteLogon\.zip/ nocase ascii wide
                        $string146 = /\\windows\\temp\\fakefile\.exe/ nocase ascii wide
                        $string147 = /\\Xclipboard\.ps1/ nocase ascii wide
                        $string148 = /\]\sDumping\sbrowsers\scredentials\s\.\./ nocase ascii wide
                        $string149 = /\]\sDumping\smail\sserv\scredentials\s\.\./ nocase ascii wide
                        $string150 = /\]\sDumping\smessenger\scredentials\s\.\./ nocase ascii wide
                        $string151 = /\]\sSending\scredentials\sto\spastebin\s\.\./ nocase ascii wide
                        $string152 = /\]\sto\sdownload\svoid\.zip\susing\sBitsTransfer/ nocase ascii wide
                        $string153 = /0evilpwfilter\.dll/ nocase ascii wide
                        $string154 = "Administrator privileges required to spoof processes" nocase ascii wide
                        $string155 = /amibypass\.exe/ nocase ascii wide
                        $string156 = /amsibypass\.exe/ nocase ascii wide
                        $string157 = /amsitrigger_x64\.exe/ nocase ascii wide
                        $string158 = /bpysecdump\.exe/ nocase ascii wide
                        $string159 = /CommandCam\.exe\s\/devlist\s\>\s.{0,1000}\\CC\.log/ nocase ascii wide
                        $string160 = /Crandle_Builder\.ps1/ nocase ascii wide
                        $string161 = /CScrandle_fileless\.cs/ nocase ascii wide
                        $string162 = /DarkRCovery\.exe/ nocase ascii wide
                        $string163 = /DecodeRDPCache\.ps1/ nocase ascii wide
                        $string164 = /DEL\s\/q\s\/f\s\%appdata\%\\Google\\Chrome\\\\"User\sData\\"\\Default\\.{0,1000}\.tmp/ nocase ascii wide
                        $string165 = /DEL\s\/q\s\/f\s\%appdata\%\\Google\\Chrome\\\\"User\sData\\"\\Default\\History\\.{0,1000}\./ nocase ascii wide
                        $string166 = /DEL\s\/q\s\/f\s\%appdata\%\\Microsoft\\Windows\\Recent\\.{0,1000}\./ nocase ascii wide
                        $string167 = /DEL\s\/q\s\/f\s\%windir\%\\.{0,1000}\.log/ nocase ascii wide
                        $string168 = /DEL\s\/q\s\/f\s\%windir\%\\.{0,1000}\.tmp/ nocase ascii wide
                        $string169 = /DEL\s\/q\s\/f\s\%windir\%\\Prefetch\\.{0,1000}\.pf/ nocase ascii wide
                        $string170 = /DEL\s\/q\s\/f\s\%windir\%\\system\\.{0,1000}\.log/ nocase ascii wide
                        $string171 = /DEL\s\/q\s\/f\s\%windir\%\\system\\.{0,1000}\.tmp/ nocase ascii wide
                        $string172 = /DEL\s\/q\s\/f\s\%windir\%\\system32\\.{0,1000}\.log/ nocase ascii wide
                        $string173 = /DEL\s\/q\s\/f\s\%windir\%\\system32\\.{0,1000}\.tmp/ nocase ascii wide
                        $string174 = /DEL\s\/q\s\/f\s\%windir\%\\Temp\\.{0,1000}\.inf/ nocase ascii wide
                        $string175 = /DEL\s\/q\s\/f\s\%windir\%\\Temp\\.{0,1000}\.lnk/ nocase ascii wide
                        $string176 = /DEL\s\/q\s\/f\s\/s\s\%appdata\%\\Microsoft\\Windows\\Cookies\\.{0,1000}\./ nocase ascii wide
                        $string177 = /DEL\s\/q\s\/f\s\/s\s\%appdata\%\\Microsoft\\Windows\\Cookies\\.{0,1000}\./ nocase ascii wide
                        $string178 = /DEL\s\/q\s\/f\s\/s\s\%appdata\%\\Microsoft\\Windows\\Recent\\.{0,1000}\./ nocase ascii wide
                        $string179 = /DEL\s\/q\s\/f\s\/s\s\%appdata\%\\Mozilla\\Firefox\\Profiles\\.{0,1000}\./ nocase ascii wide
                        $string180 = /DEL\s\/q\s\/f\s\/s\s\%userprofile\%\\.{0,1000}\.log/ nocase ascii wide
                        $string181 = /DEL\s\/q\s\/f\s\/s\s\%userprofile\%\\.{0,1000}\.tmp/ nocase ascii wide
                        $string182 = /DeletePSscriptSignning\.bat/ nocase ascii wide
                        $string183 = /DigitalSignature\-Hijack\.ps1/ nocase ascii wide
                        $string184 = /Disable\-AMS1\.ps1/ nocase ascii wide
                        $string185 = /DisableDefender\.ps1/ nocase ascii wide
                        $string186 = /DnsSpoof\.ps1/ nocase ascii wide
                        $string187 = /DumpChromePasswords\.ps1/ nocase ascii wide
                        $string188 = /Env\:TMP\\ACl\.log/ nocase ascii wide
                        $string189 = /eviltree_x64\.exe/ nocase ascii wide
                        $string190 = "fail to retrieve SAM hashs!" nocase ascii wide
                        $string191 = /FakeCmdLine\.exe/ nocase ascii wide
                        $string192 = /Fake\-Cmdline\.exe/ nocase ascii wide
                        $string193 = /HarvestBrowserPasswords\.exe/ nocase ascii wide
                        $string194 = /HarvestBrowserPasswords\.pdb/ nocase ascii wide
                        $string195 = /HiddenUser\.ps1/ nocase ascii wide
                        $string196 = /How\-to\-bypass\-UAC\-in\-newer\-Windows\-versions\.html/ nocase ascii wide
                        $string197 = /Invoke\-HiveNightmare\.ps1/ nocase ascii wide
                        $string198 = /Invoke\-LazySign\.ps1/ nocase ascii wide
                        $string199 = "Invoke-Mimikatz" nocase ascii wide
                        $string200 = "Invoke-PortScan" nocase ascii wide
                        $string201 = "Invoke-PuttyCreds" nocase ascii wide
                        $string202 = "Invoke-SAMDump" nocase ascii wide
                        $string203 = "Invoke-SendToPasteBin" nocase ascii wide
                        $string204 = /Invoke\-WDigest\.ps1/ nocase ascii wide
                        $string205 = /Invoke\-WebCamAvi\.ps1/ nocase ascii wide
                        $string206 = "Key`logger running in background" nocase ascii wide
                        $string207 = /Keylogger\.ps1/ nocase ascii wide
                        $string208 = /List\-AllMailboxAndPST\.ps1/ nocase ascii wide
                        $string209 = /meterpeter\.ps1/ nocase ascii wide
                        $string210 = /Meterpeter_\$RandMe\.zip/ nocase ascii wide
                        $string211 = /Mouselogger\.ps1/ nocase ascii wide
                        $string212 = /mozlz4\-win32\.exe/ nocase ascii wide
                        $string213 = /MpCmdRun\.exe\s\-RemoveDefinitions\s\-All/ nocase ascii wide
                        $string214 = /MyMeterpreter\.ps1/ nocase ascii wide
                        $string215 = /Out\-PasteBin\.ps1/ nocase ascii wide
                        $string216 = /patch\-amsi\-x64\-powershell\.ps1/ nocase ascii wide
                        $string217 = /PPIDSpoof\.ps1/ nocase ascii wide
                        $string218 = /PrintNotifyPotato\.exe/ nocase ascii wide
                        $string219 = /PrintNotifyPotato\-NET2\.exe/ nocase ascii wide
                        $string220 = /r00t\-3xp10it\/venom\/master\/bin\/void\.zip/ nocase ascii wide
                        $string221 = /Reg\sAdd\s\'HKLM\\Software\\Policies\\Microsoft\\Windows\sDefender\'\s\/v\sDisableAntiSpyware\s\/t\sREG_DWORD\s\/d\s1\s\/f/ nocase ascii wide
                        $string222 = /REG\sDELETE\s\\"HKCU\\Software\\Classes\\Local\sSettings\\Software\\Microsoft\\Windows\\Shell\\MuiCache\\"\s\/f/ nocase ascii wide
                        $string223 = /REG\sDELETE\s\\"HKCU\\Software\\Microsoft\\Internet\sExplorer\\TypedPaths\\"\s\/f/ nocase ascii wide
                        $string224 = /REG\sDELETE\s\\"HKCU\\Software\\Microsoft\\Internet\sExplorer\\TypedURLs\\"\s\/f/ nocase ascii wide
                        $string225 = /REG\sDELETE\s\\"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\FeatureUsage\\AppBadgeUpdated\\"\s\/f/ nocase ascii wide
                        $string226 = /REG\sDELETE\s\\"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\FeatureUsage\\AppLaunch\\"\s\/f/ nocase ascii wide
                        $string227 = /REG\sDELETE\s\\"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\FeatureUsage\\ShowJumpView\\"\s\/f/ nocase ascii wide
                        $string228 = /REG\sDELETE\s\\"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\RecentDocs\\"\s\/f/ nocase ascii wide
                        $string229 = /REG\sDELETE\s\\"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\RunMRU\\"\s\/f/ nocase ascii wide
                        $string230 = /REG\sDELETE\s\\"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\UserAssist\\"\s\/f/ nocase ascii wide
                        $string231 = /REG\sDELETE\s\\"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Search\\RecentApps\\"\s\/f/ nocase ascii wide
                        $string232 = "-Rem@ov@eDef@ini@tio@ns -@Al@l" nocase ascii wide
                        $string233 = /revTCPclient\.ps1/ nocase ascii wide
                        $string234 = /RevTcpShell\.exe/ nocase ascii wide
                        $string235 = /ScanInterception_x64\.ps1/ nocase ascii wide
                        $string236 = "Scanning ConsoleHost_History for creds" nocase ascii wide
                        $string237 = "Scanning credential store for creds!" nocase ascii wide
                        $string238 = "Scanning registry for winlogon creds" nocase ascii wide
                        $string239 = "Scanning Teamviewer for creds!" nocase ascii wide
                        $string240 = "Scanning winlogon for crypted creds!" nocase ascii wide
                        $string241 = /Sending\sloot\sto\spastebin\swebserver\./ nocase ascii wide
                        $string242 = /SendToPasteBin\.ps1/ nocase ascii wide
                        $string243 = /ServiceName.{0,1000}CorpVPN/ nocase ascii wide
                        $string244 = /SharpGhost\.exe/ nocase ascii wide
                        $string245 = /SharpGhosting\.exe/ nocase ascii wide
                        $string246 = /Show\-BallonTip\.ps1/ nocase ascii wide
                        $string247 = /Show\-BalloonTip\.ps1/ nocase ascii wide
                        $string248 = /Sigthief\.py/ nocase ascii wide
                        $string249 = /SilenceDefender\.ps1/ nocase ascii wide
                        $string250 = /SilenceDefender_ATP\.log/ nocase ascii wide
                        $string251 = /SilenceDefender_ATP\.ps1/ nocase ascii wide
                        $string252 = /smblogin\.results\.log/ nocase ascii wide
                        $string253 = /smblogin\.results\.log/ nocase ascii wide
                        $string254 = /smblogin\-spray\.ps1/ nocase ascii wide
                        $string255 = /Spray\-Passwords\.ps1/ nocase ascii wide
                        $string256 = /Start\-SimpleHTTPServer\.ps1/ nocase ascii wide
                        $string257 = /TeamViewerDecrypt\.ps1/ nocase ascii wide
                        $string258 = /Temp\\graca\.log/ nocase ascii wide
                        $string259 = /TestMyPrivs\.ps1/ nocase ascii wide
                        $string260 = "-u SSARedTeam:s3cr3t" nocase ascii wide
                        $string261 = /UACBypassCMSTP\.ps1/ nocase ascii wide
                        $string262 = /vbs_obfuscator\.vbs/ nocase ascii wide
                        $string263 = /vbs_ofuscator\.vbs/ nocase ascii wide
                        $string264 = "vssadmin delete shadows /for=%systemdrive% /all /quiet" nocase ascii wide
                        $string265 = /WebBrowserPassView\.cfg/ nocase ascii wide
                        $string266 = /WebBrowserPassView\.exe/ nocase ascii wide
                        $string267 = /WebBrowserPassView\.pdb/ nocase ascii wide
                        $string268 = /WifiPasswords\.ps1/ nocase ascii wide
                        $string269 = /WinBruteLogon\.exe/ nocase ascii wide
                        $string270 = "wtXx6sM1482OWfsMXon6Am4Hi01idvFNgog3jTCsyAA=" nocase ascii wide

    condition:
        any of them
}