rule win_homefry_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.homefry."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.homefry"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 4157 4883ec20 4c8b7908 0fb701 4d8bf0 410fb61f 4c8bda }
                                                                                                
        $sequence_1 = { c744246038020000 ff15???????? 85c0 751d }
                                                            
        $sequence_2 = { 410fb61f 4c8bda 83f801 7623 }
                                                            
        $sequence_3 = { 488905???????? ff15???????? 488b0d???????? 448b4c2470 4c8b05???????? 488b15???????? }
                                                                                    
        $sequence_4 = { ffd5 85c0 0f8860010000 488b0d???????? 458d4e20 4c8d05480f0000 488b09 }
                                                                                                
        $sequence_5 = { e9???????? 480578ffffff 833d????????06 488905???????? }
                                                            
        $sequence_6 = { 751c 488d0d8f060000 488b742440 488b7c2448 4883c420 415e }
                                                                                    
        $sequence_7 = { 7343 0f1f8000000000 4983c9ff 488bd7 488bcb }
                                                                        
        $sequence_8 = { 488917 48630a 4883c104 4803ca 48890f }
                                                                        
        $sequence_9 = { 742e 48ffc3 483bdd 72d0 488bcf ff15???????? 33c0 }
                                                                                                
    condition:
        7 of them and filesize < 65536
}