rule MALPEDIA_Win_Grok_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "870cf4c1-459b-52f4-a686-b281f5585948"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.grok"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.grok_auto.yar#L1-L130"
    license_url        = "N/A"
    logic_hash         = "f55e3b1924db1bff1757dac784f11d8f8a3020681a2893ba57b274944ef08137"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0 = { 39 70 2c 74 13 56 ff 70 2c ff d3 a1 ?? ?? ?? ?? 89 70 2c }
    $sequence_1 = { 7c 62 a1 ?? ?? ?? ?? 39 70 44 74 12 56 ff 70 44 ff 15 ?? ?? ?? ?? }
    $sequence_2 = { 51 57 50 e8 ?? ?? ?? ?? 83 c4 0c 57 53 }
    $sequence_3 = { 33 ff 89 7d d8 81 ff 00 01 00 00 7d 28 8d 0c 17 8b 45 14 03 c7 }
    $sequence_4 = { a1 ?? ?? ?? ?? 89 58 20 a1 ?? ?? ?? ?? 39 58 24 }
    $sequence_5 = { 89 4d f4 eb 09 8b 55 f4 83 c2 01 89 55 f4 8b 45 f8 83 c0 09 }
    $sequence_6 = { 5f 56 56 6a 22 6a 01 56 }
    $sequence_7 = { 50 e8 ?? ?? ?? ?? 3b c3 7d 7e 39 5d 08 74 79 3d 43 00 00 c0 }
    $sequence_8 = { 33 ff 47 3b c3 89 45 fc 0f 8c 9c 00 00 00 39 1d ?? ?? ?? ?? 74 10 }
    $sequence_9 = { 53 51 03 c6 50 e8 ?? ?? ?? ?? 8b 46 3c 8d 8c 30 80 00 00 00 }

  condition:
    7 of them and filesize < 84992
}