rule rule_Dameware_greyware_tool_keyword
{
    meta:
        description = "Detection patterns for the tool 'Dameware' taken from the ThreatHunting-Keywords github project"
        author = "@mthcht"
        reference = "https://github.com/mthcht/ThreatHunting-Keywords"
        tool = "Dameware"
        rule_category = "greyware_tool_keyword"

    strings:
                        $string1_Dameware_greyware_tool_keyword = /\s\/monitor\s\/from_service\s\/cpu_memory_refresh\s.{0,100}\s\/disk_space_refresh\s.{0,100}\s\/proc_list_refresh\s.{0,100}\s\/semkey\s/ nocase ascii wide
                        $string2_Dameware_greyware_tool_keyword = " /r /proxy  /proxyport  /proxyusername  /proxypasswd "
                        $string3_Dameware_greyware_tool_keyword = " /register  /proxy  /proxyport  /proxyusername  /proxypasswd"
                        $string4_Dameware_greyware_tool_keyword = " -a tcrmtshellagentmodule_" nocase ascii wide
                        $string5_Dameware_greyware_tool_keyword = " Dameware Mini Remote Control x64 -- Installation completed successfully" nocase ascii wide
                        $string6_Dameware_greyware_tool_keyword = " -log-level trace -dre -log-path " nocase ascii wide
                        $string7_Dameware_greyware_tool_keyword = /\stkc_agent_dre\.deb/ nocase ascii wide
                        $string8_Dameware_greyware_tool_keyword = /\.exe\s\-\-pn\sdre_video_uploader\s\-\-logpath\slogs/ nocase ascii wide
                        $string9_Dameware_greyware_tool_keyword = /\.mspa\.n\-able\.com/ nocase ascii wide
                        $string10_Dameware_greyware_tool_keyword = /\/damewareagent\.exe/ nocase ascii wide
                        $string11_Dameware_greyware_tool_keyword = /\/DWMRC_St_64\.msi/ nocase ascii wide
                        $string12_Dameware_greyware_tool_keyword = /\/DWRCC\.exe/ nocase ascii wide
                        $string13_Dameware_greyware_tool_keyword = /\/DWRCCMD\.exe/ nocase ascii wide
                        $string14_Dameware_greyware_tool_keyword = /\/DWRCS\.exe/ nocase ascii wide
                        $string15_Dameware_greyware_tool_keyword = /\/SolarWinds\-Dameware\-DRS\-St\.exe/ nocase ascii wide
                        $string16_Dameware_greyware_tool_keyword = /\/tkc_agent_dre\.deb/ nocase ascii wide
                        $string17_Dameware_greyware_tool_keyword = /\\appdata\\local\\damewa\~1\\/ nocase ascii wide
                        $string18_Dameware_greyware_tool_keyword = /\\appdata\\local\\dameware\sremote\severywhere/ nocase ascii wide
                        $string19_Dameware_greyware_tool_keyword = /\\appdata\\local\\microsoft\\windows\\inetcache\\ie\\can_install_pc\[1\]\.xml/ nocase ascii wide
                        $string20_Dameware_greyware_tool_keyword = /\\AppData\\Roaming\\DameWare\sDevelopment\\/ nocase ascii wide
                        $string21_Dameware_greyware_tool_keyword = /\\baconsoleapp\.exe/ nocase ascii wide
                        $string22_Dameware_greyware_tool_keyword = /\\baconsoleappen\.dll/ nocase ascii wide
                        $string23_Dameware_greyware_tool_keyword = /\\baseclient\.exe.{0,100}\s\-consoleinstallcomplete/ nocase ascii wide
                        $string24_Dameware_greyware_tool_keyword = /\\basupclphlp\.exe/ nocase ascii wide
                        $string25_Dameware_greyware_tool_keyword = /\\basupclpprg\.exe/ nocase ascii wide
                        $string26_Dameware_greyware_tool_keyword = /\\basupconhelper\.exe/ nocase ascii wide
                        $string27_Dameware_greyware_tool_keyword = /\\basuplib\.dll/ nocase ascii wide
                        $string28_Dameware_greyware_tool_keyword = /\\basupportexpresssrvcupdater_dameware/ nocase ascii wide
                        $string29_Dameware_greyware_tool_keyword = /\\basupportexpressstandaloneservice_dameware/ nocase ascii wide
                        $string30_Dameware_greyware_tool_keyword = /\\basupregedithlpr\.exe/ nocase ascii wide
                        $string31_Dameware_greyware_tool_keyword = /\\basupregedithlpr_.{0,100}\.log/ nocase ascii wide
                        $string32_Dameware_greyware_tool_keyword = /\\basupsrvc\.cfg/ nocase ascii wide
                        $string33_Dameware_greyware_tool_keyword = /\\basupsrvc\.exe/ nocase ascii wide
                        $string34_Dameware_greyware_tool_keyword = /\\basupsrvc\.ico/ nocase ascii wide
                        $string35_Dameware_greyware_tool_keyword = /\\basupsrvc\.ini/ nocase ascii wide
                        $string36_Dameware_greyware_tool_keyword = /\\basupsrvc\.xml/ nocase ascii wide
                        $string37_Dameware_greyware_tool_keyword = /\\basupsrvc_.{0,100}\.log/ nocase ascii wide
                        $string38_Dameware_greyware_tool_keyword = /\\basupsrvccnfg\.exe/ nocase ascii wide
                        $string39_Dameware_greyware_tool_keyword = /\\basupsrvccnfg_.{0,100}\.log/ nocase ascii wide
                        $string40_Dameware_greyware_tool_keyword = /\\basupsrvccnfg_dameware/ nocase ascii wide
                        $string41_Dameware_greyware_tool_keyword = /\\basupsrvccnfgde\.dll/ nocase ascii wide
                        $string42_Dameware_greyware_tool_keyword = /\\basupsrvccnfgen\.dll/ nocase ascii wide
                        $string43_Dameware_greyware_tool_keyword = /\\basupsrvccnfges\.dll/ nocase ascii wide
                        $string44_Dameware_greyware_tool_keyword = /\\basupsrvccnfgfr\.dll/ nocase ascii wide
                        $string45_Dameware_greyware_tool_keyword = /\\basupsrvccnfgit\.dll/ nocase ascii wide
                        $string46_Dameware_greyware_tool_keyword = /\\basupsrvccnfgpt\.dll/ nocase ascii wide
                        $string47_Dameware_greyware_tool_keyword = /\\basupsrvcde\.dll/ nocase ascii wide
                        $string48_Dameware_greyware_tool_keyword = /\\basupsrvcen\.dll/ nocase ascii wide
                        $string49_Dameware_greyware_tool_keyword = /\\basupsrvces\.dll/ nocase ascii wide
                        $string50_Dameware_greyware_tool_keyword = /\\basupsrvcevnt3\.dll/ nocase ascii wide
                        $string51_Dameware_greyware_tool_keyword = /\\basupsrvcfr\.dll/ nocase ascii wide
                        $string52_Dameware_greyware_tool_keyword = /\\basupsrvcit\.dll/ nocase ascii wide
                        $string53_Dameware_greyware_tool_keyword = /\\basupsrvcpt\.dll/ nocase ascii wide
                        $string54_Dameware_greyware_tool_keyword = /\\basupsrvcupdater\.exe/ nocase ascii wide
                        $string55_Dameware_greyware_tool_keyword = /\\basupsrvcupdater_.{0,100}\.log/ nocase ascii wide
                        $string56_Dameware_greyware_tool_keyword = /\\basupsysinf.{0,100}\.log/ nocase ascii wide
                        $string57_Dameware_greyware_tool_keyword = /\\basupsysinf\.exe/ nocase ascii wide
                        $string58_Dameware_greyware_tool_keyword = /\\basupsysinf\.ini/ nocase ascii wide
                        $string59_Dameware_greyware_tool_keyword = /\\basupsysshell\.exe/ nocase ascii wide
                        $string60_Dameware_greyware_tool_keyword = /\\basupsysshell64\.exe/ nocase ascii wide
                        $string61_Dameware_greyware_tool_keyword = /\\basuptshelper\.exe/ nocase ascii wide
                        $string62_Dameware_greyware_tool_keyword = /\\basuptshelper_.{0,100}\.log/ nocase ascii wide
                        $string63_Dameware_greyware_tool_keyword = /\\basuptshelperlib\.dll/ nocase ascii wide
                        $string64_Dameware_greyware_tool_keyword = /\\basupunelev\.exe/ nocase ascii wide
                        $string65_Dameware_greyware_tool_keyword = /\\basupvista\.dll/ nocase ascii wide
                        $string66_Dameware_greyware_tool_keyword = /\\bavideochat\.exe/ nocase ascii wide
                        $string67_Dameware_greyware_tool_keyword = /\\bawhook\.dll/ nocase ascii wide
                        $string68_Dameware_greyware_tool_keyword = /\\beanywhere\ssupport\sexpress\sservice\s\-\s\[dameware\]/ nocase ascii wide
                        $string69_Dameware_greyware_tool_keyword = /\\currentversion\\uninstall\\dameware\sremote\severywhere/ nocase ascii wide
                        $string70_Dameware_greyware_tool_keyword = /\\DameWare\sDevelopment\\MrcVerbLog/ nocase ascii wide
                        $string71_Dameware_greyware_tool_keyword = /\\Dameware\sMini\sRemote\sControl\sx64\\/ nocase ascii wide
                        $string72_Dameware_greyware_tool_keyword = /\\dameware\smini\sremote\scontrol\sx64\\/ nocase ascii wide
                        $string73_Dameware_greyware_tool_keyword = /\\DameWare\sMini\sRemote\sControl.{0,100}\.exe/ nocase ascii wide
                        $string74_Dameware_greyware_tool_keyword = /\\Dameware\sMini\sRemote\sControl\.lnk/ nocase ascii wide
                        $string75_Dameware_greyware_tool_keyword = /\\dameware\sremote\severywhere\sagent/ nocase ascii wide
                        $string76_Dameware_greyware_tool_keyword = /\\dameware\sremote\severywhere\.lnk/ nocase ascii wide
                        $string77_Dameware_greyware_tool_keyword = /\\Dameware\sRemote\sSupport\s\.lnk/ nocase ascii wide
                        $string78_Dameware_greyware_tool_keyword = /\\Dameware\sRemote\sSupport\\/ nocase ascii wide
                        $string79_Dameware_greyware_tool_keyword = /\\DameWare\.Diagnostics/ nocase ascii wide
                        $string80_Dameware_greyware_tool_keyword = /\\DameWare\.LogAdjuster\.exe/ nocase ascii wide
                        $string81_Dameware_greyware_tool_keyword = /\\DameWare\.LogAdjuster\.exe\.config/ nocase ascii wide
                        $string82_Dameware_greyware_tool_keyword = /\\damewareagent\.exe/ nocase ascii wide
                        $string83_Dameware_greyware_tool_keyword = /\\damewareagent\.exe/ nocase ascii wide
                        $string84_Dameware_greyware_tool_keyword = /\\damewareremoteeverywhere\\/ nocase ascii wide
                        $string85_Dameware_greyware_tool_keyword = /\\damewareremoteeverywhereagentinstaller\.install\.log/ nocase ascii wide
                        $string86_Dameware_greyware_tool_keyword = /\\disable\sdameware\sremote\severywhere\sagent\.lnk/ nocase ascii wide
                        $string87_Dameware_greyware_tool_keyword = /\\DMRC\-10\-Evaluation\.lic/ nocase ascii wide
                        $string88_Dameware_greyware_tool_keyword = /\\DNTU\.exe/ nocase ascii wide
                        $string89_Dameware_greyware_tool_keyword = /\\dre_mac_console\.zip/ nocase ascii wide
                        $string90_Dameware_greyware_tool_keyword = /\\DWAMTD\.dll/ nocase ascii wide
                        $string91_Dameware_greyware_tool_keyword = /\\DWAMTDRES\.dll/ nocase ascii wide
                        $string92_Dameware_greyware_tool_keyword = /\\DWMRC_St_64\.msi/ nocase ascii wide
                        $string93_Dameware_greyware_tool_keyword = /\\DWMSISET\.W32/ nocase ascii wide
                        $string94_Dameware_greyware_tool_keyword = /\\DWMSISET\.X64/ nocase ascii wide
                        $string95_Dameware_greyware_tool_keyword = /\\DWNativeWCFClient\.dll/ nocase ascii wide
                        $string96_Dameware_greyware_tool_keyword = /\\DWNativeWCFClientRES\.dll/ nocase ascii wide
                        $string97_Dameware_greyware_tool_keyword = /\\DWPing\.dll/ nocase ascii wide
                        $string98_Dameware_greyware_tool_keyword = /\\DWPINGRES\.dll/ nocase ascii wide
                        $string99_Dameware_greyware_tool_keyword = /\\DWRCBA\.dll/ nocase ascii wide
                        $string100_Dameware_greyware_tool_keyword = /\\DWRCBN\.dll/ nocase ascii wide
                        $string101_Dameware_greyware_tool_keyword = /\\DWRCC\.chm/ nocase ascii wide
                        $string102_Dameware_greyware_tool_keyword = /\\DWRCC\.exe/ nocase ascii wide
                        $string103_Dameware_greyware_tool_keyword = /\\DWRCC\.log/ nocase ascii wide
                        $string104_Dameware_greyware_tool_keyword = /\\DWRCC\.log/ nocase ascii wide
                        $string105_Dameware_greyware_tool_keyword = /\\DWRCC\.Logging\.xml/ nocase ascii wide
                        $string106_Dameware_greyware_tool_keyword = /\\DWRCCH\.dll/ nocase ascii wide
                        $string107_Dameware_greyware_tool_keyword = /\\DWRCChat\.dll/ nocase ascii wide
                        $string108_Dameware_greyware_tool_keyword = /\\DWRCChatRES\.dll/ nocase ascii wide
                        $string109_Dameware_greyware_tool_keyword = /\\DWRCCMD\.exe/ nocase ascii wide
                        $string110_Dameware_greyware_tool_keyword = /\\DWRCCRES\.dll/ nocase ascii wide
                        $string111_Dameware_greyware_tool_keyword = /\\DWRCCSFTv2\.data/ nocase ascii wide
                        $string112_Dameware_greyware_tool_keyword = /\\DWRCD\.dll/ nocase ascii wide
                        $string113_Dameware_greyware_tool_keyword = /\\DWRCD\.dll/ nocase ascii wide
                        $string114_Dameware_greyware_tool_keyword = /\\DWRCK\.dll/ nocase ascii wide
                        $string115_Dameware_greyware_tool_keyword = /\\DWRCOP\.dll/ nocase ascii wide
                        $string116_Dameware_greyware_tool_keyword = /\\DWRCOPRES\.dll/ nocase ascii wide
                        $string117_Dameware_greyware_tool_keyword = /\\DWRCPN\.dll/ nocase ascii wide
                        $string118_Dameware_greyware_tool_keyword = /\\DWRCRSA\.dll/ nocase ascii wide
                        $string119_Dameware_greyware_tool_keyword = /\\DWRCRSS\.dll/ nocase ascii wide
                        $string120_Dameware_greyware_tool_keyword = /\\DWRCRSS\.dll/ nocase ascii wide
                        $string121_Dameware_greyware_tool_keyword = /\\DWRCS\.exe/ nocase ascii wide
                        $string122_Dameware_greyware_tool_keyword = /\\DWRCS\.Logging\.xml/ nocase ascii wide
                        $string123_Dameware_greyware_tool_keyword = /\\DWRCS\.reg/ nocase ascii wide
                        $string124_Dameware_greyware_tool_keyword = /\\DWRCSET\.dll/ nocase ascii wide
                        $string125_Dameware_greyware_tool_keyword = /\\DWRCSETRES\.dll/ nocase ascii wide
                        $string126_Dameware_greyware_tool_keyword = /\\DWRCSh\.dll/ nocase ascii wide
                        $string127_Dameware_greyware_tool_keyword = /\\DWRCSHRegister\.cmd/ nocase ascii wide
                        $string128_Dameware_greyware_tool_keyword = /\\DWRCSI\.dll/ nocase ascii wide
                        $string129_Dameware_greyware_tool_keyword = /\\DWRCSI\.dll/ nocase ascii wide
                        $string130_Dameware_greyware_tool_keyword = /\\DWRCSIRES\.dll/ nocase ascii wide
                        $string131_Dameware_greyware_tool_keyword = /\\DWRCSMSI\.exe/ nocase ascii wide
                        $string132_Dameware_greyware_tool_keyword = /\\DWRCSMSIRES\.dll/ nocase ascii wide
                        $string133_Dameware_greyware_tool_keyword = /\\DWRCSPC\.exe/ nocase ascii wide
                        $string134_Dameware_greyware_tool_keyword = /\\DWRCSPCRES\.dll/ nocase ascii wide
                        $string135_Dameware_greyware_tool_keyword = /\\DWRCSPX\.exe/ nocase ascii wide
                        $string136_Dameware_greyware_tool_keyword = /\\DWRCSPXRES\.dll/ nocase ascii wide
                        $string137_Dameware_greyware_tool_keyword = /\\DWRCSRES\.dll/ nocase ascii wide
                        $string138_Dameware_greyware_tool_keyword = /\\DWRCST\.exe/ nocase ascii wide
                        $string139_Dameware_greyware_tool_keyword = /\\DWRCST\.Logging\.xml/ nocase ascii wide
                        $string140_Dameware_greyware_tool_keyword = /\\DWRCSTRES\.dll/ nocase ascii wide
                        $string141_Dameware_greyware_tool_keyword = /\\DWRCU3\.dll/ nocase ascii wide
                        $string142_Dameware_greyware_tool_keyword = /\\DWRCWHD\.Logging\.xml/ nocase ascii wide
                        $string143_Dameware_greyware_tool_keyword = /\\DWRCWHDAPI\.dll/ nocase ascii wide
                        $string144_Dameware_greyware_tool_keyword = /\\DWRCWHDUI\.dll/ nocase ascii wide
                        $string145_Dameware_greyware_tool_keyword = /\\DWRCWHDUIRES\.dll/ nocase ascii wide
                        $string146_Dameware_greyware_tool_keyword = /\\DWRCWol\.dll/ nocase ascii wide
                        $string147_Dameware_greyware_tool_keyword = /\\DWRCWXL\.dll/ nocase ascii wide
                        $string148_Dameware_greyware_tool_keyword = /\\DWRTD\.dll/ nocase ascii wide
                        $string149_Dameware_greyware_tool_keyword = /\\DWRTDE\.exe/ nocase ascii wide
                        $string150_Dameware_greyware_tool_keyword = /\\DWRTDR\.dll/ nocase ascii wide
                        $string151_Dameware_greyware_tool_keyword = /\\DWRTDR\.dll/ nocase ascii wide
                        $string152_Dameware_greyware_tool_keyword = /\\DWSGRWRP\.dll/ nocase ascii wide
                        $string153_Dameware_greyware_tool_keyword = /\\DWUtil\.dll/ nocase ascii wide
                        $string154_Dameware_greyware_tool_keyword = /\\DWWFDS\.dll/ nocase ascii wide
                        $string155_Dameware_greyware_tool_keyword = /\\enable\sdameware\sremote\severywhere\sagent\.lnk/ nocase ascii wide
                        $string156_Dameware_greyware_tool_keyword = /\\eventlog\\application\\dameware\s/ nocase ascii wide
                        $string157_Dameware_greyware_tool_keyword = /\\getsupportservice_common_dameware/ nocase ascii wide
                        $string158_Dameware_greyware_tool_keyword = /\\getsupportservice_dameware/ nocase ascii wide
                        $string159_Dameware_greyware_tool_keyword = /\\getsupportservice_dameware\\/ nocase ascii wide
                        $string160_Dameware_greyware_tool_keyword = /\\linuxconsole_dw\s\(1\)\.zip/ nocase ascii wide
                        $string161_Dameware_greyware_tool_keyword = /\\logs\\baseclient_.{0,100}\.log/ nocase ascii wide
                        $string162_Dameware_greyware_tool_keyword = /\\logs\\baseconsoleapp_.{0,100}\.log/ nocase ascii wide
                        $string163_Dameware_greyware_tool_keyword = /\\logs\\basupclphlp_.{0,100}\.log/ nocase ascii wide
                        $string164_Dameware_greyware_tool_keyword = /\\Logs\\DNTU\.log/ nocase ascii wide
                        $string165_Dameware_greyware_tool_keyword = /\\Mini\sRemote\sControl\sClient\sAgent\sMSI\sBuilder\.lnk/ nocase ascii wide
                        $string166_Dameware_greyware_tool_keyword = /\\Mini\sRemote\sControl\sDiagnostics\.lnk/ nocase ascii wide
                        $string167_Dameware_greyware_tool_keyword = /\\Mini\sRemote\sControl\sHelp\.lnk/ nocase ascii wide
                        $string168_Dameware_greyware_tool_keyword = /\\Mini\sRemote\sControl\sLog\sAdjuster\.lnk/ nocase ascii wide
                        $string169_Dameware_greyware_tool_keyword = /\\Mini\sRemote\sControl\sService/ nocase ascii wide
                        $string170_Dameware_greyware_tool_keyword = /\\Mini\sRemote\sControl\sService\\Settings\\SFT\:\sUpload\sFolder/ nocase ascii wide
                        $string171_Dameware_greyware_tool_keyword = /\\Mini\sRemote\sControl\.lnk/ nocase ascii wide
                        $string172_Dameware_greyware_tool_keyword = /\\MRC_12\.0_Bootstrap_Install_Log\.txt/ nocase ascii wide
                        $string173_Dameware_greyware_tool_keyword = /\\MRCCv2\.db/ nocase ascii wide
                        $string174_Dameware_greyware_tool_keyword = /\\mspacredentialprovider_.{0,100}_dameware\.dll/ nocase ascii wide
                        $string175_Dameware_greyware_tool_keyword = /\\msparegedithelper_/ nocase ascii wide
                        $string176_Dameware_greyware_tool_keyword = /\\mspxtshlpsrv_/ nocase ascii wide
                        $string177_Dameware_greyware_tool_keyword = /\\mspxwebcom\.dll/ nocase ascii wide
                        $string178_Dameware_greyware_tool_keyword = /\\multiplicar\snegocios\\beanywhere\ssupport\sexpress/ nocase ascii wide
                        $string179_Dameware_greyware_tool_keyword = /\\prefetch\\baconsoleapp\.exe/ nocase ascii wide
                        $string180_Dameware_greyware_tool_keyword = /\\prefetch\\baseclient\.exe/ nocase ascii wide
                        $string181_Dameware_greyware_tool_keyword = /\\prefetch\\basupclphlp\.exe/ nocase ascii wide
                        $string182_Dameware_greyware_tool_keyword = /\\prefetch\\basupregedithlpr\.exe/ nocase ascii wide
                        $string183_Dameware_greyware_tool_keyword = /\\prefetch\\basupsrvc\.exe/ nocase ascii wide
                        $string184_Dameware_greyware_tool_keyword = /\\prefetch\\basupsrvccnfg\.exe/ nocase ascii wide
                        $string185_Dameware_greyware_tool_keyword = /\\prefetch\\basupsrvcupdater\.exe/ nocase ascii wide
                        $string186_Dameware_greyware_tool_keyword = /\\prefetch\\basupsysinf\.exe/ nocase ascii wide
                        $string187_Dameware_greyware_tool_keyword = /\\prefetch\\basuptshelper\.exe/ nocase ascii wide
                        $string188_Dameware_greyware_tool_keyword = /\\prefetch\\damewareagent\.exe/ nocase ascii wide
                        $string189_Dameware_greyware_tool_keyword = /\\prefetch\\damewareremoteeverywhereconso/ nocase ascii wide
                        $string190_Dameware_greyware_tool_keyword = /\\prefetch\\tcrmtshellagent\.exe/ nocase ascii wide
                        $string191_Dameware_greyware_tool_keyword = /\\prefetch\\tcrmtshellviewer\.exe/ nocase ascii wide
                        $string192_Dameware_greyware_tool_keyword = /\\prefetch\\tkcuploader\.exe/ nocase ascii wide
                        $string193_Dameware_greyware_tool_keyword = /\\progra\~2\\damewa\~1\\remoteshell\\/ nocase ascii wide
                        $string194_Dameware_greyware_tool_keyword = /\\quick\slaunch\\dameware\sremote\severywhere\stech\sconsole\.lnk/ nocase ascii wide
                        $string195_Dameware_greyware_tool_keyword = /\\Service\sInstall\sOverwrite\sRemote\sCFG/ nocase ascii wide
                        $string196_Dameware_greyware_tool_keyword = /\\SFT\:\sEnable\sSimple\sFile\sTransfer/ nocase ascii wide
                        $string197_Dameware_greyware_tool_keyword = /\\SolarWinds\.DepInjectedClassWalker\.dll/ nocase ascii wide
                        $string198_Dameware_greyware_tool_keyword = /\\SolarWinds\.Diags\.Contract\.dll/ nocase ascii wide
                        $string199_Dameware_greyware_tool_keyword = /\\SolarWinds\.Diags\.DameWare\.Extensions\.dll/ nocase ascii wide
                        $string200_Dameware_greyware_tool_keyword = /\\SolarWinds\.Diags\.exe/ nocase ascii wide
                        $string201_Dameware_greyware_tool_keyword = /\\SolarWinds\.Diags\.exe\.config/ nocase ascii wide
                        $string202_Dameware_greyware_tool_keyword = /\\SolarWinds\.Diags\.Extensions\.Common\.dll/ nocase ascii wide
                        $string203_Dameware_greyware_tool_keyword = /\\SolarWinds\.Diags\.Extensions\.dll/ nocase ascii wide
                        $string204_Dameware_greyware_tool_keyword = /\\SolarWinds\.Diags\.Platform\.Extensions\.dll/ nocase ascii wide
                        $string205_Dameware_greyware_tool_keyword = /\\SolarWinds\.Diags\.Strings\.dll/ nocase ascii wide
                        $string206_Dameware_greyware_tool_keyword = /\\SOLARWINDS\.DRS\.LICENSOR\.EXE\-/ nocase ascii wide
                        $string207_Dameware_greyware_tool_keyword = /\\SolarWinds\.LicenseManager\.msi/ nocase ascii wide
                        $string208_Dameware_greyware_tool_keyword = /\\SolarWinds\.Licensing\.Gen4\.dll/ nocase ascii wide
                        $string209_Dameware_greyware_tool_keyword = /\\SolarWinds\.Licensing\.Gen4\.dll\.config/ nocase ascii wide
                        $string210_Dameware_greyware_tool_keyword = /\\SolarWinds\.Licensing\.Gen4\.Resources\.dll/ nocase ascii wide
                        $string211_Dameware_greyware_tool_keyword = /\\SolarWinds\.Licensing\.Gen4\.UI\.dll/ nocase ascii wide
                        $string212_Dameware_greyware_tool_keyword = /\\SolarWinds\.Licensing\.MRC\.COMWrapper\.dll/ nocase ascii wide
                        $string213_Dameware_greyware_tool_keyword = /\\SolarWinds\.Licensing\.MRC\.COMWrapper\.dll\.config/ nocase ascii wide
                        $string214_Dameware_greyware_tool_keyword = /\\SolarWinds\.Licensing\.MRC\.COMWrapper\.tlb/ nocase ascii wide
                        $string215_Dameware_greyware_tool_keyword = /\\SolarWinds\.Logging\.dll/ nocase ascii wide
                        $string216_Dameware_greyware_tool_keyword = /\\SolarWinds\.MRC\.Licensor\.exe/ nocase ascii wide
                        $string217_Dameware_greyware_tool_keyword = /\\SolarWinds\.MRC\.Licensor\.exe/ nocase ascii wide
                        $string218_Dameware_greyware_tool_keyword = /\\SolarWinds\.MRC\.Licensor\.exe\.config/ nocase ascii wide
                        $string219_Dameware_greyware_tool_keyword = /\\SolarWinds\.MRC\.Licensor\.log/ nocase ascii wide
                        $string220_Dameware_greyware_tool_keyword = /\\SolarWinds\.Pluggability\.Contract\.dll/ nocase ascii wide
                        $string221_Dameware_greyware_tool_keyword = /\\SolarWinds\.Pluggability\.dll/ nocase ascii wide
                        $string222_Dameware_greyware_tool_keyword = /\\SolarWinds\\Dameware\sMini\sRemote\sControl/ nocase ascii wide
                        $string223_Dameware_greyware_tool_keyword = /\\SolarWinds\\Logs\\Dameware/ nocase ascii wide
                        $string224_Dameware_greyware_tool_keyword = /\\SOLARWINDS\-DAMEWARE\-DRS\-ST\.EX\-/ nocase ascii wide
                        $string225_Dameware_greyware_tool_keyword = /\\SolarWinds\-Dameware\-DRS\-St\.exe/ nocase ascii wide
                        $string226_Dameware_greyware_tool_keyword = /\\start\sdameware\sremote\severywhere\sagent\.lnk/ nocase ascii wide
                        $string227_Dameware_greyware_tool_keyword = /\\start\smenu\\programs\\dameware/ nocase ascii wide
                        $string228_Dameware_greyware_tool_keyword = /\\tcdirectchat\.exe/ nocase ascii wide
                        $string229_Dameware_greyware_tool_keyword = /\\tcdirectchatde\.dll/ nocase ascii wide
                        $string230_Dameware_greyware_tool_keyword = /\\tcdirectchaten\.dll/ nocase ascii wide
                        $string231_Dameware_greyware_tool_keyword = /\\tcdirectchates\.dll/ nocase ascii wide
                        $string232_Dameware_greyware_tool_keyword = /\\tcdirectchatfr\.dll/ nocase ascii wide
                        $string233_Dameware_greyware_tool_keyword = /\\tcdirectchatit\.dll/ nocase ascii wide
                        $string234_Dameware_greyware_tool_keyword = /\\tcdirectchatpt\.dll/ nocase ascii wide
                        $string235_Dameware_greyware_tool_keyword = /\\tcrmtshellagent\.exe/ nocase ascii wide
                        $string236_Dameware_greyware_tool_keyword = /\\tcrmtshellagent_.{0,100}\.log/ nocase ascii wide
                        $string237_Dameware_greyware_tool_keyword = /\\tcrmtshellagentmodule_/ nocase ascii wide
                        $string238_Dameware_greyware_tool_keyword = /\\tcrmtshellviewer\.exe/ nocase ascii wide
                        $string239_Dameware_greyware_tool_keyword = /\\tcrmtshellviewer_.{0,100}\.log/ nocase ascii wide
                        $string240_Dameware_greyware_tool_keyword = /\\tcrmtshellviewermodule_/ nocase ascii wide
                        $string241_Dameware_greyware_tool_keyword = /\\tkcuploader\.exe/ nocase ascii wide
                        $string242_Dameware_greyware_tool_keyword = /\\wow6432node\\multiplicar\snegocios\\bace_dameware/ nocase ascii wide
                        $string243_Dameware_greyware_tool_keyword = "<data>dameware remote everywhere</data>" nocase ascii wide
                        $string244_Dameware_greyware_tool_keyword = "<data>n-able take control</data>" nocase ascii wide
                        $string245_Dameware_greyware_tool_keyword = /\<provider\sname\=\\"dameware\sremote\severywhere\s\-\s\[dameware\]\\"\s\/\>/ nocase ascii wide
                        $string246_Dameware_greyware_tool_keyword = /admin\..{0,100}\.swi\-dre\.com/ nocase ascii wide
                        $string247_Dameware_greyware_tool_keyword = /C\:\\Program\sFiles\\SolarWinds\\Dameware\sMini\sRemote\sControl\sx64\\/ nocase ascii wide
                        $string248_Dameware_greyware_tool_keyword = /C\:\\Users\\mthcht\\AppData\\Roaming\\DameWare\sDevelopment\\/ nocase ascii wide
                        $string249_Dameware_greyware_tool_keyword = /chat\.us\.n\-able\.com/ nocase ascii wide
                        $string250_Dameware_greyware_tool_keyword = "'company'>n-able take control</data>" nocase ascii wide
                        $string251_Dameware_greyware_tool_keyword = /comserver\.corporate\.beanywhere\.com/ nocase ascii wide
                        $string252_Dameware_greyware_tool_keyword = /DameWare\sDevelopment\sCommon\sData\\Mini\sRemote\sControl/ nocase ascii wide
                        $string253_Dameware_greyware_tool_keyword = /DameWare\sDevelopment\\Agent\sConfiguration/ nocase ascii wide
                        $string254_Dameware_greyware_tool_keyword = /dameware\sremote\severywhere\sagent\s\-\s\[dameware\]/ nocase ascii wide
                        $string255_Dameware_greyware_tool_keyword = /DameWare\sRemote\sSupport\.exe/ nocase ascii wide
                        $string256_Dameware_greyware_tool_keyword = /damewareagent\.msi/ nocase ascii wide
                        $string257_Dameware_greyware_tool_keyword = /damewareremoteeverywhereagent\.exe/ nocase ascii wide
                        $string258_Dameware_greyware_tool_keyword = /damewareremoteeverywhereconsole\.exe/ nocase ascii wide
                        $string259_Dameware_greyware_tool_keyword = "'Description'>Dameware products</Data>" nocase ascii wide
                        $string260_Dameware_greyware_tool_keyword = /download\.global\.mspa\.n\-able\.com\// nocase ascii wide
                        $string261_Dameware_greyware_tool_keyword = /getsupportservice_common_dameware\\logs/ nocase ascii wide
                        $string262_Dameware_greyware_tool_keyword = /https\:\/\/downloads\.solarwinds\.com\/solarwinds\/Release\/DameWare\// nocase ascii wide
                        $string263_Dameware_greyware_tool_keyword = /login\.swi\-dre\.com/ nocase ascii wide
                        $string264_Dameware_greyware_tool_keyword = /msi\-installs\.swi\-rc\.com\// nocase ascii wide
                        $string265_Dameware_greyware_tool_keyword = /notifications\..{0,100}\.swi\-rc\.com/ nocase ascii wide
                        $string266_Dameware_greyware_tool_keyword = "product: damewareagent --" nocase ascii wide
                        $string267_Dameware_greyware_tool_keyword = /provider\sname\=\\"n\-able\stake\scontrol\s\-\s\[dameware\]\\"\s\/\>/ nocase ascii wide
                        $string268_Dameware_greyware_tool_keyword = /\-\-single\-argument\shttps\:\/\/www\.solarwinds\.com\/.{0,100}\/remote\-support\-software/ nocase ascii wide
                        $string269_Dameware_greyware_tool_keyword = /SolarWinds\.MRC\.Licensor/ nocase ascii wide
                        $string270_Dameware_greyware_tool_keyword = /SolarWinds\.Orion\.MaintDateCheck/ nocase ascii wide
                        $string271_Dameware_greyware_tool_keyword = /SolarWinds\-Dameware\-DRS\-St\.exe/ nocase ascii wide
                        $string272_Dameware_greyware_tool_keyword = /SolarWinds\-Dameware\-DRS\-St\-Eval\.zip/ nocase ascii wide
                        $string273_Dameware_greyware_tool_keyword = /SolarWinds\-Dameware\-MRC\-32bit\-St\.exe/ nocase ascii wide
                        $string274_Dameware_greyware_tool_keyword = /SolarWinds\-Dameware\-MRC\-32bit\-St\-Eval\.zip/ nocase ascii wide
                        $string275_Dameware_greyware_tool_keyword = /SolarWinds\-Dameware\-MRC\-64bit\-St\.exe/ nocase ascii wide
                        $string276_Dameware_greyware_tool_keyword = /SolarWinds\-Dameware\-MRC\-64bit\-St\-Eval\.zip/ nocase ascii wide
                        $string277_Dameware_greyware_tool_keyword = /stop\sdameware\sremote\severywhere\sagent\.lnk/ nocase ascii wide
                        $string278_Dameware_greyware_tool_keyword = /techws\..{0,100}\.swi\-rc\.com/ nocase ascii wide
                        $string279_Dameware_greyware_tool_keyword = /vaults\..{0,100}\.swi\-rc\.com/ nocase ascii wide
        $metadata_regex_import = /\bimport\s+[a-zA-Z0-9_.]+\b/ nocase
        $metadata_regex_function = /function\s+[a-zA-Z_][a-zA-Z0-9_]*\(/ nocase ascii
        $metadata_regex_php = /<\?php/ nocase ascii
        $metadata_regex_createobject = /(CreateObject|WScript\.)/ nocase ascii
        $metadata_regex_script = /<script\b/ nocase ascii
        $metadata_regex_javascript = /(let\s|const\s|function\s|document\.|console\.)/ nocase ascii
        $metadata_regex_powershell = /(Write-Host|Get-[a-zA-Z]+|Invoke-|param\(|\.SYNOPSIS)/ nocase ascii
        $metadata_regex_batch = /@(echo\s|call\s|set\s|goto\s|if\s|for\s|rem\s)/ nocase ascii
        $metadata_regex_shebang = /^#!\// nocase ascii

    condition:
        ((filesize < 20MB and (
            uint16(0) == 0x5a4d or             uint16(0) == 0x457f or             uint32be(0) == 0x7f454c46 or uint16(0) == 0xfeca or uint16(0) == 0xfacf or uint32(0) == 0xbebafeca or             uint32(0) == 0x504B0304 or             uint32(0) == 0xCAFEBABE or             uint32(0) == 0x4D534346 or             uint32(0) == 0xD0CF11E0 or             uint16(0) == 0x2321 or             uint16(0) == 0x3c3f         )) and 2 of ($string*)) or
        (filesize < 2MB and
        (
            2 of ($string*) and
            for any of ($metadata_regex_*) : ( @ <= 20000 )
        ))
}