rule MALPEDIA_Win_Socelars_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "b06c7ac2-d920-55f6-9edd-c06a57d2d404"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.socelars"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.socelars_auto.yar#L1-L134"
    license_url        = "N/A"
    logic_hash         = "29f15e383674389295d6d5d873e2a8fae68e30508b53f5e863e0aef43fe3264f"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0 = { f6 46 28 08 89 46 18 75 15 8b 4c 24 3c ba 14 00 00 00 e8 ?? ?? ?? ?? 89 84 24 30 01 00 00 }
    $sequence_1 = { 8b 4d fc 83 b9 cc 03 00 00 20 74 09 c7 45 c0 0c 00 00 00 eb 07 c7 45 c0 0e 00 00 00 8b 55 fc }
    $sequence_2 = { ff 46 0c 80 7e 0a 00 75 0a 8b ce e8 ?? ?? ?? ?? 8a 4e 09 8b 43 0c }
    $sequence_3 = { ff 73 0c ff 73 08 e8 ?? ?? ?? ?? 8b f8 83 c4 10 85 ff 0f 84 80 00 00 00 }
    $sequence_4 = { 8b 54 24 10 8b 52 48 f6 42 1c 20 0f 84 37 05 00 00 8b 42 14 ff 48 78 8b 88 88 00 00 00 }
    $sequence_5 = { e9 ?? ?? ?? ?? 8b 4c 24 3c 33 c0 89 84 24 30 01 00 00 ba 43 00 00 00 8b 47 2c 40 }
    $sequence_6 = { f7 da 56 1b d2 83 c2 35 eb 55 6a 00 ff 77 c4 }
    $sequence_7 = { e8 ?? ?? ?? ?? 83 c4 0c eb 36 8d 42 01 89 81 88 00 00 00 8d 0c 92 8b 44 24 38 }
    $sequence_8 = { fe 46 13 8a 46 19 fe c8 0f b6 c8 88 46 19 3b f9 7d 24 }
    $sequence_9 = { ff 74 24 24 e8 ?? ?? ?? ?? 83 c4 0c eb 32 8b 54 24 1c 8d 41 01 89 86 88 00 00 00 }

  condition:
    7 of them and filesize < 2151424
}