rule win_matrix_banker_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.matrix_banker."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.matrix_banker"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 80f905 7705 80c2a9 eb0b 8d4abf 80f905 }
                                                                                    
        $sequence_1 = { 80f905 7704 04a9 eb0a }
                                                            
        $sequence_2 = { eb16 8d489f 80f905 7704 }
                                                            
        $sequence_3 = { 66890d???????? 66030d???????? 66890d???????? e8???????? }
                                                            
        $sequence_4 = { 8d48bf 80f905 7702 04c9 }
                                                            
        $sequence_5 = { 8d4abf 80f905 7703 80c2c9 }
                                                            
        $sequence_6 = { 8d489f 80f905 7704 04a9 }
                                                            
        $sequence_7 = { eb0a 8d48bf 80f905 7702 04c9 8d4ad0 80f909 }
                                                                                                
        $sequence_8 = { 04a9 eb0a 8d48bf 80f905 7702 }
                                                                        
        $sequence_9 = { 80f905 7705 80c2a9 eb0b 8d4abf }
                                                                        
    condition:
        7 of them and filesize < 422912
}