rule MALPEDIA_Win_Citadel_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "cf6cb189-c7d7-5571-b2ec-c3b6f165f615"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.citadel"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.citadel_auto.yar#L1-L167"
    license_url        = "N/A"
    logic_hash         = "8e88ac7355b3e3defd358849e38b9e68e570cd840f3a9a1ae754cb483f4c91f5"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0  = { eb 0e 68 00 80 00 00 53 57 }
    $sequence_1  = { 55 8b ec ff 75 08 e8 ?? ?? ?? ?? e8 ?? ?? ?? ?? 5d }
    $sequence_2  = { eb 03 83 c0 02 68 ?? ?? ?? ?? 50 ff 15 ?? ?? ?? ?? }
    $sequence_3  = { e8 ?? ?? ?? ?? e8 ?? ?? ?? ?? 5d ff 25 ?? ?? ?? ?? 55 8b ec ff 75 08 }
    $sequence_4  = { 33 c0 5f 5e c2 04 00 55 8b ec 8b 4d 0c }
    $sequence_5  = { e8 ?? ?? ?? ?? 8d 7c 02 01 8b c7 e8 ?? ?? ?? ?? }
    $sequence_6  = { 50 e8 ?? ?? ?? ?? 6a 44 5a 52 }
    $sequence_7  = { 50 8d 5d fc e8 ?? ?? ?? ?? 8b 4d fc }
    $sequence_8  = { 88 46 01 33 c0 66 89 46 0c ff 4d f8 }
    $sequence_9  = { 8a 56 02 8b 4e 10 8a 5e 14 fe c8 32 d0 8a c2 32 45 fe }
    $sequence_10 = { 88 45 fe c6 45 ff 00 76 3c 8a 06 }
    $sequence_11 = { 3a ca 73 fa 0f b6 c9 8b 04 c8 eb ae 32 c0 5f }
    $sequence_12 = { 33 c0 66 89 46 0e 0f b7 46 06 66 85 c0 74 32 }
    $sequence_13 = { 85 c0 74 09 32 55 fd 8a 0f ff d0 88 07 }
    $sequence_14 = { 66 85 c0 74 32 66 ff 46 0e 66 39 46 0e }
    $sequence_15 = { 66 39 46 0c 72 28 8b 46 10 8a 4e 05 8a 56 14 85 c0 }

  condition:
    7 of them and filesize < 1236992
}