rule win_electric_powder_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.electric_powder."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.electric_powder"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 85c0 0f84b6130000 8d8de0fbffff 8d5720 8d7102 668b01 83c102 }
                                                                                                
        $sequence_1 = { 8d8d68faffff e9???????? 8d8d5cf9ffff e9???????? 8d8df8faffff e9???????? 8b857cf9ffff }
                                                                                                
        $sequence_2 = { 3bd8 0f42d8 8d4301 85c0 7504 33f6 eb34 }
                                                                                                
        $sequence_3 = { 8b35???????? 81c230750000 89b574f9ffff 52 ffd6 68???????? 6a01 }
                                                                                                
        $sequence_4 = { 3b4e08 0f838e010000 8b4604 c704c810000000 8b5608 83ea01 }
                                                                                    
        $sequence_5 = { 0f4dd0 7ce7 56 8d7207 83e6f8 3bd6 }
                                                                                    
        $sequence_6 = { c645fc79 e8???????? c785e0fbffff00000000 81cf00010000 c785e4fbffff00000000 }
                                                                        
        $sequence_7 = { c60600 8d8d30fcffff e8???????? 8d8520fdffff ba???????? 50 8d8da0fbffff }
                                                                                                
        $sequence_8 = { 8947fc eb0b 50 e8???????? 83c404 8bf8 8b4dfc }
                                                                                                
        $sequence_9 = { 8bf0 e9???????? 8b45f8 46 8b541004 8955ec 3bf2 }
                                                                                                
    condition:
        7 of them and filesize < 565248
}