rule MALPEDIA_Win_Rtpos_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "77dcd653-95cb-55c4-91a1-f9b9e9596fd3"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.rtpos"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.rtpos_auto.yar#L1-L120"
    license_url        = "N/A"
    logic_hash         = "4ad89a49b88ba1ea262b015470065dd4f3f20d950975a1f27ea85a4b99624bd0"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0 = { 68 a8 04 00 00 8b 45 ec 50 e8 ?? ?? ?? ?? 83 c4 08 c3 8b 54 24 08 }
    $sequence_1 = { 83 e9 08 8d 76 08 66 0f d6 0f 8d 7f 08 8b 04 8d 74 b4 40 00 }
    $sequence_2 = { 8b 0c c5 c4 ae 42 00 89 4d e4 85 c9 74 55 }
    $sequence_3 = { 76 19 8b 4d d4 51 ff 15 ?? ?? ?? ?? }
    $sequence_4 = { 8d 45 d8 50 6a 00 8b 4d d4 51 }
    $sequence_5 = { 85 c0 75 2c 6a 00 68 ?? ?? ?? ?? 68 ?? ?? ?? ?? 6a 02 68 ?? ?? ?? ?? }
    $sequence_6 = { 8b ec 53 8b 5d 08 33 c9 57 33 c0 8d 3c 9d 5c 65 43 00 }
    $sequence_7 = { 33 c5 89 45 fc c7 45 d8 00 00 00 00 c7 45 dc 00 00 00 00 33 c0 }
    $sequence_8 = { 2b 45 c4 3b 45 f0 76 19 8b 4d d4 51 ff 15 ?? ?? ?? ?? }
    $sequence_9 = { 6b c0 30 03 04 8d b8 6a 43 00 50 ff 15 ?? ?? ?? ?? 5d c3 }

  condition:
    7 of them and filesize < 507904
}