rule MALPEDIA_Win_Breach_Rat_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "f70ab09f-8643-5192-b966-55a3dab88920"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.breach_rat"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.breach_rat_auto.yar#L1-L134"
    license_url        = "N/A"
    logic_hash         = "8cb7f4b75bac273a3c54152da1b9e63a78dde17954dfd874b266899e47404327"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0 = { 5e 5b 8b e5 5d c2 04 00 88 4c 24 0f 8d 44 24 18 }
    $sequence_1 = { 50 8b ce e8 ?? ?? ?? ?? 8b c8 e8 ?? ?? ?? ?? 8d 8d ac f6 ff ff c7 45 fc ff ff ff ff }
    $sequence_2 = { c1 e8 1f 03 c2 89 85 d8 fe ff ff 0f 84 79 08 00 00 83 c7 24 89 bd e0 fe ff ff 8d 9b 00 00 00 00 }
    $sequence_3 = { c7 41 14 0f 00 00 00 c7 41 10 00 00 00 00 c6 01 00 e8 ?? ?? ?? ?? ff 75 10 8d 4d d4 ff 75 0c }
    $sequence_4 = { 8b e5 5d c3 68 ?? ?? ?? ?? 8b ce e8 ?? ?? ?? ?? b0 01 }
    $sequence_5 = { 8b 55 08 8b cb 0f b7 12 8b ff 66 39 10 74 08 83 c0 02 }
    $sequence_6 = { 42 8b 5d e0 3b d6 72 f2 8b 45 a4 2b c6 50 }
    $sequence_7 = { c7 47 18 00 01 00 00 8b 4d f4 8b c7 c7 47 04 00 00 00 00 c7 47 08 00 00 00 00 5f 5e }
    $sequence_8 = { eb 20 84 c9 74 ed 8b 4d f0 8d 45 d8 50 e8 ?? ?? ?? ?? }
    $sequence_9 = { e8 ?? ?? ?? ?? 68 ?? ?? ?? ?? 8d 85 9c f4 ff ff c7 45 fc 5c 00 00 00 50 8b ce e8 ?? ?? ?? ?? }

  condition:
    7 of them and filesize < 645120
}