rule rule_sc_greyware_tool_keyword
{
    meta:
        description = "Detection patterns for the tool 'sc' taken from the ThreatHunting-Keywords github project"
        author = "@mthcht"
        reference = "https://github.com/mthcht/ThreatHunting-Keywords"
        tool = "sc"
        rule_category = "greyware_tool_keyword"

    strings:
                        $string1_sc_greyware_tool_keyword = " /c sc query WinDefend" nocase ascii wide
                        $string2_sc_greyware_tool_keyword = "dnefedniw  eteled cs" nocase ascii wide
                        $string3_sc_greyware_tool_keyword = /echo\sstart\s\>\s\\\\\.\\pipe\\winreg/ nocase ascii wide
                        $string4_sc_greyware_tool_keyword = "sc  sdset RemoteAccess " nocase ascii wide
                        $string5_sc_greyware_tool_keyword = /sc\sconfig\sKeyIso\sstart\=\sDisabled\s\|\ssc\sstop\sKeyIso/ nocase ascii wide
                        $string6_sc_greyware_tool_keyword = /sc\screate\s.{0,1000}nc\.exe\s\-.{0,1000}cmd\.exe/ nocase ascii wide
                        $string7_sc_greyware_tool_keyword = /sc\sdelete\s\\"AVP18\.0\.0\\"/ nocase ascii wide
                        $string8_sc_greyware_tool_keyword = "sc delete \"ekrn\"" nocase ascii wide
                        $string9_sc_greyware_tool_keyword = "sc delete \"FirebirdGuardianDefaultInstance\"" nocase ascii wide
                        $string10_sc_greyware_tool_keyword = "sc delete \"FirebirdServerDefaultInstance\"" nocase ascii wide
                        $string11_sc_greyware_tool_keyword = "sc delete \"hvdswvc\"" nocase ascii wide
                        $string12_sc_greyware_tool_keyword = "sc delete \"klbackupdisk\"" nocase ascii wide
                        $string13_sc_greyware_tool_keyword = "sc delete \"klbackupflt\"" nocase ascii wide
                        $string14_sc_greyware_tool_keyword = "sc delete \"klflt\"" nocase ascii wide
                        $string15_sc_greyware_tool_keyword = "sc delete \"klhk\"" nocase ascii wide
                        $string16_sc_greyware_tool_keyword = "sc delete \"KLIF\"" nocase ascii wide
                        $string17_sc_greyware_tool_keyword = "sc delete \"klim6\"" nocase ascii wide
                        $string18_sc_greyware_tool_keyword = "sc delete \"klkbdflt\"" nocase ascii wide
                        $string19_sc_greyware_tool_keyword = "sc delete \"klmouflt\"" nocase ascii wide
                        $string20_sc_greyware_tool_keyword = "sc delete \"klpd\"" nocase ascii wide
                        $string21_sc_greyware_tool_keyword = "sc delete \"kltap\"" nocase ascii wide
                        $string22_sc_greyware_tool_keyword = /sc\sdelete\s\\"KSDE1\.0\.0\\"/ nocase ascii wide
                        $string23_sc_greyware_tool_keyword = "sc delete \"ntrtscan\"" nocase ascii wide
                        $string24_sc_greyware_tool_keyword = "sc delete \"nvspwmi\"" nocase ascii wide
                        $string25_sc_greyware_tool_keyword = "sc delete \"ofcservice\"" nocase ascii wide
                        $string26_sc_greyware_tool_keyword = "sc delete \"storflt\"" nocase ascii wide
                        $string27_sc_greyware_tool_keyword = "sc delete \"sysmon\"" nocase ascii wide
                        $string28_sc_greyware_tool_keyword = "sc delete \"TmCCSF\"" nocase ascii wide
                        $string29_sc_greyware_tool_keyword = "sc delete \"TmFilter\"" nocase ascii wide
                        $string30_sc_greyware_tool_keyword = "sc delete \"TMiCRCScanService\"" nocase ascii wide
                        $string31_sc_greyware_tool_keyword = "sc delete \"tmlisten\"" nocase ascii wide
                        $string32_sc_greyware_tool_keyword = "sc delete \"TMLWCSService\"" nocase ascii wide
                        $string33_sc_greyware_tool_keyword = "sc delete \"TmPreFilter\"" nocase ascii wide
                        $string34_sc_greyware_tool_keyword = "sc delete \"TmProxy\"" nocase ascii wide
                        $string35_sc_greyware_tool_keyword = "sc delete \"TMSmartRelayService\"" nocase ascii wide
                        $string36_sc_greyware_tool_keyword = "sc delete \"tmusa\"" nocase ascii wide
                        $string37_sc_greyware_tool_keyword = "sc delete \"vmicguestinterface\"" nocase ascii wide
                        $string38_sc_greyware_tool_keyword = "sc delete \"vmicheartbeat\"" nocase ascii wide
                        $string39_sc_greyware_tool_keyword = "sc delete \"vmickvpexchange\"" nocase ascii wide
                        $string40_sc_greyware_tool_keyword = "sc delete \"vmicrdv\"" nocase ascii wide
                        $string41_sc_greyware_tool_keyword = "sc delete \"vmicshutdown\"" nocase ascii wide
                        $string42_sc_greyware_tool_keyword = "sc delete \"vmictimesync\"" nocase ascii wide
                        $string43_sc_greyware_tool_keyword = "sc delete \"vmicvss\"" nocase ascii wide
                        $string44_sc_greyware_tool_keyword = "sc delete \"VSApiNt\"" nocase ascii wide
                        $string45_sc_greyware_tool_keyword = "sc delete \"wmms\"" nocase ascii wide
                        $string46_sc_greyware_tool_keyword = "sc delete \"WRSVC\"" nocase ascii wide
                        $string47_sc_greyware_tool_keyword = /sc\sdelete\sAVP18\.0\.0/ nocase ascii wide
                        $string48_sc_greyware_tool_keyword = "sc delete ekrn" nocase ascii wide
                        $string49_sc_greyware_tool_keyword = "sc delete FirebirdGuardianDefaultInstance" nocase ascii wide
                        $string50_sc_greyware_tool_keyword = "sc delete FirebirdServerDefaultInstance" nocase ascii wide
                        $string51_sc_greyware_tool_keyword = "sc delete hvdswvc" nocase ascii wide
                        $string52_sc_greyware_tool_keyword = "sc delete klbackupdisk" nocase ascii wide
                        $string53_sc_greyware_tool_keyword = "sc delete klbackupflt" nocase ascii wide
                        $string54_sc_greyware_tool_keyword = "sc delete klflt" nocase ascii wide
                        $string55_sc_greyware_tool_keyword = "sc delete klhk" nocase ascii wide
                        $string56_sc_greyware_tool_keyword = "sc delete KLIF" nocase ascii wide
                        $string57_sc_greyware_tool_keyword = "sc delete klim6" nocase ascii wide
                        $string58_sc_greyware_tool_keyword = "sc delete klkbdflt" nocase ascii wide
                        $string59_sc_greyware_tool_keyword = "sc delete klmouflt" nocase ascii wide
                        $string60_sc_greyware_tool_keyword = "sc delete klpd" nocase ascii wide
                        $string61_sc_greyware_tool_keyword = "sc delete kltap" nocase ascii wide
                        $string62_sc_greyware_tool_keyword = /sc\sdelete\sKSDE1\.0\.0/ nocase ascii wide
                        $string63_sc_greyware_tool_keyword = "sc delete MBAMProtection" nocase ascii wide
                        $string64_sc_greyware_tool_keyword = "sc delete MBAMService" nocase ascii wide
                        $string65_sc_greyware_tool_keyword = "sc delete ntrtscan" nocase ascii wide
                        $string66_sc_greyware_tool_keyword = "sc delete nvspwmi" nocase ascii wide
                        $string67_sc_greyware_tool_keyword = "sc delete ofcservice" nocase ascii wide
                        $string68_sc_greyware_tool_keyword = "sc delete storflt" nocase ascii wide
                        $string69_sc_greyware_tool_keyword = "sc delete sysmon" nocase ascii wide
                        $string70_sc_greyware_tool_keyword = "sc delete TmCCSF" nocase ascii wide
                        $string71_sc_greyware_tool_keyword = "sc delete TmFilter" nocase ascii wide
                        $string72_sc_greyware_tool_keyword = "sc delete TMiCRCScanService" nocase ascii wide
                        $string73_sc_greyware_tool_keyword = "sc delete tmlisten" nocase ascii wide
                        $string74_sc_greyware_tool_keyword = "sc delete TMLWCSService" nocase ascii wide
                        $string75_sc_greyware_tool_keyword = "sc delete TmPreFilter" nocase ascii wide
                        $string76_sc_greyware_tool_keyword = "sc delete TmProxy" nocase ascii wide
                        $string77_sc_greyware_tool_keyword = "sc delete TMSmartRelayService" nocase ascii wide
                        $string78_sc_greyware_tool_keyword = "sc delete tmusa" nocase ascii wide
                        $string79_sc_greyware_tool_keyword = "sc delete vmicguestinterface" nocase ascii wide
                        $string80_sc_greyware_tool_keyword = "sc delete vmicheartbeat" nocase ascii wide
                        $string81_sc_greyware_tool_keyword = "sc delete vmickvpexchange" nocase ascii wide
                        $string82_sc_greyware_tool_keyword = "sc delete vmicrdv" nocase ascii wide
                        $string83_sc_greyware_tool_keyword = "sc delete vmicshutdown" nocase ascii wide
                        $string84_sc_greyware_tool_keyword = "sc delete vmictimesync" nocase ascii wide
                        $string85_sc_greyware_tool_keyword = "sc delete vmicvss" nocase ascii wide
                        $string86_sc_greyware_tool_keyword = "sc delete VSApiNt" nocase ascii wide
                        $string87_sc_greyware_tool_keyword = "sc delete VSS" nocase ascii wide
                        $string88_sc_greyware_tool_keyword = "sc delete wmms" nocase ascii wide
                        $string89_sc_greyware_tool_keyword = "sc delete WRSVC" nocase ascii wide
                        $string90_sc_greyware_tool_keyword = "sc qtriggerinfo RemoteRegistry" nocase ascii wide
                        $string91_sc_greyware_tool_keyword = /sc\ssdset\sscmanager\sD\:\(A\;\;KA\;\;\;WD\)/ nocase ascii wide
                        $string92_sc_greyware_tool_keyword = "sc start RemoteRegistry" nocase ascii wide
                        $string93_sc_greyware_tool_keyword = "sc stop eventlog" nocase ascii wide
                        $string94_sc_greyware_tool_keyword = "sc stop MBAMProtection" nocase ascii wide
                        $string95_sc_greyware_tool_keyword = "sc stop MBAMService" nocase ascii wide
                        $string96_sc_greyware_tool_keyword = "sc stop Sophos File Scanner Service" nocase ascii wide
                        $string97_sc_greyware_tool_keyword = /sc\.exe\s\ssdset\sRemoteAccess\s/ nocase ascii wide
                        $string98_sc_greyware_tool_keyword = /sc\.exe\sdelete\s\\"SAVAdminService\\"/ nocase ascii wide
                        $string99_sc_greyware_tool_keyword = /sc\.exe\sdelete\s\\"SAVAdminService\\"/ nocase ascii wide
                        $string100_sc_greyware_tool_keyword = /sc\.exe\sdelete\s\\"SAVService\\"/ nocase ascii wide
                        $string101_sc_greyware_tool_keyword = /sc\.exe\sdelete\s\\"SAVService\\"/ nocase ascii wide
                        $string102_sc_greyware_tool_keyword = /sc\.exe\sdelete\s\\"SntpService\\"/ nocase ascii wide
                        $string103_sc_greyware_tool_keyword = /sc\.exe\sdelete\s\\"Sophos\sAgent\\"/ nocase ascii wide
                        $string104_sc_greyware_tool_keyword = /sc\.exe\sdelete\s\\"Sophos\sAutoUpdate\sService\\"/ nocase ascii wide
                        $string105_sc_greyware_tool_keyword = /sc\.exe\sdelete\s\\"Sophos\sEndpoint\sDefense\sService\\"/ nocase ascii wide
                        $string106_sc_greyware_tool_keyword = /sc\.exe\sdelete\s\\"Sophos\sMessage\sRouter\\"/ nocase ascii wide
                        $string107_sc_greyware_tool_keyword = /sc\.exe\sdelete\s\\"Sophos\sSystem\sProtection\sService\\"/ nocase ascii wide
                        $string108_sc_greyware_tool_keyword = /sc\.exe\sdelete\s\\"Sophos\sWeb\sControl\sService\\"/ nocase ascii wide
                        $string109_sc_greyware_tool_keyword = /sc\.exe\sdelete\s\\"swi_service\\"/ nocase ascii wide
                        $string110_sc_greyware_tool_keyword = /sc\.exe\sdelete\s\\"swi_update\\"/ nocase ascii wide
                        $string111_sc_greyware_tool_keyword = /sc\.exe\sdelete\ssysmon/ nocase ascii wide
                        $string112_sc_greyware_tool_keyword = /sc\.exe\ssdset\sscmanager\sD\:\(A\;\;KA\;\;\;WD\)/ nocase ascii wide
                        $string113_sc_greyware_tool_keyword = /sc\.exe\sstop\s.{0,1000}Sophos\sFile\sScanner\sService/ nocase ascii wide
                        $string114_sc_greyware_tool_keyword = /sc\.exe\sstop\sbits/ nocase ascii wide
                        $string115_sc_greyware_tool_keyword = /sc\.exe\sstop\seventlog/ nocase ascii wide
                        $string116_sc_greyware_tool_keyword = /sc\.exe\\"\s\ssdset\sRemoteAccess\s/ nocase ascii wide
                        $string117_sc_greyware_tool_keyword = /sc\.exe\\"\sdelete\s\\"sysmon\\"/ nocase ascii wide
                        $string118_sc_greyware_tool_keyword = /sc\.exe\\"\sdelete\ssysmon/ nocase ascii wide
                        $string119_sc_greyware_tool_keyword = /sc\.exe.{0,1000}sdset\sscmanager\sD\:\(A\;\;KA\;\;\;WD\)/ nocase ascii wide

    condition:
        any of them
}