rule win_newbounce_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.newbounce."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.newbounce"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 83e00f 7e05 2bf0 83c610 }
                                                            
        $sequence_1 = { 7c11 8a03 4b8b8cf8a0b40600 48ffc3 }
                                                            
        $sequence_2 = { 7c2f 803b39 7f2a 488d4c2420 }
                                                            
        $sequence_3 = { 7c07 488d4c2438 eb0a 4889442430 488d4c2430 488b09 483b8e78020000 }
                                                                                                
        $sequence_4 = { 7c0c 488d15bad00200 e9???????? 488d1566d00200 }
                                                            
        $sequence_5 = { 7c8d 4863c8 498bd6 85c0 }
                                                            
        $sequence_6 = { 7c4b 4c8bc6 e8???????? 48017748 }
                                                            
        $sequence_7 = { 7c07 488d4c2460 eb0a 4889442468 }
                                                            
        $sequence_8 = { 81ec68010000 a1???????? 33c4 89842464010000 56 57 8bf1 }
                                                                                                
        $sequence_9 = { 81ec20020000 a1???????? 33c4 89842418020000 56 }
                                                                        
        $sequence_10 = { 81ec50030000 a1???????? 33c5 8945ec 53 }
                                                                        
        $sequence_11 = { 81ec28010000 a1???????? 33c5 8945fc 8b4610 }
                                                                        
        $sequence_12 = { 81ec64060000 a1???????? 33c4 89842460060000 53 }
                                                                        
        $sequence_13 = { 81ec8c010000 56 a1???????? 33c5 }
                                                            
        $sequence_14 = { 81ec58030000 a1???????? 33c4 89842450030000 }
                                                            
    condition:
        7 of them and filesize < 8637440
}