rule MALPEDIA_Win_Teleport_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "20d896b0-1f61-5a48-80a3-7c8e4c6de03e"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.teleport"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.teleport_auto.yar#L1-L129"
    license_url        = "N/A"
    logic_hash         = "a391399ac3b60b63dbd3a4a77f0c3e70c536a7803fbc2f2dce00674fad1b8479"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0 = { 50 89 45 fc 68 ?? ?? ?? ?? c7 45 f0 01 00 00 00 }
    $sequence_1 = { 57 8b fa 89 7d e8 89 b7 a0 00 00 00 8b 41 04 89 87 a4 00 00 00 8b 51 08 }
    $sequence_2 = { 88 06 46 89 b5 04 ff ff ff 8b 8d 04 ff ff ff 0f b6 f0 8d 85 f8 fe ff ff 56 }
    $sequence_3 = { c6 85 ef fe ff ff 00 50 6a 00 6a 00 c7 85 e0 fe ff ff 14 00 00 00 c7 85 e4 fe ff ff 00 00 00 00 c7 85 f0 fe ff ff 01 00 00 00 }
    $sequence_4 = { 8d 8d 80 f7 ff ff 89 9d 68 f7 ff ff e8 ?? ?? ?? ?? 83 cb 08 f6 c3 04 74 0e }
    $sequence_5 = { 8b 35 ?? ?? ?? ?? 6a 28 85 f6 74 51 c7 85 60 f7 ff ff 80 b5 42 00 e8 ?? ?? ?? ?? 89 85 84 f7 ff ff }
    $sequence_6 = { 66 89 45 a8 eb 17 83 7e 34 08 8d 46 20 c7 40 10 00 00 00 00 72 02 8b 00 }
    $sequence_7 = { 33 0c 85 60 c2 42 00 0f b6 c2 33 0c 85 60 b6 42 00 8b c3 c1 e8 10 89 4d e0 89 8f 94 00 00 00 }
    $sequence_8 = { 1b c0 83 c8 01 85 c0 0f 84 00 01 00 00 b8 ?? ?? ?? ?? 8d 8d 60 fd ff ff 66 90 }
    $sequence_9 = { 89 41 10 72 08 8b 09 89 8d 74 ff ff ff 8d 04 36 50 }

  condition:
    7 of them and filesize < 458752
}