rule MALPEDIA_Win_Bernhardpos_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "7b2918eb-6e4b-588b-9817-19ede384242f"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.bernhardpos"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.bernhardpos_auto.yar#L1-L122"
    license_url        = "N/A"
    logic_hash         = "b0e71b787dda9e2d7e79e7ddddae77406aa6aa8d138e23e43da621be02324cd1"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0 = { 0f 84 0a 01 00 00 8d 85 ec fb ff ff 50 68 2a 02 00 00 68 ?? ?? ?? ?? 8b 8d f0 fb ff ff }
    $sequence_1 = { ff 15 ?? ?? ?? ?? 8b 8d 54 fe ff ff 66 89 01 6a 10 8d 85 5c fe ff ff 50 }
    $sequence_2 = { 0f be 54 15 f8 33 ca 8b 45 08 03 45 f4 88 08 eb c7 5f }
    $sequence_3 = { 89 45 fc 8b 45 fc 8b 4d 08 03 48 3c 89 4d f4 }
    $sequence_4 = { 88 08 eb c7 5f 5e 5b }
    $sequence_5 = { 66 8b 0d ?? ?? ?? ?? 66 89 4d fc 8a 15 ?? ?? ?? ?? 88 55 fe 8d 45 f8 50 ff 15 ?? ?? ?? ?? }
    $sequence_6 = { 83 e8 63 5f 5e 5b }
    $sequence_7 = { 51 ff 15 ?? ?? ?? ?? 8d 85 ec fe ff ff 50 e8 ?? ?? ?? ?? 83 c4 04 85 c0 }
    $sequence_8 = { eb 2c 33 c0 eb 2d 33 c0 eb 29 }
    $sequence_9 = { e8 ?? ?? ?? ?? 83 c4 04 6a 01 8d 85 d0 fe ff ff 50 ff 15 ?? ?? ?? ?? }

  condition:
    7 of them and filesize < 368640
}