rule MALPEDIA_Win_Miancha_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "5e7fc19e-d4d3-5751-a42a-778cf2bcb637"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.miancha"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.miancha_auto.yar#L1-L119"
    license_url        = "N/A"
    logic_hash         = "1f67b71b2562c78fd331e78fe99dcc1e4206e3c62481b807645f41343dd343bc"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0 = { 74 12 8d 54 24 18 52 ff 15 ?? ?? ?? ?? }
    $sequence_1 = { 68 03 00 00 80 ff 15 ?? ?? ?? ?? 85 c0 74 1f 6a 00 }
    $sequence_2 = { 8b 15 ?? ?? ?? ?? 89 48 08 8a 0d ?? ?? ?? ?? 89 50 0c 88 48 10 }
    $sequence_3 = { 40 50 56 8b 35 ?? ?? ?? ?? 6a 02 6a 00 }
    $sequence_4 = { 85 f6 74 12 8d 54 24 18 52 ff 15 ?? ?? ?? ?? 50 }
    $sequence_5 = { ff 15 ?? ?? ?? ?? 50 ff d6 85 c0 74 1a }
    $sequence_6 = { 8d 54 24 18 52 ff 15 ?? ?? ?? ?? 50 ff d6 85 c0 }
    $sequence_7 = { 50 68 ?? ?? ?? ?? e8 ?? ?? ?? ?? 33 f6 83 c4 08 }
    $sequence_8 = { 89 10 8b 15 ?? ?? ?? ?? 89 48 04 8b 0d ?? ?? ?? ?? 89 50 08 8a 15 ?? ?? ?? ?? }
    $sequence_9 = { 89 10 8b 15 ?? ?? ?? ?? 89 48 04 8b 0d ?? ?? ?? ?? 89 50 08 8a 15 ?? ?? ?? ?? 89 48 0c }

  condition:
    7 of them and filesize < 376832
}