rule win_btcware_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.btcware."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.btcware"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 8d85f4faffff 68???????? 50 ffd6 83c418 8d85f0faffff 50 }
                                                                                                
        $sequence_1 = { 8b4610 c6040800 83ff03 7ca9 8b7dd8 33db }
                                                                                    
        $sequence_2 = { e8???????? 8904bd40d04100 85c0 7514 }
                                                            
        $sequence_3 = { 6888d38101 68???????? 6a00 ffd3 33d2 }
                                                                        
        $sequence_4 = { 50 ffb5a0d7ffff ff15???????? 85c0 0f8518feffff }
                                                                        
        $sequence_5 = { 5d c3 55 8bec 83e4f8 b81c820000 }
                                                                                    
        $sequence_6 = { b880fd8101 c3 b87cfd8101 c3 53 56 }
                                                                                    
        $sequence_7 = { 897df4 3bfb 0f8e6fffffff 83c8ff eb07 8b04cdc42f4100 5f }
                                                                                                
        $sequence_8 = { c78564ffffff0f000000 c68550ffffff00 83f810 7245 8b8d38ffffff }
                                                                        
        $sequence_9 = { 8945e0 8d8058c54100 8945e4 803800 8bc8 7435 8a4101 }
                                                                                                
    condition:
        7 of them and filesize < 458752
}