rule win_hermeticwizard_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.hermeticwizard."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.hermeticwizard"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 6800080000 50 e8???????? 83c410 85c0 }
                                                                        
        $sequence_1 = { 1bdb 83cb01 85db 0f94c0 }
                                                            
        $sequence_2 = { 6685db 7415 668b5902 663b5f02 750f 83c104 83c704 }
                                                                                                
        $sequence_3 = { 6689853effffff 66898540ffffff 33c0 66898542ffffff 8b45f8 66898d16ffffff }
                                                                                    
        $sequence_4 = { 3bc7 7442 8b35???????? 83c008 50 }
                                                                        
        $sequence_5 = { 57 8bf1 8bfa 68???????? 56 ff15???????? 85c0 }
                                                                                                
        $sequence_6 = { 894310 8b45f0 c745ec989d0110 8d1486 }
                                                            
        $sequence_7 = { 7410 68???????? 8bce e8???????? 59 894308 }
                                                                                    
        $sequence_8 = { 668b4104 663b4204 750b 8b4108 3b4208 7503 }
                                                                                    
        $sequence_9 = { 50 e8???????? 3b30 7533 8b45fc }
                                                                        
    condition:
        7 of them and filesize < 263168
}