rule MALPEDIA_Win_Httpdropper_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "eb6cb470-4fa5-55f1-aaf4-34eabe7782e1"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.httpdropper"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.httpdropper_auto.yar#L1-L165"
    license_url        = "N/A"
    logic_hash         = "c6973c071283bf0dc986d288edaa8567196f172f5da7a23c655925f94d3c03cb"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0  = { 8d 4c 24 3c 51 8d 54 24 1c 52 53 }
    $sequence_1  = { 51 6a 00 6a 00 68 ?? ?? ?? ?? 52 c7 45 f4 04 00 00 00 }
    $sequence_2  = { 75 06 c6 01 00 49 eb ec 8b c3 }
    $sequence_3  = { e8 ?? ?? ?? ?? 68 04 01 00 00 8d 95 ed fd ff ff 6a 00 52 c6 85 ec fd ff ff 00 }
    $sequence_4  = { 74 14 57 c6 47 03 00 e8 ?? ?? ?? ?? 83 c4 04 }
    $sequence_5  = { 51 8d 95 ec f8 ff ff 68 ?? ?? ?? ?? 52 e8 ?? ?? ?? ?? 8d 85 f4 fd ff ff }
    $sequence_6  = { 68 02 00 00 80 ff 15 ?? ?? ?? ?? 8b 85 d8 fb ff ff 8d 8d dc fb ff ff 51 }
    $sequence_7  = { c6 85 d4 f4 ff ff 00 e8 ?? ?? ?? ?? 57 68 ff 03 00 00 }
    $sequence_8  = { 33 c0 ba 01 00 00 00 f2 ae 44 8b c2 48 f7 d1 48 ff c9 }
    $sequence_9  = { 48 c7 c1 02 00 00 80 48 89 44 24 38 48 89 7c 24 30 c7 44 24 28 3f 00 0f 00 89 7c 24 20 }
    $sequence_10 = { 33 d2 41 b8 04 01 00 00 c6 84 24 f0 00 00 00 00 e8 ?? ?? ?? ?? 48 8d 15 52 0f 02 00 48 8d 8c 24 f0 00 00 00 }
    $sequence_11 = { 48 8b fb 48 8d 73 ff f2 ae 48 f7 d1 48 ff c9 }
    $sequence_12 = { 0f b7 cd 48 89 44 24 28 66 89 74 24 28 48 89 44 24 30 ff 15 ?? ?? ?? ?? 48 8b cf }
    $sequence_13 = { e8 ?? ?? ?? ?? 48 8d 8d 81 04 00 00 33 d2 41 b8 7f 0c 00 00 }
    $sequence_14 = { c1 e8 08 41 8b d1 40 32 c7 4a 0f be bc 35 da 02 00 00 81 e2 fd ff 00 00 }
    $sequence_15 = { 48 8d 4d f0 e8 ?? ?? ?? ?? b8 01 00 00 00 e9 ?? ?? ?? ?? }

  condition:
    7 of them and filesize < 524288
}