rule win_snappy_client_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-05-04"
        version = "1"
        description = "Detects win.snappy_client."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.snappy_client"
        malpedia_rule_date = "20260422"
        malpedia_hash = "a182e35da64e6d71cb55f125c4d4225196523f14"
        malpedia_version = "20260504"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { eb12 8d4608 8bcb 50 8d442414 50 e8???????? }
                                                                                                
        $sequence_1 = { ff762c 894df8 ff15???????? 8bc8 83c408 85c9 751c }
                                                                                                
        $sequence_2 = { eb06 ff75e0 ff7624 8b4e08 e8???????? 8b4e08 8b01 }
                                                                                                
        $sequence_3 = { ff7514 8bf1 ff7510 8975fc e8???????? ff7508 83a6a800000000 }
                                                                                                
        $sequence_4 = { ebf8 55 8bec 51 8365fc00 56 8b7508 }
                                                                                                
        $sequence_5 = { e9???????? 8d8d10ffffff e9???????? 8d4dcc e9???????? 8d8d00ffffff e9???????? }
                                                                                                
        $sequence_6 = { ff15???????? 85c0 7428 8b9f84000000 8bb780000000 eb16 837e0803 }
                                                                                                
        $sequence_7 = { ff7110 e8???????? 83c410 5d c20400 8d412c c6410d00 }
                                                                                                
        $sequence_8 = { ff750c 895dd4 03fb 8bcf 897de0 8d4738 8945d8 }
                                                                                                
        $sequence_9 = { ff15???????? 50 ff15???????? a3???????? c605????????00 57 8b7d18 }
                                                                                                
    condition:
        7 of them and filesize < 7315456
}