rule base64_hashed_default_creds_openmarket
{
    meta:
        version = "1.0"
        status = "RELEASED"
        sharing = "TLP:WHITE"
        source = "NDAAL GESELLSCHAFT FÜR SICHERHEIT INDER INFORMATIONSTECHNIK MBH & CO KG"
        author = "Alaa Jubakhanji@ndaal Gesellschaft fürSicherheit in der Informationstechnik mbH & Co KG"
        description = "Hashed values of default credentials for openmarket."
        category = "INFO"
        info = "SHA3_512"
        reference = "https://gitlab.com/ndaal_open_source/ndaal_yara_passwords_default/-/tree/main/yara_rules"

strings:
    $a0="YWRtaW4="
    $a1="ZGVtbw=="
    $a2="Qm9ibw=="
    $a3="aGVsbG8="
    $a4="Q29jbw=="
    $a5="aGVsbG8="
    $a6="Rmxv"
    $a7="aGVsbG8="
    $a8="Sm9l"
    $a9="aGVsbG8="
    $a10="TW9l"
    $a11="aGVsbG8="
    $a12="dXNlcl9hbmFseXN0"
    $a13="ZGVtbw=="
    $a14="dXNlcl9hcHByb3Zlcg=="
    $a15="ZGVtbw=="
    $a16="dXNlcl9hdXRob3I="
    $a17="ZGVtbw=="
    $a18="dXNlcl9jaGVja2Vy"
    $a19="ZGVtbw=="
    $a20="dXNlcl9kZXNpZ25lcg=="
    $a21="ZGVtbw=="
    $a22="dXNlcl9lZGl0b3I="
    $a23="ZGVtbw=="
    $a24="dXNlcl9leHBlcnQ="
    $a25="ZGVtbw=="
    $a26="dXNlcl9tYXJrZXRlcg=="
    $a27="ZGVtbw=="
    $a28="dXNlcl9wcmljZXI="
    $a29="ZGVtbw=="
    $a30="dXNlcl9wdWJsaXNoZXI="
    $a31="ZGVtbw=="
condition:
    ($a0 and $a1) or ($a2 and $a3) or ($a4 and $a5) or ($a6 and $a7) or ($a8 and $a9) or ($a10 and $a11) or ($a12 and $a13) or ($a14 and $a15) or ($a16 and $a17) or ($a18 and $a19) or ($a20 and $a21) or ($a22 and $a23) or ($a24 and $a25) or ($a26 and $a27) or ($a28 and $a29) or ($a30 and $a31)
}