rule win_pgift_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.pgift."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.pgift"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { c645fc03 e8???????? ff7510 8d4de8 }
                                                            
        $sequence_1 = { e8???????? 8d7e01 57 ebac }
                                                            
        $sequence_2 = { 53 6a11 ff15???????? 8bd8 8d45ec }
                                                                        
        $sequence_3 = { 53 6a01 6800000040 ff75ec ff15???????? 8bd8 }
                                                                                    
        $sequence_4 = { 7408 ff4510 83c710 eb99 8b4e14 }
                                                                        
        $sequence_5 = { 89450c 8d45e4 53 50 8d4594 50 }
                                                                                    
        $sequence_6 = { 50 8d4de4 e8???????? 33db 8d8de4feffff 895dfc 895dec }
                                                                                                
        $sequence_7 = { 8d4de8 c645fc01 e8???????? 83f8ff 750f 6a2f 8d4de8 }
                                                                                                
        $sequence_8 = { e9???????? 8b4d08 8bc3 2bc1 c1f802 3bc7 7369 }
                                                                                                
        $sequence_9 = { e8???????? ff75e8 ff15???????? eb53 8b45ec 3958f8 742f }
                                                                                                
    condition:
        7 of them and filesize < 98304
}