rule win_diceloader_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.diceloader."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.diceloader"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 488bcb e8???????? 4c634518 488d4c2420 4c03c3 41ffd0 }
                                                                                    
        $sequence_1 = { ff15???????? 488bd7 488d0d14260000 e8???????? }
                                                            
        $sequence_2 = { 8b5710 4c8d054f250000 488b4f08 41b91f000000 e8???????? }
                                                                        
        $sequence_3 = { 448b07 488d1569000000 8b5f04 488d0d4b1e0000 e8???????? 4885c0 7413 }
                                                                                                
        $sequence_4 = { 0fb6c2 8a13 48c1e804 488b44c430 488941f8 }
                                                                        
        $sequence_5 = { ff15???????? 488b1e 4885db 7420 488b1b 498bd6 }
                                                                                    
        $sequence_6 = { 440f4fe8 48035d48 418bd5 488d4b30 e8???????? 418bd5 8945e0 }
                                                                                                
        $sequence_7 = { 488dac2450faffff 4881ecb0060000 4c8d3d7b250000 c705????????00000000 }
                                                            
        $sequence_8 = { 448b541620 8b5c1624 4c03d2 4803da 4533c9 458d7901 458b02 }
                                                                                                
        $sequence_9 = { 488bda 448bc1 488d1561ffffff 488d0d761d0000 e8???????? }
                                                                        
    condition:
        7 of them and filesize < 41984
}