rule win_mimikatz_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.mimikatz."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.mimikatz"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 83f8ff 750e ff15???????? c7002a000000 }
                                                            
        $sequence_1 = { f7f1 85d2 7406 2bca }
                                                            
        $sequence_2 = { 3c02 7207 e8???????? eb10 }
                                                            
        $sequence_3 = { eb84 668b442430 eb1d 834608fe }
                                                            
        $sequence_4 = { 83f812 72f1 33c0 c3 }
                                                            
        $sequence_5 = { e8???????? 83c8ff e9???????? 8d0412 89442438 }
                                                                        
        $sequence_6 = { ff15???????? 85c0 0f94c3 85db 7508 }
                                                                        
        $sequence_7 = { 6683f83f 7607 32c0 e9???????? }
                                                            
        $sequence_8 = { c3 81f998000000 7410 81f996000000 7408 }
                                                                        
        $sequence_9 = { 66894108 33c0 39410c 740b }
                                                            
        $sequence_10 = { ff15???????? bd6f000000 3bc3 7405 }
                                                            
        $sequence_11 = { e8???????? 8bf0 85c0 7433 8b542478 d1ea 7420 }
                                                                                                
        $sequence_12 = { ff15???????? 3bc7 0f84d4010000 8b542430 }
                                                            
        $sequence_13 = { 2bc1 85c9 7403 83c008 }
                                                            
        $sequence_14 = { 83fb04 7cdc 8b5df8 8ad3 02d2 8ac7 c0e804 }
                                                                                                
        $sequence_15 = { 83e001 51 894614 c7461ce0164000 c74620f0164000 c7462410174000 }
                                                                                    
        $sequence_16 = { 897e14 897e70 c686c800000043 c6864b01000043 c7466878d14600 6a0d }
                                                                                    
        $sequence_17 = { c745fc00000000 ff15???????? 50 e8???????? 8bd8 }
                                                                        
        $sequence_18 = { 03c2 c1f802 57 50 33db 33f6 e8???????? }
                                                                                                
        $sequence_19 = { 6a00 50 e8???????? 83c40c c7450800000000 }
                                                                        
        $sequence_20 = { 83f805 7d10 668b4c4310 66890c45b8e14600 40 }
                                                                        
        $sequence_21 = { c705????????cf2f4000 8935???????? a3???????? ff15???????? a3???????? 83f8ff }
                                                                                    
    condition:
        7 of them and filesize < 1642496
}