rule win_shimrat_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.shimrat."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.shimrat"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 59 ff750c 8b4d08 e8???????? 8b4508 5f }
                                                                                    
        $sequence_1 = { 6aff ff75fc 56 ff7514 ffd7 8bd8 8d4301 }
                                                                                                
        $sequence_2 = { 8d4d50 e8???????? ff7570 e8???????? 8d4d50 }
                                                                        
        $sequence_3 = { 85ff 7e1a 8b19 ff742410 8d0433 50 e8???????? }
                                                                                                
        $sequence_4 = { ff15???????? 895df8 3bc3 0f8483000000 }
                                                            
        $sequence_5 = { 53 8d45e8 56 50 e8???????? 6a02 }
                                                                                    
        $sequence_6 = { 742e 837dfc04 7519 68???????? ff75f8 e8???????? 59 }
                                                                                                
        $sequence_7 = { 8d4ddc e8???????? 85c0 754b 8d4df0 e8???????? }
                                                                                    
        $sequence_8 = { 33c0 40 c3 a810 7404 }
                                                                        
        $sequence_9 = { ff15???????? c20400 55 8bec 81ec88000000 8365ec00 53 }
                                                                                                
    condition:
        7 of them and filesize < 65536
}