rule MALPEDIA_Win_Makop_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "0ddd5ad6-ed99-5e37-bafe-b552882375b1"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.makop"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.makop_auto.yar#L1-L129"
    license_url        = "N/A"
    logic_hash         = "153590702efa562c07e5adda47cdb1581820d31e1d121adbb82083fd02f6f827"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0 = { 55 8b ec 83 e4 f8 81 ec 10 04 00 00 53 55 56 }
    $sequence_1 = { 8b 84 24 4c 01 00 00 8b cb 51 8b 8c 24 4c 01 00 00 52 50 51 }
    $sequence_2 = { 11 7c 24 1c 8b b8 40 08 00 00 01 7c 24 20 8b b8 44 08 00 00 11 7c 24 24 8b 80 50 08 00 00 3b c3 }
    $sequence_3 = { 3d 11 01 00 00 0f 85 67 03 00 00 0f b7 44 24 44 05 17 fc ff ff 83 f8 06 0f 87 54 03 00 00 ff 24 85 9c 4f 40 00 }
    $sequence_4 = { 53 ff 15 ?? ?? ?? ?? 85 c0 0f 84 f1 00 00 00 6a 00 8d 44 24 18 }
    $sequence_5 = { 8d 44 24 18 50 51 e8 ?? ?? ?? ?? 85 c0 0f 85 cb 00 00 00 }
    $sequence_6 = { bb 01 00 00 00 39 5d 08 75 71 b8 ?? ?? ?? ?? 66 8b 08 83 c0 02 66 85 c9 }
    $sequence_7 = { 5e 5b 83 c4 1c c3 ff 15 ?? ?? ?? ?? 50 }
    $sequence_8 = { 33 db 3b f3 74 0f 56 89 5e 18 89 5e 1c }
    $sequence_9 = { 89 5c 24 1c 89 5c 24 20 89 5c 24 24 74 5e 90 8b 06 }

  condition:
    7 of them and filesize < 107520
}