rule MALPEDIA_Win_Nocturnalstealer_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "16d4de33-3c54-5479-87ac-366869086324"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.nocturnalstealer"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.nocturnalstealer_auto.yar#L1-L134"
    license_url        = "N/A"
    logic_hash         = "6f15e0c8b7c880f99f33b6a9409ba20c65fe7c5674e094de4ef3ad4c2fb61399"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0 = { ff 34 24 5e 56 e9 ?? ?? ?? ?? 81 e9 45 41 80 82 01 ca e9 ?? ?? ?? ?? }
    $sequence_1 = { e9 ?? ?? ?? ?? 09 d6 5f 81 e2 20 00 00 00 ba 00 00 00 00 81 f7 00 00 00 80 81 ee ff ff ff 7f }
    $sequence_2 = { e9 ?? ?? ?? ?? 01 74 24 04 ff 34 24 5e 57 89 e7 e9 ?? ?? ?? ?? }
    $sequence_3 = { 89 ef ba 00 02 00 00 25 24 00 00 00 09 cb 05 ff ff ff 7f 81 e6 ff ff ff 7f 81 c7 a2 00 00 00 }
    $sequence_4 = { e9 ?? ?? ?? ?? 83 c0 04 33 04 24 31 04 24 33 04 24 5c 55 }
    $sequence_5 = { b8 b4 88 8b 7f 25 18 10 fb 62 25 3a 26 e3 7e 05 b6 80 54 fc 31 c7 e9 ?? ?? ?? ?? 33 1c 24 }
    $sequence_6 = { e9 ?? ?? ?? ?? 8d 85 27 31 bc 18 52 89 e2 50 b8 04 00 00 00 01 c2 }
    $sequence_7 = { e9 ?? ?? ?? ?? 89 5c 24 04 8b 1c 24 83 c4 04 89 34 24 89 04 24 e9 ?? ?? ?? ?? }
    $sequence_8 = { e9 ?? ?? ?? ?? 57 89 1c 24 89 04 24 e9 ?? ?? ?? ?? 81 c7 04 00 00 00 81 c7 04 00 00 00 }
    $sequence_9 = { f7 d8 f7 d0 c1 e8 08 c1 e8 02 e9 ?? ?? ?? ?? 29 cf 8b 0c 24 }

  condition:
    7 of them and filesize < 10739712
}