rule win_8base_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.8base."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.8base"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 6a00 ff15???????? 8d8e04a2feff 81f98c230000 770b }
                                                                        
        $sequence_1 = { 8b5104 8b4c2408 c74432f45c394000 5e }
                                                            
        $sequence_2 = { 8815???????? c605????????6f 880d???????? c605????????65 c605????????63 }
                                                                        
        $sequence_3 = { 8d3485c0289100 8b06 83e71f c1e706 03c7 8a5824 }
                                                                                    
        $sequence_4 = { c684249c00000002 50 c7442410043a4000 e8???????? }
                                                            
        $sequence_5 = { d3ea 89542414 8b442434 01442414 8b442424 31442410 }
                                                                                    
        $sequence_6 = { ff15???????? 8b442414 40 3d???????? 89442414 0f8c0effffff 8b35???????? }
                                                                                                
        $sequence_7 = { 8bf7 83e61f c1e606 033485c0289100 c745e401000000 }
                                                                        
        $sequence_8 = { 6689442416 33c9 668954241a 8d442434 50 66894c241c 8b4c241c }
                                                                                                
        $sequence_9 = { 899c24ac000000 3bfb 7449 8b8424b8000000 56 8d742418 }
                                                                                    
    condition:
        7 of them and filesize < 10838016
}