rule MALPEDIA_Win_Netsupportmanager_Rat_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "cef2dd3b-0f7d-59a7-a048-7ced175e981a"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.netsupportmanager_rat"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.netsupportmanager_rat_auto.yar#L1-L134"
    license_url        = "N/A"
    logic_hash         = "79986ba5845ddb197c2cbb664d974c015a806cc2574092a014c092c0439de61a"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0 = { ff 15 ?? ?? ?? ?? 8b 7d f0 3b fb c7 45 fc ff ff ff ff 74 10 8b cf e8 ?? ?? ?? ?? }
    $sequence_1 = { f3 a4 8d 4d fc 51 e8 ?? ?? ?? ?? 83 c4 04 66 3d ff ff 66 89 45 dc }
    $sequence_2 = { e8 ?? ?? ?? ?? 8b cb e8 ?? ?? ?? ?? 8b 45 10 8b 08 89 4b 34 8b 50 04 }
    $sequence_3 = { ff 15 ?? ?? ?? ?? 85 ff 74 17 8b 1b 81 e7 ff ff 00 00 6a 00 57 }
    $sequence_4 = { c6 44 02 04 00 e8 ?? ?? ?? ?? 8b 85 58 ff ff ff 83 c4 04 85 c0 75 14 8b 95 50 ff ff ff }
    $sequence_5 = { e8 ?? ?? ?? ?? 8b 97 50 03 00 00 52 e8 ?? ?? ?? ?? 8b 45 0c 8b 75 10 83 c4 08 }
    $sequence_6 = { ff 15 ?? ?? ?? ?? 85 c0 75 0e 8b 45 e8 8b 4d e4 50 51 }
    $sequence_7 = { e8 ?? ?? ?? ?? eb 02 33 c0 c6 45 fc 01 8b f0 3b f3 75 47 }
    $sequence_8 = { e9 ?? ?? ?? ?? 68 6c 01 00 00 e8 ?? ?? ?? ?? 8b f0 83 c4 04 89 75 08 85 f6 }
    $sequence_9 = { 8d 4d f0 c7 45 fc 00 00 00 00 e8 ?? ?? ?? ?? 8b 47 04 85 c0 76 09 83 f8 ff }

  condition:
    7 of them and filesize < 4734976
}