title: '[ZSCALER-ZPA] Private application access denied (no matching policy)'
id: e3205464-0a65-52ae-982d-c5babdad106f
status: experimental
description: Converted from Sagan rule SID 5017951 (rev 2), file zscaler-zpa.rules.
author: sagan2sigma
logsource:
  product: zscaler
detection:
  selection_1:
    syslog_appname|cased: Zscaler
  selection_2:
    InternalReason|cased: BRK_MT_SETUP_FAIL_NO_POLICY_FOUND
  selection_3:
    IPProtocol|exists: true
  filter_4:
    IPProtocol|cased: 1" content
  condition: selection_1 and selection_2 and selection_3 and not filter_4
falsepositives:
  - 'Unassessed: automatically converted, not yet tuned'
level: low
tags:
  - attack.t1046
  - attack.ta0007
  - sagan.classtype.reconnaissance
custom_attributes:
  sagan.sid: '5017951'
  sagan.rev: '2'
  sagan.source_file: zscaler-zpa.rules
  rsigma.suppress: 30m
  sagan.metadata: created_at=2026_08_11,updated_at=2026_08_11