rule MALPEDIA_Win_Bunitu_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "fdd29b03-d926-5cbf-98be-29b287d71b21"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.bunitu"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.bunitu_auto.yar#L1-L119"
    license_url        = "N/A"
    logic_hash         = "c3bd7c13018c7a8c4646040c13e12026479d672a4bbef2d99f41e09a2ac2f388"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0 = { 68 ?? ?? ?? ?? 50 6a 00 68 ?? ?? ?? ?? 6a 00 50 ff 15 ?? ?? ?? ?? }
    $sequence_1 = { 58 6a 02 ff b5 24 fd ff ff ff 15 ?? ?? ?? ?? ff b5 24 fd ff ff }
    $sequence_2 = { 50 ff 75 ec e8 ?? ?? ?? ?? 0b c0 7e 18 50 }
    $sequence_3 = { 48 40 8d 44 38 25 66 8b 00 }
    $sequence_4 = { c7 00 03 00 00 00 ff b5 24 fd ff ff 8f 40 04 ff b5 28 fd ff ff 8f 40 08 }
    $sequence_5 = { ff b5 24 fd ff ff e8 ?? ?? ?? ?? eb 12 6a 08 68 ?? ?? ?? ?? ff b5 24 fd ff ff e8 ?? ?? ?? ?? }
    $sequence_6 = { 59 8b d0 8b df b8 2f 00 00 00 }
    $sequence_7 = { 89 50 04 b9 ?? ?? ?? ?? 8d 55 fc 52 68 00 00 01 00 50 51 }
    $sequence_8 = { c7 00 03 00 00 00 ff 75 f0 8f 40 04 ff 75 ec 8f 40 08 }
    $sequence_9 = { 83 7d f0 00 76 14 6a 02 ff 75 f0 ff 15 ?? ?? ?? ?? }

  condition:
    7 of them and filesize < 221184
}