rule MALPEDIA_Win_Rm3_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "7719069f-32fe-5972-8438-aed4e36844e7"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.rm3"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.rm3_auto.yar#L1-L378"
    license_url        = "N/A"
    logic_hash         = "108e288ac75d378107658478aa6294381528e48e962e4f140c133bb5541af046"
    score              = 75
    quality            = 73
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0  = { 8d 7c 13 ff 4a f7 d2 23 fa 3b f8 76 09 }
    $sequence_1  = { 8b 41 38 8b 56 08 8d 54 10 ff 48 f7 d0 }
    $sequence_2  = { 8b 45 f8 83 c6 28 ff 4d fc 85 c0 }
    $sequence_3  = { 89 31 8b 70 04 89 71 04 8b 48 08 ff 70 04 }
    $sequence_4  = { 03 4c 24 0c 8b 00 51 03 c2 50 e8 ?? ?? ?? ?? }
    $sequence_5  = { 3b f8 76 09 8b 41 3c 8d 54 18 ff eb 0a }
    $sequence_6  = { 8b 46 0c 03 c2 39 45 08 73 03 89 75 f8 8b 45 f8 }
    $sequence_7  = { 8b 5e 10 8d 44 38 ff 4f f7 d7 23 c7 8d 7c 13 ff 4a }
    $sequence_8  = { 41 ff 45 08 ff 4d 0c 88 54 05 fc }
    $sequence_9  = { 57 8b c3 8d 95 68 ff ff ff e8 ?? ?? ?? ?? 8b 84 9d 64 ff ff ff }
    $sequence_10 = { e8 ?? ?? ?? ?? 8b 55 08 57 8b c3 8d 8d 58 fe ff ff e8 ?? ?? ?? ?? }
    $sequence_11 = { 8b 75 0c 50 8d b4 b5 58 fe ff ff 89 45 10 }
    $sequence_12 = { 8b f0 2b 75 08 f7 de 1b f6 83 e6 0b }
    $sequence_13 = { e8 ?? ?? ?? ?? 8b d8 85 db 74 20 8d 45 fc }
    $sequence_14 = { e8 ?? ?? ?? ?? 2b f3 89 75 0c 0f 88 b3 00 00 00 8d 3c 1e 8d bc bd 58 fe ff ff }
    $sequence_15 = { 74 4b 89 75 fc 6a 18 5e }
    $sequence_16 = { 33 d2 45 33 c0 41 0f c9 48 f7 b4 24 88 00 00 00 8b 15 ?? ?? ?? ?? }
    $sequence_17 = { 48 8b f3 48 8b ce e8 ?? ?? ?? ?? 48 85 c0 48 8b d8 74 15 }
    $sequence_18 = { 41 55 41 56 41 57 48 83 ec 30 4c 8b 05 ?? ?? ?? ?? 49 b9 1d dd 6c 4f 91 f4 45 25 }
    $sequence_19 = { 41 be 18 00 00 00 48 8b 15 ?? ?? ?? ?? 48 8b 42 70 48 8b c8 48 c1 e9 0c 48 33 c1 48 8b c8 }
    $sequence_20 = { 57 41 54 41 55 41 56 41 57 48 83 ec 20 4c 8b 05 ?? ?? ?? ?? }
    $sequence_21 = { 48 8b c1 48 c1 e8 1b 48 33 c1 33 c9 48 0f af c3 }
    $sequence_22 = { ff 15 ?? ?? ?? ?? 85 c0 74 45 48 8d 4c 24 68 ff 15 ?? ?? ?? ?? ff 15 ?? ?? ?? ?? }
    $sequence_23 = { 48 8d 4c 24 40 4c 8b ce 4c 8b c5 49 8b d4 }
    $sequence_24 = { 89 95 68 ff ff ff 89 b5 64 ff ff ff 88 9d 63 ff ff ff 75 70 31 c0 89 85 5c ff ff ff eb 16 }
    $sequence_25 = { 8d 0d 84 30 87 02 31 d2 8b 75 f0 89 46 2c 89 0c 24 }
    $sequence_26 = { 88 58 01 39 d7 89 7d b8 89 75 b4 75 d7 8d 45 d4 }
    $sequence_27 = { a1 ?? ?? ?? ?? 6a 00 6a 00 6a 00 6a 00 68 ?? ?? ?? ?? ff d0 }
    $sequence_28 = { ff d0 8d 0d d1 31 87 02 89 04 24 89 4c 24 04 e8 ?? ?? ?? ?? 83 f8 00 }
    $sequence_29 = { 52 8b b5 e0 fb ff ff 56 89 85 d0 fb ff ff 89 95 cc fb ff ff 89 8d c8 fb ff ff ff d7 }
    $sequence_30 = { 89 45 d0 8b 45 d0 8b 4d d4 8b 55 ec 01 ca 89 14 24 }
    $sequence_31 = { 89 7d ec 89 55 e8 89 75 e4 ff d3 83 ec 10 89 04 24 }
    $sequence_32 = { 53 57 56 83 ec 20 8b 45 0c 8b 4d 08 31 d2 }
    $sequence_33 = { 89 0c 24 c7 44 24 04 00 00 00 00 89 55 dc e8 ?? ?? ?? ?? 8d 0d 77 31 87 02 89 04 24 }
    $sequence_34 = { 8b 78 34 8b 5f 3c 89 45 f0 89 f8 01 d8 81 3c 1f 50 45 00 00 }
    $sequence_35 = { 8b bd 64 fd ff ff 89 7e 08 8b 9d 68 fd ff ff 89 1e }
    $sequence_36 = { c7 46 0c fe 30 87 02 c7 46 04 ?? ?? ?? ?? 8b 35 ?? ?? ?? ?? 89 85 e0 fd ff ff 89 8d dc fd ff ff 89 95 d8 fd ff ff }
    $sequence_37 = { 89 8d fc fe ff ff e8 ?? ?? ?? ?? 89 04 24 8b 85 3c ff ff ff 89 44 24 04 }
    $sequence_38 = { 89 e2 89 4a 04 c7 02 04 01 00 00 8b 15 ?? ?? ?? ?? 89 85 e8 fd ff ff 89 8d e4 fd ff ff }
    $sequence_39 = { 8b 59 24 89 85 5c ff ff ff 89 d8 c1 e8 1e 83 e0 01 }

  condition:
    7 of them and filesize < 221184
}