rule win_dimnie_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.dimnie."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.dimnie"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { eb04 c645af3d 8b4d0c 8a55af 885102 837d1002 }
                                                                                    
        $sequence_1 = { 7e28 8b5508 0fb64201 83e00f c1e002 8b4d08 0fb65102 }
                                                                                                
        $sequence_2 = { 8b450c eb54 8b550c 2b5508 83fa01 751c 0f31 }
                                                                                                
        $sequence_3 = { c70201000000 8b4508 8b08 83e10f 8b5508 }
                                                                        
        $sequence_4 = { eb54 8b550c 2b5508 83fa01 751c }
                                                                        
        $sequence_5 = { eb61 8b4d08 3b4d0c 7605 8b450c eb54 8b550c }
                                                                                                
        $sequence_6 = { c70201000000 8b4508 8b08 83e10f 8b5508 890a }
                                                                                    
        $sequence_7 = { 8855ae eb04 c645ae3d 8b450c 8a4dae }
                                                                        
        $sequence_8 = { b90d000000 be???????? 8d7dbc f3a5 }
                                                            
        $sequence_9 = { 8b4d0c 8a55af 885102 837d1002 7e13 8b4508 }
                                                                                    
    condition:
        7 of them and filesize < 212992
}