rule MALPEDIA_Win_Ziyangrat_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "61b87837-dc98-50eb-8916-bc6cbc20d03f"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.ziyangrat"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.ziyangrat_auto.yar#L1-L125"
    license_url        = "N/A"
    logic_hash         = "63664fb49a7b130cd77da76446f0977d6b37fb6657ee0279b7de100f4571b771"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0 = { 89 44 24 05 89 44 24 09 66 89 44 24 0d 88 44 24 0f 8b 11 8d 44 24 10 }
    $sequence_1 = { c3 8b 9c 24 a4 00 00 00 68 ?? ?? ?? ?? 53 8d 4c 24 44 }
    $sequence_2 = { c6 84 24 e2 00 00 00 69 88 84 24 e3 00 00 00 88 9c 24 e4 00 00 00 88 8c 24 eb 00 00 00 c6 84 24 ec 00 00 00 47 c6 84 24 ed 00 00 00 20 }
    $sequence_3 = { b9 3f 00 00 00 33 c0 8d bc 24 41 01 00 00 88 9c 24 40 01 00 00 b2 65 f3 ab }
    $sequence_4 = { 8d bd 48 f7 ff ff 83 c9 ff 33 c0 f2 ae f7 d1 83 c1 ff 51 }
    $sequence_5 = { 88 9c 24 10 02 00 00 89 44 24 61 88 9c 24 10 07 00 00 66 89 44 24 65 88 9c 24 10 03 00 00 }
    $sequence_6 = { 8b 4c 24 10 56 50 51 e8 ?? ?? ?? ?? 68 ?? ?? ?? ?? 8d 54 24 20 }
    $sequence_7 = { 48 0d 00 00 ff ff 40 66 89 44 24 08 25 ff ff 00 00 8d 14 40 }
    $sequence_8 = { 50 e8 ?? ?? ?? ?? 83 c4 0c 85 c0 75 2a e8 ?? ?? ?? ?? }
    $sequence_9 = { 8b 7c 24 0c 8b 04 bd 10 89 40 00 8d 1c bd 10 89 40 00 3d 00 10 00 00 0f 84 c8 00 00 00 8b 04 bd 20 09 41 00 56 }

  condition:
    7 of them and filesize < 188416
}