rule MALPEDIA_Win_Nimgrabber_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "3ff9ecdf-434a-5531-ae47-14063d732bcc"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.nimgrabber"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.nimgrabber_auto.yar#L1-L133"
    license_url        = "N/A"
    logic_hash         = "d88020b2287429253ba602c12d16ae36bc236c828c7e32d50b3c884fb53a1e20"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0 = { 0f 8f a7 00 00 00 c7 81 98 14 00 00 00 40 00 00 b8 00 40 00 00 c7 44 24 0c 04 00 00 00 c7 44 24 08 00 30 00 00 39 c7 0f 8f d0 01 00 00 }
    $sequence_1 = { 8b 84 24 90 00 00 00 83 c0 04 89 44 24 30 0f 80 de 2e 00 00 8b 84 24 d8 00 00 00 8b 00 39 44 24 30 }
    $sequence_2 = { c7 05 ?? ?? ?? ?? b8 3b 48 00 c7 05 ?? ?? ?? ?? 20 00 00 00 c7 05 ?? ?? ?? ?? 02 00 00 00 c7 05 ?? ?? ?? ?? 00 25 48 00 66 89 15 ?? ?? ?? ?? c6 05 ?? ?? ?? ?? 01 c7 05 ?? ?? ?? ?? 00 00 00 00 }
    $sequence_3 = { 8d 47 10 8d 5f 08 be ?? ?? ?? ?? b9 0b 00 00 00 c7 43 04 2b 00 00 00 c7 47 08 2b 00 00 00 89 c7 }
    $sequence_4 = { c1 f8 0c 89 44 24 18 89 e8 0f b6 c0 8d 04 83 89 44 24 1c 8b 80 84 10 00 00 }
    $sequence_5 = { 7f 0d b9 ?? ?? ?? ?? e8 ?? ?? ?? ?? 8b 45 14 83 e8 01 0f 80 67 16 00 00 89 45 14 }
    $sequence_6 = { c7 04 24 ?? ?? ?? ?? 89 4c 24 74 89 54 24 04 e8 ?? ?? ?? ?? 8b 4c 24 74 31 c0 89 4b 04 }
    $sequence_7 = { 8b 6f 04 81 fd 00 00 00 3f 7e 28 c7 04 24 00 00 00 3f 89 fa 89 f1 e8 ?? ?? ?? ?? }
    $sequence_8 = { 89 f9 e8 ?? ?? ?? ?? 8b 4c 24 54 89 da e8 ?? ?? ?? ?? 8b 07 }
    $sequence_9 = { 74 0a 8b 0b 85 c9 0f 88 a6 02 00 00 e8 ?? ?? ?? ?? 31 ed 89 44 24 30 }

  condition:
    7 of them and filesize < 1238016
}