rule win_dlrat_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.dlrat."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.dlrat"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 488d0de60b1600 e8???????? 488975b0 4989d9 4531c0 baaa020000 488d0dcb0b1600 }
                                                                                                
        $sequence_1 = { 488d1df28e0500 48895dc8 48c745c011000000 488d55c0 488d0dcb8e0500 48894dd8 48c745d009000000 }
                                                                                                
        $sequence_2 = { e8???????? 85c0 7818 3de4000000 7311 4898 488d0d723b0100 }
                                                                                                
        $sequence_3 = { e8???????? 83fb01 7754 488d05aa270b00 488945a8 48c745a000000000 488d55a0 }
                                                                                                
        $sequence_4 = { 48ffc0 482bd8 48899df0fcffff 488b9de8fcffff 4803d8 48899df8fcffff 488d0513701600 }
                                                                                                
        $sequence_5 = { 488b8d20ffffff 4883ec20 e8???????? 4883c420 4889c2 488d0de71f1800 4883ec20 }
                                                                                                
        $sequence_6 = { 41c64424076c 41c644240863 41c644240979 41c644240a39 41c644240b6f 41c644240c5a 41c644240d57 }
                                                                                                
        $sequence_7 = { 488b03 488985a0fcffff 488995a8fcffff 488b3d???????? 488b97b0000000 488b87a8000000 488985b0fcffff }
                                                                                                
        $sequence_8 = { e8???????? 48c745b000000000 4c8bce 4c8bc3 ba2f070000 488d0d5e411500 e8???????? }
                                                                                                
        $sequence_9 = { ffc1 e8???????? 48894580 48895588 488d4580 48898520ffffff 488d1d6a691000 }
                                                                                                
    condition:
        7 of them and filesize < 4121600
}