rule MALPEDIA_Win_Neutrino_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "b9eb1524-9975-578b-ab6d-93138480d1f6"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.neutrino"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.neutrino_auto.yar#L1-L324"
    license_url        = "N/A"
    logic_hash         = "b8cd6770a3479380c0f958a2776eccb26f589975e6ef7e101cff7469e248afc4"
    score              = 60
    quality            = 43
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0  = { ff 15 ?? ?? ?? ?? c1 e0 10 50 ff 15 ?? ?? ?? ?? }
    $sequence_1  = { 50 6a 0b 6a 07 e8 ?? ?? ?? ?? }
    $sequence_2  = { 50 6a 05 6a 03 e8 ?? ?? ?? ?? }
    $sequence_3  = { 85 c9 74 39 8b 55 0c 89 55 fc 8b 45 fc 0f be 08 85 c9 }
    $sequence_4  = { 0f be 02 85 c0 74 47 8b 4d f4 0f be 11 8b 45 fc 0f be 08 }
    $sequence_5  = { 04 04 04 04 04 04 04 02 02 02 02 02 }
    $sequence_6  = { 8b 4d 0c 89 4d fc 8b 55 f4 83 c2 01 89 55 f4 eb af 8b 45 f4 }
    $sequence_7  = { 04 04 04 04 01 04 04 02 02 }
    $sequence_8  = { 02 04 02 04 04 04 04 04 04 04 04 04 04 04 03 }
    $sequence_9  = { 51 0f b6 55 e7 52 8b 45 e0 50 e8 ?? ?? ?? ?? }
    $sequence_10 = { 0f be 08 85 c9 74 1b 8b 55 fc 0f be 02 8b 4d f8 0f be 11 }
    $sequence_11 = { 89 4d fc 8b 55 fc 0f be 02 85 c0 75 0f 8b 4d 0c 89 4d fc }
    $sequence_12 = { 6a 00 ff 15 ?? ?? ?? ?? 68 80 00 00 00 ff 15 ?? ?? ?? ?? }
    $sequence_13 = { 01 04 04 02 02 02 04 02 04 04 }
    $sequence_14 = { e9 ?? ?? ?? ?? 6a 01 ff 15 ?? ?? ?? ?? 85 c0 }
    $sequence_15 = { 52 ff 15 ?? ?? ?? ?? 83 f8 ff 75 04 32 c0 eb 02 b0 01 }
    $sequence_16 = { 89 4d 08 0f b6 55 0c 83 fa 01 75 09 8b 45 08 83 c0 01 89 45 08 }
    $sequence_17 = { 74 07 81 4a 18 00 30 00 00 f6 45 fe 01 0f 84 94 02 00 00 83 4a 18 01 8b 45 f4 }
    $sequence_18 = { 6a 1c 5b 8d 4d e0 51 50 89 5d e0 ff 15 ?? ?? ?? ?? }
    $sequence_19 = { 8a 00 ff 45 f4 8b 72 18 8a d8 c0 eb 06 88 5d fc }
    $sequence_20 = { 73 54 8b 3b 0f b6 f2 6a 05 58 2b c6 8d 14 37 }
    $sequence_21 = { 51 ff 35 ?? ?? ?? ?? c7 46 04 80 00 00 00 ff 15 ?? ?? ?? ?? 89 06 }
    $sequence_22 = { 33 d2 81 e1 00 f0 ff ff eb 08 3b c1 74 09 8b d0 }
    $sequence_23 = { f6 45 fe 02 74 0a 83 4a 18 04 8a 03 88 42 10 43 f6 45 fe 40 }
    $sequence_24 = { 83 c1 20 81 fa e0 0f 00 00 76 ea 8b 0d ?? ?? ?? ?? 89 08 a3 ?? ?? ?? ?? 5f }
    $sequence_25 = { 8d 85 b8 fe ff ff 50 68 ?? ?? ?? ?? ff 15 ?? ?? ?? ?? 89 45 fc }
    $sequence_26 = { 83 c4 0c 68 04 01 00 00 8d 85 f8 fd ff ff 50 }
    $sequence_27 = { 75 07 68 ?? ?? ?? ?? eb 05 68 ?? ?? ?? ?? 50 ff 51 0c }
    $sequence_28 = { 75 22 be ?? ?? ?? ?? ff 15 ?? ?? ?? ?? 57 89 06 ff 15 ?? ?? ?? ?? 83 c6 04 }
    $sequence_29 = { 74 12 68 ?? ?? ?? ?? 50 ff 15 ?? ?? ?? ?? f7 d8 1b c0 }
    $sequence_30 = { 57 33 ff 39 3d ?? ?? ?? ?? 75 22 be ?? ?? ?? ?? }
    $sequence_31 = { ff 15 ?? ?? ?? ?? 50 ff 15 ?? ?? ?? ?? 83 7d fc 00 0f 95 c0 c9 }
    $sequence_32 = { ff 75 0c ff 75 08 ff 15 ?? ?? ?? ?? 83 f8 ff 0f 95 c0 }

  condition:
    7 of them and filesize < 507904
}