rule win_gacrux_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.gacrux."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.gacrux"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 85c9 743c 6548 8b0425???????? 80780201 7428 48 }
                                                                                                
        $sequence_1 = { 33db e8???????? 48 8bf8 48 85c0 742f }
                                                                                                
        $sequence_2 = { 3900 75f4 48 63c2 85d2 740a 48 }
                                                                                                
        $sequence_3 = { 740b 41 81cb00900000 45 895821 40 f6c610 }
                                                                                                
        $sequence_4 = { e8???????? 4c 8bc3 33d2 48 8bcf ffd0 }
                                                                                                
        $sequence_5 = { 3c40 755f 41 0fbaea1e 40 8ac7 c0e803 }
                                                                                                
        $sequence_6 = { 0fb6c3 44 3bc8 0f850f010000 44 0fb66d67 43 }
                                                                                                
        $sequence_7 = { 75f6 e8???????? 48 83c428 c3 48 }
                                                                                    
        $sequence_8 = { eb02 33db 8b4c2460 0337 392f 75a5 eb5d }
                                                                                                
        $sequence_9 = { 83e801 7463 83e801 7457 83e802 744b }
                                                                                    
    condition:
        7 of them and filesize < 122880
}