rule MALPEDIA_Win_Nautilus_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "bd0f8568-9347-5c4b-aef6-8e7929cf6017"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.nautilus"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.nautilus_auto.yar#L1-L134"
    license_url        = "N/A"
    logic_hash         = "6e0983236c8ba852bb2af3aa295c07b825fa6ac12512321743324e3ea59238a7"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0 = { 8b cf e8 ?? ?? ?? ?? 8b d8 8b cd e8 ?? ?? ?? ?? 85 db 8b ce }
    $sequence_1 = { 85 c0 74 0c 48 8b 45 98 48 33 c7 e9 ?? ?? ?? ?? c7 44 24 20 0f 00 00 00 e9 ?? ?? ?? ?? }
    $sequence_2 = { 8b fe 48 63 13 48 8d 0d cc 34 06 00 f6 04 0a 02 74 4b 41 8d 46 fa 48 8b cb }
    $sequence_3 = { 85 c0 78 92 48 8d 4c 24 30 49 8b d4 e8 ?? ?? ?? ?? 85 c0 79 81 }
    $sequence_4 = { ba 03 00 00 00 4d 8b c5 8d 4a ff e8 ?? ?? ?? ?? 4c 8b e0 48 85 c0 75 09 }
    $sequence_5 = { 85 f6 75 0c 33 c0 eb 3a 48 8b 0b 49 89 0e eb 30 }
    $sequence_6 = { 85 c0 79 d6 4c 8d 45 cf 48 8d 55 cf 48 8d 4d b7 e8 ?? ?? ?? ?? 8b d8 }
    $sequence_7 = { eb 07 c7 45 e0 06 00 00 00 48 8d 45 e0 41 b9 12 00 00 00 4d 8b c4 49 8b d5 48 8b cf }
    $sequence_8 = { 48 83 f8 03 0f 8c ef 01 00 00 48 8b d3 48 8b cd ff 95 c8 01 00 00 85 c0 0f 85 99 fe ff ff }
    $sequence_9 = { e8 ?? ?? ?? ?? 85 c0 75 31 48 8d 4d b0 33 d2 e8 ?? ?? ?? ?? 85 c0 }

  condition:
    7 of them and filesize < 1302528
}