rule win_zeus_mailsniffer_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.zeus_mailsniffer."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.zeus_mailsniffer"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 81ec1c020000 56 6a1c 58 8945f0 c745f4c89d2d01 8945f8 }
                                                                                                
        $sequence_1 = { 0f8486000000 6a10 58 e8???????? 8bf0 85f6 }
                                                                                    
        $sequence_2 = { e8???????? 83c40c 833e00 894608 897e0c 7421 }
                                                                                    
        $sequence_3 = { 8b4508 8b4dec c745f451000000 8908 83ff17 750f }
                                                                                    
        $sequence_4 = { e8???????? 57 68???????? 57 e8???????? 83c424 }
                                                                                    
        $sequence_5 = { 85c0 0f8498010000 8b45f4 8365c800 83c004 }
                                                                        
        $sequence_6 = { 57 8d85ecfeffff 50 53 8d85b4faffff }
                                                                        
        $sequence_7 = { ff15???????? ffb424f4040000 ff15???????? 8b8424cc040000 }
                                                            
        $sequence_8 = { 83c410 85ff 742c 8b462c ff7608 ff7628 85c0 }
                                                                                                
        $sequence_9 = { 743f 66833f00 7439 56 6a16 8d75e4 58 }
                                                                                                
    condition:
        7 of them and filesize < 368640
}