rule win_tinyfluff_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.tinyfluff."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.tinyfluff"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 51 50 51 ffb5dcfbffff 8d8d74fbffff e8???????? 8d8590fbffff }
                                                                                                
        $sequence_1 = { 85c0 7418 8b858cfbffff 85c0 7407 50 }
                                                                                    
        $sequence_2 = { 8b0c8550704100 8a043b 03ce 8b75dc }
                                                            
        $sequence_3 = { eb6f 8b07 8d1c85446d4100 8b33 85f6 }
                                                                        
        $sequence_4 = { e8???????? be01000000 8b95d8fbffff 83fa08 7235 }
                                                                        
        $sequence_5 = { c7404860604100 8b4508 6689486c 8b4508 66898872010000 8d4dff 8b4508 }
                                                                                                
        $sequence_6 = { c7404860604100 8b4508 6689486c 8b4508 66898872010000 }
                                                                        
        $sequence_7 = { 33c0 c744246000000000 c744246407000000 6689442450 }
                                                            
        $sequence_8 = { 8d85a8fbffff 6a01 0f4385a8fbffff 68???????? }
                                                            
        $sequence_9 = { c1fa06 8934b8 8bc7 83e03f 6bc838 8b049550704100 8b440818 }
                                                                                                
    condition:
        7 of them and filesize < 245760
}