rule win_smarteyes_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.smarteyes."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.smarteyes"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 84c9 75f6 8b8da8feffff 8bc1 c1e817 2401 8885dafeffff }
                                                                                                
        $sequence_1 = { 8b7b3c 898580fbffff 33c0 66898594fbffff 8b432c 89859cfbffff 8b4310 }
                                                                                                
        $sequence_2 = { 84c9 75f9 2bc6 8d8418280a0000 50 e8???????? 8bd8 }
                                                                                                
        $sequence_3 = { 3bc8 727c 03c0 8945fc 3bc1 7703 894dfc }
                                                                                                
        $sequence_4 = { ffb5e0feffff e8???????? 59 8bbde4feffff 8b4508 6a4b 83c708 }
                                                                                                
        $sequence_5 = { 814df800000001 3bd7 7507 814df800008000 8b5d08 57 }
                                                                                    
        $sequence_6 = { 33c9 3c01 0f94c1 8d442430 52 51 50 }
                                                                                                
        $sequence_7 = { 50 e8???????? 8b4de4 83c40c 6bc930 8975e0 8db118bb0210 }
                                                                                                
        $sequence_8 = { 56 57 6a09 59 33c0 be1c010000 56 }
                                                                                                
        $sequence_9 = { 53 55 56 57 33c0 be???????? 6a06 }
                                                                                                
    condition:
        7 of them and filesize < 429056
}