rule MALPEDIA_Win_Gameover_P2P_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "f23c7d41-302b-54ee-89d3-a1fcd7481d37"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.gameover_p2p"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.gameover_p2p_auto.yar#L1-L127"
    license_url        = "N/A"
    logic_hash         = "15df0db5593f1e0961da9a214002cfa7e3553ad059d6ba39628050e96c9953a2"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0 = { 8b 01 89 75 dc 85 c0 74 0f ff b0 9c 01 00 00 8d 45 d4 50 }
    $sequence_1 = { 8d 87 3c 01 00 00 50 88 9f 38 01 00 00 ff d6 }
    $sequence_2 = { ba ?? ?? ?? ?? 8d 8d 70 fd ff ff e8 ?? ?? ?? ?? 85 c0 0f 95 c0 84 c0 75 09 }
    $sequence_3 = { 74 3f 53 8d 44 24 20 50 57 56 ff 74 24 28 }
    $sequence_4 = { 77 69 8a 44 24 12 0f b6 c0 66 89 01 8a 44 24 13 0f b6 c0 66 89 41 02 }
    $sequence_5 = { 74 15 ff 77 0c 8d 44 24 18 51 }
    $sequence_6 = { e8 ?? ?? ?? ?? 8b f8 68 9a 00 00 00 8b d3 8b ce 89 7c 24 2c }
    $sequence_7 = { b9 a6 00 00 00 8d 55 88 e8 ?? ?? ?? ?? e8 ?? ?? ?? ?? 8b c8 e8 ?? ?? ?? ?? 8b 75 0c }
    $sequence_8 = { 85 c0 75 48 68 ?? ?? ?? ?? ff 35 ?? ?? ?? ?? ff d6 85 c0 75 37 }
    $sequence_9 = { f3 ab 33 db 68 18 01 00 00 66 ab 8d 84 24 10 01 00 00 53 50 }

  condition:
    7 of them and filesize < 598016
}