rule win_grillmark_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.grillmark."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.grillmark"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { ff15???????? 8d4df4 56 51 53 50 57 }
                                                                                                
        $sequence_1 = { 6800000080 ff7510 ff15???????? 8bf8 83ffff 7436 53 }
                                                                                                
        $sequence_2 = { f3ab 66ab aa 8d458c 895df8 50 895df4 }
                                                                                                
        $sequence_3 = { 83ffff 7504 33c0 eb1a }
                                                            
        $sequence_4 = { 66a5 a4 5f 33c0 3905???????? 5e 50 }
                                                                                                
        $sequence_5 = { 57 e8???????? 8d85f4fcffff 50 57 }
                                                                        
        $sequence_6 = { ff15???????? 6a40 33c0 59 8dbdfdfeffff 889dfcfeffff 53 }
                                                                                                
        $sequence_7 = { 66ab aa 8d85fcfeffff 50 6804010000 e8???????? }
                                                                                    
        $sequence_8 = { 50 57 ffb604010000 56 e8???????? 83c410 85c0 }
                                                                                                
        $sequence_9 = { 6a01 ff7508 e8???????? 56 e8???????? ff75f4 }
                                                                                    
    condition:
        7 of them and filesize < 212992
}