rule MALPEDIA_Win_Disttrack_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "2e51f756-65a0-5587-a62f-f2956dec5749"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.disttrack"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.disttrack_auto.yar#L1-L264"
    license_url        = "N/A"
    logic_hash         = "ea5b03edf12e9b7619694e3ef0c115e1438e4209a3ddaae7b74afa494e3c57a2"
    score              = 75
    quality            = 73
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0  = { 52 6a 00 6a 00 68 48 00 07 00 }
    $sequence_1  = { ff 15 ?? ?? ?? ?? 5d 5b 8b c7 5f 5e }
    $sequence_2  = { 68 ?? ?? ?? ?? ff 15 ?? ?? ?? ?? 8d 45 dc 50 ff 15 ?? ?? ?? ?? 8b 4d dc }
    $sequence_3  = { e8 ?? ?? ?? ?? 6a 07 e8 ?? ?? ?? ?? 59 c3 6a 10 }
    $sequence_4  = { e8 ?? ?? ?? ?? 83 c4 04 50 e8 ?? ?? ?? ?? 83 c4 04 68 ?? ?? ?? ?? ff 15 ?? ?? ?? ?? }
    $sequence_5  = { 48 8b c8 e8 ?? ?? ?? ?? eb d1 49 8b 94 dc a0 94 01 00 }
    $sequence_6  = { 41 bd 08 00 00 00 41 80 fd fe 76 0d 48 8d 0d 39 2e 01 00 e8 ?? ?? ?? ?? }
    $sequence_7  = { 74 42 48 8d 15 7a 84 00 00 48 8b cf e8 ?? ?? ?? ?? 85 c0 75 25 }
    $sequence_8  = { 89 5c 24 40 89 5c 24 44 89 9c 24 d8 00 00 00 89 9c 24 b0 00 00 00 89 9c 24 b8 00 00 00 }
    $sequence_9  = { 88 4c 30 ff 3b f3 72 e6 8b 75 ec 6a 00 }
    $sequence_10 = { c3 8b 04 cd 44 ec 42 00 5d c3 05 44 ff ff ff }
    $sequence_11 = { 57 48 83 ec 20 48 8d 0d c7 4a 01 00 e8 ?? ?? ?? ?? 48 83 3d ?? ?? ?? ?? 00 75 10 48 8d 0d b1 4a 01 00 }
    $sequence_12 = { 0f b7 da 66 83 fa 30 0f 86 2b 01 00 00 8b 44 24 1c 33 c9 66 89 4c 44 22 66 89 5c 44 20 }
    $sequence_13 = { 88 5d f3 8b 41 04 80 78 19 00 8b f9 75 14 38 58 0c }
    $sequence_14 = { c7 45 08 00 00 00 00 e8 ?? ?? ?? ?? 68 ?? ?? ?? ?? 8d 4d f4 51 c7 45 f4 6c 92 41 00 }
    $sequence_15 = { e8 ?? ?? ?? ?? 03 f0 56 e8 ?? ?? ?? ?? 83 c4 04 c7 45 fc 00 00 00 00 }
    $sequence_16 = { 51 ff 15 ?? ?? ?? ?? 8b 55 d4 89 55 e4 8b 45 d8 }
    $sequence_17 = { 8b c1 eb 0c 0f b6 c9 0f be 89 68 00 42 00 }
    $sequence_18 = { 8b 40 04 80 78 19 00 74 ee 80 79 19 00 75 05 8b c8 }
    $sequence_19 = { 45 33 c0 49 8b d4 33 c9 c7 44 24 28 00 00 00 08 89 5c 24 20 ff 15 ?? ?? ?? ?? 85 c0 }
    $sequence_20 = { 75 f9 2b c2 56 57 8d 78 01 }
    $sequence_21 = { be 01 00 00 00 48 83 63 08 00 48 8d 05 cf 45 01 00 48 89 03 48 8d 4c 24 28 }
    $sequence_22 = { 48 63 48 04 48 8d 05 b0 27 01 00 48 89 44 19 e8 48 83 c4 30 }
    $sequence_23 = { 52 50 68 ?? ?? ?? ?? ff 15 ?? ?? ?? ?? 8d 34 f5 b0 04 42 00 89 44 24 20 33 ff }
    $sequence_24 = { 7d 13 48 63 ca 8a 44 19 1c 42 88 84 01 60 2a 02 00 ff c2 eb e1 }
    $sequence_25 = { 8d 84 24 98 03 00 00 64 a3 00 00 00 00 8b 45 08 33 db 89 44 24 30 }
    $sequence_26 = { 3b c3 0f 84 76 01 00 00 68 ?? ?? ?? ?? 68 ?? ?? ?? ?? }

  condition:
    7 of them and filesize < 1112064
}