rule poshc2
{
    meta:
        description = "Detection patterns for the tool 'poshc2' taken from the ThreatHunting-Keywords github project"
        author = "@mthcht"
        reference = "https://github.com/mthcht/ThreatHunting-Keywords"
        tool = "poshc2"
        rule_category = "offensive_tool_keyword"

    strings:
                        $string1 = " -c2server " nocase ascii wide
                        $string2 = " -daisyserver " nocase ascii wide
                        $string3 = " -LocalPoshC2ProjectDir " nocase ascii wide
                        $string4 = " -LocalPoshC2ProjectDir " nocase ascii wide
                        $string5 = /\s\-Payload\s.{0,1000}\s\-method\ssysprep/ nocase ascii wide
                        $string6 = " PayloadsDirectory" nocase ascii wide
                        $string7 = " PoshC2 " nocase ascii wide
                        $string8 = " -PoshC2Dir " nocase ascii wide
                        $string9 = " -PoshC2Dir " nocase ascii wide
                        $string10 = " SharpSocks " nocase ascii wide
                        $string11 = "/bin/posh"
                        $string12 = /\/C2Server\.py/ nocase ascii wide
                        $string13 = /\/Macro\-Payloads\.py/ nocase ascii wide
                        $string14 = "/nettitude/" nocase ascii wide
                        $string15 = "/opt/PoshC2" nocase ascii wide
                        $string16 = /\/posh\.key/ nocase ascii wide
                        $string17 = "/PoshC2" nocase ascii wide
                        $string18 = "/poshc2-" nocase ascii wide
                        $string19 = "/PoshC2/" nocase ascii wide
                        $string20 = "/posh-config" nocase ascii wide
                        $string21 = "/posh-log" nocase ascii wide
                        $string22 = "/posh-project" nocase ascii wide
                        $string23 = "/posh-server" nocase ascii wide
                        $string24 = "/posh-service" nocase ascii wide
                        $string25 = "/posh-stop-service" nocase ascii wide
                        $string26 = "/posh-update" nocase ascii wide
                        $string27 = /\/SharpHandler\.py/ nocase ascii wide
                        $string28 = /\\jaccdpqnvbrrxlaf/ nocase ascii wide
                        $string29 = /\\PoshC2/ nocase ascii wide
                        $string30 = "_posh-common" nocase ascii wide
                        $string31 = /_Shellcode\.bin/ nocase ascii wide
                        $string32 = "brute-locadmin " nocase ascii wide
                        $string33 = "bypass-amsi" nocase ascii wide
                        $string34 = /C2\.KillDate/ nocase ascii wide
                        $string35 = /C2\.UserAgent/ nocase ascii wide
                        $string36 = "clipboard-monitor " nocase ascii wide
                        $string37 = "createdaisypayload" nocase ascii wide
                        $string38 = "createlinuxpayload"
                        $string39 = "createnewpayload" nocase ascii wide
                        $string40 = "createnewshellcode" nocase ascii wide
                        $string41 = "createpbindpayload" nocase ascii wide
                        $string42 = "createproxypayload -" nocase ascii wide
                        $string43 = "createproxypayload" nocase ascii wide
                        $string44 = "cred-popper " nocase ascii wide
                        $string45 = "dcomexec -" nocase ascii wide
                        $string46 = /dllsearcher\s.{0,1000}\.dll/ nocase ascii wide
                        $string47 = "find-allvulns" nocase ascii wide
                        $string48 = "find-interestingfile -" nocase ascii wide
                        $string49 = "fpc -c Seatbelt" nocase ascii wide
                        $string50 = "get_c2_messages" nocase ascii wide
                        $string51 = "get_c2server_all" nocase ascii wide
                        $string52 = "get_cmd_from_task_id" nocase ascii wide
                        $string53 = "get_implants_all" nocase ascii wide
                        $string54 = "get_newimplanturl" nocase ascii wide
                        $string55 = "get_sharpurls" nocase ascii wide
                        $string56 = "get-creditcarddata " nocase ascii wide
                        $string57 = "getdllbaseaddress" nocase ascii wide
                        $string58 = "get-dodgyprocesses" nocase ascii wide
                        $string59 = "getgppgroups  " nocase ascii wide
                        $string60 = "getgpppassword " nocase ascii wide
                        $string61 = "get-implantworkingdirectory" nocase ascii wide
                        $string62 = "Get-KeystrokeData" nocase ascii wide
                        $string63 = "get-keystrokes" nocase ascii wide
                        $string64 = "get-killdate" nocase ascii wide
                        $string65 = "get-netfileserver -domain " nocase ascii wide
                        $string66 = "get-passnotexp" nocase ascii wide
                        $string67 = /get\-process\s.{0,1000}amsi\.dll/ nocase ascii wide
                        $string68 = "getremoteprocesslisting" nocase ascii wide
                        $string69 = "get-screenshot" nocase ascii wide
                        $string70 = "get-screenshotallwindows" nocase ascii wide
                        $string71 = "get-wmiregcachedrdpconnection" nocase ascii wide
                        $string72 = "get-wmireglastloggedon" nocase ascii wide
                        $string73 = "get-wmiregmounteddrive" nocase ascii wide
                        $string74 = "hide-implant" nocase ascii wide
                        $string75 = "inject-shellcode " nocase ascii wide
                        $string76 = "installexe-persistence" nocase ascii wide
                        $string77 = "install-persistence" nocase ascii wide
                        $string78 = "install-persistence-cron" nocase ascii wide
                        $string79 = "invoke-aclscanner" nocase ascii wide
                        $string80 = "invoke-arpscan" nocase ascii wide
                        $string81 = "invoke-bloodhound" nocase ascii wide
                        $string82 = "invoke-daisychain" nocase ascii wide
                        $string83 = "invoke-dcompayload" nocase ascii wide
                        $string84 = "invoke-edrchecker" nocase ascii wide
                        $string85 = "invoke-eternalblue" nocase ascii wide
                        $string86 = "invoke-hostenum -" nocase ascii wide
                        $string87 = "invoke-hostscan" nocase ascii wide
                        $string88 = "invoke-kerberoast " nocase ascii wide
                        $string89 = "Invoke-Pbind " nocase ascii wide
                        $string90 = /Invoke\-Pbind\.ps1/ nocase ascii wide
                        $string91 = "invoke-pipekat " nocase ascii wide
                        $string92 = "invoke-psexecpayload" nocase ascii wide
                        $string93 = "Invoke-PsUACme" nocase ascii wide
                        $string94 = "invoke-runaspayload" nocase ascii wide
                        $string95 = "invoke-sharefinder " nocase ascii wide
                        $string96 = "invoke-smbclient " nocase ascii wide
                        $string97 = "invoke-smbexec " nocase ascii wide
                        $string98 = "invoke-smblogin " nocase ascii wide
                        $string99 = "invoke-sniffer " nocase ascii wide
                        $string100 = "invoke-urlcheck -urls" nocase ascii wide
                        $string101 = "invoke-winrmsession" nocase ascii wide
                        $string102 = "invoke-wmiexec " nocase ascii wide
                        $string103 = "invoke-wmijspayload" nocase ascii wide
                        $string104 = "invoke-wmipayload" nocase ascii wide
                        $string105 = "kill-implant" nocase ascii wide
                        $string106 = "label-implant " nocase ascii wide
                        $string107 = "ldap-searcher " nocase ascii wide
                        $string108 = "linuxprivchecker"
                        $string109 = /loadmodule\s.{0,1000}\.ps1/ nocase ascii wide
                        $string110 = /loadmodume\s.{0,1000}\/modules\/.{0,1000}\.ps1/ nocase ascii wide
                        $string111 = /lockless\s.{0,1000}\.dat/ nocase ascii wide
                        $string112 = "PayloadCommsHost" nocase ascii wide
                        $string113 = "Posh_v4_dropper_" nocase ascii wide
                        $string114 = /Posh_v4_x64_.{0,1000}\.bin/ nocase ascii wide
                        $string115 = /Posh_v4_x86_.{0,1000}\.bin/ nocase ascii wide
                        $string116 = /PoshC2\-.{0,1000}\.zip/ nocase ascii wide
                        $string117 = /poshc2\.server/ nocase ascii wide
                        $string118 = /poshc2\.service/ nocase ascii wide
                        $string119 = /poshc2\-ansible\-main\.yml/ nocase ascii wide
                        $string120 = "posh-cookie-decryptor" nocase ascii wide
                        $string121 = "posh-delete " nocase ascii wide
                        $string122 = "posh-project " nocase ascii wide
                        $string123 = "posh-project -" nocase ascii wide
                        $string124 = "posh-server -" nocase ascii wide
                        $string125 = "posh-server -" nocase ascii wide
                        $string126 = "posh-update " nocase ascii wide
                        $string127 = "process_mimikatz" nocase ascii wide
                        $string128 = /pslo\s.{0,1000}\.ps1/ nocase ascii wide
                        $string129 = "removeexe-persistence" nocase ascii wide
                        $string130 = "remove-persistence" nocase ascii wide
                        $string131 = "remove-persistence-cron" nocase ascii wide
                        $string132 = "runas-netonly " nocase ascii wide
                        $string133 = "run-dll SharpSploit" nocase ascii wide
                        $string134 = "safetydump" nocase ascii wide
                        $string135 = "seatbelt -" nocase ascii wide
                        $string136 = "seatbelt all" nocase ascii wide
                        $string137 = "set-killdate " nocase ascii wide
                        $string138 = "set-pushover-applicationtoken" nocase ascii wide
                        $string139 = "set-pushover-userkeys" nocase ascii wide
                        $string140 = "shadowcopy enum" nocase ascii wide
                        $string141 = /Sharp_v4_x64.{0,1000}\.bin/ nocase ascii wide
                        $string142 = /Sharp_v4_x86.{0,1000}\.bin/ nocase ascii wide
                        $string143 = "sharpapplocker" nocase ascii wide
                        $string144 = "sharpchromium " nocase ascii wide
                        $string145 = "sharpcookiemonster" nocase ascii wide
                        $string146 = "sharpedrchecker" nocase ascii wide
                        $string147 = "sharphound -" nocase ascii wide
                        $string148 = /sharpps\s\$psversiontable/ nocase ascii wide
                        $string149 = "sharpps get-process" nocase ascii wide
                        $string150 = /sharpsc\s.{0,1000}cmd/ nocase ascii wide
                        $string151 = "sharptelnet " nocase ascii wide
                        $string152 = "sharpweb all" nocase ascii wide
                        $string153 = "sharpwmi action=" nocase ascii wide
                        $string154 = "standin --asrep" nocase ascii wide
                        $string155 = "standin --dc" nocase ascii wide
                        $string156 = "standin --delegation" nocase ascii wide
                        $string157 = /standin\s\-\-group\s.{0,1000}Domain\sAdmins/ nocase ascii wide
                        $string158 = "standin --object " nocase ascii wide
                        $string159 = "standin --spn" nocase ascii wide
                        $string160 = "startanotherimplant" nocase ascii wide
                        $string161 = "startdaisy" nocase ascii wide
                        $string162 = "start-keystrokes" nocase ascii wide
                        $string163 = "start-keystrokes-writefile" nocase ascii wide
                        $string164 = /start\-process\sntdsutil\.exe\s.{0,1000}create\sfull/ nocase ascii wide
                        $string165 = "stopdaisy" nocase ascii wide
                        $string166 = "stop-keystrokes" nocase ascii wide
                        $string167 = "sweetpotato -p" nocase ascii wide
                        $string168 = /temp\\pbind\.exe/ nocase ascii wide
                        $string169 = "timestomp c:" nocase ascii wide
                        $string170 = "unhide-implant" nocase ascii wide
                        $string171 = /XOR\-Payloads\.py/ nocase ascii wide

    condition:
        any of them
}