rule MALPEDIA_Win_Equationdrug_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "37b1b451-51c5-5fbc-9487-21d701b707d2"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.equationdrug"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.equationdrug_auto.yar#L1-L133"
    license_url        = "N/A"
    logic_hash         = "f8f538888e4dbac5fbcd6d58b6a95043a330081a5194049d400ba3c70341afe9"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0 = { 5b c2 10 00 8b d0 56 81 e2 ff 0f 00 00 53 83 c7 04 }
    $sequence_1 = { 0f 84 f4 00 00 00 8b 7c 24 14 f7 c7 ff 01 00 00 0f 85 e4 00 00 00 8b 4e 04 8d 44 24 10 50 }
    $sequence_2 = { 56 8d 4c 24 18 c6 44 24 58 00 e8 ?? ?? ?? ?? 8d 4c 24 14 e8 ?? ?? ?? ?? 84 c0 }
    $sequence_3 = { 84 c0 74 1a 66 8b 4e f8 66 0f be d0 66 8b 46 fa 52 50 }
    $sequence_4 = { 89 54 24 14 8b 54 24 10 0f bf c2 40 0f af c1 3b fb 73 c4 }
    $sequence_5 = { c6 44 24 5c 00 e8 ?? ?? ?? ?? 83 c4 04 89 44 24 64 85 c0 c6 44 24 58 02 74 11 }
    $sequence_6 = { e8 ?? ?? ?? ?? 85 c0 0f 86 4b 02 00 00 53 8b cd e8 ?? ?? ?? ?? 50 }
    $sequence_7 = { 33 c0 eb 07 8b 47 08 2b c6 d1 f8 33 d2 33 db }
    $sequence_8 = { 8b ca b0 01 83 e1 03 f3 a4 5f 5e 5d }
    $sequence_9 = { 66 85 c0 75 37 8b 44 24 08 3d ff ff 00 00 77 2c c1 e0 09 }

  condition:
    7 of them and filesize < 449536
}