rule MALPEDIA_Win_Aukill_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "a6d13b29-a1c3-5db7-ac5c-09009229e7b9"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.aukill"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.aukill_auto.yar#L1-L117"
    license_url        = "N/A"
    logic_hash         = "ebc3504ab44ddd68fe35d4be4361ca674b2d7f3006cec23148755c773291be1b"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0 = { 85 c0 75 1f 48 8b 4c 24 58 ff 15 ?? ?? ?? ?? }
    $sequence_1 = { 0f b7 da 8b f9 e8 ?? ?? ?? ?? 4c 8b c8 45 33 c0 }
    $sequence_2 = { 45 33 c0 33 d2 48 8b cb ff 15 ?? ?? ?? ?? 85 c0 75 26 48 8b cb }
    $sequence_3 = { 48 89 44 24 20 ff 15 ?? ?? ?? ?? 85 c0 75 1f 48 8b 4c 24 58 ff 15 ?? ?? ?? ?? }
    $sequence_4 = { 75 1d 48 8b cb ff 15 ?? ?? ?? ?? ff 15 ?? ?? ?? ?? }
    $sequence_5 = { 44 89 44 24 20 45 3b 01 73 46 4b 8d 14 40 41 0f 10 4c d1 08 0f 11 4c 24 28 f2 41 0f 10 44 d1 18 }
    $sequence_6 = { 44 8d 49 20 48 89 4c 24 50 48 8b 0d ?? ?? ?? ?? 48 89 7c 24 58 }
    $sequence_7 = { 48 8b d3 33 c9 ff 15 ?? ?? ?? ?? 85 c0 75 1f }
    $sequence_8 = { 48 89 5c 24 08 57 48 83 ec 60 48 8b fa 8b d9 e8 ?? ?? ?? ?? 33 c9 }
    $sequence_9 = { ff c2 80 f9 20 75 ee 4c 63 c2 }

  condition:
    7 of them and filesize < 446464
}