rule win_nimrev_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.nimrev."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.nimrev"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 8845ef eb01 90 807def00 }
                                                            
        $sequence_1 = { 0fb600 3c5f 7507 b801000000 }
                                                            
        $sequence_2 = { 3c7d 7407 b801000000 eb05 }
                                                            
        $sequence_3 = { 7507 b801000000 eb05 b800000000 8845f7 eb01 90 }
                                                                                                
        $sequence_4 = { 0fb600 3c7d 7407 b801000000 eb05 b800000000 }
                                                                                    
        $sequence_5 = { ffd0 90 e9???????? 90 b9d0070000 }
                                                                        
        $sequence_6 = { c1e002 01d0 01c0 29c1 89c8 83c030 89c1 }
                                                                                                
        $sequence_7 = { 89c2 89d0 c1e002 01d0 01c0 29c1 89c8 }
                                                                                                
        $sequence_8 = { 83f001 84c0 7408 90 e8???????? eb01 }
                                                                                    
        $sequence_9 = { 0f9ec0 8845ef eb01 90 807def00 }
                                                                        
    condition:
        7 of them and filesize < 1141760
}