rule ldap_sha1_hashed_default_creds_apache_tomcat_web
{
    meta:
        version = "1.0"
        status = "RELEASED"
        sharing = "TLP:WHITE"
        source = "NDAAL GESELLSCHAFT FÜR SICHERHEIT INDER INFORMATIONSTECHNIK MBH & CO KG"
        author = "Alaa Jubakhanji@ndaal Gesellschaft fürSicherheit in der Informationstechnik mbH & Co KG"
        description = "Hashed values of default credentials for apache_tomcat_web."
        category = "INFO"
        info = "LDAP_SHA1"
        reference = "https://gitlab.com/ndaal_open_source/ndaal_yara_passwords_default/-/tree/main/yara_rules"

strings:
    $a0="{SHA}0DPiKuNIrrVmD8IUCuw1hQxNqZc="
    $a1="{SHA}0DPiKuNIrrVmD8IUCuw1hQxNqZc="
    $a2="{SHA}tSHKpuHbguWgHJJKQZhwy3K4FjU="
    $a3="{SHA}tSHKpuHbguWgHJJKQZhwy3K4FjU="
    $a4="{SHA}RPTybnrJpO8exuh9+S4dzye6tzg="
    $a5="{SHA}0DPiKuNIrrVmD8IUCuw1hQxNqZc="
    $a6="{SHA}U2wLM5NFYWwbM8r0VEVNi4oZDWw="
    $a7="{SHA}0DPiKuNIrrVmD8IUCuw1hQxNqZc="
    $a8="{SHA}LqWTjDvr1bQoAybV0cn6eL8bPkA="
    $a9="{SHA}F6RLiiKVCccj+InrcjtRLCc+3Jw="
    $a10="{SHA}Xx8thnKe7YhbzhI6YgZxp87TwKY="
    $a11="{SHA}Xx8thnKe7YhbzhI6YgZxp87TwKY="
    $a12="{SHA}5SfBgdzFKCwzlF0yKjxXUN6A0qY="
    $a13="{SHA}pDYXy9MIDnO+HBgfgiz6Ca0F+rY="
    $a14="{SHA}0VtWLxlC1A/Amf9aWvfCjyiQnEM="
    $a15="{SHA}brgWg7hzog8miBwi5VxBimGRW/c="
    $a16="{SHA}kbGlNpWQurEABm4cg+IxehrbKnY="
    $a17="{SHA}kbGlNpWQurEABm4cg+IxehrbKnY="
    $a18="{SHA}U2wLM5NFYWwbM8r0VEVNi4oZDWw="
    $a19="{SHA}kbGlNpWQurEABm4cg+IxehrbKnY="
    $a20="{SHA}zbDnbBpphzy9zb4KFC1WwCPcnyI="
    $a21="{SHA}jcpGQo0AWi9MLgOfslCWTWE5qLI="
    $a22="{SHA}3Hbp8MAAbo+RngxRXGbbujmC94U="
    $a23="{SHA}3Hbp8MAAbo+RngxRXGbbujmC94U="
    $a24="{SHA}zbDnbBpphzy9zb4KFC1WwCPcnyI="
    $a25="{SHA}U2wLM5NFYWwbM8r0VEVNi4oZDWw="
    $a26="{SHA}/vNB+F2HQ559kaLUZbmHHvZrXpg="
    $a27="{SHA}U2wLM5NFYWwbM8r0VEVNi4oZDWw="
    $a28="{SHA}U2wLM5NFYWwbM8r0VEVNi4oZDWw="
    $a29="{SHA}U2wLM5NFYWwbM8r0VEVNi4oZDWw="
    $a30="{SHA}k7RZhxxE0CcXmhMkOCqfKMbWUpo="
    $a31="{SHA}k7RZhxxE0CcXmhMkOCqfKMbWUpo="
condition:
    ($a0 and $a1) or ($a2 and $a3) or ($a4 and $a5) or ($a6 and $a7) or ($a8 and $a9) or ($a10 and $a11) or ($a12 and $a13) or ($a14 and $a15) or ($a16 and $a17) or ($a18 and $a19) or ($a20 and $a21) or ($a22 and $a23) or ($a24 and $a25) or ($a26 and $a27) or ($a28 and $a29) or ($a30 and $a31)
}