rule MALPEDIA_Win_Madmax_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "230eedbf-6cae-5fdd-90b6-aea0b58f95e1"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.madmax"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.madmax_auto.yar#L1-L134"
    license_url        = "N/A"
    logic_hash         = "8fadf42f6b346841d23791b849b5705de38f9f89679dc44544ef7b477d437506"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0 = { d0 cd 99 86 d6 4c ae 2f 4e }
    $sequence_1 = { b8 0c 32 e1 73 8a c5 08 67 9e fb 59 80 50 cb 80 ba ef 81 2a 0a }
    $sequence_2 = { e0 7d d8 cc 6a 55 60 25 a2 37 f3 01 4a 4c }
    $sequence_3 = { 8d 8d d0 fe ff ff e8 ?? ?? ?? ?? 8d b3 96 00 00 00 6a 3b 9c f6 05 ?? ?? ?? ?? d6 0f 85 1c 01 00 00 }
    $sequence_4 = { 93 9f 85 6d 67 66 4c 86 57 b6 49 15 2b 9b e0 c2 }
    $sequence_5 = { d9 dd 09 55 27 17 44 4b 60 1f }
    $sequence_6 = { f7 23 56 c8 d9 5b cc 0e 64 a0 4d 98 f5 db 6e 05 1e 07 9c c8 }
    $sequence_7 = { ad 7e a5 6a bd 65 0e 9c 35 28 e5 63 a7 6c }
    $sequence_8 = { f6 05 ?? ?? ?? ?? e2 0f 85 1d 01 00 00 73 e7 f2 24 86 85 e6 21 0a e7 88 }
    $sequence_9 = { f6 05 ?? ?? ?? ?? a5 75 31 df 2e 8b 1b f8 b3 6a 79 28 }

  condition:
    7 of them and filesize < 3227648
}