rule MALPEDIA_Win_Webc2_Greencat_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "60cc7c89-f223-5f05-b50e-ef8d73401362"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.webc2_greencat"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.webc2_greencat_auto.yar#L1-L120"
    license_url        = "N/A"
    logic_hash         = "e9fd4938930988d9b35f1bca39290f31fad2f360914fa390eec34fabf9934b56"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0 = { 57 50 e8 ?? ?? ?? ?? 59 8b d8 59 eb 03 }
    $sequence_1 = { 59 59 e9 ?? ?? ?? ?? ff 35 ?? ?? ?? ?? ff 15 ?? ?? ?? ?? 3b c6 }
    $sequence_2 = { 33 f6 89 5d f4 8d 45 0c 50 ff 35 ?? ?? ?? ?? ff 15 ?? ?? ?? ?? 81 7d 0c 03 01 00 00 }
    $sequence_3 = { 39 5d dc 75 2d 39 1d ?? ?? ?? ?? 75 25 3b f3 75 21 }
    $sequence_4 = { e8 ?? ?? ?? ?? 83 c4 18 53 6a 02 }
    $sequence_5 = { 8d 85 fc fe ff ff 33 ff 68 04 01 00 00 50 }
    $sequence_6 = { 50 53 ff 15 ?? ?? ?? ?? 33 c9 89 45 f0 }
    $sequence_7 = { 8b f0 39 5d dc 75 2d 39 1d ?? ?? ?? ?? 75 25 3b f3 75 21 }
    $sequence_8 = { ff 75 fc ff 15 ?? ?? ?? ?? 83 c4 28 53 68 80 00 00 00 }
    $sequence_9 = { 0f be 40 07 83 e8 30 89 45 f8 8d 85 f8 fd ff ff 50 }

  condition:
    7 of them and filesize < 57344
}