rule MALPEDIA_Win_Penco_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "0506b7c6-0597-5673-b29d-0e2e4b0bbb8c"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.penco"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.penco_auto.yar#L1-L129"
    license_url        = "N/A"
    logic_hash         = "b907c123e9f48e051972fa4ccfde76e3114fafc16984b4ff739806928ca43da4"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0 = { 53 6a 01 68 00 00 00 80 8d 95 00 01 00 00 52 8b 1d ?? ?? ?? ?? }
    $sequence_1 = { 33 34 bd 00 d8 34 00 0f b6 7c 24 14 33 34 bd 00 d4 34 00 8b 4c 24 1c 33 70 0c 83 c0 10 8b de }
    $sequence_2 = { 40 89 44 24 18 3b 44 24 14 0f 82 ff fe ff ff eb 13 8d 04 2e 68 ?? ?? ?? ?? }
    $sequence_3 = { 74 1c 68 ?? ?? ?? ?? 68 ff 01 0f 00 56 ff 15 ?? ?? ?? ?? 56 85 c0 }
    $sequence_4 = { 0f be 80 e8 98 34 00 83 e0 0f 33 f6 eb 04 33 f6 33 c0 }
    $sequence_5 = { 8d 45 98 50 6a 00 6a 00 8d 4d b8 51 8b 55 a4 }
    $sequence_6 = { 33 c0 84 c9 74 28 8d 64 24 00 80 f9 30 7c 1c 80 f9 39 }
    $sequence_7 = { 89 4c 24 18 8b 4c 24 44 f7 f1 33 d2 c7 44 24 20 01 00 00 00 03 44 24 10 89 44 24 14 }
    $sequence_8 = { 75 04 8b f0 eb 3e 6a 0a }
    $sequence_9 = { 8b 34 95 28 e8 34 00 8b 54 24 28 0f b6 f9 33 34 bd 00 d8 34 00 8b 4c 24 1c c1 ea 18 33 34 95 28 ec 34 00 }

  condition:
    7 of them and filesize < 319488
}