rule MALPEDIA_Win_Pkybot_Auto: FILE {
  meta:
    description        = "autogenerated rule brought to you by yara-signator"
    author             = "Felix Bilstein - yara-signator at cocacoding dot com"
    id                 = "b29148a6-8685-5645-99d4-ca854d32849e"
    date               = "2023-12-06"
    modified           = "2023-12-08"
    reference          = "https://malpedia.caad.fkie.fraunhofer.de/details/win.pkybot"
    source_url         = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.pkybot_auto.yar#L1-L120"
    license_url        = "N/A"
    logic_hash         = "809773f54b9553ffea062fd7f87645abd3e261a3e38fb26640ff099fc49a005e"
    score              = 75
    quality            = 75
    tags               = "FILE"
    version            = "1"
    tool               = "yara-signator v0.6.0"
    signator_config    = "callsandjumps;datarefs;binvalue"
    malpedia_rule_date = "20231130"
    malpedia_hash      = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
    malpedia_version   = "20230808"
    malpedia_license   = "CC BY-SA 4.0"
    malpedia_sharing   = "TLP:WHITE"

  strings:
    $sequence_0 = { ff 15 ?? ?? ?? ?? 8b f8 83 ff ff 74 29 56 56 }
    $sequence_1 = { 8d 45 e0 50 8b 06 83 c0 04 50 }
    $sequence_2 = { 8b 4e 04 21 41 3c c7 41 30 0e 00 00 00 89 79 38 5f 5e }
    $sequence_3 = { 74 09 ff 75 dc e8 ?? ?? ?? ?? 59 56 }
    $sequence_4 = { 8b 0d ?? ?? ?? ?? 89 41 08 e8 ?? ?? ?? ?? a3 ?? ?? ?? ?? }
    $sequence_5 = { 75 18 ff 35 ?? ?? ?? ?? e8 ?? ?? ?? ?? 59 89 3d ?? ?? ?? ?? 89 3d ?? ?? ?? ?? }
    $sequence_6 = { 56 a3 ?? ?? ?? ?? e8 ?? ?? ?? ?? 83 c4 48 }
    $sequence_7 = { 57 6a 10 ff 75 10 8d 45 ec 50 e8 ?? ?? ?? ?? }
    $sequence_8 = { 74 30 50 3b f7 75 07 e8 ?? ?? ?? ?? eb 05 e8 ?? ?? ?? ?? }
    $sequence_9 = { 8d 85 ec fd ff ff 50 8d 45 f4 50 53 57 ff 75 fc }

  condition:
    7 of them and filesize < 204800
}