rule win_resident_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-01-05"
        version = "1"
        description = "Detects win.resident."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.resident"
        malpedia_rule_date = "20260105"
        malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
        malpedia_version = "20251219"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    


    strings:
        $sequence_0 = { 6a00 8d95dcf9ffff 52 6a00 ff15???????? 85c0 }
                                                                                    
        $sequence_1 = { c1e606 03348500b94000 8b45f8 8b00 8906 8b45fc 8a00 }
                                                                                                
        $sequence_2 = { 894c243c 8b4c2460 89442404 89542440 8b54245c }
                                                                        
        $sequence_3 = { 895c2410 c744240cffffffff 89742408 c744240400000000 }
                                                            
        $sequence_4 = { e8???????? 89c6 85c0 0f8427010000 c70424???????? 8d6c243e e8???????? }
                                                                                                
        $sequence_5 = { 8d85d8f9ffff e8???????? 8b95d4f9ffff 8bf0 03d2 8d45dc e8???????? }
                                                                                                
        $sequence_6 = { 750f 33c0 807dfa01 0f94c0 8d740010 eb41 83f803 }
                                                                                                
        $sequence_7 = { 8d55e4 52 ffd6 85c0 75e3 5b }
                                                                                    
        $sequence_8 = { 6689442430 668954242c 8b542422 b830000000 6689442428 66894c242e 0fb74c2420 }
                                                                                                
        $sequence_9 = { c744240800000000 c744240400000000 ff15???????? 83ec20 891c24 e8???????? }
                                                                                    
        $sequence_10 = { 8d34ad00000000 8b04a8 890424 e8???????? 83f825 76da }
                                                                                    
        $sequence_11 = { 8b37 89442418 8d460a 890424 e8???????? 89c3 85c0 }
                                                                                                
        $sequence_12 = { 75e4 b801000000 893c24 8944241c e8???????? }
                                                                        
        $sequence_13 = { ff15???????? 6a04 8d55fc 52 6a06 }
                                                                        
        $sequence_14 = { ff15???????? 83ec04 0fb7442446 66895c2450 }
                                                            
        $sequence_15 = { eb05 e8???????? 83c404 84c0 0f848e000000 }
                                                                        
    condition:
        7 of them and filesize < 125952
}