rule AutoRDPwn
{
    meta:
        description = "Detection patterns for the tool 'AutoRDPwn' taken from the ThreatHunting-Keywords github project"
        author = "@mthcht"
        reference = "https://github.com/mthcht/ThreatHunting-Keywords"
        tool = "AutoRDPwn"
        rule_category = "offensive_tool_keyword"

    strings:
                        $string1 = /\s\-Reverse\s\-IPAddress\s.{0,1000}\s\-Port\s/ nocase ascii wide
                        $string2 = /\s\-TaskName\s.{0,1000}AutoRDPwn/ nocase ascii wide
                        $string3 = /\/AutoBypass\.ps1/ nocase ascii wide
                        $string4 = /\/autordpwn\.php/ nocase ascii wide
                        $string5 = "/AutoRDPwn/master/" nocase ascii wide
                        $string6 = "656761faa342911d398af21edaf085f978ffa53a6bf3919763dfa82aba2301f1" nocase ascii wide
                        $string7 = "86c1800ab9c9f90d5d5ce81a1f1daae1446cdb98686c59b4d5336216725bfb8e" nocase ascii wide
                        $string8 = "97b8d3a33ca3a06d24553a8ea8a5a89520ebe15655fa338b2f7c7c8883ae38da" nocase ascii wide
                        $string9 = "Add-ServiceDacl" nocase ascii wide
                        $string10 = /AutoBypass\.ps1/ nocase ascii wide
                        $string11 = "AutoRDPwn" nocase ascii wide
                        $string12 = /AutoRDPwn\.ps1/ nocase ascii wide
                        $string13 = "Bypass-UAC" nocase ascii wide
                        $string14 = "c7874c257949a3c09dcb16f17c6fdb5ea0c5adb143004e7cc4adc63eb3ed785c" nocase ascii wide
                        $string15 = /Chachi\-Enumerator\.ps1/ nocase ascii wide
                        $string16 = /Check\-LocalAdminHash\.ps1/ nocase ascii wide
                        $string17 = "d366383b6e737fd3af2acc5ebc9f209a2c49209b7b444af3c7fe1d39e1775894" nocase ascii wide
                        $string18 = "DownloadAndExtractFromRemoteRegistry" nocase ascii wide
                        $string19 = "Get-CredPersist" nocase ascii wide
                        $string20 = "Get-DecodedPassword" nocase ascii wide
                        $string21 = "Get-DecryptedCpassword" nocase ascii wide
                        $string22 = "Get-DecryptedPassword" nocase ascii wide
                        $string23 = "Get-DiscosdurosGet-PSDrive" nocase ascii wide
                        $string24 = "Get-LsaRunAsPPLStatus" nocase ascii wide
                        $string25 = /Get\-NTLM\.ps1/ nocase ascii wide
                        $string26 = "Get-UnattendSensitiveData" nocase ascii wide
                        $string27 = "Get-UserPrivileges" nocase ascii wide
                        $string28 = "Get-Wlan-Keys" nocase ascii wide
                        $string29 = "Invoke-ApplicationsOnStartupCheck" nocase ascii wide
                        $string30 = "Invoke-CredentialFilesCheck" nocase ascii wide
                        $string31 = "Invoke-DllHijackingCheck" nocase ascii wide
                        $string32 = "Invoke-GPPPasswordCheck" nocase ascii wide
                        $string33 = "Invoke-HijackableDllsCheck" nocase ascii wide
                        $string34 = "Invoke-InstalledServicesCheck" nocase ascii wide
                        $string35 = "Invoke-Keylogger" nocase ascii wide
                        $string36 = "Invoke-LapsCheck" nocase ascii wide
                        $string37 = "Invoke-LocalAdminGroupCheck" nocase ascii wide
                        $string38 = "Invoke-LsaProtectionsCheck" nocase ascii wide
                        $string39 = /Invoke\-Mimikatz\.ps1/ nocase ascii wide
                        $string40 = "Invoke-Phant0m" nocase ascii wide
                        $string41 = /Invoke\-Phant0m\.ps1/ nocase ascii wide
                        $string42 = /Invoke\-PipeShell\.ps1/ nocase ascii wide
                        $string43 = "Invoke-Portscan" nocase ascii wide
                        $string44 = /Invoke\-Portscan\.ps1/ nocase ascii wide
                        $string45 = "Invoke-PowerShellTcp" nocase ascii wide
                        $string46 = /Invoke\-PowerShellTcp\.ps1/ nocase ascii wide
                        $string47 = "Invoke-PrivescCheck" nocase ascii wide
                        $string48 = /Invoke\-PrivescCheck\.ps1/ nocase ascii wide
                        $string49 = /Invoke\-PSexec\.ps1/ nocase ascii wide
                        $string50 = /Invoke\-RDPwrap\.ps1/ nocase ascii wide
                        $string51 = "Invoke-RegistryAlwaysInstallElevatedCheck" nocase ascii wide
                        $string52 = /Invoke\-RevShellServer\.ps1/ nocase ascii wide
                        $string53 = /Invoke\-RunAs\.ps1/ nocase ascii wide
                        $string54 = "Invoke-SamBackupFilesCheck" nocase ascii wide
                        $string55 = "Invoke-ScheduledTasksCheck" nocase ascii wide
                        $string56 = "Invoke-ServicesImagePermissionsCheck" nocase ascii wide
                        $string57 = "Invoke-ServicesPermissionsCheck" nocase ascii wide
                        $string58 = "Invoke-ServicesPermissionsRegistryCheck" nocase ascii wide
                        $string59 = "Invoke-ServicesUnquotedPathCheck" nocase ascii wide
                        $string60 = "Invoke-SessionGopher" nocase ascii wide
                        $string61 = /Invoke\-SharpRDP\.ps1/ nocase ascii wide
                        $string62 = /Invoke\-SharpWeb\.ps1/ nocase ascii wide
                        $string63 = "Invoke-SMBExec" nocase ascii wide
                        $string64 = /Invoke\-SMBExec\.ps1/ nocase ascii wide
                        $string65 = "Invoke-SystemStartupHistoryCheck" nocase ascii wide
                        $string66 = "Invoke-UacCheck" nocase ascii wide
                        $string67 = "Invoke-UnattendFilesCheck" nocase ascii wide
                        $string68 = "Invoke-UserPrivilegesCheck" nocase ascii wide
                        $string69 = "Invoke-VaultCredCheck" nocase ascii wide
                        $string70 = /Invoke\-VNCServer\.ps1/ nocase ascii wide
                        $string71 = /Invoke\-VNCViewer\.ps1/ nocase ascii wide
                        $string72 = /Invoke\-WebRev\.ps1/ nocase ascii wide
                        $string73 = "Invoke-WinlogonCheck" nocase ascii wide
                        $string74 = "Invoke-WMIExec" nocase ascii wide
                        $string75 = /ListAllUsers\.ps1/ nocase ascii wide
                        $string76 = /net\slocalgroup\s.{0,1000}\sAutoRDPwn\s\/add/ nocase ascii wide
                        $string77 = "net user AutoRDPwn" nocase ascii wide
                        $string78 = "PortScan-Alive" nocase ascii wide
                        $string79 = "Portscan-Port" nocase ascii wide
                        $string80 = /RDP\-Caching\.ps1/ nocase ascii wide
                        $string81 = /Resources\/Design\/NinjaStyle\.ps1/ nocase ascii wide
                        $string82 = "Search-cpassword" nocase ascii wide
                        $string83 = /SessionGopher\.ps1/ nocase ascii wide
                        $string84 = /Set\-Content\s\-Path\spsexec\.exe/ nocase ascii wide
                        $string85 = /Set\-Content\s\-Path\sserver\.exe/ nocase ascii wide
                        $string86 = /Set\-Content\s\-Path\sSharpRDP\.exe/ nocase ascii wide
                        $string87 = /Set\-Content\s\-Path\sSharpWeb\.exe/ nocase ascii wide
                        $string88 = /Sherlock\.ps1/ nocase ascii wide
                        $string89 = /Start\-WebServer\.ps1/ nocase ascii wide
                        $string90 = "Test-DllExists" nocase ascii wide
                        $string91 = "Test-ServiceDaclPermission" nocase ascii wide
                        $string92 = /VNCViewer\.exe\s\/password\sAutoRDPwn\s/ nocase ascii wide
                        $string93 = "Write-PortscanOut" nocase ascii wide

    condition:
        any of them
}